#!/usr/bin/env python3
"""portexec/exec_harness.py -- compile and RUN a kernel the PORT emitted.

The port's C text is NOT transcribed here. It is read out of the port's own
stdout (`port-rows.txt`, produced by `./bin/bend tinybendygrad/renderer/cstyle.bend`),
from ONE row's OWN column -- the `NAME = [...]` half, never the `py=[...]` half,
which is a transcription of CPython and would make this lane circular.

WHAT IS THE PORT'S AND WHAT IS THE HARNESS'S, because the boundary is the whole
point of the exercise:

  PORT      the row value: `render_kernel`'s signature, buftypes, prefixes and
            framing, verbatim, plus the gate's `g_kernel()` body fixture which
            is an INPUT to `render_kernel` on both sides (upstream is handed the
            same two lines, renderer_oracle.py:508).
  HARNESS   (a) the `float4` typedef preamble, which is UPSTREAM's own
                `ClangRenderer.render_vector_prefix` text, written by oracle.py --
                `float4` in the body fixture only exists once a vector prefix has
                been declared;
            (b) `main()`, the buffers and the readback print;
            (c) the `extern` prototype, obtained by PARSING the port's own
                signature line out of the row value, not typed.

So this lane proves the port's SIGNATURE AND FRAMING are semantically live C,
not merely text-equal. It does NOT claim the port generated the arithmetic --
the two body lines are a literal fixture at `cstyle.bend:1879`.

    .venv/bin/python .agents/slop/portexec/exec_harness.py <outdir> [row]
"""
import json, pathlib, re, sys

SEP = "]   py=["


def port_rows(path):
  """`NAME -> the port's OWN column`, unescaped (`\\n` -> newline)."""
  out = {}
  for line in pathlib.Path(path).read_text().splitlines():
    i = line.find(SEP)
    if i < 0:
      continue
    out[line[:line.find(" = [")]] = line[line.find(" = ["):i][4:].replace("\\n", "\n")
  return out


def signature(kernel):
  """THE PORT'S OWN SIGNATURE, parsed. `void NAME(TYPE NAME, ...)` is the first
  `void NAME(...)` followed by `{`; nothing else in the text has that shape."""
  m = re.search(r"\bvoid\s+(\w+)\s*\(([^)]*)\)\s*\{", kernel)
  if not m:
    raise SystemExit("no `void NAME(...) {` in the port's row")
  args = []
  for a in m.group(2).split(","):
    toks = a.split()
    args.append((" ".join(toks[:-1]), toks[-1]))
  return m.group(1), args


def which_are_outputs(kernel, args):
  """WHICH PARAMETER EACH SIDE WRITES, read off the BODY TEXT rather than assumed.
  The store arm is `render_access(bidx) = ctx[var];`, so the name in the body's
  `NAME = ...;` left-hand side is the kernel's OUTPUT. Getting this backwards
  returned all zeros on the first run of oracle.py."""
  lhs = re.findall(r"\*\(\(float4\*\)\(\((\w+)\+0\)\)\)\s*=", kernel)
  return lhs[0] if lhs else args[0][1]


def driver(fname, args, names, in_names, in_words, out_name, nwords):
  """THE DRIVER, generated. One shape for every lane, so a difference between
  lanes is the KERNEL's and never the harness's.

  THE BUFFERS ARE `float` AND NOT `unsigned int`, so the pointer types MATCH the
  port's own declared parameter types and `cc` emits no incompatible-pointer
  warning. `cc -Wall -Werror` is on in stage1.sh: a kernel that only compiles
  under a suppressed diagnostic has not been shown to compile."""
  n = nwords
  bufs = "\n".join(f"  static _Alignas(16) float {x}[{n}];" for x in names)
  seed = "\n".join(f"  ((unsigned int*){in_names})[{i}] = 0x{w:08x}u;"
                   for i, w in enumerate(in_words))
  zero = f"  for (int i = 0; i < {n}; i++) ((unsigned int*){out_name})[i] = 0u;"
  proto = f"extern void {fname}({', '.join(a + ' ' + b for a, b in args)});"
  call = f"  {fname}({', '.join(names)});"
  dump = (f'  for (int i = 0; i < {n}; i++) printf("WORD %d 0x%08x\\n", i, '
          f'((unsigned int*){out_name})[i]);')
  return ("/* GENERATED BY exec_harness.py -- the driver, not the kernel. */\n"
          "#include <stdio.h>\n" + proto + "\nint main(void) {\n" + bufs + "\n"
          + zero + "\n" + seed + "\n" + call + "\n" + dump + "\n  return 0;\n}\n")


def main():
  out = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".")
  row = sys.argv[2] if len(sys.argv) > 2 else "kern2 CLANG      "
  in_row = sys.argv[3] if len(sys.argv) > 3 else "stage1_in_words"
  orc = json.loads((out / "oracle.json").read_text())
  rows = port_rows(out / "port-rows.txt")
  if row not in rows:
    raise SystemExit(f"row {row!r} is not in the port's output ({len(rows)} rows read)")
  kernel = rows[row]
  fname, args = signature(kernel)
  out_name = which_are_outputs(kernel, args)
  names = [b for _, b in args]
  in_words = orc[in_row]
  # THE INPUT BUFFER IS the one the body READS. Every other parameter of this
  # kernel family is a pure output, and assuming otherwise is how the first run
  # of oracle.py printed four zeros and looked like a kernel fault.
  read = re.search(r"\(\(float4\*\)\(\((\w+)\+0\)\)\)", kernel)
  in_name = read.group(1) if read else names[-1]
  print(f"PORT ROW         : {row.strip()}")
  print(f"PORT SIGNATURE   : void {fname}({', '.join(a + ' ' + b for a, b in args)})")
  print(f"PORT KERNEL BYTES: {len(kernel)}")
  print(f"HARNESS ARGS     : {names}  (output={out_name} input={in_name})")
  src = "\n".join([orc["vec4_typedef"], kernel,
                   driver(fname, args, names, in_name, in_words, out_name, len(in_words))])
  (out / "stage1.c").write_text(src)
  print(f"WROTE            : {out / 'stage1.c'} ({len(src)} bytes)")


if __name__ == "__main__":
  main()
