#!/usr/bin/env python3
"""portexec/gen_ffi.py -- GENERATE the shim and the Bend program for Stage 2/3.

THE SHIM'S ABI IS THE PORT'S. `extern void E_4(float* restrict data0_4, float*
restrict data1_4);` is COPIED out of the port's own emitted kernel text by
`exec_harness.signature`, byte for byte. It is not typed here, so a change in the
port's signature cannot leave the shim agreeing with it by accident.

WHAT THE SHIM IS: the five primitives tinygrad's CPU backend also needs and
Bend cannot express -- `malloc`, a word store, a word load, a call through a
kernel POINTER, and the kernel's own address. Every one of them is a `law` with
`import "./shim.c"` and nothing else, so `bend -o` inlines the shim and `cc`
links the port's kernel object against it.

WHY THE KERNEL POINTER IS A `Nat`: it is the one thing that could not work, and
it is measured rather than assumed. `malloc` on this machine returns 0x1008xxxxx
to 0x1047xxxxx and the stack sits at 0x16bd36284 -- 4.3e9 to 6.2e9, against a
`Nat` ceiling of 2^51-1 = 2.25e15. MEASURED in `addrprobe.c`, three runs, both
addresses below 2^48.

    .venv/bin/python .agents/slop/portexec/gen_ffi.py <outdir> <row> <wordkey> <nkern>
"""
import json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from exec_harness import port_rows, signature, which_are_outputs

# FIVE LAWS. `kaddr` is the kernel's OWN address and it is round-tripped through
# a `Nat` before it is called, so the pointer survives Bend rather than never
# leaving C.
SHIM = """/* GENERATED BY gen_ffi.py -- the FFI, not the kernel. */
/* THE PROTOTYPE BELOW IS THE PORT'S OWN SIGNATURE LINE, COPIED OUT OF ITS
   EMITTED C BY PARSING. Do not edit: gen_ffi.py writes it from the port. */
{proto}

typedef void (*port_kern_t)({ptypes});

Term kaddr_run(Env e, Term* f, IoWork* w) {{ return (Term)(uintptr_t)({fname}); }}
Term kmalloc_run(Env e, Term* f, IoWork* w) {{ return (Term)(uintptr_t)calloc((size_t)f[0], 1); }}
Term kstore_run(Env e, Term* f, IoWork* w) {{ *(volatile unsigned int*)(uintptr_t)f[0] = (u32)f[1]; return 0; }}
Term kload_run(Env e, Term* f, IoWork* w) {{ return (Term)*(volatile unsigned int*)(uintptr_t)f[0]; }}
Term klaunch_run(Env e, Term* f, IoWork* w) {{
  ((port_kern_t)(uintptr_t)f[0])({callargs});
  return 0;
}}

static void __attribute__((constructor)) shim_use(void) {{
  io_eff(CID(kaddr), kaddr_run, 0);
  io_eff(CID(kmalloc), kmalloc_run, 0);
  io_eff(CID(kstore), kstore_run, 0);
  io_eff(CID(kload), kload_run, 0);
  io_eff(CID(klaunch), klaunch_run, 0);
}}
"""


def main():
    out = pathlib.Path(sys.argv[1])
    row = sys.argv[2] if len(sys.argv) > 2 else "kern2 CLANG      "
    wordkey = sys.argv[3] if len(sys.argv) > 3 else "stage1_in_words"
    orc = json.loads((out / "oracle.json").read_text())
    kernel = port_rows(out / "port-rows.txt")[row]
    fname, args = signature(kernel)
    in_name = which_are_outputs(kernel, args)
    names = [b for _, b in args]
    proto = f"extern void {fname}({', '.join(a + ' ' + b for a, b in args)});"
    ptypes = ", ".join(a.replace("restrict", "").strip() for a, _ in args)
    (out / "shim.c").write_text(SHIM.format(
        proto=proto, ptypes=ptypes, fname=fname,
        callargs=", ".join("(void*)(uintptr_t)f[%d]" % (i + 1) for i in range(len(args)))))
    (out / "kernel.c").write_text(orc["vec4_typedef"] + "\n" + kernel +
                                  "\n/* the address of the PORT's own emitted symbol */\n"
                                  f"void* port_kernel_addr(void) {{ return (void*)&{fname}; }}\n")
    print("PORT ROW       :", row.strip())
    print("PORT PROTOTYPE :", proto)
    print("SHIM CALL      :", ", ".join(names))


if __name__ == "__main__":
    main()
