#!/usr/bin/env python3
"""portexec/gen_ffi.py -- GENERATE the shim, the kernel object and the Bend
program for Stage 2 and Stage 3.

THE SHIM'S ABI IS THE PORT'S. `extern void E_4(float* restrict data0_4, float*
restrict data1_4);` is COPIED out of the port's own emitted kernel text by
`exec_harness.signature`, byte for byte, and the function-pointer type and the
call's argument order are derived from that same parse. Nothing about the kernel's
interface is typed here, so the shim cannot agree with the port by accident.

WHY THE SHIM SPLITS THE ADDRESS ONCE AND WHY THE LOOPS CARRY `(hi, lo)` AS
`U32`s.  MEASURED, not designed: **`Nat` is a LINEAR type in bend 2.0.35.** A
`Nat` parameter used twice is a compile error -- `Nat.add(n, Nat.add(n, n))`
fails with `observed : n (consumed more than once)` -- so a buffer address cannot
be threaded through a loop the way a `U32` can, and a `Nat` cursor walked N
times is not spellable in Bend at all.  So the ALLOCATION returns a `Nat` (the
round trip Stage 2 exists to measure), the address is SPLIT ONCE into `(hi, lo)`,
and the loops carry two copyable `U32`s plus a byte offset.  The pointer
arithmetic is one line of C; the loops, the words, the sequencing and the
printing are all Bend.

    .venv/bin/python .agents/slop/portexec/gen_ffi.py <outdir> <row> <wordkey>
"""
import json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from exec_harness import port_rows, signature, which_are_outputs

SHIM_HEAD = """/* GENERATED BY gen_ffi.py -- the FFI and the driver, NOT the kernel. */
#include <stdlib.h>
#include <stdint.h>
static uintptr_t g_ptr;

/* THE LINE BELOW IS THE PORT'S OWN SIGNATURE, COPIED OUT OF ITS EMITTED C BY
   PARSING (exec_harness.signature). Do not hand-edit: gen_ffi.py rewrites it. */
{proto}
typedef void (*port_kern_t)({ptypes});

/* THE ALLOCATION IS C's `calloc`, and the address comes back to Bend as a `Nat`.
   That round trip is what Stage 2 measures: a `Term` is one 64-bit word and a
   Bend `Nat` is a double, so an address above 2^53 could not cross at all.
   MEASURED on this machine (addrprobe.c, three runs): the heap returns
   0x1008xxxxx..0x1047xxxxx and the stack sits at 0x16bd36284 -- 4.3e9 to 6.2e9,
   against a `Nat` ceiling of 2^51-1 = 2.25e15, and inside 2^48 as well. */
Term kmalloc_run(Env e, Term* f, IoWork* w) {{
  g_ptr = (uintptr_t)calloc((size_t)f[0], 1);
  return (Term)g_ptr;
}}
/* hi/lo ONCE, so Bend's loops can carry two COPYABLE `U32`s -- see the header. */
Term khi_run(Env e, Term* f, IoWork* w) {{ return (Term)(u32)(g_ptr >> 32); }}
Term klo_run(Env e, Term* f, IoWork* w) {{ return (Term)(u32)(g_ptr & 0xffffffffu); }}

/* (hi, lo, byte_offset, word) */
Term kstore_run(Env e, Term* f, IoWork* w) {{
  unsigned int* p = (unsigned int*)(((uint64_t)f[0] << 32) | f[1]);
  p[f[2] / 4u] = (u32)f[3];
  return 0;
}}
/* (hi, lo, byte_offset) -> the word there */
Term kread_run(Env e, Term* f, IoWork* w) {{
  unsigned int* p = (unsigned int*)(((uint64_t)f[0] << 32) | f[1]);
  return (Term)p[f[2] / 4u];
}}
/* THE KERNEL IS CALLED THROUGH A POINTER THAT CAME BACK FROM C AS A `Nat`, and
   each BUFFER IS AN (hi, lo) PAIR IN THE PORT'S OWN PARAMETER ORDER. */
Term klaunch_run(Env e, Term* f, IoWork* w) {{
  ((port_kern_t)(uintptr_t)f[0])({spread});
  return 0;
}}

static void __attribute__((constructor)) shim_use(void) {{
  io_eff(CID(kmalloc), kmalloc_run, 0);
  io_eff(CID(khi), khi_run, 0);
  io_eff(CID(klo), klo_run, 0);
  io_eff(CID(kstore), kstore_run, 0);
  io_eff(CID(kread), kread_run, 0);
  io_eff(CID(klaunch), klaunch_run, 0);
}}
"""

# (name, law type, bend def parameter names). Written out rather than derived,
# because a law's arity is part of its interface and deriving it from the type
# string is a parsing exercise with no payoff at six rows.
LAWS = [("kaddr", "IO(Nat)", ""),
        ("kmalloc", "Nat -> IO(Nat)", "n"),
        ("khi", "IO(U32)", ""),
        ("klo", "IO(U32)", ""),
        ("kstore", "U32 -> U32 -> U32 -> U32 -> IO(U32)", "hi, lo, off, w"),
        ("kread", "U32 -> U32 -> U32 -> IO(U32)", "hi, lo, off")]

BEND = """import Base

# THE PRIMITIVES, AND NOTHING ELSE. Each `def` is a `law` body whose only content
# is `import "./shim.c"`, which is how `bend -o` INLINES the shim: in
# ffi-experiment it sat at line 3018 of a 78,426-byte out.c. The shim must not be
# concatenated by hand -- that is a redefinition.
{lawndecls}

# THE INPUT BYTES AS u32 BIT PATTERNS, copied by gen_ffi.py out of the JSON
# CPython wrote. No word here is typed by a human, so a typo cannot masquerade as
# a port bug.
def in_words() -> List<&2, U32>: [{words}]

# THE OUTPUT INDICES, as a LIST rather than a counter: a `match` on a `Nat`
# parameter has no `case 0` arm (MEASURED -- `expected : a constructor of Nat`),
# and a list is also what keeps the index LINEAR: `i` is consumed exactly once,
# by `Nat.show`.
def out_ix() -> List<&2, Nat>: [{ixs}]

# EVERY SCALAR IS A LINEAR TYPE IN bend 2.0.35 -- MEASURED, all of these fail with
# `observed : x (consumed more than twice)`:
#     def f(n: U32) -> U32: U32.add(n, n)
#     def f(n: Nat) -> Nat: Nat.add(n, Nat.add(n, n))
# `Nat.add` / `Nat.sub` additionally take `n`-suffixed literals, and a bare `+`
# operator is REFUSED (`a type for this operator (write (a + b : Nat))`). The fix
# is `+` ON THE BINDER, not on the type: `def f(+n: U32) -> U32: U32.add(n, n)`
# compiles and prints 6. `+D` sets D's leading quantities to `&2`, so a `+`
# parameter may be read twice. That is why the buffer ADDRESSES never leave Bend.
def fill.go(xs: List<&2, U32>, +hi: U32, +lo: U32, +off: U32) -> IO(Unit):
  match xs:
    case Nil{{}}: IO.pure(Unit, Unit{{}})
    case h <> t:
      do IO<Unit>:
      _ : U32 <- kstore(hi, lo, off, h)
      fill.go(t, hi, lo, U32.add(off, 4))

def dump.go(ixs: List<&2, Nat>, +hi: U32, +lo: U32, +off: U32) -> IO(Unit):
  match ixs:
    case Nil{{}}: IO.pure(Unit, Unit{{}})
    case i <> t:
      do IO<Unit>:
      v : U32 <- kread(hi, lo, off)
      IO.print("WORD " ++ Nat.show(i) ++ " " ++ U32.show(v))
      dump.go(t, hi, lo, U32.add(off, 4))
"""


def bend_run(nwords, nbytes, inputs, launch_nats, lawndecls):
  """THE WHOLE ORCHESTRATION IS IN BEND: allocate, split, fill, LAUNCH THE KERNEL
  BY POINTER, read the words back, print them.  The C side holds no words.

  `inputs` is `[(binder, [words]), ...]` -- one entry per input buffer, so the
  NUMBER OF BUFFERS IS THE PORT'S SIGNATURE and not a constant here."""
  tail = ["\ndef go() -> IO(Unit):", "  do IO<Unit>:",
          "  +k : Nat <- kaddr()", '  IO.print("KERNEL_NAT " ++ Nat.show(k))']
  tail += ["  +dst : Nat <- kmalloc(NBYTESn)", '  IO.print("DST_NAT " ++ Nat.show(dst))']
  # THE (hi, lo) PAIR IS TAKEN IMMEDIATELY, BEFORE THE NEXT ALLOCATION. `khi`/`klo`
  # read a C static that `kmalloc` OVERWRITES, so reading them after the next
  # allocation makes two buffers the SAME pointer. MEASURED: the first version of
  # this program did exactly that and the lane was GREEN for the wrong reason --
  # the kernel was self-aliased, and a self-aliased call of a one-input kernel
  # returns the correct answer by construction. Only the "fill the wrong buffer"
  # negative control exposed it, because that control was supposed to turn the
  # lane red and did not.
  tail += ["  +dst_hi : U32 <- khi()", "  +dst_lo : U32 <- klo()"]
  for tag, _ in inputs:
    tail += [f"  +{tag} : Nat <- kmalloc(NBYTESn)", f'  IO.print("{tag.upper()}_NAT " ++ Nat.show({tag}))',
             f"  +{tag}_hi : U32 <- khi()", f"  +{tag}_lo : U32 <- klo()",
             f"  fill.go(in_{tag}(), {tag}_hi, {tag}_lo, 0)"]
  tail += [f"  _ : U32 <- klaunch(LAUNCHARGS)",
           f"  dump.go(out_ix(), dst_hi, dst_lo, 0)", '  IO.print("DONE 1")', "",
           "def main() -> IO(Unit):", "  do IO<Unit>:", "  _ : Unit <- go()", '  IO.print("")']
  return ("\n".join(tail)
          .replace("NBYTESn", str(nbytes) + "n")
          .replace("LAUNCHARGS", ", ".join(["k"] + list(launch_nats))))


def main():
    out = pathlib.Path(sys.argv[1])
    row = sys.argv[2] if len(sys.argv) > 2 else "kern2 CLANG      "
    mode = sys.argv[3] if len(sys.argv) > 3 else "row"
    orc = json.loads((out / "oracle.json").read_text())
    if mode == "mm":
        # THE KERNEL COMES FROM `emit-mm.bend`, WHICH CALLED THE PORT'S OWN
        # `render_kernel` WITH FOUR BUFFERS. Read out of that file between the two
        # markers; nothing here is transcribed.
        t = (out / "mm-rows.txt").read_text()
        kernel = t[t.index("KERNEL_BEGIN") + 12:t.index("KERNEL_END")].strip("\n")
        words = {"A": orc["mm_A"], "B": orc["mm_B"], "C": orc["mm_C"]}
        inputs = [(k, words[k]) for k in ("A", "B", "C")]
    else:
        key = row if row != "kern2 CLANG      " else "stage1_in_words"
        kernel = port_rows(out / "port-rows.txt")[row]
        inputs = [("src", orc[key if key in orc else "stage1_in_words"])]
    fname, args = signature(kernel)
    names = [b for _, b in args]
    proto = f"extern void {fname}({', '.join(a + ' ' + b for a, b in args)});"
    ptypes = ", ".join(a.replace("restrict", "").strip() for a, _ in args)
    spread = ", ".join("(float*)((((uint64_t)f[%d] << 32) | f[%d]))" % (1 + 2 * k, 2 + 2 * k)
                       for k in range(len(args)))
    # `kaddr` needs the kernel's own address, which lives in the KERNEL object.
    # The replace target carries SINGLE braces because `.format` has already
    # unescaped the template's `{{` by this point -- an earlier version searched
    # for `{{` and silently inserted nothing, which an assert now catches.
    shim = SHIM_HEAD.format(proto=proto, ptypes=ptypes, spread=spread).replace(
        "static void __attribute__((constructor)) shim_use(void) {",
        "extern void* port_kernel_addr(void);\n"
        "Term kaddr_run(Env e, Term* f, IoWork* w) { return (Term)(uintptr_t)port_kernel_addr(); }\n\n"
        "static void __attribute__((constructor)) shim_use(void) {\n"
        "  io_eff(CID(kaddr), kaddr_run, 0);")
    assert "CID(kaddr)" in shim, "kaddr was not wired in -- the replace target moved"
    (out / "shim.c").write_text(shim)
    (out / "kernel.c").write_text(orc["vec4_typedef"] + "\n" + kernel +
                                  f"\n/* the address of the PORT's own emitted symbol */\n"
                                  f"void* port_kernel_addr(void) {{ return (void*)&{fname}; }}\n")
    launch_ty = "Nat -> " + " -> ".join(["U32"] * (2 * len(args))) + " -> IO(U32)"
    launch_ps = ", ".join(["kp"] + [f"b{k}_{h}" for k in range(len(args)) for h in ("hi", "lo")])
    lawndecls = "\n".join(f"law {n}:\n  {t}\n\ndef {n}({p}):\n  import \"./shim.c\"\n"
                          for n, t, p in LAWS + [("klaunch", launch_ty, launch_ps)])
    decls = "".join(f"def in_{t}() -> List<&2, U32>: [{', '.join(str(w) for w in ws)}]\n\n"
                    for t, ws in inputs)
    nwords = len(inputs[0][1])
    hi_lo = (["dst_hi", "dst_lo"] + [f"{t}_{h}" for t, _ in inputs for h in ("hi", "lo")])
    body = BEND.format(lawndecls=lawndecls,
                       words=", ".join(str(w) for w in inputs[0][1]),
                       ixs=", ".join(f"{i}n" for i in range(nwords)))
    body = body.replace("def in_words() -> List<&2, U32>: [" +
                        ", ".join(str(w) for w in inputs[0][1]) + "]", "")
    (out / "run-kernel.bend").write_text(body + decls +
                                         bend_run(nwords, nwords * 4, inputs, hi_lo, lawndecls))
    print("PORT ROW       :", row if mode != "mm" else "emit-mm.bend (the port's own render_kernel, 4 bufs)")
    print("PORT PROTOTYPE :", proto)
    print("SHIM CALL      :", ", ".join(names))
    print("KERNEL BYTES   :", len(kernel))
    print("INPUT WORDS    :", {t: len(ws) for t, ws in inputs})


if __name__ == "__main__":
    main()
