#!/usr/bin/env python3
"""portexec/oracle.py -- THE EXPECTATIONS for the port's EXECUTION lanes.

Nothing here is transcribed. Every number is produced by CALLING CPython:

  * `emit_kernel(dev)` calls `ClangRenderer.render_kernel` (or the base) LIVE,
    with the same arguments `cstyle.bend`'s `kern2_row` is handed, so the C text
    this file writes is upstream's own answer and not a copy of the port's.
  * `expect_words(dev, in_words)` calls CPython arithmetic on the SAME input
    words, in numpy float32, so "what the kernel must produce" is CPython's
    answer rather than a hand-written constant.
  * `numpy_words(x)` is what tinygrad itself would print for a buffer, and
    `run_kernel` is tinygrad's own CPU device -- so lane `py` is the kernel
    running under CPython/tinygrad, not under the port.

The one thing that is NOT a CPython call is the `main()` driver around the
kernel: tinygrad's real driver is `render`'s tail (`compiler_cpu`-built ELF plus
`ctypes.CFUNCTYPE`), which needs a full program. Stage 1 and Stage 3 share ONE
driver shape, written out verbatim into `driver.c`, and it is printed here so
the reader can see that the driver is not a CPython artifact.

    .venv/bin/python .agents/slop/portexec/oracle.py <outdir>
"""
import json, struct, sys, dataclasses
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

from tinygrad.renderer.cstyle import CStyleLanguage, ClangRenderer, OpenCLRenderer, MetalRenderer, CUDARenderer, HIPRenderer
from tinygrad.device import Target, Compiled
from tinygrad.uop.ops import UOp, Ops, dtypes
from tinygrad.uop.ops import AddrSpace

import numpy as np

# THE SAME FIXTURE cstyle.bend:1879 `g_kernel()` hands `render_kernel`, and the
# same fixture renderer_oracle.py:508 `BODY` hands upstream. It is an INPUT to
# render_kernel on both sides: neither side generates the body.
BODY = ["  float4 val0 = (*((float4*)((data1_4+0))));",
        "  *((float4*)((data0_4+0))) = (float4){(val0[0]+1.0f)};"]

CALLER = ["// generated by tinybendygrad", "#pragma OPENCL EXTENSION cl_khr_fp16 : enable"]


def bare(cls, arch="TEST"):
  """renderer_oracle.py:128 `_bare`, verbatim in spirit: `__init__` builds a
  COMPILER (clang, nvrtc, hipcc) and that is the runtime layer, not the string
  layer under test. Every attribute `render_kernel` reads is a CLASS attribute
  except `target`, so `__new__` + a hand-set `target` is enough."""
  o = object.__new__(cls)
  o.target = dataclasses.replace(Target(f"TEST {arch}"), arch=arch)
  return o


CLG = bare(ClangRenderer, "x86_64,znver2")
CS = bare(CStyleLanguage)
DEVS = {"BASE": CS, "CLANG": CLG}


def bufs(dtype=dtypes.f32, vol0=False):
  return [("data0_4", (UOp.param(0, dtype, (), volatile=vol0), True)),
          ("data1_4", (UOp.param(1, dtype, ()), True))]


def emit_kernel(dev, fname="E_4", body=None, prefix=None, vol0=False):
  """CPython's own `render_kernel` call. Returns the C text."""
  return DEVS[dev].render_kernel(fname, BODY if body is None else body,
                                 bufs(vol0=vol0), [], prefix)


# ---------------------------------------------------------------------------
# WHAT THE KERNEL MUST COMPUTE. `(float4){(val0[0]+1.0f)}` is a C compound
# literal with ONE initializer, so the three unlisted lanes are ZERO -- that is
# a fact about C, not about this project, and it is what makes the expected
# words checkable without running anything.
def expect_words(dev, in_words):
  """CPython arithmetic for the body above, in float32."""
  if dev != "CLANG":
    raise SystemExit(f"expect_words is only written for CLANG, not {dev}")
  x = np.frombuffer(struct.pack(f"<{len(in_words)}I", *in_words), dtype=np.float32).copy()
  out = np.zeros(4, dtype=np.float32)
  out[0] = np.float32(x[0] + np.float32(1.0))     # val0[0]+1.0f
  return [int(v) for v in out.view(np.uint32)]


def words_of(floats):
  return [int(v) for v in np.asarray(floats, dtype=np.float32).view(np.uint32)]


def vec4_typedef():
  """THE PREAMBLE `float4` NEEDS, and it is tinygrad's OWN text:
  `ClangRenderer.render_vector_prefix` (cstyle.py:304-307) is the def that emits
  `typedef float float4 __attribute__((aligned(16),ext_vector_type(4)));`, and
  the port has the same def as `emit_vecs`/`g_clang_vecs`. Called here, not
  typed."""
  return CLG.render_vector_prefix(dtypes.f32, 4)


def tinygrad_words(in_words):
  """THE KERNEL RUNNING UNDER CPython's TINYGRAD, on the real CPU device. This
  is the reference the port's execution must match bit for bit, and it is not a
  re-implementation: it is `Compiled` + `CPUProgram` + `ctypes`, i.e. the same
  path `DEV=CPU` takes."""
  from tinygrad.device import Device, TinyELF
  from tinygrad.runtime.ops_cpu import CPUProgram
  src = "\n".join([vec4_typedef(), emit_kernel("CLANG")])
  dev = Device["CPU"]
  target = Target(dev.arch)
  lib = dev.compiler.compile(src)
  sig = (("data0_4", 0, dtypes.f32, (4,)), ("data1_4", 0, dtypes.f32, (4,)))
  prog = dev.runtime(TinyELF(lib, "E_4", target, sig))
  src_w = np.array(struct.unpack("<4f", struct.pack("<4I", *in_words)), dtype=np.float32)
  dst_w = np.zeros(4, dtype=np.float32)
  # THE ARGUMENT ORDER IS THE SIGNATURE'S, READ OFF THE C TEXT and not guessed:
  # `E_4(float* data0_4, float* data1_4)` reads data1_4 and writes data0_4, so
  # the OUT buffer is FIRST. Getting this backwards returned all zeros the first
  # run -- a zero that meant "I wrote the input" and looked like a kernel bug.
  prog(ctypes_ptr(dst_w), ctypes_ptr(src_w))
  return [int(v) for v in dst_w.view(np.uint32)]


def ctypes_ptr(arr):
  import ctypes
  return ctypes.addressof(ctypes.c_char.from_buffer(arr))


def main():
  out = Path(sys.argv[1] if len(sys.argv) > 1 else ROOT / "runs/portexec")
  out.mkdir(parents=True, exist_ok=True)
  res = {"clang_kernel": emit_kernel("CLANG"), "base_kernel": emit_kernel("BASE"),
         "clang_kernel_vol0": emit_kernel("CLANG", vol0=True),
         "clang_kernel_caller": emit_kernel("CLANG", prefix=CALLER),
         "vec4_typedef": vec4_typedef()}
  # THE E2E MATMUL, AND EVERY WORD OF IT COMES FROM `e2e_mm.py`'s OWN RECORD.
  # `checks/e2e-mm-oracle.json` is that script's output: `mats.A/B/Cm` are the
  # three 8x8 f32 inputs as u32 bit patterns and `answer_u32` is the 64-word answer
  # for `(A @ B) @ Cm`. Re-running `e2e_mm.py` is left to `e2e.sh`; this lane READS
  # the record rather than recomputing, so the two lanes cannot drift. THE RECORD
  # MOVED OUT OF THE IGNORED `runs/` to the TRACKED `checks/` -- see
  # `.agents/slop/runsgate/REPORT.md`; `ROOT` is the copy's own root under the
  # controls, so the plant lives at `<copy>/checks/e2e-mm-oracle.json`.
  e2e = ROOT / "checks/e2e-mm-oracle.json"
  if e2e.exists():
    d = json.loads(e2e.read_text())
    res["mm_A"], res["mm_B"], res["mm_C"] = d["mats"]["A"], d["mats"]["B"], d["mats"]["Cm"]
    res["mm_expect_words"] = d["answer_u32"]
    res["mm_source"] = str(e2e.relative_to(ROOT))
  else:
    # NO e2e RECORD: say so loudly rather than quietly substituting our own
    # matmul, which would make the comparison against "e2e_mm.py's words" a
    # comparison against a different program.
    res["mm_missing"] = f"{e2e} is absent -- run .agents/slop/e2e_mm.py first"
  dy = [-2.0, -1.5, -0.75, -0.5, -0.25, 0.25, 0.5, 1.5]
  mat = [[dy[(r * 8 + c) % 8] for c in range(8)] for r in range(8)]
  res["mm_mat"] = mat
  res["mm_in_words"] = words_of([v for row in mat for v in row])
  res["stage1_in_words"] = words_of([-2.0, 1.5, 0.25, -0.75])
  res["stage1_expect_words"] = expect_words("CLANG", res["stage1_in_words"])
  res["tinygrad_stage1_words"] = tinygrad_words(res["stage1_in_words"])
  (out / "oracle.json").write_text(json.dumps(res, indent=1))
  for k in ("clang_kernel", "base_kernel", "vec4_typedef"):
    (out / f"cpython-{k}.c").write_text(res[k] + "\n")
  print("ORACLE WRITTEN", out / "oracle.json")
  print("clang kernel bytes:", len(res["clang_kernel"]))
  print("stage1 in   words:", res["stage1_in_words"])
  print("stage1 CPython expect:", res["stage1_expect_words"])
  print("stage1 tinygrad/DEV=CPU:", res["tinygrad_stage1_words"])
  print("stage1 agree:", res["stage1_expect_words"] == res["tinygrad_stage1_words"])
  if "mm_expect_words" in res:
    print("mm words from :", res["mm_source"], "->", len(res["mm_expect_words"]), "answer words")
  else:
    print("mm NO RECORD  :", res["mm_missing"])


if __name__ == "__main__":
  main()
