#!/usr/bin/env python3
"""GENERATED by bc-u32-gen.py -- DO NOT HAND-EDIT. The CPython lane of the
`bitcast_dims` gate. Every expectation is CALLED, never typed: it is the real tinygrad
BITCAST arm (ops.py:390-396) reached through `Tensor.bitcast`.

ONE string per row and never empty: `raise`, or `[dim,...]` rendered from CPython's own
post-bitcast shape.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from bc_u32_table import ROWS, cpython, render  # noqa: E402

if __name__ == "__main__":
    for name, dim, inp, out in ROWS:
        print(f"{name}={render(cpython(dim, inp, out))}")
