#!/usr/bin/env python3
"""CPython oracle for the I64 -> F32 conversion. WRITES BOTH SIDES' TABLE.

    .venv/bin/python .agents/slop/wk-f32-rows.py

The unit is `wk_i64_to_f32` (uop/weak.bend:271), and it is the primitive every
`weakint -> weakfloat` promotion goes through, so `tanh` is held behind it and so is
anything else that widens an int constant.

THE REFERENCE IS `float(int)`, and that is the whole point of the gate. CPython's
`float` of an int is CORRECTLY ROUNDED to the nearest f32, and the port's implementation
is a two-term decomposition `lo + sgn(hi) * 2**32` that needs `hi` EXACTLY. f32 has 24
mantissa bits and cannot represent a 32-bit integer exactly above 2**24, so for a
negative value `U32.to_f32(0xFFFFFFFF)` is 2**32 -- correctly rounded -- where the
formula needs 4294967295. MEASURED: both -1 and -2 convert to 4294967296.0.

THE TABLE IS WRITTEN ONCE, HERE, and both sides are generated from it, because a fixture
transcribed twice is a fixture that can be wrong and green. The values are (hi, lo) WORD
PAIRS so every one of them is exact on both sides and nothing has to be re-spelled.

EACH VALUE IS HERE FOR A REASON, and the reasons are not "coverage":

  0, 1, 2                    the trivial arm, where any implementation agrees
  0:16777215, 0:16777216     2**24-1 and 2**24: the last integer f32 holds exactly and
                             the first it does not, so a chunk size of 24 is pinned
  0:16777217                 2**24+1: the first value that must ROUND, and it rounds DOWN
  0:4294967294, 0:4294967295 2**32-2 and 2**32-1, which BOTH round to 2**32 -- the two
                             spellings of the same f32, so a gate that used only one of
                             them could not tell a correct rounding from a truncation
  1:0, 1:1                   2**32 and 2**32+1: just above the boundary the old formula
                             lost, and 2**32+1 must round DOWN to 2**32
  8:0                        2**63, the largest power of two an i64 holds
  2147483647:4294967295       int64.max, nineteen digits of mantissa-relevant range
  4294967295:4294967295      -1: the value the bug is NAMED on
  4294967295:4294967294      -2, which the old formula gets IDENTICALLY to -1
  4294967295:0               -2**32, the boundary of the old formula's collapse
  2147483648:0               int64.min, |x| = 2**63, the largest magnitude
  32768:0, 32768:1           a value whose low bit is the ONLY thing that rounds
"""
import pathlib
import sys
import struct

# (name, hi, lo) as UNSIGNED word pairs.
ROWS = [
    ("z", 0, 0), ("one", 0, 1), ("two", 0, 2),
    ("m24m1", 0, 16777215), ("m24", 0, 16777216), ("m24p1", 0, 16777217),
    ("m32m2", 0, 4294967294), ("m32m1", 0, 4294967295),
    ("m32", 1, 0), ("m32p1", 1, 1),
    ("p63", 8, 0),
    ("i64max", 2147483647, 4294967295),
    ("neg1", 4294967295, 4294967295), ("neg2", 4294967295, 4294967294),
    ("negm32", 4294967295, 0),
    ("i64min", 2147483648, 0),
    ("p45", 32768, 0), ("p45p1", 32768, 1),
]


def signed(hi, lo):
    v = ((hi & 0xFFFFFFFF) << 32) | (lo & 0xFFFFFFFF)
    return v - (1 << 64) if v >> 63 else v


def f32_bits(x):
    return struct.unpack('I', struct.pack('f', float(x)))[0]


def main():
    out = pathlib.Path('.agents/slop/wk-f32-table.txt')
    lines = []
    for nm, hi, lo in ROWS:
        v = signed(hi, lo)
        lines.append(f"{nm}={hi} {lo} {f32_bits(v)}")
    out.write_text('\n'.join(lines) + '\n')

    # the oracle: CPython's own correctly-rounded float()
    for nm, hi, lo in ROWS:
        v = signed(hi, lo)
        print(f"{nm}={f32_bits(v)}")

    # the bend driver: every value as a (hi, lo) pair, transcribed ONCE from the table
    b = pathlib.Path('gates/wk-f32.bend')
    body = ['import Base', 'import ./../tinybendygrad/helpers.bend as H', '',
            '# GENERATED by wk-f32-rows.py -- do not hand-edit. The table lives in',
            '# wk-f32-rows.py and is written once, so the fixture cannot drift between the',
            '# two lanes. Every value is a (hi, lo) WORD PAIR, so nothing is re-spelled as a',
            '# decimal on the Bend side and a value above 2**31 needs no negative literal',
            '# (which is not a term).', '',
            # `p` BEFORE `row`: R-3 wants a def filled before it is used, and a row
            # emitter that calls its own printer is the obvious place to get that backwards.
            'def p(nm: String, v: String) -> IO(Unit): IO.print(String.concat([nm, "=", v]))',
            '',
            'def row(+nm: String, hi: U32, lo: U32) -> IO(Unit):',
            '  p(nm, U32.show(F32.bits(W.wk_i64_to_f32(H.i64_of_hi_lo(hi, lo)))))', '',
            'def rows() -> IO(Unit):', '  do IO<Unit>:']
    # A `do IO<Unit>` block needs a TRAILING EXPRESSION: every `x : Unit <- ...` is a
    # statement, so a block made only of bindings ends where the parser wants a term and
    # bend reports "the keyword 'def' cannot head one". So the LAST row is a bare call.
    letters = [c for c in 'abcdefghijklmnopqrstuvwxyz']
    for i, (nm, hi, lo) in enumerate(ROWS):
        call = f'row("{nm}", {hi}, {lo})'
        body.append(f'    row("{nm}", {hi}, {lo})' if i == len(ROWS) - 1
                    else f'    {letters[i]} : Unit <- {call}')
    body += ['', 'def main() -> IO(Unit): rows()', '']
    # W is weak.bend; the driver lives in slop so it reaches two levels down.
    body[2] = 'import ./../tinybendygrad/uop/weak.bend as W'
    b.write_text('\n'.join(body))
    # TO STDERR, and that is not cosmetic: the gate redirects this script's STDOUT into
    # the oracle row file, so a progress line on stdout becomes a phantom row and the gate
    # reports a DISAGREE that is really a status message.
    print(f"  wrote {out} and {b} with {len(ROWS)} rows", file=sys.stderr, flush=True)


if __name__ == '__main__':
    main()
