#!/bin/zsh
# STAGE 1 -- DOES THE PORT'S EMITTED C COMPILE?
#
# Reproduce:  zsh .agents/slop/cstyle-live/stage1.sh
#
# NOTHING IS PATCHED IN THE REPO TREE. The scratch tree is a COPY of `tinybendygrad/`
# under $TMPDIR (a whole tree, because agent-core.md records that a single-file scratch
# copy cannot resolve a relative import and produced 22 phantom blind spots), and the one
# file added to it is `emit-real.bend`, which calls `cstyle.bend`'s own defs. The live
# `tinybendygrad/renderer/cstyle.bend` is READ ONLY by this script.
#
# THE FOUR STEPS ARE REPORTED SEPARATELY, because "it did not work" is not a result:
#   step1 bend parse/check   step2 cc compile   step3 link   step4 run
set -u
REPO=/Users/cyberistic/src/tries/2026-09-30-tinybendygrad
BEND=$REPO/bin/bend
W="$TMPDIR/cstyle-live"
cd "$W" || exit 1

# ---------------------------------------------------------------- the port's own gate row
# `kern2 CLANG` is the row cstyle-gate.py compares to a live CPython call. It is reproduced
# here by the SAME def with the SAME arguments (`emit_min()`, no vector prefix).
$BEND "$W/tree/tinybendygrad/renderer/emit-real.bend" 2>/dev/null > "$W/live.txt" || {
  echo "step1 bend FAILED for emit-real.bend"; exit 1; }
print -r -- "step1 bend ok  ($(grep -c . "$W/live.txt") live rows from emit-real.bend)"
print -r -- ""
python3 "$REPO/.agents/slop/cstyle-live/extract.py" "$REPO/.agents/slop/cstyle-live/port.txt" \
  'kern2 CLANG' "$W/gate_kern2_clang.c"
python3 "$REPO/.agents/slop/cstyle-live/unlive.py" "$W/live.txt" 'live CLANG full' "$W/live_clang_full.c"
python3 "$REPO/.agents/slop/cstyle-live/unlive.py" "$W/live.txt" 'live BASE full' "$W/live_base_full.c"
python3 "$REPO/.agents/slop/cstyle-live/unlive.py" "$W/live.txt" 'live CLANG fixture' "$W/live_clang_fixture.c"

print -r -- ""
print -r -- "=== is the emitted text the SAME TEXT CPYTHON COMPILED? ==="
# ⚠ AFTER the extraction, never before it. The first version of this block sat above the four
# `unlive.py` calls, so on a clean $TMPDIR it compared against a file that did not exist yet:
#   diff: .../live_clang_full.c: No such file or directory
#   DIFFER:
# A MISSING FILE IS NOT A DIFFERENCE, and a harness that reports one as the other invents a
# finding about the port out of an ordering bug in the harness. MEASURED.
[[ -s $W/live_clang_full.c ]] || { print -r -- "  !! live_clang_full.c is missing or empty"; exit 4; }
(cd "$REPO" && PYTHONPATH=. DEV=CPU python3 "$REPO/.agents/slop/cstyle-live/cstyle-oracle.py" \
   > "$W/cpython_real.c") || { print -r -- "  oracle FAILED"; exit 4; }
# ⚠ AND `cpython_real.c` IS CHECKED AFTER THE ORACLE RAN, never before: the first version of
# this guard tested it for non-emptiness BEFORE the command that creates it, so on a clean
# $TMPDIR it refused to compare a file it had not made yet. A guard that fires on its own
# harness is still a guard that reports nothing useful. MEASURED, twice, in this file.
[[ -s $W/cpython_real.c ]] || { print -r -- "  !! the oracle produced nothing"; exit 4; }
if cmp -s "$W/cpython_real.c" "$W/live_clang_full.c"; then
  print -r -- "  IDENTICAL  sha256 $(shasum -a 256 "$W/live_clang_full.c" | cut -d' ' -f1)"
else
  print -r -- "  DIFFER:"; diff "$W/cpython_real.c" "$W/live_clang_full.c" | sed 's/^/    /'
fi

# ---------------------------------------------------------------- step2: cc
# The invocation is the one tinygrad's own `ClangCompiler.compile` uses
# (tinygrad/runtime/support/compiler_cpu.py:14-17), MINUS the freestanding/ELF flags that
# only matter for a kernel that is going to be `mmap`ed and `dllopen`ed: this one is going
# to be linked into a host program that calls it. Both are recorded so the difference is not
# a silent convenience.
CLANGFLAGS="-c -x c -O2 -fPIC -ffreestanding -fno-math-errno -fno-ident"
for f in live_clang_full live_base_full live_clang_fixture gate_kern2_clang; do
  print -r -- ""
  print -r -- "=== step2 cc -c $f.c ==="
  print -r -- "  \$ cc $CLANGFLAGS $f.c -o $f.o"
  cc $=CLANGFLAGS "$W/$f.c" -o "$W/$f.o" 2>"$W/$f.cc.err"
  rc=$?
  if [[ $rc -eq 0 ]]; then
    print -r -- "  step2 COMPILED ok  ($(wc -c < $W/$f.o | tr -d ' ') bytes of object)"
  else
    print -r -- "  step2 FAILED rc=$rc, $(grep -c 'error:' $W/$f.cc.err) error line(s):"
    grep 'error:' "$W/$f.cc.err" | head -3 | sed 's/^/    /'
  fi
done

# ---------------------------------------------------------------- step3+4
# Only a file that COMPILED gets a driver, and the driver is generated by the script so the
# kernel text itself is never edited: the kernel is `#include`d, so the emitted text is
# compiled as its own translation unit exactly as a compiler would see it.
cat > "$W/driver.c" <<'EOF'
#include <stdio.h>
#include <stdint.h>
void E_4(float* data0_4, float* data1_4);
int main(void) {
  float in[4]  = {1.0f, 2.0f, 3.0f, 4.0f};
  float out[4] = {-1.0f, -1.0f, -1.0f, -1.0f};
  E_4(out, in);
  for (int i = 0; i < 4; i++) printf("out[%d]=%.9g\n", i, out[i]);
  return 0;
}
EOF
for f in live_clang_full live_base_full live_clang_fixture; do
  print -r -- ""
  print -r -- "=== step3+4 link+run $f ==="
  print -r -- "  \$ cc $f.c driver.c -o $f.out && ./$f.out"
  cc "$W/$f.c" "$W/driver.c" -o "$W/$f.out" 2>"$W/$f.link.err"
  if [[ $? -ne 0 ]]; then
    print -r -- "  step3 LINK FAILED:"; head -3 "$W/$f.link.err" | sed 's/^/    /'; continue
  fi
  print -r -- "  step3 LINK ok"
  "$W/$f.out" 2>&1 | sed 's/^/  step4 /'
  print -r -- "  step4 rc=$?"
done