#!/usr/bin/env python3
"""Emit the Bend FIXTURE for autogen.bend: a Data tree carrying every field the
ported `tname`/`typehint`/`gen` read out of libclang.

This is INPUT, not an expectation, and it is generated by CALLING libclang --
never transcribed.  The expectation is `gen()`'s own output, captured separately
by ag-oracle.py, and the two are compared BYTE FOR BYTE.

Emitted shape (one `Ty`/`Cur` per line, id-indexed):
  Ty <id> <kind> <declkind> <anon:0|1> <size> <canon:id|-> <pointee:id|->
     <elem:id|-> <arrsz:N|-> <res:id|-> <f:file>:<line>
     args:<id>,<id>,...
     fields:<nm>#<tyid>#<off>#<bw>#<bf>,...
  Cur <id> <kind> <nm> <ty:id>
"""
import sys, os, re, json
sys.path.insert(0, "/Users/cyberistic/src/tries/2026-09-30-tinybendygrad")
os.environ.setdefault("CLANG", "/opt/homebrew/opt/llvm@20/lib/libclang.dylib")
import ctypes, importlib.util
import tinygrad.runtime.autogen.libclang as clang

spec = importlib.util.spec_from_file_location("ag",
    "/Users/cyberistic/src/tries/2026-09-30-tinybendygrad/tinygrad/runtime/support/autogen.py")
ag = importlib.util.module_from_spec(spec); spec.loader.exec_module(ag)

hdr = os.path.abspath(sys.argv[1])
out = os.path.abspath(sys.argv[2])

TYS, CURS = [], []
tmap_seen, cur_seen = {}, {}


def tid(t):
  k = (int(t.kind), ag.nm(t))
  if k not in tmap_seen:
    tmap_seen[k] = len(TYS)
    TYS.append(None)
  return tmap_seen[k]


def cid(c):
  k = (int(c.kind), ag.nm(c))
  if k not in cur_seen:
    cur_seen[k] = len(CURS)
    CURS.append(None)
  return cur_seen[k]


def fill_t(i, t):
  decl = clang.clang_getTypeDeclaration(t)
  rec = dict(kind=int(t.kind), nm=ag.nm(t),
             declkind=int(decl.kind) if decl is not None and int(decl.kind) else -1,
             anon=bool(clang.clang_Cursor_isAnonymous(decl)),
             size=clang.clang_Type_getSizeOf(t) if int(t.kind) in (clang.CXType_Record,) else -1,
             canon=-1, pointee=-1, elem=-1, arrsz=-1, res=-1,
             args=[], fields=[],
             loc=f"{ag.loc_file(ag.loc(decl))}:{ag.loc_line(ag.loc(decl))}" if decl is not None else "")
  if t.kind == clang.CXType_Typedef: rec["canon"] = tid(clang.clang_getCanonicalType(t))
  if t.kind == clang.CXType_Pointer: rec["pointee"] = tid(clang.clang_getPointeeType(t))
  if t.kind == clang.CXType_ObjCObjectPointer: rec["pointee"] = tid(clang.clang_getPointeeType(t))
  if t.kind == clang.CXType_ConstantArray:
    rec["elem"] = tid(clang.clang_getArrayElementType(t)); rec["arrsz"] = clang.clang_getArraySize(t)
  if t.kind == clang.CXType_IncompleteArray:
    rec["elem"] = tid(clang.clang_getArrayElementType(t))
  if t.kind in ag.fps:
    rec["res"] = tid(clang.clang_getResultType(t))
    rec["args"] = [tid(a) for a in ag.arguments(t)]
  if t.kind == clang.CXType_Record:
    for f, off in ag.all_fields(t):
      ty = clang.clang_getCanonicalType(clang.clang_getCursorType(f))
      bf = clang.clang_Cursor_isBitField(f)
      rec["fields"].append([ag.nm(f), tid(ty), off,
                            clang.clang_getFieldDeclBitWidth(f) if bf else -1,
                            1 if bf else 0])
  TYS[i] = rec
  for j in rec["args"]: fill_t(j, tyof(j))
  for j in (rec["canon"], rec["pointee"], rec["elem"], rec["res"]):
    if j >= 0: fill_t(j, tyof(j))
  for f in rec["fields"]: fill_t(f[1], tyof(f[1]))


TYOBJ = {}


def tyof(i): return TYOBJ[i]


# first pass: register every object, second: fill
idx = clang.clang_createIndex(False, 0)
tu = clang.clang_parseTranslationUnit(idx, os.fspath(hdr).encode(), None, 0, None, 0,
                                      clang.CXTranslationUnit_DetailedPreprocessingRecord)


def build(objs, getnm):
  """objs: list of (kind, spelling, getter)"""
  for i, (k, n, g) in enumerate(objs):
    if k not in tmap_seen:
      tmap_seen[k] = len(TYS); TYS.append(None); TYOBJ[len(TYS) - 1] = g
      cur_seen[k] = len(CURS); CURS.append(None)


def collect_types():
  seen = {}

  def reg(t):
    k = (int(t.kind), ag.nm(t))
    if k in seen: return seen[k]
    i = tid(t); seen[k] = i; TYOBJ[i] = t
    decl = clang.clang_getTypeDeclaration(t)
    if t.kind == clang.CXType_Typedef: reg(clang.clang_getCanonicalType(t))
    if t.kind in (clang.CXType_Pointer, clang.CXType_ObjCObjectPointer): reg(clang.clang_getPointeeType(t))
    if t.kind in (clang.CXType_ConstantArray, clang.CXType_IncompleteArray): reg(clang.clang_getArrayElementType(t))
    if t.kind in ag.fps:
      reg(clang.clang_getResultType(t))
      for a in ag.arguments(t): reg(a)
    if t.kind == clang.CXType_Record:
      for f, off in ag.all_fields(t): reg(clang.clang_getCanonicalType(clang.clang_getCursorType(f)))
    return i
  return reg


reg = collect_types()
root = ag.unwrap_cursor(clang.clang_getTranslationUnitCursor(tu))
top = [c for c in ag.children(root) if ag.loc_file(ag.loc(c)) == hdr]

# register every cursor+type the walk will touch
def regc(c):
  k = (int(c.kind), ag.nm(c))
  if k in cid_seen: return
  cid(c); cid_seen[k] = len(CURS); CURS.append(None)
  reg(clang.clang_getCursorType(c))
  if c.kind in (clang.CXCursor_StructDecl, clang.CXCursor_UnionDecl, clang.CXCursor_EnumDecl,
                clang.CXCursor_FunctionDecl, clang.CXCursor_VarDecl):
    for ch in ag.children(c): regc(ch)
cid_seen = {}
for c in top: regc(c)

for i in range(len(TYS)): fill_t(i, TYOBJ[i])

# cursors: name + the TYPE they carry, and their CHILDREN (for struct/enum/func)
CIDX = {}


def cidx(c):
  k = (int(c.kind), ag.nm(c))
  if k not in CIDX:
    CIDX[k] = len(CIDX)
    CURS.append(None)
  return CIDX[k]


def fill_c(i, c):
  kids = []
  if c.kind in (clang.CXCursor_StructDecl, clang.CXCursor_UnionDecl, clang.CXCursor_EnumDecl,
                clang.CXCursor_FunctionDecl, clang.CXCursor_VarDecl):
    kids = [cidx(ch) for ch in ag.children(c)]
  CURS[i] = (int(c.kind), ag.nm(c), cidx_t(clang.clang_getCursorType(c)), kids)


ctmap = {}


def cidx_t(t):
  k = (int(t.kind), ag.nm(t))
  if k not in ctmap: ctmap[k] = len(ctmap)
  return ctmap[k]


for c in top:
  cidx(c); fill_c(cid_seen[(int(c.kind), ag.nm(c))], c)

L = ["# GENERATED by ag-fixture.py from %s -- DO NOT EDIT" % os.path.basename(hdr)]
for i, t in enumerate(TYS):
  L.append("Ty %d %d %d %d %d %d %d %d %d %d %s %s %s" % (
    i, t["kind"], t["declkind"], 1 if t["anon"] else 0, t["size"], t["canon"], t["pointee"],
    t["elem"], t["arrsz"], t["res"], t["loc"],
    ",".join(str(a) for a in t["args"]) or "-",
    ",".join("%s#%d#%d#%d#%d" % tuple(f) for f in t["fields"]) or "-"))
for i, c in enumerate(CURS):
  if c is None: continue
  L.append("Cur %d %d %s %d %s" % (i, c[0], c[1], c[2], ",".join(str(k) for k in c[3]) or "-"))
open(out, "w").write("\n".join(L) + "\n")
print(f"{len(TYS)} types, {len(CURS)} cursors -> {out}")
