#!/usr/bin/env python3
"""MEASUREMENT 2b: WHICH files does autogen.py actually generate?

`autogen/__init__.py` is the driver: every `load("<name>", ...)` arm names one
generated file, and `load` writes it only under REGEN. So the set of `load`
names IS the generator's output set, and it is SMALLER than the directory.
The difference matters: `autogen/am/regs.py` and `autogen/am/pmc.py` are in the
directory but are not made by this generator.
"""
import re, os, collections

ROOT = "/Users/cyberistic/src/tries/2026-09-30-tinybendygrad/tinygrad/runtime"
src = open(os.path.join(ROOT, "autogen", "__init__.py")).read()
# `load("name"` and `load(nm,` / `load(f"..."`
names = set(re.findall(r'load\(\s*"([a-z0-9_]+)"', src))
print("names in `load(\"...\"...)` arms:", len(names))
print("  ", " ".join(sorted(names)))

# the on-disk .py files under autogen/
ondisk = set()
for d, _, fs in os.walk(os.path.join(ROOT, "autogen")):
    for f in fs:
        if f.endswith(".py"):
            rel = os.path.relpath(os.path.join(d, f), os.path.join(ROOT, "autogen"))
            ondisk.add(rel)
names_rel = {n + ".py" for n in names}
print()
print(f"on-disk .py under autogen/: {len(ondisk)}")
in_gen = sorted(ondisk & names_rel)
not_gen = sorted(ondisk - names_rel)
print(f"  GENERATED by autogen.py: {len(in_gen)} files, {sum(sum(1 for _ in open(os.path.join(ROOT,'autogen',f), errors='replace')) for f in in_gen)} lines")
print(f"  NOT generated by autogen.py: {len(not_gen)} files, "
      f"{sum(sum(1 for _ in open(os.path.join(ROOT,'autogen',f), errors='replace')) for f in not_gen)} lines")
for f in not_gen:
    n = sum(1 for _ in open(os.path.join(ROOT, "autogen", f), errors="replace"))
    print(f"      {f:44s} {n:6d}")
print()
print("### the load() arms that are NOT plain names (dynamic / alias):")
for m in re.finditer(r'case "([^"]+)".*?load\((nm|f"[^"]+")', src):
    print("   ", m.group(1), "->", m.group(2))
