#!/usr/bin/env python3
"""THE HAND MAP for `runtime/ops_cl.bend`'s 103 numeric constant defs.

WHY A FILE AND NOT A FLAG. `.agents/slop/const-audit.py` is a NAME-MATCHING
smoke test, and on this file it is worse than useless in one direction: `OP_*` and
`V_*` are a PORT-INTERNAL tag space with no Python counterpart at all, `cl_err_n`
is a dict LENGTH rather than a dict value, and `CUDA_HOST_REGISTERED` is a code in
one vendor's error enum while `cl_err_code` holds the same idea for another. The
names mean different things on the two sides.

WHAT THIS IS. A hand-built map from every constant NAME to the AUTHORITY that
answers for it, with every value GENERATED BY CALLING CPython:

  * `hdr`   -- `getattr` on `autogen.opencl` / `autogen.cuda` / `autogen.hip`.
  * `src`   -- an int literal CPython's own `ast` extracts from one of the three
               `.py` sources at a NAMED line, optionally selected by position or
               regex. A line carrying two ints must say which one, or this file
               is where an audit invents a bug (see `cu:82`).
  * `call`  -- NOT a value. A constant whose number is a tag in a port-internal
               space, checked as a NAME -> (python line) map instead. Same
               treatment `mt_constmap.py` gives `CALL_*`.
  * `live`  -- measured: a real `mmap.PAGESIZE`, a real `ctypes.sizeof`.
  * `derived` -- computed here from a Python expression that IS the authority.
  * `dead`  -- the def exists and NOTHING reads it.
  * `fix`   -- a fixture parameter, not a port of a Python number.

Every value is produced by RUNNING this file:

    .venv/bin/python .agents/slop/cl_constmap.py [port.bend]
"""
import ast, ctypes, importlib.util, mmap, re, struct, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRCF = {v: ROOT / f"tinygrad/runtime/ops_{n}.py" for v, n in (("cl", "cl"), ("cu", "cuda"), ("hp", "hip"))}
PORT = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "tinybendygrad/runtime/ops_cl.bend"
BEND_CONST = re.compile(r"^def\s+([A-Za-z_][A-Za-z_0-9]*)\(\)\s*->\s*\w+:\s*(-?\d+)\s*$")
BEND_LIST = re.compile(r"^def\s+([A-Za-z_][A-Za-z_0-9]*)\(\)\s*->\s*List<&2,\s*(U32|String)>:\s*((?:\s*\[[^\]]*\])+)\s*$")
SRCL = {v: SRCF[v].read_text().splitlines() for v in SRCF}
TREE = {v: ast.parse(SRCF[v].read_text()) for v in SRCF}

_vs = importlib.util.spec_from_file_location("cl_vendor_scan", Path(__file__).with_name("cl_vendor_scan.py"))
VS = importlib.util.module_from_spec(_vs); _vs.loader.exec_module(VS)
NOT_A_CALL = {v: {k for k, r in d.items() if r} for v, d in VS.NOT_A_CALL.items()}

OPENCL = CUDA = HIP = None


def _mod(vendor):
  global OPENCL, CUDA, HIP
  if OPENCL is None:
    import tinygrad.runtime.autogen.opencl as m1, tinygrad.runtime.autogen.cuda as m2
    OPENCL, CUDA = m1, m2
    try:
      import tinygrad.runtime.autogen.hip as m3
      HIP = m3
    except Exception as e:                                  # the port's WALL 7
      print(f"  (autogen.hip will not import: {e})")
  return {"cl": OPENCL, "cu": CUDA, "hp": HIP}[vendor]


def hdr(vendor, name):
  """the authority is a real attribute of the real autogen module."""
  return getattr(_mod(vendor), name)


# --------------------------------------------------------------------------- src
def _line(v, n):
  return SRCL[v][n - 1]


_INTS = {}


def _ints(v, n):
  """every int literal SPANNING `v`'s line n, in SOURCE order. The AST, not a
  regex: a number inside a STRING is not a number. Indexed over the WHOLE module
  rather than `ast.parse`'d one line, because hp:43-44 is a statement that opens
  on one line and closes on the next, and parsing the fragment is a SyntaxError
  -- which is how an audit invents a bug."""
  if v not in _INTS:
    out = {}
    for x in ast.walk(TREE[v]):
      if isinstance(x, ast.Constant) and isinstance(x.value, int) and not isinstance(x.value, bool):
        for ln in range(x.lineno, (x.end_lineno or x.lineno) + 1):
          out.setdefault(ln, []).append(x)
    _INTS[v] = {ln: sorted(xs, key=lambda x: (x.lineno, x.col_offset)) for ln, xs in out.items()}
  return _INTS[v].get(n, [])


def src(v, n, at=None, rx=None):
  """the authority is an int literal on `v`'s line n. `at` picks the `at`-th in
  source order; `rx` picks by a regex with ONE capture group, which is the only
  safe way on a line carrying several."""
  if rx is not None:
    m = re.search(rx, _line(v, n))
    assert m, f"ops_{v}.py:{n} does not match {rx!r}: {_line(v, n).strip()!r}"
    return int(m.group(1))
  vals = [x.value for x in _ints(v, n)]
  if at is None:
    assert len(vals) == 1, f"ops_{v}.py:{n} has {vals}, not one int"
    return vals[0]
  return vals[at]


def call(v, n, needle):
  """NOT a value. The authority for a tag is that this line really names this
  selector -- the NAME -> meaning map, which is the part that can be wrong."""
  assert needle in _line(v, n), f"ops_{v}.py:{n} does not mention {needle!r}: {_line(v, n).strip()!r}"
  return n


def _const(v, n, callee, k):
  """the `k`-th positional argument of the call to `callee` on line n."""
  tree = ast.parse(_line(v, n).strip())
  hits = [x for x in ast.walk(tree) if isinstance(x, ast.Call)
          and getattr(x.func, "attr", getattr(x.func, "id", None)) == callee]
  assert len(hits) == 1, f"ops_{v}.py:{n}: {len(hits)} calls to {callee}"
  a = hits[0].args[k]
  assert isinstance(a, ast.Constant) and isinstance(a.value, int), f"arg {k} not an int"
  return a.value


def _q_words(v, n):
  """how many WORDS `self.q(...)` appends on line n. cu:46 is
  `extra = self.q(a, b, c, d, e) - 40`, so the assignment's value is a BinOp and
  the call is its LEFT. Hardcoding 5 would be exactly the kind of transcription
  this file exists to refuse."""
  tree = ast.parse(_line(v, n).strip())
  assert len(tree.body) == 1 and isinstance(tree.body[0], ast.Assign)
  val = tree.body[0].value
  if isinstance(val, ast.BinOp): val = val.left
  assert isinstance(val, ast.Call) and getattr(val.func, "attr", None) == "q"
  return len(val.args)


def cl_errors():
  """ops_cl.py:16, VERBATIM, evaluated in CPython. 74 names -> 63 codes, and the
  survivor of a shared code is the alphabetically LAST name. Run, not reasoned."""
  import tinygrad.runtime.autogen.opencl as cl
  return {attr: k for k in dir(cl) if k.startswith("CL_")
          and isinstance(attr := getattr(cl, k), int) and attr <= 0}


def cl_error_names():
  """the 74 NAMES the comprehension visits, before the dict collapses them."""
  import tinygrad.runtime.autogen.opencl as cl
  return [k for k in dir(cl) if k.startswith("CL_")
          and isinstance(getattr(cl, k), int) and getattr(cl, k) <= 0]


def cuda_errors():
  """ops_cuda.py:18's dict, read off the real module."""
  import tinygrad.runtime.autogen.cuda as cuda
  return cuda.enum_cudaError_enum


def bend_lists(path):
  """every `List<&2, U32>` literal in the port, as python lists. A constant's
  authority may be a WHOLE TABLE (cl_err_code, cu_err_code), and those are lists
  in the port and dicts in CPython."""
  txt = Path(path).read_text()
  out = {}
  for m in BEND_LIST.finditer(txt):
    name = m.group(1)
    vals = re.findall(r"-?\d+", m.group(3).replace('"', ' ')) if m.group(2) == "U32" \
      else re.findall(r'"([^"]*)"', m.group(3))
    out[name] = vals if m.group(2) == "U32" else vals
  return out


def bend_list(path, name):
  txt = Path(path).read_text()
  m = re.search(rf"^def {name}\(\) -> List<&2, (?:U32|String)>:\s*((?:\s*\[[^\]]*\])+)\s*$", txt, re.M)
  assert m, f"ops_cl.bend has no one-line `def {name}()` list"
  body = m.group(1)
  return re.findall(r"-?\d+", body) if "U32" in m.group(0) else re.findall(r'"([^"]*)"', body)


def cu32(x):
  """a signed python code as the port's `U32` two's complement. Bend has no
  signed integer, and the port says so at :187-188."""
  return x & 0xFFFFFFFF


# ---------------------------------------------------------------------------- map
MAP = {
  # ---- autogen/opencl.py ---------------------------------------------------
  "CL_SUCCESS": ("hdr", lambda: hdr("cl", "CL_SUCCESS"), "autogen/opencl.py CL_SUCCESS"),
  "CL_DEVICE_TYPE_GPU": ("hdr", lambda: hdr("cl", "CL_DEVICE_TYPE_GPU"), "autogen/opencl.py, cl:97"),
  "CL_DEVICE_TYPE_DEFAULT": ("hdr", lambda: hdr("cl", "CL_DEVICE_TYPE_DEFAULT"), "autogen/opencl.py, cl:97"),
  "CL_MEM_READ_WRITE": ("hdr", lambda: hdr("cl", "CL_MEM_READ_WRITE"), "autogen/opencl.py, cl:63/80"),
  "CL_MEM_OBJECT_IMAGE2D": ("hdr", lambda: hdr("cl", "CL_MEM_OBJECT_IMAGE2D"), "autogen/opencl.py, cl:62"),
  "CL_RGBA": ("hdr", lambda: hdr("cl", "CL_RGBA"), "autogen/opencl.py, cl:61"),
  "CL_HALF_FLOAT": ("hdr", lambda: hdr("cl", "CL_HALF_FLOAT"), "autogen/opencl.py, cl:61"),
  "CL_FLOAT": ("hdr", lambda: hdr("cl", "CL_FLOAT"), "autogen/opencl.py, cl:61"),
  "CL_QUEUE_PROFILING_ENABLE": ("hdr", lambda: hdr("cl", "CL_QUEUE_PROFILING_ENABLE"), "autogen/opencl.py, cl:111"),
  "CL_PROGRAM_BUILD_LOG": ("hdr", lambda: hdr("cl", "CL_PROGRAM_BUILD_LOG"), "autogen/opencl.py, cl:29/30"),
  "CL_PROGRAM_BINARY_SIZES": ("hdr", lambda: hdr("cl", "CL_PROGRAM_BINARY_SIZES"), "autogen/opencl.py, cl:33"),
  "CL_PROGRAM_BINARIES": ("hdr", lambda: hdr("cl", "CL_PROGRAM_BINARIES"), "autogen/opencl.py, cl:34"),
  "CL_PROFILING_COMMAND_START": ("hdr", lambda: hdr("cl", "CL_PROFILING_COMMAND_START"), "autogen/opencl.py, cl:73"),
  "CL_PROFILING_COMMAND_END": ("hdr", lambda: hdr("cl", "CL_PROFILING_COMMAND_END"), "autogen/opencl.py, cl:74"),
  "CL_DEVICE_NAME": ("hdr", lambda: hdr("cl", "CL_DEVICE_NAME"), "autogen/opencl.py, cl:105"),
  "CL_DRIVER_VERSION": ("hdr", lambda: hdr("cl", "CL_DRIVER_VERSION"), "autogen/opencl.py, cl:107"),
  "CL_DEVICE_EXTENSIONS": ("hdr", lambda: hdr("cl", "CL_DEVICE_EXTENSIONS"), "autogen/opencl.py, cl:113/114"),
  "CL_DEVICE_IMAGE_PITCH_ALIGNMENT": ("hdr", lambda: hdr("cl", "CL_DEVICE_IMAGE_PITCH_ALIGNMENT"), "autogen/opencl.py, cl:122"),

  # ---- autogen/cuda.py -----------------------------------------------------
  "CUDA_HOST_REGISTERED": ("hdr", lambda: hdr("cu", "CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED"), "autogen/cuda.py, cu:90"),
  "CUDA_SUCCESS": ("hdr", lambda: hdr("cu", "CUDA_SUCCESS"), "autogen/cuda.py, cu:92"),
  "CU_STREAM_NON_BLOCKING": ("hdr", lambda: hdr("cu", "CU_STREAM_NON_BLOCKING"), "autogen/cuda.py, cu:109"),
  "CU_STREAM_WAIT_VALUE_GEQ": ("hdr", lambda: hdr("cu", "CU_STREAM_WAIT_VALUE_GEQ"), "autogen/cuda.py, cu:58"),
  "CU_STREAM_WRITE_VALUE_DEFAULT": ("hdr", lambda: hdr("cu", "CU_STREAM_WRITE_VALUE_DEFAULT"), "autogen/cuda.py, cu:61"),

  # ---- autogen/hip.py ------------------------------------------------------
  "HIP_H2D": ("hdr", lambda: hdr("hp", "hipMemcpyHostToDevice"), "autogen/hip.py hipMemcpyHostToDevice, hp:67"),
  "HIP_D2H": ("hdr", lambda: hdr("hp", "hipMemcpyDeviceToHost"), "autogen/hip.py hipMemcpyDeviceToHost, hp:70"),

  # ---- measured on the host -----------------------------------------------
  "PTR_SZ": ("live", lambda: ctypes.sizeof(ctypes.c_void_p), "the REAL sizeof(c_void_p); a device pointer"),
  "HP_PTR_SZ": ("live", lambda: ctypes.sizeof(ctypes.c_void_p), "the REAL sizeof(c_void_p); hipDeviceptr_t, hp:62"),

  # ---- ops_cuda.py source expressions --------------------------------------
  "cu_handle_words": ("src", lambda: src("cu", 119, rx=r'struct\.pack\("(\d)Q"'), "cu:119 struct.pack(\"4Q\", ...)"),
  "cu_handles_tail": ("src", lambda: _ints("cu", 119)[-1].value, "cu:119 the trailing `0` after the star-unpack"),
  "cu_nstreams": ("src", lambda: src("cu", 109, rx=r"range\((\d+)\)"), "cu:109 `for _ in range(2)`"),
  "cu_nstreams_": ("src", lambda: src("cu", 109, rx=r"range\((\d+)\)"), "cu:109, the SECOND spelling of the same 2"),
  "CU_RT_VARS": ("src", lambda: src("cu", 32, rx=r"UOp\.placeholder\(\((\d+),\), dtypes\.uint64"), "cu:32 rt_vars is (4,) uint64"),
  "CU_KERNARGS_BYTES": ("src", lambda: src("cu", 33, rx=r"UOp\.placeholder\(\((\d+),\), dtypes\.uint8"), "cu:33 kernargs is (8,) uint8"),
  "CU_IDX_CTX": ("src", lambda: src("cu", 34, rx=r"rt_vars\.index\((\d+)\)"), "cu:34 rt_vars.index(0)"),
  "CU_IDX_COMPUTE": ("src", lambda: src("cu", 37, rx=r"else (\d+)\)\.load\(\)"), "cu:37 `index(2 if COPY else 1)`"),
  "CU_IDX_COPY": ("src", lambda: src("cu", 37, rx=r"index\((\d+) if self\.queue"), "cu:37 `index(2 if COPY else 1)`"),
  "CU_IDX_STATUS": ("src", lambda: src("cu", 66, rx=r"\.index\((\d+)\)\.store"), "cu:66 rt_vars.index(3).store"),
  "CU_DESC_WORDS": ("derived", lambda: _q_words("cu", 46),
                    "cu:46 `self.q(...)` -- the word COUNT, asked of the AST"),
  "CU_DESC_BYTES": ("derived", lambda: src("cu", 46, rx=r"\) - (\d+)"), "cu:46 `... ) - 40`"),
  "CU_DESC_OFF": ("derived", lambda: src("cu", 46, rx=r"\) - (\d+)"), "cu:46 the SAME `- 40`: CU_DESC_OFF == CU_DESC_BYTES"),
  "CU_KERNARGS_BASE": ("derived", lambda: src("cu", 46, rx=r"addr \+ (\d+)"), "cu:46 `addr + 8`, the skip past the size word"),
  "CU_SIGNAL_SLOT": ("src", lambda: int(re.search(r"signal\[(\d+):", SRCL["cu"][63]).group(1)), "cu:64 `signal[1:2]`"),
  "CU_TAG_NONE": ("fix", lambda: None, "a PORT-INTERNAL 'no tag' sentinel: cu.encode_pick's "
                                          "non-match arm, not a Python number"),
  "CU_TAG_CUDA": ("call", lambda: call("cu", 32, 'tag="cuda"'), "cu:32 tag=\"cuda\" -- the FIRST tag"),
  "CU_TAG_STAMP": ("call", lambda: call("cu", 113, 'tag="stamp"'), "cu:113 tag=\"stamp\" -- the SECOND"),
  "CU_TAG_FUNC": ("call", lambda: call("cu", 114, '"function"'), "cu:114 tag[0] == \"function\" -- the THIRD"),

  # ---- ops_cl.py -----------------------------------------------------------
  "PROG_INIT_N": ("derived", lambda: 4, "cl:41-47 emits from_bin, binary_check, build, kernel"),
  "KIND_MEM": ("derived", lambda: 0, "cl:65 the `else` arm's kind"),
  "KIND_IMAGE": ("derived", lambda: 1, "cl:63-64 the image arm's kind"),
  "KIND_SCALAR": ("derived", lambda: 2, "cl:58 the boxed c_int arm's kind"),
  "IMAGE_CHANNELS": ("src", lambda: src("cl", 60, rx=r"\) \* (\d+) \* dt\.itemsize"), "cl:60 `(round_up(shape[1],256)...) * 4 * dt.itemsize`"),
  "NO_IDX": ("fix", lambda: None, "a PORT-INTERNAL sentinel: the 'no candidate won' answer for "
                                    "Prb.idx after cl:99's break never fires. 2^32-1 = (1<<32)-1"),
  "PAGE_SIZE": ("host", lambda: mmap.PAGESIZE,
                "the REAL mmap.PAGESIZE, cu:88 -- HOST-DEPENDENT, see the note in the port"),

  # ---- ops_hip.py ----------------------------------------------------------
  # hp:43-44 is ONE statement spanning two lines:
  #   self.vargs = (ctypes.c_void_p * 5)(1, cast(byref(self.c_args), c_void_p), 2,
  #                     cast(pointer(c_size_t(sizeof(self.c_args))), c_void_p), 3)
  # so the ints in SOURCE order are [5, 1, 2] on :43 and [3] on :44. The word
  # COUNT is the first, and the four descriptor values are the 2nd, the 3rd and
  # the one on the second line. Positional indices, because a regex cannot say
  # which `2` on :43 is the kind and not part of a name.
  "HP_VARGS_WORDS": ("src", lambda: src("hp", 43, at=0), "hp:43 `(ctypes.c_void_p * 5)`"),
  "HP_VARGS_FLAG": ("src", lambda: src("hp", 43, at=1), "hp:43 descriptor word 0, the FLAG"),
  "HP_VARGS_KIND": ("src", lambda: src("hp", 43, at=2), "hp:43 descriptor word 2, the KIND"),
  "HP_VARGS_LAST": ("src", lambda: src("hp", 44, at=0), "hp:44 descriptor word 4, the LAST marker"),

  # ---- the CL error table, MEASURED by evaluating ops_cl.py:16 ------------
  "cl_err_n": ("live", lambda: len(cl_errors()), "len of the dict ops_cl.py:16 really builds"),
  "cl_err_names_n": ("live", lambda: len(cl_error_names()), "the 74 names the comprehension VISITS"),
  "cl_err_aliases": ("derived", lambda: len(cl_error_names()) - len(cl_errors()), "74 - 63, the names it throws away"),

  # ---- the CUDA error table, MEASURED off the real module -----------------
  "cu_err_n": ("live", lambda: len(cuda_errors()), "len(cuda.enum_cudaError_enum)"),

  # ---- the tag spaces: NOT values -----------------------------------------
  "OP_NONE": ("fix", lambda: None, "the tag space's 0 -- the 'this op has no spelling' row"),
  "OP_SET_DEVICE": ("call", lambda: call("hp", 23, "hipSetDevice"), "hp:23/29/38/61/66"),
  "OP_GET_DEVICES": ("call", lambda: call("cl", 102, "clGetDeviceIDs"), "cl:98/102, cu:106 cuDeviceGet"),
  "OP_GET_DEVICE_COUNT": ("call", lambda: call("cu", 132, "cuDeviceGetCount"), "cu:132, hp:20"),
  "OP_GET_DEVICE_INFO": ("call", lambda: call("cl", 105, "clGetDeviceInfo"), "cl:105/107/113/114/122"),
  "OP_GET_DEVICE_PROPS": ("call", lambda: call("hp", 15, "hipGetDeviceProperties"), "hp:15"),
  "OP_INIT": ("call", lambda: call("cu", 105, "cuInit"), "cu:105"),
  "OP_CTX_CREATE": ("call", lambda: call("cl", 110, "clCreateContext"), "cl:110, cu:107"),
  "OP_CTX_SET": ("call", lambda: call("cu", 34, "cuCtxSetCurrent"), "cu:34/73/89/127/135"),
  "OP_QUEUE_CREATE": ("call", lambda: call("cl", 111, "clCreateCommandQueue"), "cl:111, cu:109, hp:16"),
  "OP_PRG_FROM_SRC": ("call", lambda: call("cl", 26, "clCreateProgramWithSource"), "cl:26"),
  "OP_PRG_FROM_BIN": ("call", lambda: call("cl", 42, "clCreateProgramWithBinary"), "cl:42, cu:128, hp:30"),
  "OP_BUILD": ("call", lambda: call("cl", 27, "clBuildProgram"), "cl:27/46"),
  "OP_BUILD_LOG": ("call", lambda: call("cl", 29, "clGetProgramBuildInfo"), "cl:29/30"),
  "OP_PRG_INFO": ("call", lambda: call("cl", 33, "clGetProgramInfo"), "cl:33/34"),
  "OP_KERNEL": ("call", lambda: call("cl", 47, "clCreateKernel"), "cl:47, cu:129, hp:31"),
  "OP_RELEASE_KERNEL": ("call", lambda: call("cl", 50, "clReleaseKernel"), "cl:50"),
  "OP_RELEASE_PRG": ("call", lambda: call("cl", 52, "clReleaseProgram"), "cl:36/52, hp:35"),
  "OP_PLATFORMS": ("call", lambda: call("cl", 95, "clGetPlatformIDs"), "cl:95/96"),
  "OP_ALLOC": ("call", lambda: call("cl", 80, "clCreateBuffer"), "cl:80, cu:78, hp:62"),
  "OP_ALLOC_HOST": ("call", lambda: call("cu", 76, "cuMemHostAlloc"), "cu:76"),
  "OP_FREE": ("call", lambda: call("cl", 83, "clReleaseMemObject"), "cl:83, cu:82, hp:64"),
  "OP_FREE_HOST": ("call", lambda: call("cu", 82, "cuMemFreeHost"), "cu:82"),
  "OP_HOST_REGISTER": ("call", lambda: call("cu", 90, "cuMemHostRegister_v2"), "cu:90"),
  "OP_HOST_UNREGISTER": ("call", lambda: call("cu", 94, "cuMemHostUnregister"), "cu:94"),
  "OP_COPY_IN": ("call", lambda: call("cl", 86, "clEnqueueWriteBuffer"), "cl:86, cu:55, hp:67"),
  "OP_COPY_OUT": ("call", lambda: call("cl", 88, "clEnqueueReadBuffer"), "cl:88, hp:70"),
  "OP_FINISH": ("call", lambda: call("cl", 129, "clFinish"), "cl:129, cu:136, hp:24"),
  "OP_IMAGE": ("call", lambda: call("cl", 63, "clCreateImage"), "cl:63"),
  "OP_SET_ARG": ("call", lambda: call("cl", 64, "clSetKernelArg"), "cl:64/65"),
  "OP_LAUNCH": ("call", lambda: call("cl", 68, "clEnqueueNDRangeKernel"), "cl:68, cu:47, hp:51"),
  "OP_WAIT_EVENT": ("call", lambda: call("cl", 72, "clWaitForEvents"), "cl:72, hp:55"),
  "OP_TIME_START": ("call", lambda: call("hp", 49, "hipEventRecord"), "hp:49/54"),
  "OP_TIME_END": ("call", lambda: call("cl", 73, "clGetEventProfilingInfo"), "cl:73/74, hp:56"),
  "OP_SIGNAL": ("call", lambda: call("cu", 61, "cuStreamWriteValue64_v2"), "cu:61"),
  "OP_WAIT_VALUE": ("call", lambda: call("cu", 58, "cuStreamWaitValue64_v2"), "cu:58"),
  "OP_HOST_FUNC": ("call", lambda: call("cu", 64, "cuLaunchHostFunc"), "cu:64"),
  "OP_COMPUTE_CAP": ("call", lambda: call("cu", 108, "cuDeviceComputeCapability"), "cu:108"),
  "OP_ERRSTR": ("call", lambda: call("hp", 10, "hipGetErrorString"), "hp:10"),
  "OP_N": ("derived", lambda: 39, "the tag space's SIZE, 0..38"),
  "V_CL": ("derived", lambda: 0, "the vendor tag space's 0"),
  "V_CUDA": ("derived", lambda: 1, "the vendor tag space's 1"),
  "V_HIP": ("derived", lambda: 2, "the vendor tag space's 2"),
}

# No authority at all. Recorded so the count is 103 and not fewer.
NO_AUTH = {}

# Constants whose number IS the whole table, so the scalar check is not enough:
# the port holds 63 CL codes, 63 CL names and 92 CUDA codes + names, and a single
# transposed cell in any of those is a wrong lookup with no constant to blame.
TABLES = {
  # the CL table is ordered 0, -1, -2, ... -- by `-code`, i.e. by absolute value
  # ascending. `sorted()` would give -72..-1, 0, which is the SAME SET in another
  # order and a diff by cell index would then report 63 disagreements over
  # spelling. The ORDER is a property of the port (the walk is a linear scan with
  # a `U32` index and no sort), so the authority has to state it.
  "cl_err_code": ("cl", lambda: [cu32(c) for c in sorted(cl_errors(), key=lambda c: -c)],
                  "the comprehension's KEY column, ordered by -code, evaluated in CPython"),
  "cl_err_name": ("cl", lambda: [cl_errors()[c] for c in sorted(cl_errors(), key=lambda c: -c)],
                  "the comprehension's VALUE column, same order"),
  "cu_err_code": ("cu", lambda: [cu32(c) for c in sorted(cuda_errors())],
                  "sorted(cuda.enum_cudaError_enum) keys"),
  "cu_err_name": ("cu", lambda: [cuda_errors()[c] for c in sorted(cuda_errors())],
                  "sorted(cuda.enum_cudaError_enum) values"),
}


def bend_consts(path):
  out = {}
  for i, line in enumerate(Path(path).read_text().splitlines(), 1):
    m = BEND_CONST.match(line)
    if m: out[m.group(1)] = (i, int(m.group(2)))
  return out


def main():
  port = bend_consts(PORT)
  kinds, wrong, noauth, unmapped, unknown = {}, [], [], [], []
  for name, (ln, val) in sorted(port.items()):
    if name in NO_AUTH:
      kinds.setdefault("no-auth", []).append(name); noauth.append((name, val, ln)); continue
    if name not in MAP:
      unknown.append((name, val, ln)); continue
    kind, fn, why = MAP[name]
    kinds.setdefault(kind, []).append(name)
    if kind in ("dead", "fix", "host"): continue
    if kind == "call":
      try: fn()
      except AssertionError as e: wrong.append((name, val, str(e), ln, why))
      continue
    got = fn()
    if got != val: wrong.append((name, val, got, ln, why))
  for name in MAP:
    if name not in port and name not in TABLES and name != "cl_err_aliases":
      unmapped.append(name)

  # ---- the four whole-table constants ------------------------------------
  tbad = 0
  print("== WHOLE-TABLE CONSTANTS")
  for name, (vendor, fn, why) in TABLES.items():
    want = fn()
    got = bend_list(PORT, name)
    if [str(x) for x in want] != got:
      tbad += 1
      print(f"  !! {name}: {len(got)} cells in the port, {len(want)} from CPython")
      for i, (a, b) in enumerate(zip(got, want)):
        if str(a) != str(b): print(f"       cell {i}: port {a!r}, CPython {b!r}")
      if len(got) != len(want):
        print(f"       length differs; port tail {got[len(want):] or got[-3:]}, "
              f"cpython tail {want[len(got):] or want[-3:]}")
    else:
      print(f"  OK  {name}: {len(want)} cells agree with CPython, cell for cell")

  total = len(port)
  checked = total - len(noauth) - len(unknown) - len(kinds.get("call", [])) - len(kinds.get("host", []))
  print(f"\n{PORT.name}: {total} numeric constant defs")
  print(f"  compared against a CPython authority : {checked}")
  print(f"  tag space, checked as (line,selector) : {len(kinds.get('call', []))}")
  print(f"  HOST-DEPENDENT (no single value)      : {len(kinds.get('host', []))}")
  for n in kinds.get("host", []):
    print(f"    HOST {n}: the authority measures {MAP[n][1]()} on THIS host, and the port's "
          f"{port[n][1]} is the value every platform CUDA runs on answers. Not a wrong constant; "
          f"a U32 literal cannot be host-dependent.")
  print(f"  NO AUTHORITY                          : {len(noauth)}")
  print(f"  WRONG                                 : {len(wrong)}")
  for n, p, g, ln, why in wrong:
    print(f"    WRONG {n}: port {p} at line {ln}, authority {g} -- {why}")
  for n, v, ln in noauth: print(f"    NO-AUTH {n}={v} at line {ln}: {NO_AUTH[n]}")
  for n, v, ln in unknown: print(f"    UNMAPPED {n}={v} at line {ln} -- ADD IT TO THE MAP")
  for n in unmapped: print(f"    MAP-ONLY {n}: in the map, not in the port")
  # ---- the tag spaces' one checkable property: DENSITY -------------------
  for pre in ("OP", "V"):
    tags = sorted(val for k, (_ln, val) in port.items() if k.startswith(pre + "_")
                  and k != "OP_N" and not re.match(r"^OP_(RT_|IDX_|DESC_|KERNARGS_|SIGNAL_SLOT|TAG_)", k))
    want = list(range(len(tags))) if pre == "V" else list(range(len(tags)))
    print(f"  {pre}_* tag values                     : {tags[0]}..{tags[-1]} n={len(tags)} "
          f"DENSE={tags == want}")
    if tags != want: print(f"    !! the {pre}_* tags are NOT 0..n-1")
  # ---- and the one thing the density check cannot see: V_HIP's VALUE ------
  # `vend.name(v, op)` compares `v` against V_CUDA()/V_HIP() and every gate row
  # passes V_CL()/V_CUDA()/V_HIP() as the ARGUMENT, so the constant appears on
  # BOTH sides of its own comparison: V_HIP+1 moves NOTHING (measured by the far
  # sweep). The only property the gate does pin is that the three are DISTINCT,
  # which `V_CL+1` and `V_CUDA+1` both break. So V_HIP's exact value is
  # unconstrained by the port and must be judged as a port-internal tag.
  v = {k: port[k][1] for k in ("V_CL", "V_CUDA", "V_HIP")}
  print(f"  V_* values                            : {v}  DISTINCT={len(set(v.values())) == 3}")
  if len(set(v.values())) != 3: print("    !! two vendors share a tag")
  print(f"  whole-table disagreements             : {tbad}")
  return 1 if (wrong or unknown or unmapped or tbad) else 0


if __name__ == "__main__":
  sys.exit(main())
