"""Append the ops_cl.bend header retitle and the three post-split addenda to
cl_split.py. Kept separate from the split script itself because these are pure
PROSE blocks and a failed assertion here must not cost a working split."""
import pathlib

p = pathlib.Path(".agents/slop/cl_split.py")
s = p.read_text()

OLD_CL = 'put("cl", cut(1, 257))                       # the header, retitled below\nput("cl", cut(258, 259))                     # import Base / helpers.bend as H\n'
NEW_CL = '''put("cl", [
  "# tinybendygrad/runtime/ops_cl.bend -- port of tinygrad/runtime/ops_cl.py.",
  "#",
  "# ONE `.bend` PER UPSTREAM `.py`, AT THE SAME PATH. This file used to hold THREE",
  "# ports -- ops_cl.py, ops_cuda.py and ops_hip.py -- and the 1:1 ruling made it",
  "# three files. `ops_cuda.bend` and `ops_hip.bend` import this one; this one",
  "# imports neither, because bend has NO IMPORT CYCLE (MEASURED: \\"an import",
  "# cycle through .../a.bend\\"), and an acyclic graph of three files has exactly",
  "# one leaf.",
  "#",
  "# SO THE CROSS-CUTTING RATIONALE STAYS HERE AND THE THREE VENDOR TABLES DO NOT.",
  "# The header below is about all three files and is part of the reason this file",
  "# is the leaf; the tables are DATA about one file each, and a `vend.cu` in",
  "# `ops_cl.bend` is exactly the violation the ruling exists to stop. The",
  "# consequence is at THE IMPORT DAG and it is not free: `vend.name(+v, +op)`",
  "# became `vend.name(+op)` in each file, because a reader of all three tables",
  "# cannot live in any one of the three files.",
  "#",
  "# ONE DEVICE, THREE VENDOR SPELLINGS. `ops_cl.py` is the BASE CLASS for CUDA and",
  "# HIP: `CUDADevice` and `HIPDevice` are both `Compiled`, and `Program.__call__`",
  "# (device.py:372) is the one entry point all three share. So the three files are",
  "# not three backends to be compared -- they are ONE backend whose every operation",
  "# has a CL spelling, a CUDA spelling and a HIP spelling, and most of which are",
  "# NOT the same operation under a different name. `hipMalloc` is `clCreateBuffer`",
  "# is `cuMemAlloc_v2`; but `clSetKernelArg` has NO CUDA spelling at all (CUDA",
  "# packs a kernargs blob) and no HIP spelling either (HIP packs a `c_args`",
  "# struct), and `clReleaseKernel` exists in exactly ONE of the three. That table",
  "# is the content of all three files, and `vend` is it -- one table per file now.",
  "#",
  "# WHAT IS IN THIS FILE, precisely: the OpenCL port (`CLDevice`, `CLProgram`,",
  "# `CLAllocator`, `CLCompiler`, `CL_*`) and `cl_err_*` (ops_cl.py:16), plus the",
  "# port-LOCAL TRACE that all three files share -- `OP_*`, `Call`, `Tr`, `Tr.*`,",
  "# `Sig`/`Arg`/`Buf`/`Made`, `u32_dec`/`u32s`, `one_s`/`one_u`, `vend.argname`,",
  "# `cl_dev_index`, and the gate's row printers. None of that has a counterpart in",
  "# ops_cl.py alone: it is the `runtime/support/c.py` seam that all three files",
  "# import (`init_c_var`, `init_c_struct_t`, `ccall`), and it lives here because",
  "# this is the leaf of the DAG. `vend.cu`, `cu_err_*`, `Spec` and `cu.*` are in",
  "# `ops_cuda.bend`; `vend.hp`, `hp_err_of`, `timing.scale_hp` and `hp.*` are in",
  "# `ops_hip.bend`.",
  "#",
])
put("cl", cut(3, 257))                       # the rest of the header, verbatim
put("cl", cut(258, 259))                     # import Base / helpers.bend as H
put("cl", [
  "# ===========================================================================",
  "# THE IMPORT DAG, and the ONE thing the 1:1 split cost.",
  "#",
  "#   ops_cl.bend   the leaf. The OpenCL port, `cl_err_*`, and the port-local",
  "#                 trace seam (`OP_*`, `Call`, `Tr`, `Sig`, `Arg`, `Buf`,",
  "#                 `Made`, `u32_dec`, `u32s`, `one_s`, `one_u`, `vend.argname`,",
  "#                 `cl_dev_index`, the row printers).",
  "#   ops_cuda.bend imports ops_cl.bend as `CL.`",
  "#   ops_hip.bend  imports ops_cl.bend as `CL.` and ops_cuda.bend as `CU.`",
  "#",
  "# bend REFUSES an import cycle -- MEASURED, `a.bend` importing `b.bend` with",
  "# `b` importing `a` back reports \\"an import cycle through .../a.bend\\". So a",
  "# def that reads all THREE vendor tables cannot live in any of the three files,",
  "# and the four shared picks -- `vend.name`, `vend.count`,",
  "# `vend.checked`/`chk_count`, `vend.trace`/`vend.line` -- had to become PER",
  "# FILE. What that DELETED:",
  "#",
  "#   V_CUDA, V_HIP     nothing indexes them once the picks are per file.",
  "#   vend.name.at      the `Bool.pick` ladder over three tables.",
  "#   the `v` argument  on four signatures -- 61 `vend.trace(v, cs)` call sites,",
  "#                     20 `vend.name(v, op)`, 17 `vend.checked(v, op)`,",
  "#                     11 `chk_count(v)`, 11 `vend.count(v)`, 3 `V_*` records.",
  "#",
  "# What it ADDED: `cu.sync` in `ops_cuda.bend` -- cu:82 is CUDA's own",
  "# `cuCtxSynchronize`, and before the split CUDA called `cl.sync` because this",
  "# file was the only `OP_FINISH` emitter. Two call sites moved, and mutation M2",
  "# in `ops_cuda.bend` is what proves the ORDER of cu:80 survived it.",
  "#",
  "# WHAT IT DID NOT COST: the 445 rows. `ops_cl.bend` 229, `ops_cuda.bend` 120,",
  "# `ops_hip.bend` 96, and all 445 `name=value` LINES are byte-identical to the",
  "# pre-split snapshot. 444 of them changed POSITION, because the old `t_vend`,",
  "# `t_check` and `t_err` interleaved the three vendors row by row and one",
  "# concatenation of three programs cannot interleave -- so the gate diffs",
  "# SORTED, which is strictly stronger on VALUES, and `cl_split_rows.py` checks",
  "# that no row landed in the wrong FILE. See `.agents/slop/ops-cl-gate.sh`.",
  "#",
  "# MUTATIONS over what stayed in this file, in whole `name=value` LINES.",
  "# Reproduce with `.agents/slop/cl_split_mutate.py`.",
  "#",
  "#   M10  8 lines  `cl_err_msg`: spell the tag wrong. Moves `cl_err_0`,",
  "#               `cl_err_m1`, `cl_err_m2`, `cl_err_m3`, `cl_err_m19`,",
  "#               `cl_err_m30`, `cl_err_m72`, `cl_err_p999`.",
  "#   M12  5 lines  `cl.PITCH_ALIGN`: 256 -> 128. Moves `cl_pitch_align` and the",
  "#               four `cl_pitch_osx_*` rows.",
  "#   M13  0 lines  `Sig`: swap `h` and `w` in the TYPE DECLARATION. THEOREM, and",
  "#               M16 is its proof: in bend 2.0.34 a `Data` record's",
  "#               `type ... is Data:` field list is DOCUMENTATION, because the",
  "#               constructor and every reader bind POSITIONALLY. M16 swaps the",
  "#               same two names in `Sig.w`'s READER and moves 4 rows. So the",
  "#               field-NAME discipline this repo records lands on the READERS,",
  "#               not on the declaration -- which is where `ops_cl`'s original",
  "#               `Sig` inversion actually was.",
  "#   M15  6 lines  THE TRAP, the tc_ptx unit's exact bug class: rewrite a string",
  "#               LITERAL (`clEnqueueNDRangeKernel` -> `T.r1_NDRangeKernel`).",
  "#               THE ROW COUNT STAYS 445 and the byte diff catches it:",
  "#               `vend_names_cl`, the four `cl_call_trace*` rows, `x_launch`. A",
  "#               harness that diffed row NAMES would have reported 0. This",
  "#               file's qualifier skips string literals for exactly that reason.",
  "#   M11  0 lines  `V_CL`: 0 -> 1. A REAL BLIND SPOT, reported and not closed:",
  "#               after the split `V_CL` is DEAD. `Prog.of`'s first argument",
  "#               lands in `Prog`'s `vendor` field and NO reader reads that",
  "#               field, while `cl_prog_unit` reads `Prog.unit` -- a different",
  "#               field, which `Prog.of` sets to the literal 0. So that row",
  "#               asserts `Prog.of`'s literal and not `V_CL`, and it did so",
  "#               before the split too. Deleting `V_CL` and `Prog.vendor` is a",
  "#               real simplification but it is NOT a split; it is the owner's.",
  "# ===========================================================================",
  "",
])
'''
assert OLD_CL in s
s = s.replace(OLD_CL, NEW_CL)

CU_TAIL = '''  "    # A `do IO<Unit>` block's last line is the block's RESULT, so the last test",
  "    # is CALLED there rather than bound (bend2-constraints: `ops_cpu.bend` does",
  "    # the same).",
  "    t_cualloc()",
  "",
])'''
assert CU_TAIL in s
s = s.replace(CU_TAIL, CU_TAIL[:-3] + '''
put("cu", [
  "# ===========================================================================",
  "# THE SPLIT, MEASURED. 120 of the pre-split file's 445 rows are here, and every",
  "# one is byte-identical to the pre-split snapshot. The 22 `x_*` cross-vendor",
  "# rows are NOT: they are in `ops_hip.bend`, for the DAG reason in this file's",
  "# header.",
  "#",
  "# MUTATIONS, over what moved into THIS file. Each is applied to a scratch copy",
  "# and reverted; each is counted in whole `name=value` LINES.",
  "#",
  "#   M1   7 lines   `vend.cu`: swap cells 19 and 20 (`cuMemAlloc_v2` /",
  "#                `cuMemHostAlloc`). Moves `vend_names_cu`, `vend_alloc_cu`,",
  "#                `cu_alloc_dev`, `cu_alloc_host`, `cu_alloc_cpu`, `x_alloc`,",
  "#                `x_alloc_host` -- so the CUDA spelling is load-bearing.",
  "#   M2   4 lines   `cu.free.at`: drop the `cuCtxSynchronize` before the free.",
  "#                Moves `cu_free_dev`, `cu_free_host`, `cu_free_cpu`,",
  "#                `x_free_cu`. This is the mutation that proves the split's",
  "#                forced `cu.sync` edit preserved cu:80's ORDER.",
  "#   M3   0 lines   `Spec`: swap `host` and `cpu` in the TYPE DECLARATION.",
  "#                THEOREM -- the same one as `ops_cl.bend`'s M13, and the reason",
  "#                it is worth writing down: in bend 2.0.34 a `Data` record's",
  "#                declaration is documentation because every constructor and",
  "#                reader binds POSITIONALLY.",
  "#   M4   3 lines   `cu.kernarg_extra`: drop the 40-byte descriptor offset.",
  "#                Moves `cu_extra_fresh`, `cu_extra_44`, `cu_extra_84`.",
  "#   M17  0 lines   `Spec.of`: swap the `host` and `cpu` ARGUMENTS. THEOREM, and",
  "#                a PROVABLE one: the only reader is `spec.is_host(s)` =",
  "#                `Bool.or(Spec.host(s), Spec.cpu(s))`, which is SYMMETRIC in",
  "#                its two arguments, so swapping them is the same function over",
  "#                every reachable `Spec` and no fixture can separate them. The",
  "#                consequence is a LOC observation, not a bug: upstream cu:75 is",
  "#                ONE test (`options.host or options.cpu_access`), so `Spec`'s",
  "#                two `Bool` fields could be one.",
  "# ===========================================================================",
  "",
])''')

HP_TAIL = '''  "    # NO trailing print: see the note in `ops_cuda.bend`'s main.",
  "    t_cross()",
  "",
])'''
assert HP_TAIL in s
s = s.replace(HP_TAIL, HP_TAIL[:-3] + '''
put("hp", [
  "# ===========================================================================",
  "# THE SPLIT, MEASURED. 96 of the pre-split file's 445 rows are here, all of them",
  "# byte-identical to the pre-split snapshot: the HIP column of",
  "# `t_vend`/`t_check`/`t_err`, `t_hpinit`, `t_hpargs`, `timing_hp_scale_bits`,",
  "# and the 22 `x_*` cross-vendor rows.",
  "#",
  "# MUTATIONS, over what moved into THIS file. Reproduce with",
  "# `.agents/slop/cl_split_mutate.py`.",
  "#",
  "#   M5   4 lines   `vend.hp`: typo a symbol (`hipMalloc` -> `hipMallocX`).",
  "#                Moves `vend_names_hp`, `vend_alloc_hp`, `hp_alloc_trace`,",
  "#                `x_alloc`.",
  "#   M6   3 lines   `hp_err_of`: change the message prefix. Moves `hp_err_0`,",
  "#                `hp_err_1`, `hp_err_999`.",
  "#   M7   2 lines   `vend.checked`: forget `hp_unchecked` (say `hipEventCreate`",
  "#                IS checked). Moves `vend_nchecked_hp`, `chk_hp_queue`. NOT",
  "#                `chk_hp_launch`: `hipModuleLaunchKernel` is checked under both",
  "#                readings, so that row is a CONSTANT against this mutation and",
  "#                not a witness for it.",
  "#   M8   1 line    `timing.scale_hp`: hp:57's `1e-3` -> `1e-2`. Moves",
  "#                `timing_hp_scale_bits` -- the one row that followed the factor",
  "#                out of `ops_cl.bend`'s `t_print`.",
  "#   M9   1 line    `t_cross`: swap the second and third cells of `x_launch`.",
  "#                Moves `x_launch` and nothing else, which is what a row that",
  "#                JOINS three spellings is supposed to do.",
  "#   M14  5 lines   THE TRAP, the tc_ptx unit's exact bug class: rewrite a string",
  "#                LITERAL (`hipModuleLaunchKernel` -> `T.r1_ModuleLaunchKernel`).",
  "#                THE ROW COUNT STAYS 445 and the byte diff catches it:",
  "#                `vend_names_hp`, `hp_call_first_trace`, `hp_call_wait_trace`,",
  "#                `hp_call_second_trace`, `x_launch`. A harness that diffed row",
  "#                NAMES would have reported 0.",
  "# ===========================================================================",
  "",
])''')

p.write_text(s)
print("all three addenda wired")