#!/usr/bin/env python3
import sys, inspect
sys.path.insert(0, '.')
from tinygrad.dtype import dtypes, AddrSpace
from tinygrad.helpers import Target
from tinygrad.uop.ops import UOp, Ops
from tinygrad.renderer.cstyle import (CStyleLanguage, OpenCLRenderer, ClangRenderer, MetalRenderer,
                                      CUDARenderer, HIPRenderer, _wmma_name, uops_to_dtypes)
def bare(cls, arch="TEST"):
  o = object.__new__(cls); o.target = Target(f"TEST {arch}"); return o
OCL, CLG, MTL, CUD, HIP = bare(OpenCLRenderer,"gfx000"), bare(ClangRenderer,"x86_64,znver2"), \
                        bare(MetalRenderer,"Apple M4"), bare(CUDARenderer,"sm_89"), bare(HIPRenderer,"gfx1100")
CS = CStyleLanguage(Target("NULL"))
BODY = ["  float4 val0 = (*((float4*)((data1_4+0))));", "  *((float4*)((data0_4+0))) = (float4){(val0[0]+1.0f)};"]
def bufs(dtype=dtypes.f32, vol0=False):
  return [("data0_4", (UOp.param(0, dtype, (), volatile=vol0), True)), ("data1_4", (UOp.param(1, dtype, ()), True))]

# vec: an ALU uop with shape (4,)
p4 = UOp.param(0, dtypes.half, (4,))
vec = UOp(Ops.CAST, (p4,), dtypes.half)
print("vec:", vec.shape, vec.addrspace, vec.max_numel(), uops_to_dtypes([vec]))
print("CUDA vecs:", repr(CUD.render_kernel("E_4", BODY, bufs(), [vec], None)))
print("HIP vecs:", repr(HIP.render_kernel("E_4", BODY, bufs(), [vec], None)))
bf = UOp(Ops.CAST, (UOp.param(0, dtypes.bfloat16, (4,)),), dtypes.bfloat16)
print("CUDA bf16:", repr(CUD.render_kernel("E_4", BODY, bufs(), [bf], None)))
print("CUDA fp8 :", repr(CUD.render_kernel("E_4", BODY, bufs(), [UOp(Ops.CAST,(UOp.param(0,dtypes.fp8e4m3,()),),dtypes.fp8e4m3)], None)))
# HIP bf16, cdna4
b16 = UOp(Ops.CAST, (UOp.const(1, dtypes.bfloat16),), dtypes.bfloat16)
print("HIP bf16 :", repr(HIP.render_kernel("E_4", BODY, bufs(), [b16], None))[:200])
print("HIP cdna4:", repr(bare(HIPRenderer,"gfx950").render_kernel("E_4", BODY, bufs(), [b16], None))[:200])
# ALU bufs
alu_buf = UOp.param(0, dtypes.f32, (), addrspace=AddrSpace.ALU)
abu = [("alu0_1", (alu_buf, True)), ("alu1_1", (UOp.param(1, dtypes.f32, (), addrspace=AddrSpace.ALU), True))]
print("BASE alu :", repr(CS.render_kernel("E_4", BODY, abu, [], None)))
print("CLANG alu:", repr(CLG.render_kernel("E_4", BODY, abu, [], None)))
print("METAL alu:", repr(MTL.render_kernel("E_4", BODY, abu, [], None)))
# caller prefix
print("BASE caller:", repr(CS.render_kernel("E_4", BODY, bufs(), [], ["// generated by tinybendygrad","#pragma OPENCL EXTENSION cl_khr_fp16 : enable"])))
print("BASE empty :", repr(CS.render_kernel("E_4", BODY, bufs(), [], [])))
print("OPENCL pref:", repr(OCL.render_kernel("E_4", BODY, bufs(), [], ["// generated by tinybendygrad"])))
print("OPENCL f16 :", repr(OCL.render_kernel("E_4", BODY, bufs(), [UOp(Ops.ADD,(UOp.const(1,dtypes.f16),UOp.const(2,dtypes.f16)),None)], ["// generated by tinybendygrad"])))
# volatile
print("BASE vol   :", repr(CS.render_kernel("E_4", BODY, bufs(vol0=True), [], None)))
print("CLANG vol  :", repr(CLG.render_kernel("E_4", BODY, bufs(vol0=True), [], None)))
# HIP ocml full
sq = lambda dt: UOp(Ops.SQRT, (UOp.const(1, dt),), None)
print("HIP ocml2 :", repr(HIP.render_kernel("E_4", BODY, bufs(dtypes.half), [sq(dtypes.half), sq(dtypes.f32)], None)))
# render_index
CS.r = {}
ab = UOp.param(0, dtypes.f32, (), addrspace=AddrSpace.ALU)
i = lambda k: UOp(Ops.CAST, (UOp.const(k),), dtypes.i32)
CS.r[ab] = "B"
for k in (0,1,3):
  n = i(k); CS.r[n] = "R"; print(f"idx BASE sz1 k{k}:", repr(CS.render_index(n, ab, n)))
lane = UOp(Ops.INDEX, (i(0),), dtypes.f32); CS.r[lane] = "R"
print("idx BASE lane:", repr(CS.render_index(lane, ab, lane)))
CLG.r = {ab: "B", lane: "R"}
print("idx CLANG lane:", repr(CLG.render_index(lane, ab, lane)))
rb = UOp.param(0, dtypes.f32, (), addrspace=AddrSpace.REG)
CS.r[rb] = "B"; CS.r[i(0)] = "R"
print("idx BASE reg(add):", repr(CS.render_index(i(0), rb, i(0))))
# wmma
for dims, din, dout in (((16,16,16), dtypes.half, dtypes.half), ((16,16,16), dtypes.int8, dtypes.int8),
                        ((8,8,32), dtypes.bfloat16, dtypes.bfloat16), ((16,16,128), dtypes.fp8e4m3, dtypes.fp8e4m3)):
  u = UOp(Ops.WMMA, (UOp.param(0, din, dims),), dout, arg=AWmma(list(dims), din, 32, []))
  print("wmma", dims, "->", repr(_wmma_name(u)))
# buftypes via render_kernel signature
for nm, r in (("BASE",CS),("CLANG",CLG),("OPENCL",OCL),("METAL",MTL),("CUDA",CUD),("HIP",HIP)):
  for an, a in (("alu",AddrSpace.ALU),("glob",AddrSpace.GLOBAL),("loc",AddrSpace.LOCAL)):
    for vol in (False,True):
      u = UOp.param(0, dtypes.f32, (), addrspace=a, volatile=vol)
      s = r.render_kernel("E", ["  ;"], [("v0",(u,True))], [], None)
      print(f"buft {nm} {an} vol={vol}: {s.split('(')[1].split(')')[0]!r}")
import tinygrad.dtype as td
names = sorted({d.name for d in td.dtypes if hasattr(d,'name')})
print("names with space:", [n for n in names if " " in n])
print("n names:", len(names))