#!/usr/bin/env python3
"""GENERATE the gate rows of `renderer/amd/dsl.bend` and APPEND them.

WHY A GENERATOR. The oracle names every row after the CPython expression that
produced it (`names_fwd_102`, `bfset_3_0_3735928559_-1`), so a port row that is
hand-typed with a different name is a row the harness cannot pair -- and a row
the harness cannot pair is a row that never ran. Generating both sides' NAMES
from one spec is what keeps the diff honest, and it is the same discipline as
".agents/slop/mt_constmap.py", which is a generator too.

WHAT IT GENERATES, IN ORDER.

  T  the four tables, both directions, plus each table's length
  C  the register constants and the space boundaries
  R  `Reg.__getitem__` -- index, slice, and both refusals
  F  `Reg.fmt` -- every arm, at sz 1 and sz>1, upper and not, with modifiers
  M  the modifier flags and `__neg__`/`__abs__`/`.h`/`.l`
  B  `BitField` masks and `set`, with both refusals
  E  the five field classes' `encode`, one negative per positive
  N  `_needs_literal`
  I  the `Inst` field order, `_base_size`, and the raw-word walk
  O  `op_bits` / `op_regs` / `canonical_*` / `num_srcs`
  V  `_variant_suffix`

    usage: .venv/bin/python .agents/slop/dsl_gen.py [--check]
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PORT = ROOT / "tinybendygrad/renderer/amd/dsl.bend"
MARK = "# ==== GATE BODY (generated by .agents/slop/dsl_gen.py) ===="
# The fixture VALUES live in a file, not in this generator: the generator
# REPLACES everything from MARK down, so a fixture written after the marker is
# deleted on the next run. Measured, and it cost one run.
FIXTURES = (Path(__file__).resolve().parent / "dsl_fixtures.txt").read_text()

NAMES = [102, 103, 104, 105, 106, 107, 124, 125, 126, 127, 233, 234, 235, 236, 237, 238,
         240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255]
NAME_TEXT = {102: "FLAT_SCRATCH_LO", 103: "FLAT_SCRATCH_HI", 104: "XNACK_MASK_LO",
             105: "XNACK_MASK_HI", 106: "VCC_LO", 107: "VCC_HI", 124: "NULL", 125: "M0",
             126: "EXEC_LO", 127: "EXEC_HI", 233: "DPP8", 234: "DPP8FI",
             235: "SHARED_BASE", 236: "SHARED_LIMIT", 237: "PRIVATE_BASE",
             238: "PRIVATE_LIMIT", 240: "0.5", 241: "-0.5", 242: "1.0", 243: "-1.0",
             244: "2.0", 245: "-2.0", 246: "4.0", 247: "-4.0", 248: "INV_2PI",
             249: "SDWA", 250: "DPP", 251: "VCCZ", 252: "EXECZ", 253: "SCC",
             254: "SRC_LDS_DIRECT", 255: "LIT"}
FLOATS = [240, 241, 242, 243, 244, 245, 246, 247]
FLOAT_TEXT = {240: "0.5", 241: "-0.5", 242: "1.0", 243: "-1.0", 244: "2.0",
              245: "-2.0", 246: "4.0", 247: "-4.0"}
CANON_IN = ["src0", "vsrc0", "ssrc0", "src1", "vsrc1", "ssrc1", "src2", "vdst",
            "sdst", "sdata", "data", "vdata", "data0", "vsrc", "op", "off", "abs",
            "neg", "opsel", "src3"]
SRC_OFFS = [0, 1, 63, 104, 105, 106, 107, 108, 123, 124, 125, 126, 127, 128, 129, 192,
            193, 208, 209, 239, 240, 248, 255, 256, 257, 510, 511]
FMT_CASES = [(0, 1), (0, 4), (1, 2), (105, 1), (256, 1), (256, 4), (300, 2), (511, 1),
             (106, 2), (126, 2), (106, 1), (126, 1), (102, 1), (103, 2), (104, 1),
             (105, 1), (107, 1), (233, 1), (234, 1), (235, 1), (236, 1), (237, 1),
             (238, 1), (240, 1), (241, 1), (242, 1), (243, 1), (244, 1), (245, 1),
             (246, 1), (247, 1), (248, 1), (249, 1), (250, 1), (251, 1), (252, 1),
             (253, 1), (254, 1), (255, 1), (108, 1), (108, 4), (115, 2), (123, 1),
             (128, 1), (129, 1), (160, 1), (192, 1), (193, 1), (194, 1), (207, 1),
             (208, 1), (209, 1), (512, 1), (108, 16), (256, 2), (106, 4)]
MODS = [(0, 1), (256, 1), (124, 1), (106, 2), (108, 1), (128, 1), (193, 1), (255, 1)]
BFIELDS = [(7, 0), (15, 8), (16, 8), (31, 16), (17, 16), (23, 8), (9, 0), (30, 24),
           (17, 9), (30, 0), (31, 0), (0, 0), (6, 0), (40, 32), (47, 32), (23, 16)]
BF_SET = [(3, 0), (7, 4), (23, 8)]


def g(sec, out):
  L = out.append
  L(f"\n# --- {sec} " + "-" * max(0, 66 - len(sec)))
  return L


def gen():
  o = []
  L = o.append

  # ---------------------------------------------------------------- T
  g("T  THE FOUR TABLES, BOTH DIRECTIONS", o)
  L('def g_tables() -> IO(Unit):\n  do IO<Unit>:')
  L('    srow("names_count", nat_text(reg_names_n()))')
  L('    srow("names_rev_count", nat_text(reg_names_n()))')
  for x in NAMES:
    L(f'    srow("names_fwd_{x}", reg_name_of({x}))')
  for x in NAMES:
    L(f'    srow("names_rev_{NAME_TEXT[x]}", u32_text(reg_off_of("{NAME_TEXT[x]}")))')
  L('    srow("pairs_count", nat_text(reg_pairs_n()))')
  L('    srow("pairs_fwd_106", pair_name_of(106))')
  L('    srow("pairs_fwd_126", pair_name_of(126))')
  L('    srow("pairs_rev_VCC", u32_text(pair_off_of("VCC")))')
  L('    srow("pairs_rev_EXEC", u32_text(pair_off_of("EXEC")))')
  for x in FLOATS:
    L(f'    srow("names_rev_{FLOAT_TEXT[x]}", u32_text(reg_off_of("{FLOAT_TEXT[x]}")))')
  L('    urow("float_enc_n", reg_pairs_n() + 6n + 0n)' if False else '    srow("float_enc_count", nat_text(float_enc_n()))')
  for x in FLOATS:
    L(f'    srow("floatenc_r_{x}", float_enc_of_text("{FLOAT_TEXT[x]}"))')
  for n in CANON_IN:
    L(f'    srow("canon_{n}", canon_of_text(canon_of("{n}")))')
  for n in ["Src0", "Src1", "S0", "xsrc0", "rsrc", "isrc", "sdst_x", "S0"]:
    L(f'    srow("canon_{n}", canon_of_text(canon_of("{n}")))')
  for i, nm in enumerate(["s0", "s1", "s2", "d", "data"]):
    L(f'    srow("canon_out_{nm}", canon_of_text(canon_of("{nm}")))')
  # the negative rows: an absent name and an absent offset, one row from a positive
  L('    srow("names_fwd_absent", reg_name_of(209))')
  L('    srow("names_rev_absent", u32_text(reg_off_of("NOSUCHREG")))')
  L('    srow("pairs_rev_absent", u32_text(pair_off_of("NOSUCHPAIR")))')
  L('    srow("floatenc_r_absent", float_enc_of_text("3.0"))')

  # ---------------------------------------------------------------- C
  g("C  THE REGISTER CONSTANTS AND THE SPACE BOUNDARIES", o)
  L('def g_const() -> IO(Unit):\n  do IO<Unit>:')
  # NULL and OFF are the SAME register (dsl.py:74) and DPP and DPP16 are the
  # same register (dsl.py:83), so their rows must print the SAME word -- two
  # aliases, four rows, one answer each way.
  for nm, cf in [("VCC_LO", "VCC_LO"), ("VCC_HI", "VCC_HI"), ("NULL", "NULL_OFF"),
                 ("OFF", "OFF_OFF"), ("M0", "M0_OFF"), ("EXEC_LO", "EXEC_LO"),
                 ("EXEC_HI", "EXEC_HI"), ("INV_2PI", "INV_2PI_OFF"), ("SDWA", "SDWA_OFF"),
                 ("DPP", "DPP_OFF"), ("DPP16", "DPP16_OFF"), ("VCCZ", "VCCZ_OFF"),
                 ("EXECZ", "EXECZ_OFF"), ("SCC", "SCC_OFF"),
                 ("SRC_LDS_DIRECT", "SRC_LDS_DIRECT_OFF"), ("LIT", "LIT_OFF")]:
    L(f'    srow("const_{nm}", rg5(Rg{{{cf}(), 1, False{{}}, False{{}}, False{{}}}}))')
  L('    row("alias_null_off", U32.is_eq(NULL_OFF(), OFF_OFF()))')
  L('    row("alias_dpp_dpp16", U32.is_eq(DPP_OFF(), DPP16_OFF()))')
  L('    row("alias_vcc_pair", U32.is_eq(VCC_OFF(), VCC_LO()))')
  L('    row("alias_exec_pair", U32.is_eq(EXEC_OFF(), EXEC_LO()))')
  for nm, lo, sz in [("src", "SRC_LO", "SRC_SZ"), ("s", "S_LO", "S_SZ"),
                     ("ttmp", "TTMP_LO", "TTMP_SZ"), ("v", "V_LO", "V_SZ")]:
    L(f'    srow("const_{nm}", rg5(Rg{{{lo}(), {sz}(), False{{}}, False{{}}, False{{}}}}))')
  for o_ in SRC_OFFS:
    L(f'    srow("src_at_{o_}", rg2({o_}, 1))')

  # ---------------------------------------------------------------- R
  g("R  Reg.__getitem__ -- index, slice, and BOTH refusals", o)
  L('def g_get() -> IO(Unit):\n  do IO<Unit>:')
  for o_ in SRC_OFFS:
    L(f'    srow("get_at_{o_}", rg2({o_}, 1))')
  for a, b in [(0, 105), (106, 107), (108, 123), (126, 127), (256, 511), (0, 511)]:
    L(f'    srow(f"get_slice_{a}_{b}", rg2({a}, U32.add(U32.sub({b}, {a}), 1)))')
  L('    srow("get_slice_default", rg2(0, 512))')
  # the two refusals, and their positive neighbours
  L(f'    srow("get_neg_index", ref(Res.msg(reg_at(4294967295, True{{}}, src_space()))))')
  L(f'    srow("get_index_ge_sz", ref(Res.msg(reg_at(512, False{{}}, src_space()))))')
  L(f'    srow("get_slice_stop_ge_sz", ref(Res.msg(reg_slice_start(src_space(), 0, 512))))')
  L(f'    srow("get_slice_neg_start", ref(Res.msg(reg_slice(4294967295, True{{}}, True{{}}, 5, False{{}}, True{{}}, src_space()))))')
  L('    srow("get_ok_511", Res.s(reg_at(511, False{}, src_space())))')
  L('    srow("get_ok_0", Res.s(reg_at(0, False{}, src_space())))')

  # ---------------------------------------------------------------- F
  g("F  Reg.fmt -- EVERY ARM, at sz 1 and sz>1, upper and not", o)
  L('def g_fmt() -> IO(Unit):\n  do IO<Unit>:')
  for off, sz in FMT_CASES:
    L(f'    srow(f"fmt_{off}_{sz}", Res.s(reg_fmt(Rg{{{off}, {sz}, False{{}}, False{{}}, False{{}}}}, 0, False{{}}, False{{}})))')
    L(f'    srow(f"fmtp_{off}_{sz}", Res.s(reg_fmt(Rg{{{off}, {sz}, False{{}}, False{{}}, False{{}}}}, 0, True{{}}, True{{}})))')
    L(f'    srow(f"fmtm_{off}_{sz}", Res.msg(reg_fmt(Rg{{{off}, {sz}, False{{}}, False{{}}, False{{}}}}, 0, False{{}}, False{{}})))')
  for off, sz in MODS:
    for neg in ("False{}", "True{}"):
      for ab in ("False{}", "True{}"):
        for hi in ("False{}", "True{}"):
          b = f"Rg{{{off}, {sz}, {neg}, {ab}, {hi}}}"
          tag = f"{off}_{sz}_{int(neg == 'True{}')}{int(ab == 'True{}')}{int(hi == 'True{}')}"
          L(f'    srow("fmtmod_{tag}", Res.s(reg_fmt({b}, 0, False{{}}, False{{}})))')
          L(f'    srow("fmtmodu_{tag}", Res.s(reg_fmt({b}, 0, True{{}}, True{{}})))')
  # `sz or self.sz` is a TRUTHINESS test, so sz=0 falls back (dsl.py:45)
  for off, sz, ov in [(0, 1, 4), (256, 1, 2), (106, 2, 2), (124, 1, 4), (108, 1, 2), (0, 1, 0)]:
    L(f'    srow(f"fmt_szov_{off}_{sz}_{ov}", Res.s(reg_fmt(Rg{{{off}, {sz}, False{{}}, False{{}}, False{{}}}}, {ov}, False{{}}, False{{}})))')

  # ---------------------------------------------------------------- M
  g("M  the modifier flags: __neg__ / __abs__ / .h / .l", o)
  L('def g_mod() -> IO(Unit):\n  do IO<Unit>:')
  for off, sz in [(0, 1), (256, 4), (108, 1), (124, 1)]:
    base = f"Rg{{{off}, {sz}, False{{}}, False{{}}, False{{}}}}"
    for nm, fn in [("neg", "rg_neg"), ("abs", "rg_ab"), ("h", "rg_hi"), ("l", "rg_lo")]:
      L(f'    srow(f"mod_{nm}_{off}_{sz}", rg5({fn}({base})))')
  # `__add__` keeps sz; `__eq__` is the 5-tuple
  L('    srow("mod_add_5_2", rg2(U32.add(5, 3), 2))')
  for nm, b in [("self", "Rg{1, 2, False{}, False{}, False{}}"), ("sz", "Rg{1, 3, False{}, False{}, False{}}"),
                ("neg", "Rg{1, 2, True{}, False{}, False{}}"), ("abs", "Rg{1, 2, False{}, True{}, False{}}"),
                ("hi", "Rg{1, 2, False{}, False{}, True{}}")]:
    L(f'    srow("eq_{nm}", Bool.show(rg_eq({b}, Rg{{1, 2, False{{}}, False{{}}, False{{}}}})))')

  # ---------------------------------------------------------------- B
  g("B  BitField masks and set, with both refusals", o)
  L('def g_bf() -> IO(Unit):\n  do IO<Unit>:')
  for hi, lo in BFIELDS:
    L(f'    srow(f"bf_{hi}_{lo}", bfg(Fld.plain("f", {hi}, {lo})))')
    L(f'    urow(f"bf_mask_{hi}_{lo}", bf_mask(Fld.plain("f", {hi}, {lo})))')
  for hi, lo in BF_SET:
    for raw in (0, 3735928559):
      for val in (0, 1, 7, 8, 255, 4294967295):
        L(f'    srow(f"bfset_{hi}_{lo}_{raw}_{val}", bfs(Fld.plain("f", {hi}, {lo}), {raw}, {val}))')
  for nm, hi, lo, dflt in [("op7", 7, 0, 0), ("enc33", 6, 0, 33), ("enc17", 16, 8, 0)]:
    L(f'    srow("fixed_{nm}", bfs(Fld.fixed("op", {hi}, {lo}, {dflt}), 4294967295, 4294967295))')
    L(f'    srow("fixed_def_{nm}", u32_text(Fld.dflt(Fld.fixed("op", {hi}, {lo}, {dflt}))))')
    L(f'    row("fixed_cls_{nm}", fixed_set(1, 0))')

  # ---------------------------------------------------------------- E
  g("E  the five field classes' encode -- one negative per positive", o)
  L('def g_enc() -> IO(Unit):\n  do IO<Unit>:')
  for hi, lo in [(8, 0), (17, 9), (25, 17), (9, 1)]:
    L(f'    urow(f"sf_mask_{hi}_{lo}", bf_mask(Fld.src("s0", {hi}, {lo})))')
    L(f'    row(f"sf_width_{hi}_{lo}", src_width_ok(Fld.src("s0", {hi}, {lo})))')
    L(f'    srow(f"sf_widthmsg_{hi}_{lo}", src_width_msg(Fld.src("s0", {hi}, {lo})))')
    for off in [0, 1, 63, 105, 106, 127, 128, 255, 256, 257, 511]:
      L(f'    urow(f"sfenc_{hi}_{lo}_{off}", Res.v(src_encode(Ov.reg({off}, 1, False{{}}, False{{}}, False{{}}), Fld.src("s0", {hi}, {lo}))))')
    for n in [0, 1, 63, 64, 65, 4294967295, 4294967280, 4294967279]:
      L(f'    urow(f"sfenc_{hi}_{lo}_i{n}", Res.v(src_encode(Ov.int({n}), Fld.src("s0", {hi}, {lo}))))')
    for off in [0, 1, 105, 127, 128, 255, 256, 257, 511]:
      L(f'    srow(f"sfdec_{hi}_{lo}_{off}", rg2({off}, 1))')
  for hi, lo in [(7, 0), (15, 8), (8, 1)]:
    L(f'    urow(f"vgpr_mask_{hi}_{lo}", bf_mask(Fld.vgpr("vdst", {hi}, {lo})))')
    for off in [256, 257, 383, 384, 511]:
      L(f'    urow(f"vgenc_{hi}_{lo}_{off}", Res.v(vgpr_encode(Ov.reg({off}, 1, False{{}}, False{{}}, False{{}}), Fld.vgpr("vdst", {hi}, {lo}))))')
    for off in [256, 300, 384, 511]:
      L(f'    urow(f"vgenchi_{hi}_{lo}_{off}", Res.v(vgpr_encode(Ov.reg({off}, 1, False{{}}, False{{}}, True{{}}), Fld.vgpr("vdst", {hi}, {lo}))))')
    L(f'    srow(f"vgencneg_{hi}_{lo}", Res.msg(vgpr_encode(Ov.reg(0, 1, False{{}}, False{{}}, False{{}}), Fld.vgpr("vdst", {hi}, {lo}))))')
  for nm, fld in [("ab", "Fld.align2(\"s\", 7, 0, 2)"), ("sb", "Fld.sbase(\"sdst\", 7, 4)"),
                  ("sr", "Fld.srsc(\"rsrc\", 6, 0)"), ("sr2", "Fld.srsc(\"rsrc\", 5, 0)")]:
    L(f'    srow("afmask_{nm}", u32_text(bf_mask({fld})))')
    for off in [0, 2, 4, 8, 100, 126, 127]:
      L(f'    urow(f"afenc_{nm}_{off}", Res.v(al_encode(Ov.reg({off}, 1, False{{}}, False{{}}, False{{}}), {fld})))')
    L(f'    srow("afenc_{nm}_zero", enc_text(al_encode(Ov.int(0), {fld})))')
    L(f'    srow("afenc_{nm}_nonreg", Res.msg(al_encode(Ov.int(7), {fld})))')
    L(f'    srow("afenc_{nm}_hi", Res.msg(al_encode(Ov.reg(128, 1, False{{}}, False{{}}, False{{}}), {fld})))')
    L(f'    srow("afenc_{nm}_odd", Res.msg(al_encode(Ov.reg(3, 1, False{{}}, False{{}}, False{{}}), {fld})))')
    for raw in [0, 1, 2, 15, 31, 32, 63]:
      L(f'    srow(f"afdec_{nm}_{raw}", rg2(U32.shln({raw}, U32.to_nat(al_shift_of({fld}))), 1))')
  for off in [256, 257, 258, 259, 510, 511, 128, 255, 0]:
    L(f'    srow("vdstyenc_{off}", enc_text(vdsty_encode(Ov.reg({off}, 1, False{{}}, False{{}}, False{{}}))))')
    L(f'    srow("vdstyencneg_{off}", Res.msg(vdsty_encode(Ov.reg({off}, 1, False{{}}, False{{}}, False{{}}))))')
  for raw in [0, 1, 2, 127, 128, 255]:
    for vdstx in [256, 257, 258, 259]:
      L(f'    srow(f"vdstyget_{raw}_{vdstx}", u32_text(vdsty_get({raw}, {vdstx})))')

  # ---------------------------------------------------------------- N
  g("N  _needs_literal", o)
  L('def g_lit() -> IO(Unit):\n  do IO<Unit>:')
  for off in [0, 1, 105, 128, 240, 255, 256, 511]:
    L(f'    row("needs_lit_reg_{off}", needs_literal(Ov.reg({off}, 1, False{{}}, False{{}}, False{{}})))')
  for n in [0, 1, 63, 64, 65, 100, 4294967295, 4294967280, 4294967279]:
    L(f'    row("needs_lit_int_{n}", needs_literal(Ov.int({n})))')
  L('    row("needs_lit_none", needs_literal(Ov.none()))')

  # ---------------------------------------------------------------- I
  g("I  the Inst field order, _base_size, and the raw-word walk", o)
  L('def g_inst() -> IO(Unit):\n  do IO<Unit>:')
  L('    srow("vop2_fields", fields_of(VOP2_FIELDS()))')
  L('    urow("vop2_base_size", base_size(hi_max(VOP2_FIELDS())))')
  L('    urow("vop2_hi_max", hi_max(VOP2_FIELDS()))')
  L('    srow("ord_fields", fields_of(ORD_FIELDS()))')
  L('    srow("ord_fields_swap", fields_of(ORD_FIELDS_SWAP()))')
  L('    srow("raw_ord", rws(raw_walk(ORD_VALS())))')
  L('    srow("raw_ord_swap", rws(raw_walk(ORD_VALS_SWAP())))')
  L('    srow("fields_F16", fields_of(F16_FIELDS()))')
  L('    urow("base_size_F16", base_size(hi_max(F16_FIELDS())))')
  L('    srow("fields_F64", fields_of(F64_FIELDS()))')
  L('    urow("base_size_F64", base_size(hi_max(F64_FIELDS())))')
  L('    urow("f64i_mask_lit", bf_mask(Fld.plain("lit", 63, 32)))')
  L('    urow("f64i_mask_frac", bf_mask(Fld.plain("f", 31, 0)))')
  L('    urow("f40i_mask", bf_mask(Fld.plain("a", 39, 8)))')
  L('    row("bf_width_ok_31", bf_width_ok(Fld.plain("f", 31, 0)))')
  L('    row("bf_width_ok_40", bf_width_ok(Fld.plain("f", 40, 0)))')
  # the raw word for a handful of field lists: the write walk's ORDER
  L('    srow("raw_vop2_all", rws(raw_walk(VOP2_ALL())))')
  L('    srow("raw_vop2_neg", rws(raw_walk(VOP2_NEG())))')
  L('    srow("raw_vop2_hi", rws(raw_walk(VOP2_HI())))')
  L('    srow("raw_vop2_int", rws(raw_walk(VOP2_INT())))')
  L('    srow("raw_vop2_fconst", rws(raw_walk(VOP2_FCONST())))')
  L('    srow("raw_vop2_fnolit", rws(raw_walk(VOP2_FNOLIT())))')
  L('    srow("raw_vop2_int65", rws(raw_walk(VOP2_INT65())))')
  L('    srow("raw_vop2_intn17", rws(raw_walk(VOP2_INTN17())))')
  L('    srow("raw_vop2_big2", rws(raw_walk(VOP2_BIG2())))')
  L('    srow("raw_vop2_lit", rws(raw_walk(VOP2_LIT())))')
  L('    srow("raw_vop2_sdwa", rws(raw_walk(VOP2_SDWA())))')
  L('    srow("raw_vop2_dpp", rws(raw_walk(VOP2_DPP())))')
  L('    srow("raw_vop2_big", rws(raw_walk(VOP2_BIG())))')
  L('    srow("raw_f32i", rws(raw_walk(F32_VALS())))')
  L('    srow("raw_f16i", rws(raw_walk(F16_VALS())))')
  L('    srow("raw_f64i", rws(raw_walk(F64_VALS())))')
  L('    srow("raw_f40i", rws(raw_walk(F40_VALS())))')
  L('    srow("raw_f8i", rws(raw_walk(F8_VALS())))')
  # THE EXEMPTION SETS, one row per boundary and one row just outside it. M44
  # and M45 were BLIND because nothing read `no_resize` / `exempt_width` at all;
  # a `0` from a mutation is a request for a fixture, not a coverage claim.
  for off in [105, 106, 107, 124, 125, 126, 127, 128, 239, 240, 248, 249, 254, 255, 256]:
    L(f'    row(f"noresize_{off}", no_resize({off}))')
    L(f'    row(f"exemptw_{off}", exempt_width({off}))')
  # `mod_merge` with the `or 0` guard and without it: the guard is what makes a
  # ZERO accumulator leave the caller's value alone (:322).
  for mg, mh, mbits in [(0, "False{}", 0), (0, "True{}", 0), (0, "False{}", 1),
                        (0, "True{}", 1), (2, "True{}", 0), (2, "True{}", 1), (6, "True{}", 1)]:
    L(f'    urow(f"modmerge_{mg}_{int(mh == chr(84) + chr(114) + chr(117) + chr(101))}_{mbits}", mod_merge({mg}, {mh}, {mbits}))')
  # `src_bit` -- the four register->bit bindings of dsl.py:314/:320. A count of
  # four would not tell you WHICH bit, so each is one row.
  for nm in ["src0", "src1", "src2", "vdst", "sdst", "op", "nosuch"]:
    L(f'    urow(f"srcbit_{nm}", src_bit("{nm}"))')
  # and the three MASKS over a real field list (:313-321)
  for bit_nm, bit in [("neg", 1), ("ab", 1), ("hi", 1), ("src0", 1), ("src1", 2), ("src2", 4), ("vdst", 8)]:
    L(f'    urow(f"modmask_{bit_nm}_vop2", mod_mask({bit}, VOP2_ALL()))')
    L(f'    urow(f"modmask_{bit_nm}_neg", mod_mask({bit}, VOP2_NEG()))')
    L(f'    urow(f"modmask_{bit_nm}_hi", mod_mask({bit}, VOP2_HI()))')
  # the modifier MERGE, and its two halves (:322-324)
  L('    urow("mod_src0_neg", mod_merge(0, False{}, mod_neg(Ov.reg(3, 1, True{}, False{}, False{}), True{})))')
  L('    urow("mod_src0_ab", mod_merge(0, False{}, mod_ab(Ov.reg(3, 1, False{}, True{}, False{}), True{})))')
  L('    urow("mod_src0_hi", mod_merge(0, False{}, mod_hi(Ov.reg(3, 1, False{}, False{}, True{}), True{})))')
  L('    urow("mod_merge_or", mod_merge(2, True{}, 1))')
  L('    urow("mod_merge_zero", mod_merge(0, True{}, 0))')
  L('    urow("mod_merge_nogiven", mod_merge(0, False{}, 1))')
  # to_bytes, little endian (:416)
  L('    srow("to_bytes_vop2", bytes_of(Res.v(raw_walk(VOP2_ALL())), base_size(hi_max(VOP2_FIELDS()))))')
  L('    srow("to_bytes_f32i", bytes_of(Res.v(raw_walk(F32_VALS())), base_size(hi_max(F32_FIELDS()))))')
  L('    srow("to_bytes_f16i", bytes_of(Res.v(raw_walk(F16_VALS())), base_size(hi_max(F16_FIELDS()))))')
  # from_bytes (:440-446)
  L('    urow("from_bytes_ff", from_bytes(4294967295))')
  L('    urow("from_bytes_dead", from_bytes(3735928559))')

  # ---------------------------------------------------------------- O
  g("O  op_bits / op_regs / canonical_* / num_srcs", o)
  L('def g_ops() -> IO(Unit):\n  do IO<Unit>:')
  for nm, name in [("cndmask", "v_cndmask_f32"), ("cmp", "v_cmp_lt_f32"),
                   ("co_ci", "v_co_ci_add_f32"), ("other", "v_add_f32"),
                   ("f8f6f4", "v_f8f6f4_mfma_f32_32x32x8_f16")]:
    L(f'    urow("adj_src2_{nm}", adj_src2_bits("{name}", True{{}}))')
    L(f'    urow("adj_vdst_{nm}", adj_vdst_bits("{name}", True{{}}))')
    L(f'    row("is_f8f6f4_{nm}", is_f8f6f4("{name}"))')
    L(f'    row("is_vop3sd_{nm}", is_vop3sd("VOP3SD"))')
  for sa in [0, 1, 62, 123, 124, 125, 126, 127, 255]:
    L(f'    urow("addr_{sa}", adj_addr_bits({sa}, False{{}}))')
    L(f'    urow("addrx_{sa}", adj_addr_bits({sa}, True{{}}))')
  L('    row("addr_exempt_scratch", addr_exempt("SCRATCH"))')
  L('    row("addr_exempt_vscratch", addr_exempt("VSCRATCH"))')
  L('    row("addr_exempt_global", addr_exempt("GLOBAL"))')
  for o_ in [0, 1]:
    for i_ in [0, 1]:
      L(f'    urow(f"vaddr_{o_}{i_}", adj_vaddr_bits({o_}, {i_}))')
  for c_ in range(5):
    for b_ in range(5):
      L(f'    srow(f"f8f6f4_{c_}_{b_}", String.concat([u32_text(mfma_bits({c_}, {c_})), ",", u32_text(mfma_bits({b_}, {b_}))]))')
      L(f'    urow(f"f8f6f4_s0_{c_}_{b_}", mfma_bits({c_}, {c_}))')
  L('    srow("f8f6f4_default_9", String.concat([u32_text(mfma_bits(9, 9)), ",", u32_text(mfma_bits(9, 9))]))')
  L('    urow("mfma_raw_cbsz", mfma_raw_cbsz(65792))')
  L('    urow("mfma_raw_blgp", mfma_raw_blgp(65792))')
  for b in [0, 1, 31, 32, 64, 96, 128, 256, 511, 1000]:
    L(f'    urow("opregs_{b}", op_regs_of({b}))')
  for nm, name in [("c_s0", "src0"), ("c_vs0", "vsrc0"), ("c_ss0", "ssrc0"),
                   ("c_s1", "src1"), ("c_vs1", "vsrc1"), ("c_ss1", "ssrc1"),
                   ("c_s2", "src2"), ("c_d", "vdst"), ("c_sdst", "sdst"),
                   ("c_sdata", "sdata"), ("c_data", "data"), ("c_vdata", "vdata"),
                   ("c_data0", "data0"), ("c_vsrc", "vsrc"), ("c_unknown", "zz")]:
    L(f'    urow("canon_seed_{nm}", canon_seed_bits(canon_of("{name}")))')
  for nm, s2, s1, s0 in [("n3", "True{}", "True{}", "True{}"), ("n3b", "True{}", "True{}", "True{}"),
                         ("n3c", "True{}", "True{}", "True{}"), ("n2", "False{}", "True{}", "True{}"),
                         ("n2b", "False{}", "True{}", "True{}"), ("n2c", "False{}", "True{}", "True{}"),
                         ("n2d", "False{}", "False{}", "True{}"), ("n1", "False{}", "False{}", "True{}"),
                         ("n1b", "False{}", "False{}", "True{}"), ("n1c", "False{}", "False{}", "True{}"),
                         ("n0", "False{}", "False{}", "False{}"), ("n0b", "False{}", "False{}", "False{}"),
                         ("n0c", "False{}", "False{}", "False{}"), ("n0d", "False{}", "False{}", "False{}")]:
    L(f'    urow("numsrcs_{nm}", num_srcs({s2}, {s1}, {s0}))')

  # ---------------------------------------------------------------- V
  g("V  _variant_suffix", o)
  L('def g_vs() -> IO(Unit):\n  do IO<Unit>:')
  for off in [0, 248, 249, 250, 255, 124, 256]:
    L(f'    srow("vsuf_{off}", vs_text(vs_off({off}, False{{}})))')
    L(f'    srow("vsufc_{off}", vs_text(vs_off({off}, True{{}})))')
  L('    srow("vsuf_none", vs_text(vs_off(0, False{})))')
  L('    row("vsuf_is_some_255", is_some(vs_off(255, False{})))')
  L('    row("vsuf_is_some_0", is_some(vs_off(0, False{})))')
  return "\n".join(o)


def main():
  # Bend has NO f-string interpolation -- a probe measured that `f"..."` in a
  # `do` block is a parse error -- and every row name here is already fully
  # interpolated by THIS file's own f-strings, so the leftover `f"` prefix is
  # stripped in one place rather than chased row by row.
  # `f"` must be preceded by `(` or a space: a bare replace also eats the `f` of
  # every identifier that ENDS in f followed by a quote -- `alias_null_off"` came
  # out as `alias_null_of"`, which is a wrong row name and not a parse error.
  body = MARK + "\n" + re.sub(r'(?<=[( ])f"', '"', gen())
  if "--check" in sys.argv:
    print(body)
    return
  text = PORT.read_text()
  i = text.find(MARK)
  if i >= 0:
    text = text[:i]
  # t_names / t_names_rev from the earlier hand-written block are superseded
  for d in ("t_names", "t_names_rev"):
    a = text.find(f"def {d}() -> IO(Unit):")
    if a >= 0:
      b = a
      while b < len(text) and not text[b].startswith("def ") and not text[b].startswith("# ==="):
        b += 1
      text = text[:a] + text[b:]
  MAIN = '''def main() -> IO(Unit):
  do IO<Unit>:
    a : Unit <- g_tables()
    b : Unit <- g_const()
    c : Unit <- g_get()
    d : Unit <- g_fmt()
    e : Unit <- g_mod()
    f : Unit <- g_bf()
    +g : Unit <- g_enc()
    h : Unit <- g_lit()
    +i : Unit <- g_inst()
    +j : Unit <- g_ops()
    +k : Unit <- g_vs()
    IO.print("dsl-done=1")
'''
  a = text.find("def main() -> IO(Unit):")
  if a >= 0:
    text = text[:a]
  PORT.write_text(text.rstrip() + "\n\n" + FIXTURES.rstrip() + "\n\n" + body + "\n" + MAIN)
  print(f"wrote {PORT.relative_to(ROOT)}")


main()