"""CPython oracle probe #2 for hcq2.py: the pure arithmetic -- HWQueue.q word
sequence, loop trip arithmetic, bufferize_cmdbuf alignment, patch group keys,
lower_call's 128-alignment accumulate, hcq_fence order, unwrap_view/lane,
_is_link_patch, _is_input_addr, sched_batches queue naming, stage_copy chunking.
Every expectation in hcq2.bend is generated BY CALLING THIS."""
import sys
sys.path.insert(0, '.')
import tinygrad.runtime.support.hcq2 as H
from tinygrad.dtype import dtypes, DType
from tinygrad.uop.ops import UOp, Ops, KernelInfo, CallInfo, ProgramInfo
from tinygrad.helpers import round_up

def buf(nm, n=1, dt=dtypes.uint64, dev=('NULL:0',)):
  return UOp.placeholder((n,), dt, 0, device=dev, tag=nm)

print('=== to_name / make_submit name (hcq2.py:63, :68-70)')
sm = H.make_submit(UOp(Ops.NOOP), UOp(Ops.NOOP), devs='NULL:0', queue='COPY:0')
lin = sm.src[0]
print('make_submit', sm.op.name, 'src', [u.op.name for u in sm.src], 'body arg', lin.arg)
print('fn name', sm.arg, 'ncmds', len(lin.src))
print('names', H.make_submit(UOp(Ops.NOOP), devs=('AMD:0', 'AMD:1'), queue='COMPUTE:0').src[0].arg,
      H.make_submit(UOp(Ops.NOOP), devs=('AMD:0', 'AMD:1'), queue='COMPUTE:0').arg)
for devs, q in (('NULL:0', 'COPY:0'), ('AMD:0', 'COPY:3'), ('CUDA:1', 'COMPUTE:0'), ('QCOM:0', 'ENCDEC:0')):
  print('submit_name', devs, q, '->', H.to_name('submit', devs.split(':')[0], q.split(':')[0]))

print('=== HWQueue.q (hcq2.py:366-377) THE WORD SEQUENCE')
class Q(H.HWQueue): pass
sub = H.make_submit(UOp(Ops.NOOP), devs='NULL:0', queue='COPY:0')
hq = Q(sub)
def show(lbl, f):
  b0, p0 = bytes(hq.blob), list(hq.patches)
  r = f()
  print(lbl, 'ret', r, 'blob', bytes(hq.blob).hex(), 'patches', hq.patches)
  hq.blob, hq.patches = bytearray(b0), list(p0)
show('q 7', lambda: hq.q(7))
show('q 0x41414141', lambda: hq.q(0x41414141))
show('q c7,c8', lambda: hq.q(7, 8))
show('q c7,buf', lambda: hq.q(7, buf('a')))
show('q c7,buf,c9', lambda: hq.q(7, buf('a'), 9))
show('q const', lambda: hq.q(UOp.const(0xdeadbeef, dtypes.uint32)))
show('q const u64', lambda: hq.q(UOp.const(0xdeadbeefcafebabe, dtypes.ulong)))
show('q binary', lambda: hq.q(UOp(Ops.BINARY, arg=bytes([1, 2, 3, 4]))))
show('q binary after word', lambda: hq.q(7, UOp(Ops.BINARY, arg=bytes([9, 9]))))
show('q casted const', lambda: hq.q(UOp.const(1, dtypes.uint32).cast(dtypes.int)))
show('q casted const x2', lambda: hq.q(UOp.const(1, dtypes.uint8).cast(dtypes.int).cast(dtypes.int)))
show('q nothing', lambda: hq.q())
show('q 0', lambda: hq.q(0))
show('q 0xffffffff', lambda: hq.q(0xffffffff))
show('q 0x1ffffffff', lambda: hq.q(0x1ffffffff))
show('q buf then buf', lambda: hq.q(buf('a'), buf('b')))
show('q binary pad128', lambda: hq.q(UOp(Ops.BINARY, arg=bytes((-len(hq.blob)) % 128))))
show('q pad after 4', lambda: (hq.q(7), hq.q(UOp(Ops.BINARY, arg=bytes((-len(hq.blob)) % 128)))))

print('=== HWQueue.loop trip arithmetic (hcq2.py:379-385)')
# the pure part: patches[(o,w)] -> [(o + 4*k + r*trip, (w>>(32*k)).cast(uint32))]
for itemsz, trip, rvmax in ((8, 16, 3), (4, 12, 2), (8, 8, 1), (4, 4, 5)):
  for o in (0, 4, 8, 12):
    for k in range(itemsz // 4):
      print('loop', 'itemsz', itemsz, 'trip', trip, 'r', rvmax, 'at', o, 'k', k,
            '->', o + 4*k + 1*trip, 'dwords', itemsz // 4, 'blobgrow', trip * rvmax)

print('=== bufferize_cmdbuf alignment (hcq2.py:459-463, :471)')
for n in (0, 1, 4, 128, 129, 130, 132, 260, 384):
  print('align128', n, '-> pad', (-n) % 128, 'newend', n + ((-n) % 128))
print('loopable_r o%4 and itemsize in (4,8)')
for o, itemsz in ((0, 4), (4, 8), (8, 8), (2, 8), (0, 2), (12, 4), (0, 16)):
  print('rt_filter', o, itemsz, '->', (o % 4 == 0) and itemsz in (4, 8))
print('dword offsets  base + 4*k')
for base in (0, 8, 512):
  for k in range(2):
    print('dword_at', base, k, '->', base + 4*k)

print('=== _is_link_patch / _is_input_addr (hcq2.py:393-400)')
cases = [
  ('param untagged', UOp.param(0, dtypes.uint, 4, ('NULL:0',))),
  ('param tagged', UOp.param(0, dtypes.uint, 4, ('NULL:0',)).replace(tag='lt_input')),
  ('buffer global', buf('a')),
  ('load', buf('a').index(0).load()),
  ('after', buf('a').index(0).after(UOp(Ops.NOOP))),
  ('getaddr', buf('a').getaddr('NULL:0')),
  ('range', UOp.range(4, 0)),
  ('add of param', (UOp.param(1, dtypes.uint, 4, ('NULL:0',)) + UOp.param(0, dtypes.uint, 4, ('NULL:0',)))),
]
for nm, w in cases:
  print('is_link', nm, w.op.name, '->', H._is_link_patch(w))
for nm, w in cases:
  if w.op is Ops.GETADDR:
    print('is_input_addr', nm, '->', H._is_input_addr(w))

print('=== patch group keys (hcq2.py:404-413)')
rows = [(0, buf('a', 1, dtypes.uint64)), (4, buf('b', 1, dtypes.uint64)), (2, buf('c', 1, dtypes.uint32))]
for o, w in rows:
  print('key', o, str(w.dtype), '->', (str(w.dtype), getattr(o, 'vmin', o) % w.dtype.itemsize,
                                       type(o) is int and H._is_link_patch(w), tuple(getattr(o, 'ranges', ()))))
for o, dt in ((0, dtypes.uint32), (1, dtypes.uint32), (2, dtypes.uint32), (3, dtypes.uint32), (0, dtypes.uint64)):
  print('phase', o, 'itemsize', dt.itemsize, '->', o % dt.itemsize, 'index', o // dt.itemsize,
        'viewlen', (128 - o) // dt.itemsize * dt.itemsize)

print('=== lower_call 128-alignment accumulate (hcq2.py:530-532)')
for u in ((1, dtypes.uint8), (7, dtypes.uint8), (128, dtypes.uint8), (1, dtypes.uint32), (3, dtypes.uint32),
          (1, dtypes.uint64), (129, dtypes.uint8), (200, dtypes.uint64), (2, dtypes.uint16)):
  n, dt = u
  print('roundup128', n, str(dt), '->', round_up(n, 128), 'elems', round_up(n, 128) // dt.itemsize)
print('accumulate [3,1,2] uint64 ->', end=' ')
import itertools
print(list(itertools.accumulate([round_up(n, 128) // dtypes.uint64.itemsize for n in (3, 1, 2)], initial=0)))
print('accumulate [5,4] uint32 ->', list(itertools.accumulate([round_up(n, 128) // dtypes.uint32.itemsize for n in (5, 4)], initial=0)))
print('min(numel,1)', [(n, min(n, 1)) for n in (0, 1, 5)])

print('=== unwrap_view / unwrap_lane / select_lane (hcq2.py:50-61)')
b = buf('a', 16, dtypes.uint32)
sh = b[4:12]
bc = sh.cast(dtypes.uint8)
af = bc.after(UOp(Ops.NOOP))
af2 = af.after(UOp(Ops.NOOP))
for nm, v in (('base', b), ('shrink', sh), ('bitcast', bc), ('after', af), ('after2', af2)):
  r, off = H.unwrap_view(v)
  print('unwrap_view', nm, v.op.name, '->', r.op.name, r.tag, off, 'nbytes', r.shape[0] * r.dtype.itemsize)
ms = UOp(Ops.MSELECT, src=(sh, UOp.const(1, dtypes.int)), arg=3)
for nm, v in (('shrink', sh), ('mselect', ms)):
  r, lane, off = H.unwrap_lane(v)
  print('unwrap_lane', nm, v.op.name, '->', r.op.name, r.tag, 'lane', lane, 'off', off)

print('=== hcq_fence (hcq2.py:415-434) THE ORDER')
r = UOp.range(8, 0)
sink = UOp(Ops.SINK, src=((r+r).cast(dtypes.uint64),), arg=KernelInfo("k"))
def mkcall(bufs, outs=(0,), ins=(1,)):
  prg = UOp(Ops.PROGRAM, src=(sink,), arg=ProgramInfo(outs=outs, ins=ins))
  return UOp(Ops.CALL, src=(prg, *bufs), arg=CallInfo())
batch = [(mkcall([b, buf('d')]), ('NULL:0',), 'COMPUTE:0'), (mkcall([buf('d'), buf('e')]), ('NULL:0',), 'COPY:0')]
ctx = H.BatchCtx(batch, False)
fb = H._finalize_batch(ctx)
fence = fb.body.src[0].src[0].src[0]  # the hcq_fence custom_function's call
print('fence probe op', fence.op.name)
def find_fence(u, d=0):
  if d > 12: return None
  if u.op is Ops.CUSTOM_FUNCTION and getattr(u, 'arg', None) == 'hcq_fence': return u
  for s in u.src:
    if (r := find_fence(s, d+1)) is not None: return r
  return None
ff = find_fence(fb)
print('found hcq_fence', ff.op.name if ff is not None else None)
if ff is not None:
  fe = H.hcq_fence(ff)
  print('hcq_fence out', fe.op.name, 'nsrc', len(fe.src))
  seen = set()
  def ops_of(u, d=0):
    if u in seen or d > 12: return
    seen.add(u)
    print(' ' * d, u.op.name, str(u.dtype), repr(u.arg)[:40])
    for s in u.src: ops_of(s, d+1)
  ops_of(fe)

print('=== stage_copy chunking (hcq2.py:131, :157)')
SS, SSLOTS = H.STAGING_SIZE, H.STAGING_SLOTS
print('STAGING_SIZE', SS, 'STAGING_SLOTS', SSLOTS, 'per-slot', SS // SSLOTS)
for it, maxnumel in ((1, 1000), (4, 1000), (2, 67108865), (1, 134217729)):
  chunk = (SS // SSLOTS) // it
  n = -(-maxnumel // chunk)
  print('chunk it', it, 'numel', maxnumel, '-> chunk', chunk, 'ncopies', n, 'last', maxnumel - (n-1)*chunk)
for i in range(4):
  print('slot_of', i, '->', (i % SSLOTS) * (SS // SSLOTS) // 1)

print('=== sched_batches / get_enqueue_devs (hcq2.py:40-48, :314-333)')
print('QCOM store skip', 'QCOM:0'.startswith(('QCOM', 'METAL')), 'NV store', 'NV:0'.startswith(('QCOM', 'METAL')))
print('is_hcq AMD/AMD/NV/NULL/METAL/CUDA/QCOM/CPU:',
      [d in H.HCQ_DEVS for d in ('AMD', 'AMD:1', 'NV', 'NULL', 'METAL', 'CUDA', 'QCOM', 'CPU')])
print('HCQ_DEVS dsplit', [d.split(':')[0] in H.HCQ_DEVS for d in ('NV:0:1', 'NVX', 'NV', 'CPU:0:1:2')])
print('num_queues default min(peers,8)=', min(3, 8), 'with ALL2ALL=0 ->', 1, 'getenv clamp max(1, 0) =', max(1, 0))