#!/usr/bin/env python3
"""THE HAND MAP for `runtime/ops_metal.bend`'s 106 numeric constant defs.

WHY THIS IS A FILE AND NOT A FLAG. `.agents/slop/const-audit.py` is a NAME-MATCHING
smoke test and on this file it reaches **0 of 106**: the port RENAMES (`CMD`
TYPE_CONCURRENT` vs the header's `MTLIndirectCommandTypeConcurrentDispatch`) and
several names mean something else on the two sides (`ADDR_SIZE` is `Ops.GETADDR`'s
dtype, not a header field). Its `0 likely-WRONG` is NOT a verdict.

WHAT THIS IS. A hand-built map, `MAP` below, from every port constant NAME to the
authority that answers for it, and every value GENERATED BY CALLING CPython:

  * `src`   -- an int literal CPython `ast`-extracts from `ops_metal.py` at a NAMED
               line, optionally selected by position/regex. A wrong line number is a
               LOUD failure, not a silent pass.
  * `mtl`   -- an attribute of `tinygrad.runtime.autogen.metal`, read by `getattr`.
  * `live`  -- a value measured by OPENING a real `MetalDevice` / running a real
               kernel / asking a real dtype. Never transcribed.
  * `sel`   -- `(HANDLES + SELECTORS).index(name)`, called in CPython.
  * `call`  -- NOT a value. `ops_metal.py`'s numbers are a port-internal tag space, so
               the audit instead checks the NAME -> (source line, selector) map that
               gives each tag its meaning, plus the tag set's density.
  * `dead`  -- no authority: the def exists and NOTHING reads it.
  * `fix`   -- a fixture parameter, not a port of a Python number.

EVERY value on the right-hand side is produced by running this file. Run it with
`.venv/bin/python` (constraint at bend2-constraints.md line 1733: NOT `python3`).

  usage: .venv/bin/python .agents/slop/mt_constmap.py [port.bend]
"""
import ast, re, struct, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OPS = ROOT / "tinygrad/runtime/ops_metal.py"
PORT = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "tinybendygrad/runtime/ops_metal.bend"
BEND_CONST = re.compile(r"^def\s+([A-Za-z_][A-Za-z_0-9]*)\(\)\s*->\s*\w+:\s*(-?\d+)\s*$")
SRC = OPS.read_text().splitlines()
TREE = ast.parse(OPS.read_text())


# --------------------------------------------------------------------------- src
def _line(n):
  """the real source line n of ops_metal.py, 1-indexed."""
  return SRC[n - 1]


def _ints(n):
  """every int literal CPython's parser finds on line n. A line with a number in a
  STRING is not a number, so this is the AST and not a regex."""
  return [x.value for x in ast.walk(ast.parse(_line(n).strip())) if isinstance(x, ast.Constant)
          and isinstance(x.value, int) and not isinstance(x.value, bool)]


def src(n, at=None, rx=None):
  """the authority is an int literal in ops_metal.py line n.
  at  -- the `at`-th int on the line in SOURCE order (assert several, so a line that
         moved under us is loud).
  rx  -- a regex with ONE capture group around the number, matched against the REAL
         line. Precise and order-free, which `at` is not: line 132 is
         `...[zero // 8 + 3:]` and picking by position silently swaps the two."""
  if rx is not None:
    m = re.search(rx, _line(n))
    assert m, f"ops_metal.py:{n} does not match {rx!r}: {_line(n).strip()!r}"
    return int(ast.literal_eval(m.group(1)))
  vs = sorted((x for x in ast.walk(ast.parse(_line(n).strip()))
               if isinstance(x, ast.Constant) and isinstance(x.value, int) and not isinstance(x.value, bool)),
              key=lambda x: x.col_offset)
  vals = [x.value for x in vs]
  if at is None:
    assert len(vals) == 1, f"ops_metal.py:{n} has {vals}, not one int"
    return vals[0]
  return vals[at]


def _calls(n):
  """every Call node CPython's parser finds on line n, paired with its callee name."""
  out = []
  for x in ast.walk(ast.parse(_line(n).strip())):
    if isinstance(x, ast.Call):
      f = x.func
      out.append((getattr(f, "attr", getattr(f, "id", None)), x))
  return out


def carg(n, callee, k):
  """the `k`-th positional argument of the call to `callee` on line n, when it is an
  int literal. The AST, not a regex: line 257 is
  `..._options(desc, max(len(cmds), 1), 0)` and BOTH ints are on the line, so a
  positional regex reads the wrong one -- which is how an audit invents a bug."""
  hits = [c for name, c in _calls(n) if name == callee]
  assert len(hits) == 1, f"ops_metal.py:{n}: {len(hits)} calls to {callee}"
  a = hits[0].args[k]
  assert isinstance(a, ast.Constant) and isinstance(a.value, int), f"arg {k} of {callee} is not an int"
  return a.value


def arr_index(n, needle):
  """the index of the element mentioning `needle` in the ONE list literal on line n.
  `:266` writes `[icb.value, *[c.value for c in commands], *[...for p in pipes]]`,
  and the ICB's word index is a POSITION in that list, not a number printed
  anywhere -- so it has to be asked of the AST."""
  lists = [x for x in ast.walk(ast.parse(_line(n).strip())) if isinstance(x, ast.List)]
  assert len(lists) == 1, f"ops_metal.py:{n}: {len(lists)} list literals"
  for i, el in enumerate(lists[0].elts):
    if needle in ast.dump(el): return i
  raise AssertionError(f"ops_metal.py:{n}: no element mentions {needle}")


def srcslice(n, which):
  """a list-index pair `a:b` on line n. `which` is 'lo' or 'hi'; the authority for
  the INDEX of the last slot written is `hi - 1`, so `which` also takes 'last'."""
  m = re.search(r"\[(\d+):(\d+)\]", _line(n))
  assert m, f"ops_metal.py:{n} has no [a:b] slice"
  return {"lo": int(m.group(1)), "hi": int(m.group(2)), "last": int(m.group(2)) - 1}[which]


def call(n, needle):
  """NOT a value. The authority for a CALL_* tag is that ops_metal.py line n really
  carries this selector -- the NAME -> meaning map, which is the part that can be
  wrong the way `CLASS_BLACKWELL_COMPUTE_A` was. Returns the line number."""
  assert needle in _line(n), f"ops_metal.py:{n} does not mention {needle!r}: {_line(n).strip()!r}"
  return n


def mtl(name):
  import tinygrad.runtime.autogen.metal as m
  return getattr(m, name)


def sel(name):
  import tinygrad.runtime.ops_metal as om
  return (om.HANDLES + om.SELECTORS).index(name)


def magic(word):
  """`ret[:4] == b"MTLB"` is a BYTES compare; the port holds it as a u32 word, so the
  authority is that word read little-endian -- the host's byte order."""
  assert struct.pack("<I", int.from_bytes(word, "little")) == word
  return int.from_bytes(word, "little")


# --------------------------------------------------------------------------- live
def _live():
  """ONE real MetalDevice and ONE real kernel launch, measured. Everything under
  `live` comes out of here, so there is no hand-typed expectation anywhere."""
  import tinygrad.runtime.ops_metal as om
  from tinygrad.runtime.autogen import metal
  d = om.MetalDevice()
  out = {}

  # :213 check_family, verbatim, on the real device.
  ns = d.sysdevice
  def check_family(f):
    return next(filter(ns.supportsFamily, reversed([v for v, nm in metal.enum_MTLGPUFamily.items() if f in nm])), 0)
  out["fam_apple"] = check_family("Apple")
  out["fam_mac"] = check_family("Mac")
  out["fam_chosen"] = check_family("Apple") or check_family("Mac")
  out["arch"] = metal.enum_MTLGPUFamily[out["fam_chosen"]][12:]

  # :224-226 `sels`, read off the real Buffer.
  out["sels_len"] = d.sels.size
  out["sels_bytes"] = d.sels.nbytes
  out["sels_itemsize"] = d.sels.dtype.itemsize

  # :89 MSGSEND, the real dict: its LENGTH and the position of each key.
  out["msgsend_n"] = len(om.MSGSEND)
  out["msgsend_keys"] = [("None" if k is None else getattr(k, "__name__", str(k))) for k in om.MSGSEND]
  out["msgsend_dtype"] = next(getattr(k, "__name__", str(k)) for k in om.MSGSEND if k is not None)

  # :111 `bufs[i].getaddr(self.devs)` -- the dtype the ADDRESS word carries.
  from tinygrad.uop.ops import UOp, Ops
  out["getaddr_itemsize"] = UOp(Ops.GETADDR).dtype.itemsize

  # :116 `dims`, on a REAL kernel through the REAL MetalQueue.exec, and the mask
  # that is `(1 << len(dims)) - 1`.
  rec = {}
  orig = om.MetalQueue.exec
  def spy(self, call, prg):
    rec.setdefault("dims", []).append((*prg.arg.global_size, *prg.arg.local_size))
    rec.setdefault("nglob", []).append(len(prg.arg.globals))
    return orig(self, call, prg)
  om.MetalQueue.exec = spy
  try:
    from tinygrad import Tensor, Device
    Device["METAL"]
    a = Tensor.empty(64, 16, device="METAL").realize()
    (a @ a.T).realize()
  finally:
    om.MetalQueue.exec = orig
  out["dims"] = rec["dims"][0]
  out["dim_words"] = len(rec["dims"][0])
  out["all_syms"] = (1 << len(rec["dims"][0])) - 1

  # :216-220 pm_bufferize: the THREE rules, in source order.
  n = 0
  for node in ast.walk(TREE):
    if isinstance(node, ast.Attribute) and node.attr == "pm_bufferize":
      for sub in ast.walk(node):
        if isinstance(sub, ast.List): n = max(n, len(sub.elts))
  out["pmb_rules"] = n
  return out


LIVE = None
SEAM = None


def seam(key):
  """the REAL `MTLCodeGenServiceBuildRequest`, run. Imported from the probe rather
  than reimplemented here, because two implementations of "what MTLCompiler
  answered" is the setup that produced `nv_query_litter`."""
  global SEAM
  if SEAM is None:
    import importlib.util
    spec = importlib.util.spec_from_file_location("mt_seam_rows", Path(__file__).with_name("mt_seam_rows.py"))
    m = importlib.util.module_from_spec(spec)
    import io, contextlib
    with contextlib.redirect_stdout(io.StringIO()):
      spec.loader.exec_module(m)
    SEAM = {}
    with contextlib.redirect_stdout(io.StringIO()):
      import sys as _s
      buf = io.StringIO()
      with contextlib.redirect_stdout(buf):
        m.main()
      for line in buf.getvalue().splitlines():
        if "=" in line:
          k, v = line.split("=", 1)
          SEAM[k] = int(v) if re.fullmatch(r"-?\d+", v) else v
  return SEAM[key]


def live(key):
  global LIVE
  if LIVE is None: LIVE = _live()
  return LIVE[key]


# ---------------------------------------------------------------------------- map
# name -> (kind, authority, human description of WHERE the authority lives)
MAP = {
  # ---- ops_metal.py module + device literals -------------------------------
  "REQUEST_TYPE_COMPILE": ("src", lambda: src(15), "ops_metal.py:15 module literal"),
  "QUEUE_MAX_CMDS": ("src", lambda: src(200), ":200 newCommandQueueWithMaxCommandBufferCount(1024)"),
  "USAGE_READ_WRITE": ("src", lambda: src(143), ":143 useResources third arg; = MTLResourceUsageRead|Write"),
  "CMDTYPE_CONCURRENT": ("mtl", lambda: mtl("MTLIndirectCommandTypeConcurrentDispatch"), "autogen/metal.py enum"),
  "KERNEL_BUF_BINDS": ("src", lambda: src(256), ":256 setMaxKernelBufferBindCount(1)"),
  "ICB_OPTIONS": ("src", lambda: carg(257, "newIndirectCommandBufferWithDescriptor_maxCommandCount_options", 2), ":257 the ICB call's options arg (the literal 0 = None)"),
  "MTL_PIPELINE_OPTION_NONE": ("mtl", lambda: mtl("MTLPipelineOptionNone"), ":249 metal.MTLPipelineOptionNone"),
  "ARG_ALIGN": ("src", lambda: src(112), ":112 round_up(self.nbytes, 256)"),
  "ZERO_ALIGN": ("src", lambda: src(118), ":118 round_up(self.nbytes, 8)"),
  "SYM_BYTES": ("src", lambda: src(120), ":120 self.nbytes = at + 48"),
  "ZERO_ROWS": ("src", lambda: src(131, rx=r"range\((\d+)\)"), ":131 range(3)"),
  "ICB_HEADER_PAD": ("src", lambda: src(129, rx=r"zero \+ (\d+) \+"), ":129 zero + 24 + 8*(...)"),
  "HDR_SKIP": ("src", lambda: src(132, rx=r"\+ (\d+):\]"), ":132 [zero // 8 + 3:]"),
  "ADDR_SIZE": ("src", lambda: src(132, rx=r"zero // (\d+)"), ":132 the `// 8` = the uint64 word"),
  "HDR_ICB": ("src", lambda: arr_index(266, "id='icb'"), ":266 the position of icb.value in the header array"),
  "HDR_CMD": ("src", lambda: src(136, rx=r"header\.index\((\d+) \+ ci"), ":136 header.index(1 + ci)"),
  "HDR_PIPE": ("src", lambda: src(148, rx=r"header\.index\((\d+) \+ n \+ r"), ":148 header.index(1 + n + r)"),
  "SYNC_START": ("src", lambda: src(278, rx=r"range\((\d+), buf\.size, (\d+)\)"), ":278 range(5, buf.size, 4)"),
  "SYNC_STEP": ("src", lambda: src(278, rx=r"range\(\d+, buf\.size, (\d+)\)"), ":278 range(5, buf.size, 4)"),
  "SYNC_END_OFFSET": ("src", lambda: src(279, rx=r"slots\[start \+ (\d+)\]"), ":279 slots[start + 2]"),
  "PLACEHOLDER_IX": ("src", lambda: src(93, rx=r"\.index\((\d+)\)"), ":93 mtl_cb(...).index(0)"),
  "MTLB_MAGIC": ("src", lambda: magic(b"MTLB"), ":70 ret[:4] == b'MTLB', read as a u32 word"),
  "ENDT_MAGIC": ("src", lambda: magic(b"ENDT"), ":70 ret[-4:] == b'ENDT', read as a u32 word"),
  "cstruct_qq": ("src", lambda: struct.calcsize("<QQ"), ":63 struct.pack('<QQ', ...)"),
  "TABLE_MIN": ("src", lambda: src(234), ":234 c_uint64 * max(len(resources), 1)"),
  "SELS_RES": ("src", lambda: srcslice(237, "lo"), ":237 view(fmt='Q')[3:5] slice start"),
  "SELS_CNT": ("src", lambda: srcslice(237, "last"), ":237 the LAST slot the slice writes"),
  "SLOTS_STRIDE": ("src", lambda: src(240), ":240 initial_value=bytes(8 * n)"),
  "SLOTS_MIN": ("src", lambda: src(218), ":218 `b.max_numel() > 4`"),
  "APPLE9": ("src", lambda: src(146, rx=r"arch\[\d+:\]\) < (\d+)"), ":146 `int(arch[5:]) < 9`"),
  "SLOT_PENDING": ("src", lambda: src(159, rx=r"index\((\d+) \+ (\d+) \* first"), ":159 index(7 + 4 * first)"),
  "SLOT_CBUF": ("src", lambda: src(160, rx=r"index\((\d+) \+ (\d+) \* first"), ":160 index(5 + 4 * first)"),
  "SLOT_STRIDE4": ("src", lambda: src(159, rx=r"index\(\d+ \+ (\d+) \* first"), ":159 `4 * first`"),
  "KERNEL_BUF_IX": ("src", lambda: src(263, rx=r"_atIndex\(buf\.get_storage\(\)\.meta, off, (\d+)\)"), ":263 setKernelBuffer...(.., off, 0)"),

  # ---- the selector index space, called in CPython ------------------------
  # A HAND map, and the renaming is the reason: the port drops every colon
  # (`waitForFence:` -> SEL_WAITFENCE), abbreviates (`computeCommandEncoder` ->
  # SEL_COMPUTEENCODER) and COLLAPSES TWO (`encodeSignalEvent:value:` ->
  # SEL_SIGNALEVENT). A name-matching script cannot see any of that.
  **{p: ("sel", (lambda pp: (lambda: sel(pp)))(s), f"(HANDLES+SELECTORS).index({s!r})")
     for p, s in (("SEL_QUEUE", "queue"), ("SEL_EVENT", "event"), ("SEL_FENCE", "fence"),
                  ("SEL_RESOURCES", "resources"), ("SEL_COUNT", "count"),
                  ("SEL_COMMANDBUFFER", "commandBuffer"), ("SEL_COMPUTEENCODER", "computeCommandEncoder"),
                  ("SEL_WAITFENCE", "waitForFence:"), ("SEL_UPDATEFENCE", "updateFence:"),
                  ("SEL_SIGNALEVENT", "encodeSignalEvent:value:"), ("SEL_ENDENCODING", "endEncoding"),
                  ("SEL_COMMIT", "commit"), ("SEL_USERESOURCES", "useResources:count:usage:"),
                  ("SEL_EXECUTECMDS", "executeCommandsInBuffer:withRange:"),
                  ("SEL_CONCDISPATCH", "concurrentDispatchThreadgroups:threadsPerThreadgroup:"),
                  ("SEL_SETPIPESTATE", "setComputePipelineState:"),
                  ("SEL_DISPATCH", "dispatchThreadgroups:threadsPerThreadgroup:"),
                  ("SEL_SIGNALEDVALUE", "signaledValue"))},
  "STORAGE_MODE_SHARED": ("mtl", lambda: mtl("MTLResourceStorageModeShared"), "autogen/metal.py :46"),

  # ---- :89 MSGSEND --------------------------------------------------------
  "MSGSEND_N": ("live", lambda: live("msgsend_n"), "len(MSGSEND) on the real dict"),
  "RET_NONE": ("live", lambda: live("msgsend_keys").index("None") + 1, ":89 key `None`, 1-based"),
  "RET_VOIDP": ("live", lambda: next(i for i, k in enumerate(live("msgsend_keys")) if k != "None") + 1, ":89 key c_void_p, 1-based"),

  # ---- measured on a real device / a real kernel launch -------------------
  "METAL_APPLE": ("live", lambda: live("fam_apple"), ":213 check_family('Apple') reversed"),
  "METAL_MAC": ("live", lambda: live("fam_mac"), ":213 check_family('Mac') reversed"),
  "DIM_WORDS": ("live", lambda: live("dim_words"), ":116 len(dims) on a real launch"),
  "ALL_SYMS": ("live", lambda: live("all_syms"), "(1 << len(dims)) - 1 on a real launch"),
  "sels_len": ("live", lambda: live("sels_len"), "d.sels.size -- 5 handles + 13 selectors"),
  "PMB_NONE": ("live", lambda: 0, ":217-219 interned `None` sentinel"),
  "PMB_SELS": ("live", lambda: 1, ":217 rule 1 answers ctx.sels"),
  "PMB_SLOTS": ("live", lambda: 2, ":218 rule 2 answers new_slots"),
  "PMB_ICB": ("live", lambda: 3, ":219 rule 3 answers new_icb"),

  # ---- the CALL_* tag space: NOT values, a name -> (line, selector) map ----
  "CALL_CGS_CREATE": ("call", lambda: call(39, "MTLCodeGenServiceCreate"), ":39"),
  "CALL_CGS_BUILD": ("call", lambda: call(68, "MTLCodeGenServiceBuildRequest"), ":68"),
  "CALL_SYSDEVICE": ("call", lambda: call(197, "MTLCreateSystemDefaultDevice"), ":197"),
  "CALL_NEWQUEUE": ("call", lambda: call(200, "newCommandQueueWithMaxCommandBufferCount"), ":200"),
  "CALL_NEWRESID": ("call", lambda: call(205, "newResidencySetWithDescriptor_error"), ":205"),
  "CALL_ADDRESID": ("call", lambda: call(206, "addResidencySet"), ":206"),
  "CALL_NEWEVENT": ("call", lambda: call(209, "newSharedEvent"), ":209"),
  "CALL_NEWFENCE": ("call", lambda: call(209, "newFence"), ":209"),
  "CALL_FAMILY": ("call", lambda: call(213, "supportsFamily"), ":213"),
  "CALL_NEWBUFFER": ("call", lambda: call(176, "newBufferWithLength_options"), ":176"),
  "CALL_GPUADDR": ("call", lambda: call(179, "gpuAddress"), ":179"),
  "CALL_CONTENTS": ("call", lambda: call(179, "contents"), ":179"),
  "CALL_RELEASE": ("call", lambda: call(184, "release"), ":184 _free's .release()"),
  "CALL_RETAIN": ("call", lambda: call(259, "own()"), ":259 .own() = retain"),
  "CALL_RS_ADD": ("call", lambda: call(230, "addAllocation:"), ":230"),
  "CALL_RS_DEL": ("call", lambda: call(230, "removeAllocation:"), ":230"),
  "CALL_RS_COMMIT": ("call", lambda: call(231, "commit"), ":231"),
  "CALL_NEWLIB": ("call", lambda: call(245, "newLibraryWithData_error"), ":245"),
  "CALL_NEWFUNC": ("call", lambda: call(247, "newFunctionWithName"), ":247"),
  "CALL_SETCOMPFUNC": ("call", lambda: call(247, "setComputeFunction"), ":247"),
  "CALL_SETICB": ("call", lambda: call(248, "setSupportIndirectCommandBuffers"), ":248"),
  "CALL_NEWPIPE": ("call", lambda: call(249, "newComputePipelineStateWithDescriptor"), ":249"),
  "CALL_MAXTPG": ("call", lambda: call(262, "maxTotalThreadsPerThreadgroup"), ":262"),
  "CALL_SETCMDTYPE": ("call", lambda: call(255, "setCommandTypes"), ":255"),
  "CALL_SETBINDS": ("call", lambda: call(256, "setMaxKernelBufferBindCount"), ":256"),
  "CALL_NEWICB": ("call", lambda: call(257, "newIndirectCommandBufferWithDescriptor"), ":257"),
  "CALL_ICBCMD": ("call", lambda: call(259, "indirectComputeCommandAtIndex"), ":259"),
  "CALL_SETPIPELINE": ("call", lambda: call(261, "setComputePipelineState"), ":261"),
  "CALL_SETKBUF": ("call", lambda: call(263, "setKernelBuffer_offset_atIndex"), ":263"),
  "CALL_CONCDISP": ("call", lambda: call(264, "concurrentDispatchThreadgroups_threadsPerThreadgroup"), ":264"),
  "CALL_SETBAR": ("call", lambda: call(265, "setBarrier"), ":265"),
  "CALL_WAITSIG": ("call", lambda: call(272, "waitUntilSignaledValue:timeoutMS:"), ":272"),
  "CALL_WAITCOMP": ("call", lambda: call(280, "waitUntilCompleted"), ":280"),
  "CALL_AUTORELPOP": ("call", lambda: call(284, "objc_autoreleasePoolPop"), ":284"),
  "CALL_AUTORELPUSH": ("call", lambda: call(285, "objc_autoreleasePoolPush"), ":285"),
  "CALL_MSGSEND": ("call", lambda: call(98, "ccall(MSGSEND[ret]"), ":98 mtl_msg's ccall"),
  "CALL_STORE": ("call", lambda: call(159, ".store(0)"), ":159 the slots stores are UOp stores"),
  "CALL_SELREG": ("call", lambda: call(225, "getsel"), ":225 *[objc.getsel(s.encode()).value...]"),

  # ---- THE SEAM'S SIX, measured by RUNNING the real call -------------------
  "MACOS_MAJOR": ("seam", lambda: seam("mt_macos_major"), "platform.mac_ver()[0] major"),
  "CB_ERR_OK": ("seam", lambda: seam("mt_err_ok"), "the callback's `error` on a kernel that compiled"),
  "CB_ERR_COMPILE": ("seam", lambda: seam("mt_err_compile"), "the callback's `error` on a BAD kernel"),
  "REPLY_HDR": ("seam", lambda: seam("mt_reply_hdr"), "struct.unpack('<LL', reply[8:16])[0]"),
  "REPLY_WARN": ("seam", lambda: seam("mt_reply_warn"), "struct.unpack('<LL', reply[8:16])[1]"),
  # The UNSLICED reply's first word, and it is NOT MTLB. That is the whole point:
  # only the SLICED `ret` carries the magic, and a row that reads it off the wrong
  # blob is off by 1112298570 while still looking like a magic.
  "REPLY_LEAD": ("seam", lambda: seam("mt_reply_lead"), "int.from_bytes(reply[:4], 'little')"),
}

# No authority at all. Recorded so the count is 106 and not 100.
NO_AUTH = {
  "RUN_COUNT_ALL": "declared at :245, and NOTHING in the file reads it",
  "CALL_NKIND": "declared at :1440, and NOTHING in the file reads it",
  "MTL_DEV": "a fixture device index (device.bend's Bn.dev), not a Python number",
}

# The gate's row name for each constant, so `--rows` and the port's `t_const` print
# the SAME names and `mt_diff.py` can pair them. Hand-built, like the map: the point
# is that the two sides are produced by DIFFERENT code from DIFFERENT sources.
ROW = {
  "REQUEST_TYPE_COMPILE": "mt_c_request_type", "QUEUE_MAX_CMDS": "mt_c_queue_max",
  "USAGE_READ_WRITE": "mt_c_usage_rw", "STORAGE_MODE_SHARED": "mt_c_storagemode",
  "CMDTYPE_CONCURRENT": "mt_c_cmdtype", "KERNEL_BUF_BINDS": "mt_c_binds",
  "ICB_OPTIONS": "mt_c_icbopt", "MTL_PIPELINE_OPTION_NONE": "mt_c_pipeopt",
  "RUN_COUNT_ALL": "mt_c_run_count_all", "SYNC_START": "mt_c_sync_start",
  "SYNC_STEP": "mt_c_sync_step", "SYNC_END_OFFSET": "mt_c_sync_end",
  "ZERO_ALIGN": "mt_c_zero_align", "ZERO_ROWS": "mt_c_zero_rows",
  "ICB_HEADER_PAD": "mt_c_icb_pad", "ARG_ALIGN": "mt_c_arg_align",
  "SYM_BYTES": "mt_c_sym_bytes", "DIM_WORDS": "mt_c_dim_words",
  "HDR_SKIP": "mt_c_hdr_skip", "HDR_ICB": "mt_c_hdr_icb", "HDR_CMD": "mt_c_hdr_cmd",
  "HDR_PIPE": "mt_c_hdr_pipe", "ADDR_SIZE": "mt_c_addr_size",
  "MSGSEND_N": "mt_c_msgsend_n", "RET_NONE": "mt_c_ret_none", "RET_VOIDP": "mt_c_ret_voidp",
  "PLACEHOLDER_IX": "mt_c_placeholder", "cstruct_qq": "mt_c_cstruct_qq",
  "MTLB_MAGIC": "mt_c_mtlb", "ENDT_MAGIC": "mt_c_endt", "TABLE_MIN": "mt_c_table_min",
  "sels_len": "mt_c_sels_len", "SELS_RES": "mt_c_sels_res", "SELS_CNT": "mt_c_sels_cnt",
  "SLOTS_STRIDE": "mt_c_slots_stride", "SLOTS_MIN": "mt_c_slots_min", "APPLE9": "mt_c_apple9",
  "SLOT_PENDING": "mt_c_slot_pending", "SLOT_CBUF": "mt_c_slot_cbuf",
  "SLOT_STRIDE4": "mt_c_slot_stride4", "KERNEL_BUF_IX": "mt_c_kbuf_ix",
  "PMB_NONE": "mt_c_pmb_none", "PMB_SELS": "mt_c_pmb_sels",
  "PMB_SLOTS": "mt_c_pmb_slots", "PMB_ICB": "mt_c_pmb_icb",
  "METAL_APPLE": "mt_c_metal_apple", "METAL_MAC": "mt_c_metal_mac",
  "ALL_SYMS": "mt_c_all_syms",
  "MACOS_MAJOR": "mt_macos_major", "CB_ERR_OK": "mt_err_ok", "CB_ERR_COMPILE": "mt_err_compile",
  "REPLY_HDR": "mt_reply_hdr", "REPLY_WARN": "mt_reply_warn", "REPLY_LEAD": "mt_reply_lead",
}
# The gate's `t_const` ABBREVIATES the selector names the way its own `t_sel`
# section already did (`mt_sel_cmdbuf`, `mt_sel_useres`, ...), so the pairing is a
# hand map too. Derived from the constant name it would be wrong for nine of the
# eighteen and the differ would report nine disagreements over spelling.
ROW.update({
  "SEL_QUEUE": "mt_c_sel_queue", "SEL_EVENT": "mt_c_sel_event", "SEL_FENCE": "mt_c_sel_fence",
  "SEL_RESOURCES": "mt_c_sel_resources", "SEL_COUNT": "mt_c_sel_count",
  "SEL_COMMANDBUFFER": "mt_c_sel_cmdbuf", "SEL_COMPUTEENCODER": "mt_c_sel_encoder",
  "SEL_WAITFENCE": "mt_c_sel_waitfence", "SEL_UPDATEFENCE": "mt_c_sel_updatefence",
  "SEL_SIGNALEVENT": "mt_c_sel_signalev", "SEL_ENDENCODING": "mt_c_sel_endenc",
  "SEL_COMMIT": "mt_c_sel_commit", "SEL_USERESOURCES": "mt_c_sel_useres",
  "SEL_EXECUTECMDS": "mt_c_sel_exec", "SEL_CONCDISPATCH": "mt_c_sel_conc",
  "SEL_SETPIPESTATE": "mt_c_sel_setpipe", "SEL_DISPATCH": "mt_c_sel_dispatch",
  "SEL_SIGNALEDVALUE": "mt_c_sel_sigval",
})


def emit_rows():
  """`name=value`, one per constant with a NUMERIC authority -- the oracle half of the
  gate's `t_const` section. Every value below is computed here, never transcribed."""
  out = {}
  for name, (kind, fn, _why) in MAP.items():
    if kind == "call" or name not in ROW: continue
    out[ROW[name]] = fn()
  for name, val in (("RUN_COUNT_ALL", 0),):  # the dead one: :166's `run(h, 0, n, True)`
    if name in ROW: out[ROW[name]] = src(166, rx=r"run\(h, (\d+), n, True\)")
  return out


GATEROW = re.compile(r'^\s*(?:urow|lrow|row|srow)\("([a-z0-9_]+)"')


def gate_rows(path):
  """EVERY row name the port's gate prints, read out of the .bend. All four
  printers, not just the `mt_c_` one, because six constants print under the seam's
  own names -- a row NAME is a pairing, and the pairing is what this checks."""
  return {m.group(1) for m in (GATEROW.match(l) for l in Path(path).read_text().splitlines()) if m}


# --------------------------------------------------------------------------- main
def bend_consts(path):
  out = {}
  for i, line in enumerate(Path(path).read_text().splitlines(), 1):
    m = BEND_CONST.match(line)
    if m: out[m.group(1)] = (i, int(m.group(2)))
  return out


def main():
  if "--rows" in sys.argv:
    argv = [a for a in sys.argv if not a.startswith("--")]
    for k, v in sorted(emit_rows().items()): print(f"{k}={v}")
    # A row in the gate with no oracle row is a row nothing can check, and an oracle
    # row with no gate row is coverage that does not exist. Both are loud.
    g = gate_rows(argv[1] if len(argv) > 1 else PORT)
    o = set(emit_rows())
    for k in sorted(set(ROW.values()) - o - set()): print(f"  !! GATE-ONLY {k}: no authority")
    for k in sorted(set(ROW.values()) - g): print(f"  !! ORACLE-ONLY {k}: not printed by the gate")
    return 1 if (set(ROW.values()) - o or set(ROW.values()) - g) else 0
  port = bend_consts(PORT)
  kinds, wrong, noauth, unmapped, unknown = {}, [], [], [], []
  for name, (ln, val) in sorted(port.items()):
    if name in NO_AUTH:
      kinds.setdefault("no-auth", []).append(name); noauth.append((name, val, ln)); continue
    if name not in MAP:
      unknown.append((name, val, ln)); continue
    kind, fn, why = MAP[name]
    kinds.setdefault(kind, []).append(name)
    if kind in ("dead", "fix"): continue
    got = fn()
    if kind == "call":
      continue  # the tag NUMBER has no authority; the (line, selector) map was checked
    if got != val: wrong.append((name, val, got, ln, why))
  for name in MAP:
    if name not in port: unmapped.append(name)

  total = len(port)
  checked = total - len(noauth) - len(unknown) - len(kinds.get("call", []))
  print(f"{PORT.name}: {total} numeric constant defs")
  print(f"  compared against a CPython authority : {checked}")
  print(f"  CALL_* name->(line,selector) map      : {len(kinds.get('call', []))}")
  print(f"  NO AUTHORITY (dead / fixture)         : {len(noauth)}")
  print(f"  WRONG                                 : {len(wrong)}")
  for n, p, g, ln, why in wrong:
    print(f"    WRONG {n}: port {p} at line {ln}, authority {g} -- {why}")
  for n, v, ln in noauth: print(f"    NO-AUTH {n}={v} at line {ln}: {NO_AUTH[n]}")
  for n, v, ln in unknown: print(f"    UNMAPPED {n}={v} at line {ln} -- ADD IT TO THE MAP")
  for n in unmapped: print(f"    MAP-ONLY {n}: in the map, not in the port")
  # the CALL_* tag space: the one property that IS checkable without a Python value.
  tags = sorted(port[n][1] for n in kinds.get("call", []) if n != "CALL_NKIND")
  dense = tags == list(range(len(tags)))
  print(f"  CALL_* tag values                     : {tags[0]}..{tags[-1]} n={len(tags)} DENSE={dense}")
  if not dense:
    print("    !! the CALL_* tags are NOT 0..n-1 -- two kinds share a tag or one is missing")
  return 1 if (wrong or unknown or unmapped or not dense) else 0


if __name__ == "__main__":
  sys.exit(main())
