# Audits EVERY `def NAME() -> U32: <int>` in ops_nv.bend against the value
# nv_570 actually holds. The constant tables are where a silent wrong kernel
# lives, so each one is checked rather than trusted.
#   .venv/bin/python .agents/slop/nv-constaudit.py
import re, sys
sys.path.insert(0, '.')
from tinygrad.runtime.autogen import nv_570 as G

src = open('tinybendygrad/runtime/ops_nv.bend').read()
got = dict(re.findall(r'^def ([A-Z][A-Z0-9_]*)\(\) -> U32: (\d+)$', src, re.M))
print(f"{len(got)} U32 constants in the bend file\n")

# the bend NAME -> the nv_570 attribute it claims to be. Anything not in this
# map is a name of the port's own invention and is listed separately.
MAP = {
    'CLASS_HOPPER_USERMODE': 'HOPPER_USERMODE_A', 'CLASS_TURING_USERMODE': 'TURING_USERMODE_A',
    'CLASS_BLACKWELL_GPFIFO': 'BLACKWELL_CHANNEL_GPFIFO_A', 'CLASS_AMPERE_GPFIFO': 'AMPERE_CHANNEL_GPFIFO_A',
    'CLASS_BLACKWELL_COMPUTE_B': 'BLACKWELL_COMPUTE_B', 'CLASS_ADA_COMPUTE_A': 'ADA_COMPUTE_A',
    'CLASS_AMPERE_COMPUTE_B': 'AMPERE_COMPUTE_B', 'CLASS_BLACKWELL_DMA_COPY_B': 'BLACKWELL_DMA_COPY_B',
    'CLASS_AMPERE_DMA_COPY_B': 'AMPERE_DMA_COPY_B', 'CLASS_NVC9B0_VIDEO_DECODER': 'NVC9B0_VIDEO_DECODER',
    'CLASS_NVCFB0_VIDEO_DECODER': 'NVCFB0_VIDEO_DECODER', 'BLACKWELL_COMPUTE_A': 'BLACKWELL_COMPUTE_A',
    'M_SEM_ADDR_LO': 'NVC56F_SEM_ADDR_LO', 'M_NON_STALL_INTERRUPT': 'NVC56F_NON_STALL_INTERRUPT',
    'M_SET_OBJECT': 'NVC6C0_SET_OBJECT', 'M_SEND_PCAS_A': 'NVC6C0_SEND_PCAS_A',
    'M_SEND_SIGNALING_PCAS2_B': 'NVC6C0_SEND_SIGNALING_PCAS2_B', 'M_PM_TRIGGER': 'NVC6C0_PM_TRIGGER',
    'M_INVALIDATE_SHADER_CACHES_NO_WFI': 'NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI',
    'M_SET_SHADER_LOCAL_MEMORY_WINDOW_A': 'NVC6C0_SET_SHADER_LOCAL_MEMORY_WINDOW_A',
    'M_SET_SHADER_SHARED_MEMORY_WINDOW_A': 'NVC6C0_SET_SHADER_SHARED_MEMORY_WINDOW_A',
    'M_SET_SHADER_LOCAL_MEMORY_A': 'NVC6C0_SET_SHADER_LOCAL_MEMORY_A',
    'M_SET_SHADER_LOCAL_MEMORY_NON_THROTTLED_A': 'NVC6C0_SET_SHADER_LOCAL_MEMORY_NON_THROTTLED_A',
    'M_OFFSET_IN_UPPER': 'NVC6B5_OFFSET_IN_UPPER', 'M_LINE_LENGTH_IN': 'NVC6B5_LINE_LENGTH_IN',
    'M_LAUNCH_DMA': 'NVC6B5_LAUNCH_DMA', 'M_SET_SEMAPHORE_A': 'NVC6B5_SET_SEMAPHORE_A',
    'M_SET_APPLICATION_ID': 'NVC9B0_SET_APPLICATION_ID', 'M_SET_CONTROL_PARAMS': 'NVC9B0_SET_CONTROL_PARAMS',
    'M_SET_DRV_PIC_SETUP_OFFSET': 'NVC9B0_SET_DRV_PIC_SETUP_OFFSET',
    'M_SET_PICTURE_LUMA_OFFSET0': 'NVC9B0_SET_PICTURE_LUMA_OFFSET0',
    'M_SET_PICTURE_CHROMA_OFFSET0': 'NVC9B0_SET_PICTURE_CHROMA_OFFSET0',
    'M_SET_COLOC_DATA_OFFSET': 'NVC9B0_SET_COLOC_DATA_OFFSET',
    'M_SET_NVDEC_STATUS_OFFSET': 'NVC9B0_SET_NVDEC_STATUS_OFFSET',
    'M_HEVC_SET_TILE_SIZES_OFFSET': 'NVC9B0_HEVC_SET_TILE_SIZES_OFFSET',
    'M_SET_INTRA_TOP_BUF_OFFSET': 'NVC9B0_SET_INTRA_TOP_BUF_OFFSET', 'M_EXECUTE': 'NVC9B0_EXECUTE',
    'ESC_RM_ALLOC': 'NV_ESC_RM_ALLOC', 'ESC_RM_CONTROL': 'NV_ESC_RM_CONTROL', 'ESC_RM_FREE': 'NV_ESC_RM_FREE',
    'ESC_REGISTER_FD': 'NV_ESC_REGISTER_FD', 'ESC_CARD_INFO': 'NV_ESC_CARD_INFO',
    'UVM_INITIALIZE': 'UVM_INITIALIZE', 'UVM_MM_INITIALIZE': 'UVM_MM_INITIALIZE',
    'UVM_REGISTER_GPU': 'UVM_REGISTER_GPU', 'UVM_REGISTER_GPU_VASPACE': 'UVM_REGISTER_GPU_VASPACE',
    'UVM_CREATE_EXTERNAL_RANGE': 'UVM_CREATE_EXTERNAL_RANGE',
    'UVM_MAP_EXTERNAL_ALLOCATION': 'UVM_MAP_EXTERNAL_ALLOCATION',
    'UVM_ENABLE_PEER_ACCESS': 'UVM_ENABLE_PEER_ACCESS', 'UVM_FREE': 'UVM_FREE',
    'UVM_REGISTER_CHANNEL': 'UVM_REGISTER_CHANNEL',
    'NV01_ROOT_CLIENT': 'NV01_ROOT_CLIENT', 'NV01_DEVICE_0': 'NV01_DEVICE_0',
    'NV20_SUBDEVICE_0': 'NV20_SUBDEVICE_0', 'NV01_MEMORY_VIRTUAL': 'NV01_MEMORY_VIRTUAL',
    'FERMI_VASPACE_A': 'FERMI_VASPACE_A', 'KEPLER_CHANNEL_GROUP_A': 'KEPLER_CHANNEL_GROUP_A',
    'FERMI_CONTEXT_SHARE_A': 'FERMI_CONTEXT_SHARE_A', 'GT200_DEBUGGER': 'GT200_DEBUGGER',
    'MAXWELL_PROFILER_DEVICE': 'MAXWELL_PROFILER_DEVICE',
    'NVESCCARD_INFO': 'NV_ESC_CARD_INFO',
}
# the FLD_/V_ pairs: the shift is `getattr(f"{reg}_{k}")[1]` and the value is
# `getattr(f"{reg}_{k}_{v}")`.
FLD = {
    'FLD_SEM_PAYLOAD_SIZE': ('NVC56F_SEM_EXECUTE', 'PAYLOAD_SIZE', 1),
    'FLD_SEM_OPERATION': ('NVC56F_SEM_EXECUTE', 'OPERATION', 1),
    'FLD_SEM_RELEASE_WFI': ('NVC56F_SEM_EXECUTE', 'RELEASE_WFI', 1),
    'FLD_SEM_RELEASE_TIMESTAMP': ('NVC56F_SEM_EXECUTE', 'RELEASE_TIMESTAMP', 1),
    'FLD_INV_INSTRUCTION': ('NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI', 'INSTRUCTION', 1),
    'FLD_INV_GLOBAL_DATA': ('NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI', 'GLOBAL_DATA', 1),
    'FLD_INV_CONSTANT': ('NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI', 'CONSTANT', 1),
    'FLD_DMA_DATA_TRANSFER_TYPE': ('NVC6B5_LAUNCH_DMA', 'DATA_TRANSFER_TYPE', 1),
    'FLD_DMA_SRC_MEMORY_LAYOUT': ('NVC6B5_LAUNCH_DMA', 'SRC_MEMORY_LAYOUT', 1),
    'FLD_DMA_DST_MEMORY_LAYOUT': ('NVC6B5_LAUNCH_DMA', 'DST_MEMORY_LAYOUT', 1),
    'FLD_DMA_FLUSH_ENABLE': ('NVC6B5_LAUNCH_DMA', 'FLUSH_ENABLE', 1),
    'FLD_DMA_SEMAPHORE_TYPE': ('NVC6B5_LAUNCH_DMA', 'SEMAPHORE_TYPE', 1),
    'FLD_CTRL_CODEC_TYPE': ('NVC9B0_SET_CONTROL_PARAMS', 'CODEC_TYPE', 1),
    'FLD_CTRL_TESTRUN_ENV': ('NVC9B0_SET_CONTROL_PARAMS', 'TESTRUN_ENV', 1),
    'FLD_CTRL_GPTIMER_ON': ('NVC9B0_SET_CONTROL_PARAMS', 'GPTIMER_ON', 1),
    'FLD_CTRL_ERR_CONCEAL_ON': ('NVC9B0_SET_CONTROL_PARAMS', 'ERR_CONCEAL_ON', 1),
    'FLD_CTRL_MBTIMER_ON': ('NVC9B0_SET_CONTROL_PARAMS', 'MBTIMER_ON', 1),
    'FLD_CTRL_EVENT_TRACE_LOGGING_ON': ('NVC9B0_SET_CONTROL_PARAMS', 'EVENT_TRACE_LOGGING_ON', 1),
}
VAL = {
    'V_SEM_PAYLOAD_SIZE_64BIT': 'NVC56F_SEM_EXECUTE_PAYLOAD_SIZE_64BIT',
    'V_SEM_PAYLOAD_SIZE_32BIT': 'NVC56F_SEM_EXECUTE_PAYLOAD_SIZE_32BIT',
    'V_SEM_OPERATION_ACQ_CIRC_GEQ': 'NVC56F_SEM_EXECUTE_OPERATION_ACQ_CIRC_GEQ',
    'V_SEM_OPERATION_RELEASE': 'NVC56F_SEM_EXECUTE_OPERATION_RELEASE',
    'V_SEM_RELEASE_WFI_EN': 'NVC56F_SEM_EXECUTE_RELEASE_WFI_EN',
    'V_SEM_RELEASE_WFI_DIS': 'NVC56F_SEM_EXECUTE_RELEASE_WFI_DIS',
    'V_SEM_RELEASE_TIMESTAMP_EN': 'NVC56F_SEM_EXECUTE_RELEASE_TIMESTAMP_EN',
    'V_SEM_RELEASE_TIMESTAMP_DIS': 'NVC56F_SEM_EXECUTE_RELEASE_TIMESTAMP_DIS',
    'V_TRUE': 'NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI_INSTRUCTION_TRUE',
    'V_DMA_NON_PIPELINED': 'NVC6B5_LAUNCH_DMA_DATA_TRANSFER_TYPE_NON_PIPELINED',
    'V_DMA_PITCH': 'NVC6B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT_PITCH',
    'V_DMA_RELEASE_ONE_WORD': 'NVC6B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_ONE_WORD_SEMAPHORE',
    'V_DMA_RELEASE_FOUR_WORD': 'NVC6B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_FOUR_WORD_SEMAPHORE',
    'V_CTRL_HEVC': 'NVC9B0_SET_CONTROL_PARAMS_CODEC_TYPE_HEVC',
    'V_CTRL_PROD_RUN': 'NVC9B0_SET_CONTROL_PARAMS_TESTRUN_ENV_PROD_RUN',
    'PCAS_ACTION_PREFETCH_SCHEDULE': 'NVC6C0_SEND_SIGNALING_PCAS2_B_PCAS_ACTION_PREFETCH_SCHEDULE',
    'APP_ID_HEVC': 'NVC9B0_SET_APPLICATION_ID_ID_HEVC',
    'CWD_MEMBAR_TYPE_L1_SYSMEMBAR': 'NVC6C0_QMDV03_00_CWD_MEMBAR_TYPE_L1_SYSMEMBAR',
    'QMD_TYPE_GRID_CTA': 'NVCEC0_QMDV05_00_QMD_TYPE_GRID_CTA',
}

bad, ok, unknown = [], 0, []
for name, val in sorted(got.items()):
    want = None
    if name in MAP: want = getattr(G, MAP[name], None)
    elif name in VAL: want = getattr(G, VAL[name], None)
    elif name in FLD:
        reg, k, ix = FLD[name]; want = getattr(G, f'{reg}_{k}')[ix]
    if want is None: unknown.append(name); continue
    if int(val) == int(want): ok += 1
    else: bad.append((name, int(val), int(want)))

print(f"agree: {ok}")
print(f"DISAGREE: {len(bad)}")
for n, g, w in bad: print(f"  {n:40} bend={g:<12} nv_570={w}")
print(f"\nnot audited (the port's own tags: CALL_*, CLS_*, QMD_VER*, *_SZ*, QMD_TYPE, "
      f"ESC_*/UVMTYPE_* ordinals, sizes, VAS_*, *_THREADS, QUERY_N): {len(unknown)}")
print("  " + ", ".join(unknown))
