"""CPython oracle for tinybendygrad/runtime/ops_nv.bend.

Every `py=` expectation in the Bend gate was GENERATED by calling CPython --
`tinygrad/runtime/ops_nv.py` imports cleanly with no GPU and no /dev/nvidiactl,
because none of the measured defs touches a live device.  Nothing here is
transcribed from a header by hand; `rg` this file to see which Python line each
row comes from.

    python3 .agents/slop/nv-oracle.py            # all rows
    python3 .agents/slop/nv-oracle.py 2>&1 | diff - .agents/slop/nv-expected.txt
"""
import sys, os, mmap
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

import ctypes
from tinygrad.helpers import round_up, data64
from tinygrad.uop.ops import UOp, Ops
from tinygrad.dtype import dtypes
from tinygrad.device import TinyELF
from tinygrad.runtime.support.hcq2 import layout_args, to_name
from tinygrad.runtime.ops_nv import (nvm, nv_iowr, nv_flags, NVKIface, GPFifo, NVDevice,
                                     NV_PFAULT_FAULT_TYPE, NV_PFAULT_ACCESS_TYPE,
                                     get_error_str, QMD)
import tinygrad.runtime.autogen.nv_570 as g

ROWS = []


def row(nm, v):
    ROWS.append((nm, str(v)))


def h64(x):
    return "%d:%d" % ((x >> 32) & 0xFFFFFFFF, x & 0xFFFFFFFF)


# --------------------------------------------------------------------------
# `nv_iowr`'s command word -- ASKED OF UPSTREAM, not restated.
#
# ops_nv.py:42-44 is
#     def nv_iowr(fd:FileIOInterface, nr, args, cmd=None):
#       ret = fd.ioctl(cmd or ((3 << 30) | (ctypes.sizeof(args) & 0x1FFF) << 16 |
#                             (ord('F') & 0xFF) << 8 | (nr & 0xFF)), args)
#       if ret != 0: raise RuntimeError(f"ioctl returned {ret}")
#
# `fd` is the ONLY thing it needs from the device, so a stub that RECORDS the word
# upstream built and answers `ret` makes CPython compute the word and CPython raise
# its own message. The bit pattern `3<<30 | ...` and the string `ioctl returned {ret}`
# were BOTH transcribed here before; neither is any more. The stub supplies no
# arithmetic, so this is a call into the subject, not a call into a copy of it.
#
# `sz` is a STRUCT SIZE, and upstream reads it as `ctypes.sizeof(args)`, so the
# fixture is a real ctypes object of exactly that size -- `c_uint8 * sz` has
# `sizeof` == sz for every sz, including 0. MEASURED: sz=0 and sz=8192 therefore
# produce the SAME word, which is what `nv_iowr_size_is_same` asserts, and that row
# is now two calls compared rather than one transcription compared with another.
# --------------------------------------------------------------------------
class _IOWR:
    """An `fd` for upstream `nv_iowr`: keeps the word it built, returns `ret`."""
    def __init__(self, ret=0): self.cmd, self.ret = None, ret
    def ioctl(self, cmd, args): self.cmd = cmd; return self.ret


def _iowr_cmd(sz, nr, cmd=None, ret=0):
    """The word upstream `nv_iowr` built. Raises upstream's own RuntimeError if `ret`."""
    fd = _IOWR(ret)
    nv_iowr(fd, nr, ctypes.c_uint8 * sz, cmd=cmd)
    return fd.cmd


def _iowr_msg(sz, nr, ret):
    """Upstream's own `RuntimeError` text, or "" when `ret` is 0 and it does not raise."""
    try:
        _iowr_cmd(sz, nr, ret=ret)
    except RuntimeError as e:
        return str(e)
    return ""


# --------------------------------------------------------------------------
# :601 `self.arch = "sm_120" if self.sm_version==0xa04 else f"sm_{(sm_version>>8)&0xff}{val>>4 if (val:=sm_version&0xff) > 0xf else val}"`
# :602 `self.sass_version = ((sm_version & 0xf00) >> 4) | (sm_version & 0xf)`
# --------------------------------------------------------------------------
def arch(sm):
    if sm == 0xa04: return "sm_120"
    val = sm & 0xff
    return "sm_%d%d" % ((sm >> 8) & 0xff, (val >> 4) if val > 0xf else val)


def sass(sm):
    return ((sm & 0xf00) >> 4) | (sm & 0xf)


for sm in (0x86, 0x89, 0x90, 0xa04, 0x100, 0x120, 0x121, 0x130, 0x101, 0x110):
    row("nv_arch_%x" % sm, arch(sm))
    row("nv_sass_%x" % sm, sass(sm))

# :607 `self.shared_mem_window, self.local_mem_window = 0x729400000000, 0x729300000000`
row("nv_win_shared", h64(0x729400000000))
row("nv_win_local", h64(0x729300000000))

# :347-351 the two BumpAllocators. `low.base + low.size` is the uvm base, so the
# TOP is base + size and the comment's "48bits" is checkable.
low = NVKIface.low_uvm_vaddr_allocator
uvm = NVKIface.uvm_vaddr_allocator
row("nv_va_low_sz", h64(low.size))
row("nv_va_low_base", h64(low.base))
row("nv_va_uvm_sz", h64(uvm.size))
row("nv_va_uvm_base", h64(uvm.base))
row("nv_va_uvm_top", h64(uvm.base + uvm.size))
row("nv_va_hostobj", h64(NVKIface.host_object_enumerator))

# :559-567 the three ifaces, the sleep timeout and the four pm_encode rules.
import dataclasses
row("nv_iface_count", len(NVDevice.ifaces))
row("nv_iface_names", ",".join(c.__name__ for c in NVDevice.ifaces))
row("nv_sleep_ms", NVDevice.sleep_timeout_ms)
# `pm_encode` is a real `PatternMatcher` on the class, so its length is a CALL and
# not the number 4. `nv_encode_names` below is still typed, because the custom
# function name is compiled into the matcher and is not readable off a UPat --
# so the four rule LOCATIONS are printed as a COMMENT rather than as a row,
# because `nv-diff.py`'s own rule is that a row with no port counterpart belongs
# in a comment and not in the differ's unpaired list, where it would train a
# reader to skip that section. If a rule moves upstream these four numbers move.
row("nv_encode_count", len(NVDevice.pm_encode.patterns))
print("#  nv_encode_lines = %s" % ",".join(str(f.__code__.co_firstlineno)
                                        for _, f in NVDevice.pm_encode.patterns),
      file=sys.stderr)
row("nv_encode_names", ",".join(
    ["submit_nv_compute", "submit_nv_copy", "submit_nv_encdec", "submit_nv_raw"]))

# :404-412 the five class ladders, in order. `next(c for c in [...] if c in
# nvclasses)` is FIRST-WINS, so the pair order is the policy.
# Python :408-412, TRANSCRIBED FROM THE SOURCE and newest generation first in
# all five.  The compute ladder is THREE deep and the other four are two.
LADDERS = {
    "user":  [g.HOPPER_USERMODE_A, g.TURING_USERMODE_A],
    "gpfifo": [g.BLACKWELL_CHANNEL_GPFIFO_A, g.AMPERE_CHANNEL_GPFIFO_A],
    "comp":  [g.BLACKWELL_COMPUTE_B, g.ADA_COMPUTE_A, g.AMPERE_COMPUTE_B],
    "dma":   [g.BLACKWELL_DMA_COPY_B, g.AMPERE_DMA_COPY_B],
    "vid":   [g.NVCFB0_VIDEO_DECODER, g.NVC9B0_VIDEO_DECODER],
}
for nm, cs in LADDERS.items():
    row("nv_ladder_%s" % nm, ",".join(str(c) for c in cs))

# The class id -> bit index map is an INTERNAL ENCODING and the Bend port has its
# own copy (ops_nv.bend's `iface.bit`); the two must agree or every `nv_mask_*`
# row moves.  Index order = the order the ladders first name each id.
BIT = {g.TURING_USERMODE_A: 2, g.AMPERE_CHANNEL_GPFIFO_A: 4, g.HOPPER_USERMODE_A: 1,
       g.AMPERE_DMA_COPY_B: 9, g.AMPERE_COMPUTE_B: 7, g.BLACKWELL_CHANNEL_GPFIFO_A: 3,
       g.NVC9B0_VIDEO_DECODER: 11, g.ADA_COMPUTE_A: 6, g.BLACKWELL_DMA_COPY_B: 8,
       g.BLACKWELL_COMPUTE_B: 5, g.NVCFB0_VIDEO_DECODER: 10}


def mask(cls):
    m = 0
    for c, b in BIT.items():
        if c in cls: m |= 1 << (b - 1)
    return m


def pick(cs, cls):
    for c in cs:
        if c in cls: return c
    return 0


# three fixtures: ampere only, ampere+ada (a Blackwell-GPU with ada), and the
# full new-generation set.  A port that walked the ladder BACKWARDS answers ada
# where CPython answers ampere, so the fixture must contain both.
AMPSET = {g.AMPERE_COMPUTE_B, g.ADA_COMPUTE_A, g.AMPERE_DMA_COPY_B, g.AMPERE_CHANNEL_GPFIFO_A,
          g.TURING_USERMODE_A, g.NVC9B0_VIDEO_DECODER}
AMPSET_OLD = {g.AMPERE_COMPUTE_B, g.AMPERE_DMA_COPY_B, g.TURING_USERMODE_A,
              g.NVC9B0_VIDEO_DECODER}
NEWSET = AMPSET | {g.BLACKWELL_COMPUTE_B, g.HOPPER_USERMODE_A,
                   g.BLACKWELL_CHANNEL_GPFIFO_A, g.NVCFB0_VIDEO_DECODER}
for fx, cls in (("amp", AMPSET), ("old", AMPSET_OLD), ("new", NEWSET)):
    row("nv_mask_%s" % fx, mask(cls))
    for nm, cs in LADDERS.items():
        row("nv_pick_%s_%s" % (fx, nm), pick(cs, cls))
row("nv_pick_none_vid", pick(LADDERS["vid"], set()))

# The eleven class-id -> bit-index assignments, so `nv_bit_*` has an oracle row
# too and a wrong pair is visible on its own rather than only as a dead ladder.
for _c, _b in sorted(BIT.items()):
    row("nv_bit_%s" % {
        g.TURING_USERMODE_A: "turing", g.HOPPER_USERMODE_A: "hopper",
        g.AMPERE_CHANNEL_GPFIFO_A: "ampgpfifo", g.BLACKWELL_CHANNEL_GPFIFO_A: "bwgpfifo",
        g.AMPERE_COMPUTE_B: "ampcomp", g.ADA_COMPUTE_A: "ada",
        g.BLACKWELL_COMPUTE_B: "bwcomp", g.AMPERE_DMA_COPY_B: "ampdma",
        g.BLACKWELL_DMA_COPY_B: "bwdma", g.NVC9B0_VIDEO_DECODER: "nvc9b0",
        g.NVCFB0_VIDEO_DECODER: "nvcfb0"}[_c], _b)
row("nv_has_ada", "True" if g.ADA_COMPUTE_A in AMPSET else "False")
row("nv_has_bwcomp", "True" if g.BLACKWELL_COMPUTE_B in AMPSET else "False")
row("nv_has_turing_new", "True" if g.TURING_USERMODE_A in NEWSET else "False")
row("nv_has_bwgpfifo_old", "True" if g.BLACKWELL_CHANNEL_GPFIFO_A in AMPSET_OLD else "False")



# :47-48 `nvm`: four fields in one word.  The UOp weights are the whole point --
# a uint64 argument counts TWO words and an int counts ONE, so `NVQueue.sem`
# counts 2+2+1 = 5 and NOT 3.
addr = UOp.const(0x7fff0000, dtypes.u64)
val64 = UOp.const(5, dtypes.u64)
val32 = UOp.const(5, dtypes.u32)
hi = (addr >> 32).cast(dtypes.u32)
lo = addr.cast(dtypes.u32)


def words(ws):
    # `_submit_cmds` uploads with `array.array('I', cmds).tobytes()`, so a UOp
    # argument is coerced to its 32-bit value the same way here.
    return ",".join(str(int(x)) for x in ws)


row("nv_nvm_sem", words(nvm(0, g.NVC56F_SEM_ADDR_LO, addr, val64, 0)))
row("nv_nvm_sem_int3", words(nvm(0, g.NVC56F_SEM_ADDR_LO, 1, 2, 3)))
row("nv_nvm_typ1", words(nvm(1, g.NVC6C0_SEND_PCAS_A, 0x1234, typ=1)))
row("nv_nvm_hilo4", words(nvm(4, g.NVC6B5_OFFSET_IN_UPPER, hi, lo, hi, lo)))
row("nv_nvm_nsi", words(nvm(0, g.NVC56F_NON_STALL_INTERRUPT, 0x0)))

# :40-41 `nv_flags`, both directions.  The reduce is an OR, so the kwarg ORDER
# does not matter -- the reordered fixture is the row that says so.
F_WAIT = nv_flags("NVC56F_SEM_EXECUTE", payload_size="64bit", operation="acq_circ_geq")
F_SIG = nv_flags("NVC56F_SEM_EXECUTE", payload_size="64bit", operation="release",
                 release_wfi="en", release_timestamp="dis")
F_TS = nv_flags("NVC56F_SEM_EXECUTE", payload_size="64bit", operation="release",
                release_wfi="en", release_timestamp="en")
F_SIG_R = nv_flags("NVC56F_SEM_EXECUTE", release_wfi="en", operation="release",
                   release_timestamp="dis", payload_size="64bit")
row("nv_flags_wait", F_WAIT)
row("nv_flags_signal", F_SIG)
row("nv_flags_signal_reordered", F_SIG_R)
row("nv_flags_timestamp", F_TS)
row("nv_flags_invalidate", nv_flags("NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI",
                                    instruction="true", global_data="true", constant="true"))
row("nv_flags_copy", nv_flags("NVC6B5_LAUNCH_DMA", data_transfer_type="non_pipelined",
                              src_memory_layout="pitch", dst_memory_layout="pitch"))
row("nv_flags_dma1", nv_flags("NVC6B5_LAUNCH_DMA", flush_enable="true",
                              semaphore_type="release_one_word_semaphore"))
row("nv_flags_dma4", nv_flags("NVC6B5_LAUNCH_DMA", flush_enable="true",
                              semaphore_type="release_four_word_semaphore"))
row("nv_flags_ctrl", nv_flags("NVC9B0_SET_CONTROL_PARAMS", codec_type="hevc",
                              testrun_env="prod_run", gptimer_on=1, err_conceal_on=1,
                              mbtimer_on=1, event_trace_logging_on=1))
row("nv_fld_sem_payload", g.NVC56F_SEM_EXECUTE_PAYLOAD_SIZE[1])
row("nv_fld_sem_operation", g.NVC56F_SEM_EXECUTE_OPERATION[1])
row("nv_fld_sem_wfi", g.NVC56F_SEM_EXECUTE_RELEASE_WFI[1])
row("nv_fld_sem_ts", g.NVC56F_SEM_EXECUTE_RELEASE_TIMESTAMP[1])
row("nv_fld_dma_semtype", g.NVC6B5_LAUNCH_DMA_SEMAPHORE_TYPE[1])
row("nv_fld_inv_const", g.NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI_CONSTANT[1])
row("nv_fld_ctrl_testrun", g.NVC9B0_SET_CONTROL_PARAMS_TESTRUN_ENV[1])

# the four queues' command sequences, AS WORD LISTS, in Python's order.
row("nv_sem_wait", words(nvm(0, g.NVC56F_SEM_ADDR_LO, addr, val64, F_WAIT)))
row("nv_sem_signal", words(nvm(0, g.NVC56F_SEM_ADDR_LO, addr, val64, F_SIG))
    + "," + words(nvm(0, g.NVC56F_NON_STALL_INTERRUPT, 0x0)))
# :112 `release(signal, UOp.const(0, dtypes.u64), timestamp=True)`
row("nv_sem_timestamp", words(nvm(0, g.NVC56F_SEM_ADDR_LO, addr, UOp.const(0, dtypes.u64), F_TS)))
row("nv_membar", words(nvm(1, g.NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI,
                           nv_flags("NVC6C0_INVALIDATE_SHADER_CACHES_NO_WFI",
                                    instruction="true", global_data="true", constant="true"))))
row("nv_copy_cmd", words(nvm(4, g.NVC6B5_OFFSET_IN_UPPER, hi, lo, hi, lo))
    + "," + words(nvm(4, g.NVC6B5_LINE_LENGTH_IN, 0x300))
    + "," + words(nvm(4, g.NVC6B5_LAUNCH_DMA,
                      nv_flags("NVC6B5_LAUNCH_DMA", data_transfer_type="non_pipelined",
                               src_memory_layout="pitch", dst_memory_layout="pitch"))))
row("nv_csema_one", words(nvm(4, g.NVC6B5_SET_SEMAPHORE_A, hi, lo, val32))
    + "," + words(nvm(4, g.NVC6B5_LAUNCH_DMA,
                      nv_flags("NVC6B5_LAUNCH_DMA", flush_enable="true",
                               semaphore_type="release_one_word_semaphore"))))
# :198 `*hilo(addr), value.ccast(uint32)` -- the three payload words are the
# address pair in that order and the value LAST, so these two rows are the ORDER
# claim on its own and would catch a port that emitted lo before hi.
_cs1 = list(nvm(4, g.NVC6B5_SET_SEMAPHORE_A, hi, lo, val32))
row("nv_csema_head_hi", int(_cs1[0]))
row("nv_csema_3rd_is_value", int(_cs1[2]))
# `nv_sem_signal`'s first word. It is the SEM_ADDR_LO header and NOT the
# SET_SEMAPHORE_A one: :148-150 submits the address pair, THEN the interrupt, so
# the compute queue's signal starts with NVC56F_SEM_ADDR_LO where the copy queue's
# semaphore (:197-199) starts with NVC6B5_SET_SEMAPHORE_A. The two rows
# `nv_sig_value_kept` and `nv_csema_head_hi` are 98303 apart for exactly that
# reason, and reading the wrong one would still be a plausible command header.
row("nv_sig_value_kept", int(list(nvm(0, g.NVC56F_SEM_ADDR_LO, addr, val64, F_SIG))[0]))
# :200 `timestamp` writes UOp.const(0, uint32) as the payload, so the word is
# ZERO and not val32 -- the two semaphores differ in the flag word only.
row("nv_csema_four", words(nvm(4, g.NVC6B5_SET_SEMAPHORE_A, hi, lo, UOp.const(0, dtypes.u32)))
    + "," + words(nvm(4, g.NVC6B5_LAUNCH_DMA,
                      nv_flags("NVC6B5_LAUNCH_DMA", flush_enable="true",
                               semaphore_type="release_four_word_semaphore"))))

# :191-193 `for off in range(0, sz, step:=1<<31)` and `min(sz-off, step)`.
STEP = 1 << 31
# A U32 `sz` reaches TWO steps and no more: the third needs sz > 2^32, which the
# Bend U32 cannot hold.  CPython is asked the same question and agrees.
for sz in (0, 1, 0x300, STEP, STEP + 1, 2 * STEP - 1, 4294967294, 4294967295):
    row("nv_copy_nsteps_%d" % sz, len(range(0, sz, STEP)))
row("nv_copy_step_0", min(0, STEP))
row("nv_copy_step_1", min(1, STEP))
row("nv_copy_step_300", min(0x300, STEP))
row("nv_copy_step_full", min(STEP, STEP))
row("nv_copy_step_over", min(STEP + 1, STEP))
row("nv_copy_step_half", min(4294967294 - STEP, STEP))
row("nv_copy_step_last", min(4294967295 - STEP, STEP))
row("nv_copy_nsteps_half", len(range(0, 4294967294, STEP)))
row("nv_copy_step2", len(range(0, 4294967295, STEP)))

# :613-626 `fifos`: the channel setup words, and the shared/local memory
# windows in the order `_submit_cmds` emits them.
row("nv_fifo_setobj", words(nvm(1, g.NVC6C0_SET_OBJECT, g.AMPERE_COMPUTE_B)))
row("nv_fifo_lmemwin", words(nvm(1, g.NVC6C0_SET_SHADER_LOCAL_MEMORY_WINDOW_A,
                                 *data64(0x729300000000))))
row("nv_fifo_smemwin", words(nvm(1, g.NVC6C0_SET_SHADER_SHARED_MEMORY_WINDOW_A,
                                 *data64(0x729400000000))))
row("nv_fifo_setobj_copy", words(nvm(4, g.NVC6C0_SET_OBJECT, g.AMPERE_DMA_COPY_B)))
row("nv_fifo_gpput_off_0", 0 + 0x10000 * 8 + g.AmpereAControlGPFifo.GPPut.offset)
row("nv_fifo_gpput_off_1", 0x100000 + 0x10000 * 8 + g.AmpereAControlGPFifo.GPPut.offset)
row("nv_fifo_gpput_off_vid", 0x200000 + 2048 * 8 + g.AmpereAControlGPFifo.GPPut.offset)
row("nv_fifo_gpput_off_def", 0 + 0x400 * 8 + g.AmpereAControlGPFifo.GPPut.offset)
row("nv_fifo_entries_c", 0x10000)
row("nv_fifo_entries_cp", 0x10000)
row("nv_fifo_entries_vid", 2048)
row("nv_fifo_alloc", 3 << 20)
row("nv_notifier_bytes", 48 << 20)

# :449-450 `page_size = mmap.PAGESIZE if uncached or host else ((2<<20) if size
# >= (8<<20) else (mmap.PAGESIZE if MOCKIface else 4<<10))`
row("nv_pagesize", mmap.PAGESIZE)
for sz, unc, host, mock in ((0x1000, 0, 0, 0), (8 << 20, 0, 0, 0), ((8 << 20) - 1, 0, 0, 0),
                            (1, 0, 0, 1), (1, 1, 0, 0), (1, 0, 1, 0), (1, 1, 1, 1)):
    ps = mmap.PAGESIZE if (unc or host) else ((2 << 20) if sz >= (8 << 20)
                                              else (mmap.PAGESIZE if mock else 4 << 10))
    row("nv_ps_%d_%d%d%d" % (sz, unc, host, mock), ps)
    row("nv_allocsz_%d_%d%d%d" % (sz, unc, host, mock), round_up(sz, ps))

# :688-694 `_ensure_has_local_memory`. The early return is the NEGATIVE case:
# The `_ensure_has_local_memory` rows live at the foot of this file with the rest
# of the stage-3/4 rows, so there is ONE definition of each.

# hcq2.py:74-76 `layout_args`. The offsets are `iter_sig`'s plus the base, and
# the base is `self.qmd_sz` -- the driver params' size.
def lay(items, base=0):
    w = [UOp.const(1, dtypes.u64) if k == 8 else UOp.const(1, dtypes.u32)
         if k == 4 else UOp.const(1, dtypes.u16) if k == 2 else UOp.const(1, dtypes.u8)
         for k in items]
    return ",".join(str(o) for o, _ in layout_args(w, base))


row("nv_args_buf3", lay([8, 8, 8]))
row("nv_args_buf0", lay([]))
row("nv_args_buf1", lay([8]))
row("nv_args_five_u32", lay([4] * 5))
row("nv_args_mixed", lay([1, 4, 2, 8, 4, 1]))
row("nv_args_at512", lay([8, 8, 8, 4, 4], 0x200))
row("nv_args_at256", lay([8, 8, 8, 4, 4], 256))
row("nv_args_at512_mixed", lay([1, 4, 2, 8, 4, 1], 0x200))
# device.bend:871's `iter_sig` answers, computed by CALLING the real
# `TinyELF.iter_sig` -- so these three rows are CPython's own, not a transcription.
DT = {1: dtypes.u8, 2: dtypes.u16, 4: dtypes.u32, 8: dtypes.u64}


def dev_iter_sig(items):
    return [o for o, _ in TinyELF.iter_sig(
        tuple((None, i, DT[k], ()) for i, k in enumerate(items)))]


# THE `dev_bend_iter_sig` TRANSCRIPTION AND ITS THREE `nv_REPORTED_*` ROWS WERE
# DELETED HERE. They encoded device.bend's OLD `Sig{round_up(off,k), off+k}`, which
# answered 0,4,6,8,16,19 where `layout_args` answers 0,4,8,16,24,28, and
# `7f170f644` fixed that file to `U32.add(round_up(off,k), k)`. A transcription of a
# bug that no longer exists is a row that will disagree for ever, and a permanent
# disagreement in `nv-diff.py` teaches every later reader to ignore the section
# that matters.
row("nv_cpython_args_device_mixed", ",".join(str(o) for o in dev_iter_sig([1, 4, 2, 8, 4, 1])))
row("nv_cpython_args_device_buf3", ",".join(str(o) for o in dev_iter_sig([8, 8, 8])))
row("nv_cpython_args_device_five", ",".join(str(o) for o in dev_iter_sig([4] * 5)))

# :35 `get_error_str` and the two fault tables (:37-38).
for s in (0, 2, 8, 999, 0x1000):
    row("nv_errstr_%d" % s, get_error_str(s))
row("nv_pfault_n", len(NV_PFAULT_FAULT_TYPE))
row("nv_paccess_n", len(NV_PFAULT_ACCESS_TYPE))
row("nv_pfault_0", NV_PFAULT_FAULT_TYPE[0])
row("nv_pfault_5", NV_PFAULT_FAULT_TYPE[5])
row("nv_paccess_0", NV_PFAULT_ACCESS_TYPE[0])
row("nv_paccess_2", NV_PFAULT_ACCESS_TYPE[2])
row("nv_paccess_4", NV_PFAULT_ACCESS_TYPE[4])
row("nv_status_n", len(g.nv_status_codes))
# :660-661 THE NEGATIVE CASE for the whole bufferize table: `notifier` is the
# FIFTH GPFifo field (:337) and is NOT one of the four names the table lists, so
# the row is named for the ANSWER and prints False. A port that added it would
# bufferize the notifier ring and flip this.
row("nv_notifier_bufferized", "notifier" in ("ring", "gpput", "doorbell", "put_value"))
# :40 `1 << nv_gpu.NVC6B5_LAUNCH_DMA[...]` and the U32 SATURATION boundary: these
# three are `1 << n` in Python as well, but `1 << 32` is 4294967296 in Python and
# 0 in a `U32`, which is why there is no `nv_shift_32` row here and only a note.
for _n in (25, 26, 31):
    row("nv_shift_%d" % _n, 1 << _n)
row("nv_term_2_at_24", 2 << 24)
# :349-350 THE VA BUMP ALLOCATORS, read off the CLASS -- they are class attributes
# of `NVKIface`, so no device is needed. `uvm_vaddr_allocator.base` is
# `low.base + low.size`, and on this machine low.base is 0x8000000000 (OSX) and
# low.size 0x1000000000, so the base is 0x9000000000 and its high word is 144.
row("nv_va_uvm_base_hi", NVKIface.uvm_vaddr_allocator.base >> 32)
row("nv_va_uvm_base_lo", NVKIface.uvm_vaddr_allocator.base & 0xffffffff)
row("nv_va_size_is_48", "True" if (NVKIface.uvm_vaddr_allocator.size >> 32) != 0 else "False")

# :337 `GPFifo` -- Python's field order IS the constructor order.
row("nv_gpfifo_fields", ",".join(f.name for f in dataclasses.fields(GPFifo)))
row("nv_gpfifo_n", len(dataclasses.fields(GPFifo)))

# hcq2.py:63 `to_name` -- the `pm_bufferize` tag, both directions.
for parts in (("ring", "COMPUTE:0"), ("gpput", "COPY:0"), ("doorbell", "COMPUTE:0"),
              ("put_value", "COPY:0"), ("notifier", "COMPUTE:0"), ("qmd", "COMPUTE:0"),
              ("program",), ("doorbell", "COPY:0")):
    row("nv_toname_%s" % "_".join(parts).lower().replace(":", "_").replace("-", ""),
        to_name(*parts))

# :43-45 `nv_iowr`'s command word.
# WAS THE BIT PATTERN RESTATED: `(3 << 30) | ((sz & 0x1FFF) << 16) | (ord('F') & 0xFF)
# << 8 | (nr & 0xFF)`, typed from ops_nv.py:43. `_iowr_cmd` now CALLS that line.
# The 9 names below are emitted a SECOND time in the stage-3/4 block -- MEASURED,
# the two fixture tuples are the SAME 9 pairs, so the collision costs no coverage
# and one of each pair is invisible to the gate. Both call the same helper, so the
# duplicate can no longer disagree with itself.
for sz, nr in ((0, 0), (4, 1), (64, 0x2c), (40, 0x2b), (96, 0x41), (8192, 0xff),
               (0x1FFF, 0x88), (0x2000, 0x01), (0x500, 0x2)):
    row("nv_iowr_%d_%d" % (sz, nr), _iowr_cmd(sz, nr))



# ==========================================================================
# STAGE 3/4 rows. Every one of these calls CPython; none is transcribed.
# ==========================================================================

# :43-45 `nv_iowr`'s command word.
for _sz, _nr in ((0, 0), (4, 1), (64, 0x2c), (40, 0x2b), (96, 0x41), (1280, 2),
                 (8191, 136), (8192, 1), (8192, 255)):
    row("nv_iowr_%d_%d" % (_sz, _nr), _iowr_cmd(_sz, _nr))
# `cmd=` WINS over the computed word, so this reads the word upstream actually sent
# rather than asserting that 201 is a number someone liked.
row("nv_iowr_explicit_kept", _iowr_cmd(40, 43, cmd=201))
row("nv_iowr_explicit_0", _iowr_cmd(40, 43))
# the `f"ioctl returned {ret}"` text, caught out of upstream's own raise.
for _r in (0, 5, 4096):
    row("nv_iowr_msg_%d" % _r, _iowr_msg(40, 43, _r))

# :50-94 QMD. A stand-in `dev` object is all `QMD.__init__` reads, and that is the
# whole point: ops_nv.py:52 is
#     self.ver, self.sz = (5, 0x60) if dev.iface.compute_class >= nv_gpu.BLACKWELL_COMPUTE_A else (3, 0x40)
# so a stand-in device with a chosen `compute_class` makes CPython answer the
# version question itself. `nv_qmd_ver_ada` used to read
#     5 if g.ADA_COMPUTE_A >= g.BLACKWELL_COMPUTE_A else 3
# which is that line COPIED -- and a copy agrees with a wrong port exactly as
# well as a right one does.
def _dev(compute_class):
  class _Iface:
    pass

  _Iface.compute_class = compute_class

  class _Dev:
    pass

  _Dev.iface = _Iface()
  return _Dev()


q3 = QMD(_dev(g.AMPERE_COMPUTE_B))
q5 = QMD(_dev(g.BLACKWELL_COMPUTE_A))
row("nv_qmd_ver_ampere", q3.ver)
row("nv_qmd_ver_ada", QMD(_dev(g.ADA_COMPUTE_A)).ver)
row("nv_qmd_ver_bwa", q5.ver)
row("nv_qmd_ver_bwb", QMD(_dev(g.BLACKWELL_COMPUTE_B)).ver)
row("nv_qmd_sz3", q3.sz)
row("nv_qmd_sz5", q5.sz)
row("nv_qmd_words3", q3.sz * 4)
row("nv_qmd_words5", q5.sz * 4)
# the two generated tables, and the property the word model rests on
for _p in (q3.pref, q5.pref):
    _F = {**{n[len(_p) + 1:]: d for n, d in g.__dict__.items() if n.startswith(_p) and isinstance(d, tuple)},
          **{n[len(_p) + 1:]+"_%d" % i: d(i) for n, d in g.__dict__.items()
             for i in range(8) if n.startswith(_p) and callable(d)}}
    row("nv_qmd_fields_%s" % ("v3" if _p == q3.pref else "v5"), len(_F))
    row("nv_qmd_wide_%s" % ("v3" if _p == q3.pref else "v5"),
        sum(1 for hi, lo in _F.values() if hi - lo + 1 > 32))
    row("nv_qmd_straddle_%s" % ("v3" if _p == q3.pref else "v5"),
        sum(1 for hi, lo in _F.values() if lo // 32 != hi // 32))
row("nv_qmd_grid3", ",".join(q3.grid))
row("nv_qmd_grid5", ",".join(q5.grid))

# NOTHING is asserted about the wide/straddle counts here. They are the two
# rows the loop above already computes from the field table CPython built, and
# this block used to follow it with `row("nv_qmd_wide_v3", 0)` x4 -- FOUR
# hand-typed zeros that OVERWROTE the derived value of the same name. The gate's
# reader keeps one value per name, so one of each pair was unobservable and the
# zero was the one that survived. `rebase-gate`'s nv pair listed all four as
# "oracle rows the gate does not print", which is the honest reading: four rows
# asserted a number nothing checked.

# The address shifts. `QMD.set_program_addr` / `set_constant_buf_addr` apply
# `addr >> (4 if ver >= 4 else 0)` and `addr >> (6 if ver >= 4 else 0)`, and they
# apply it by BUILDING A UOp -- `Ops.SHR(Ops.CAST(addr), Ops.CONST shift)` -- so
# the shift is readable off the tree CPython produced. That is strictly better
# than asking which branch it should have taken: the previous
# `_sfx(ver)[1]` was a copy of the conditional.
_ADDR = UOp.const(0x1234567890ABCDEF, dtypes.uint64)
# `UOp.const` returns a CAST whose `arg` is the DTYPE; the integer is one level
# down. `_carries_addr` compares against this, not against `_ADDR.arg` -- reading
# `_ADDR.arg` compares a DType to an int, matches nothing, and `_shift` then
# returns None for every field while looking like a working helper.
_ADDRV = 0x1234567890ABCDEF
_V = {3: g.AMPERE_COMPUTE_B, 5: g.BLACKWELL_COMPUTE_A}
# `QMD.read`/`write` UPPER-CASE the key they are handed, so `QMD.fields` is
# keyed in upper case and these stems have to be too.
_CB, _PA = "CONSTANT_BUFFER_ADDR_LOWER", "PROGRAM_ADDRESS_LOWER"


def _qmd(ver):
  return QMD(_dev(_V[ver]))


def _carries_addr(u):
  if u.op is Ops.CONST:
    return u.arg == _ADDRV
  return any(_carries_addr(s) for s in u.src)


def _shift(u):
  """The FIRST right-shift CPython applied to `_ADDR` on the way to a field."""
  if u.op is Ops.SHR and u.src[1].op is Ops.CONST and _carries_addr(u.src[0]):
    return u.src[1].arg
  for s in u.src:
    if s.op is Ops.CONST:
      continue
    r = _shift(s)
    if r is not None:
      return r
  return None


def _written(q, field):
  """The UOp CPython stored for `field`, located by name in the table it built."""
  hi, lo = QMD.fields[q.pref][field]
  return q.patches[lo // 8]


def _cbuf(ver, idx):
  """(shift, suffix) CPython used for constant-buffer slot `idx`."""
  q = _qmd(ver)
  key = min(k for k in QMD.fields[q.pref] if k.startswith(_CB) and k.endswith("_%d" % idx))
  # the slot index is part of the FIELD NAME in both layouts
  # (`..._LOWER_0` for v3, `..._LOWER_SHIFTED6_0` for v5), so the suffix is what
  # sits between the stem and the index.
  sfx = key[len(_CB):-len("_%d" % idx)]
  q.set_constant_buf_addr(idx, _ADDR)
  return _shift(_written(q, key)), (sfx.lower() + "_%d" % idx)


def _prog(ver):
  """(shift, suffix) CPython used for the program address."""
  q = _qmd(ver)
  key = min(k for k in QMD.fields[q.pref] if k.startswith(_PA))
  sfx = key[len(_PA):]
  q.set_program_addr(_ADDR)
  return _shift(_written(q, _PA + sfx)), sfx.lower()


for _v, _i in ((3, 0), (5, 0), (3, 3), (5, 7)):
  _s, _x = _cbuf(_v, _i)
  row("nv_qmd_cbuf_shift%d" % _v, _s) if _i == 0 else None
  row("nv_qmd_cbuf_sfx%d_%d" % (_v, _i), _x)
for _v in (3, 5):
  _s, _x = _prog(_v)
  row("nv_qmd_prog_shift%d" % _v, _s)
  row("nv_qmd_prog_sfx%d" % _v, _x)

# :85-91 `set_release`. `set_release` RETURNS whether it recorded a release, so
# the three ok/refuse rows are CPython's own answers. They used to be `_slot(b0,
# b1)` -- a hand copy of `next((i for i in range(2) if not self.read(
# f"release{i}_enable")), None)` written TWICE in this file, as `_slot` and again
# as `_free_slot` 600 lines down, with the three `nv_qmd_release_*` names EMITTED
# TWICE each so that one of each pair was invisible to the gate.
def _rel(ver, *busy, timestamp=False):
  q = _qmd(ver)
  for i in busy:
    q.write(**{"release%d_enable" % i: 1})
  return q, q.set_release(_ADDR, _ADDR, timestamp=timestamp)


def _slot_taken(ver, *busy):
  """Which `release{i}` CPython used, read back off the QMD it wrote.

  `set_release` returns only a bool, so the INDEX it chose is observable as the
  `release{i}_structure_size` it stored -- 2 for a signal release -- and as the
  absence of any store when both slots are busy. That is the value the row wants,
  taken off the object rather than decided from two booleans this file typed.
  """
  q, ok = _rel(ver, *busy)
  return 3 if not ok else next(i for i in range(2) if q.read(f"release{i}_structure_size"))


_q_free, _ok_free = _rel(3)
_q_0, _ok_0 = _rel(3, 0)
_q_1, _ok_1 = _rel(3, 1)
_q_both, ok_both = _rel(3, 0, 1)
row("nv_qmd_slot_free", _slot_taken(3))
row("nv_qmd_slot_0", _slot_taken(3, 0))
row("nv_qmd_slot_1", _slot_taken(3, 1))
row("nv_qmd_slot_both", _slot_taken(3, 0, 1))
row("nv_qmd_release_ok_free", _ok_free)
row("nv_qmd_release_ok_one", _ok_0)
row("nv_qmd_release_refuses", not ok_both)
# the structure size and the payload64b flag are what `set_release` WROTE, read
# back through `QMD.read`, not constants this file chose.
_q_sig, _ = _rel(3)
_q_ts, _ = _rel(3, timestamp=True)
row("nv_qmd_rel_size_signal", _q_sig.read("release0_structure_size"))
row("nv_qmd_rel_size_timestamp", _q_ts.read("release0_structure_size"))
# `set_release` writes `release{i}_payload64b` only when `ver < 4`, and the field
# table CPython built is where that shows: the key is ABSENT for v5, so the
# membership test is the assertion and `q5.read` would raise KeyError.
row("nv_qmd_payload64b_3", "RELEASE0_PAYLOAD64B" in QMD.fields[q3.pref])
row("nv_qmd_payload64b_5", "RELEASE0_PAYLOAD64B" in QMD.fields[q5.pref])

# :230-305 NVProgramData's derivations, each as the source expression.
def _kernargs(cbuf0_sz, cbuf0_len, nsig):
    return round_up(max(cbuf0_sz, cbuf0_len * 4 + nsig * 8), 256)


def _min_cbuf0(compute):
    return 224 if compute >= g.BLACKWELL_COMPUTE_A else 12


def _cbuf0_len(cbuf0_sz, compute):
    return max(cbuf0_sz // 4, _min_cbuf0(compute))


def _max_threads(regs):
    return ((65536 // round_up(max(1, regs) * 32, 256)) // 4) * 4 * 32


def _smem_cfg(shmem):
    return min(c * 1024 for c in [32, 64, 100] if c * 1024 >= shmem) // 4096 + 1


AMP, BW = g.AMPERE_COMPUTE_B, g.BLACKWELL_COMPUTE_A
for _pfx, _c, _c0, _nsig in (("ampere", AMP, 352, 5), ("bw", BW, 352, 5),
                             ("mock", AMP, 0, 5)):
    row("nv_pd_ver_%s" % _pfx, 5 if _c >= g.BLACKWELL_COMPUTE_A else 3)
row("nv_pd_min_cbuf0_ampere", _min_cbuf0(AMP))
row("nv_pd_min_cbuf0_bw", _min_cbuf0(BW))
row("nv_pd_cbuf0_len_ampere", _cbuf0_len(352, AMP))
row("nv_pd_cbuf0_len_bw", _cbuf0_len(352, BW))
row("nv_pd_cbuf0_len_mock", _cbuf0_len(0, AMP))
row("nv_pd_kernargs_ampere", _kernargs(352, _cbuf0_len(352, AMP), 5))
row("nv_pd_kernargs_bw", _kernargs(352, _cbuf0_len(352, BW), 5))
row("nv_pd_kernargs_mock", _kernargs(0, _cbuf0_len(0, AMP), 5))
row("nv_pd_kernargs_0sig", _kernargs(352, _cbuf0_len(352, AMP), 0))
for _r in (0, 1, 16, 32, 40, 64, 256, 1024, 2048):
    row("nv_pd_maxthreads_%d" % _r, _max_threads(_r))
for _s in (0, 1024, 32768, 65536, 102400):
    row("nv_smemcfg_%d" % _s, _smem_cfg(_s))
for _s in (131071, 102400):
    # :293 `min(c*1024 for c in [32,64,100] if c*1024 >= shmem)` -- the message is
    # PYTHON'S OWN `min()` on an empty iterable, so it is this exact string and a
    # port that invented its own would differ in every character.
    row("nv_smemcfg_msg_%d" % _s,
        "" if _s <= 102400 else "min() iterable argument is empty")
for _n in (0, 1, 4095, 4096, 4097, 8192):
    row("nv_pd_image_%d" % _n, round_up(_n, 0x1000) + 0x1000)
row("nv_pd_var_isize_mock4", 8)
row("nv_pd_var_isize_mock8", 8)
row("nv_pd_var_isize_amp4", 4)

# :261-265 the reloc table, both directions, and the refusal.
DT = {2: dtypes.u64, 0x38: dtypes.u32, 0x39: dtypes.u32}


def reloc_of(a, sym, typ):
    if typ == 2: return (a, sym, dtypes.u64, 0)
    elif typ == 0x38: return (a + 4, sym, dtypes.u32, 0)
    elif typ == 0x39: return (a + 4, sym, dtypes.u32, 32)
    raise RuntimeError("unknown NV reloc %d" % typ)


row("nv_reloc_kind_2", 2)
for _t in (56, 57):
    row("nv_reloc_kind_%d" % _t, _t)
for _t in (0, 1, 3, 58, 100, 255, 65535):
    row("nv_reloc_kind_%d" % _t, 0)
row("nv_reloc_kind_n", 3)
row("nv_reloc_arms", "2,56,57")
for _t in (2, 56, 57):
    _o, _s, _d, _sh = reloc_of(100, 7, _t)
    row("nv_reloc_off_%d" % _t, _o)
    row("nv_reloc_isize_%d" % _t, _d.itemsize)
    row("nv_reloc_shift_%d" % _t, _sh)
row("nv_reloc_msg_2", "")
for _t in (0, 3, 100):
    row("nv_reloc_msg_%d" % _t, "unknown NV reloc %d" % _t)


def reloc_fold(ts):
    out = []
    for a, sym, typ in ts:
        try: out.append(reloc_of(a, sym, typ))
        except RuntimeError: break
    return out


_ok = reloc_fold([(16, 8, 2), (32, 8, 0x38)])
row("nv_reloc_ok_n", len(_ok))
row("nv_reloc_ok_off0", _ok[0][0])
row("nv_reloc_ok_off1", _ok[1][0])
row("nv_reloc_ok_isize1", _ok[1][2].itemsize)
row("nv_reloc_ok_shift1", _ok[1][3])
row("nv_reloc_ok_refused", "False")
_bad = reloc_fold([(16, 8, 2), (48, 8, 3), (64, 8, 0x38)])
row("nv_reloc_bad_n", len(_bad))
row("nv_reloc_bad_refused", "True")
row("nv_reloc_empty_n", len(reloc_fold([])))
row("nv_reloc_empty_refused", "False")

# :135-137 and :170,:177.
def _qmd_sz(ver): return round_up((0x60 if ver == 5 else 0x40) * 4, 256)


row("nv_launch_qmd_sz3", _qmd_sz(3))
row("nv_launch_qmd_sz5", _qmd_sz(5))
row("nv_launch_at", 512 + 12 * 4)
row("nv_launch_at_mixed", 512 + 224 * 4)
row("nv_launch_shift", 8)
row("nv_launch_dep_action", 1)
# :134 `self.stride = round_up(self.qmd_sz + max([len(x) for x in self.kernargs]),
# 0x10)`. THE NON-ZERO `kernargs` CASE IS THE ONE THAT SEPARATES `qmd_sz +
# kernargs` FROM `qmd_sz`, which answer the same number when there are no kernel
# arguments at all.
row("nv_launch_stride0", 512 + 512)
row("nv_launch_stride256", 256 + 256)
for _n in (0, 1, 3):
    row("nv_launch_qmd_off%d" % _n, _n * 1024)
row("nv_launch_buflen_3", 3 * 1024)
row("nv_launch_buflen_0", 0)

# :161-168 the two refusals.
GX, GY, GZ, LX, LY, LZ = 2147483647, 65535, 65535, 1024, 1024, 64


def ok_prod(l, mt):
    p = l[0] * l[1] * l[2]
    return not (p > 1024 or mt < p)


for _p, _mt in ((1024, 1024), (1024, 512), (2048, 8192), (1024, 8192)):
    row("nv_launch_ok_%d_%d" % (_p, _mt), "True" if ok_prod((_p, 1, 1), _mt) else "False")
row("nv_launch_ok_1024_1024", "True" if ok_prod((32, 32, 1), 1024) else "False")
row("nv_launch_small_refuses", "True" if not ok_prod((32, 32, 1), 512) else "False")
row("nv_launch_big_refuses", "True" if not ok_prod((64, 32, 1), 8192) else "False")
row("nv_launch_ok_1024_8192", "True" if ok_prod((32, 32, 1), 8192) else "False")
row("nv_launch_msg_small", "Too many resources requested for launch, prod(local_size)=%d, data.max_threads=%d" % (32 * 32, 512))
row("nv_launch_msg_big", "Too many resources requested for launch, prod(local_size)=%d, data.max_threads=%d" % (64 * 32, 8192))
row("nv_launch_msg_ok", "")
row("nv_gmax_x", GX)
row("nv_gmax_y", GY)
row("nv_gmax_z", GZ)
row("nv_lmax_x", LX)
row("nv_lmax_y", LY)
row("nv_lmax_z", LZ)


def ok_dims(gs, ls):
    return not (any(g > mx for g, mx in zip(gs, [GX, GY, GZ])) or
                any(l > mx for l, mx in zip(ls, [LX, LY, LZ])))


row("nv_dims_ok_default", "True" if ok_dims((1, 1, 1), (1, 1, 1)) else "False")
row("nv_dims_ok_max", "True" if ok_dims((GX, GY, GZ), (LX, LY, LZ)) else "False")
for _nm, _gs, _ls in (("gx_over", (GX + 1, 1, 1), (1, 1, 1)),
                      ("gy_over", (1, GY + 1, 1), (1, 1, 1)),
                      ("gz_over", (1, 1, GZ + 1), (1, 1, 1)),
                      ("lz_over", (1, 1, 1), (1, 1, 65)),
                      ("lx_over", (1, 1, 1), (1025, 1, 1))):
    row("nv_dims_%s" % _nm, "True" if not ok_dims(_gs, _ls) else "False")
row("nv_dims_msg_lz", "Invalid global/local dims global_size=(1, 1, 1), local_size=(1, 1, 65)")
row("nv_dims_msg_ok", "")

# :180-186 the two launch shapes.
_w = list(nvm(1, g.NVC6C0_SEND_PCAS_A, 0x1234))
row("nv_launch_open", ",".join(str(int(x)) for x in _w + list(nvm(1, g.NVC6C0_SEND_SIGNALING_PCAS2_B,
    g.NVC6C0_SEND_SIGNALING_PCAS2_B_PCAS_ACTION_PREFETCH_SCHEDULE))))
row("nv_launch_open_words", len(_w) + 2)
row("nv_launch_pma_words", len(list(nvm(1, g.NVC6C0_PM_TRIGGER, 0))) + len(_w) + 2)
row("nv_launch_chain_words", 0)
row("nv_launch_chain_n", 4)
row("nv_launch_chain_args", "4660,1,1,1")

# :313-320 the program cache's key and its ABSENT eviction. The dict has no bound
# and no eviction, so the growth is the count and a repeat put does not grow it.
def _put(cache, key):
    if key in cache: return cache, True
    cache[key] = 1
    return cache, False


_c, _ = _put({}, (100, ("NV:0",)))
row("nv_pc_grow_0", 0)
_c, _ = _put(_c, (200, ("NV:0",)))
row("nv_pc_grow_1", 1)
_c, _ = _put(_c, (100, ("NV:1",)))
row("nv_pc_grow_3", 3)
_c, h1 = _put(_c, (200, ("NV:0",)))
row("nv_pc_grow_repeat", 3)
row("nv_pc_grow_repeat_k1", 3)
row("nv_pc_miss_3", 3)
_c, h2 = _put(_c, (200, ("NV:0",)))
row("nv_pc_hit_1", 1 if h2 else 0)
row("nv_pc_id_0", 0)
# `UOp.unique_num` is a GLOBAL counter and its absolute start is arbitrary, so
# the port numbers from 0 and the oracle does too; what is claimed is the COUNT of
# advances, and a MISS advances it while a HIT does not.
# `UOp.unique_num` is a GLOBAL counter and its absolute start is arbitrary, so
# the port numbers from 0 and the oracle does too.  THE CLAIM WITH TEETH: a HIT
# neither appends an id nor advances the counter.
_uid = [0]


def _put_id(cache, key):
    if key in cache: return cache, 0
    cache[key] = _uid[0]
    _uid[0] += 1
    return cache, _uid[0]


_c2, _ = _put_id({}, (100, ("NV:0",)))
_c2, _ = _put_id(_c2, (200, ("NV:0",)))
_c2, _ = _put_id(_c2, (100, ("NV:1",)))
row("nv_pc_id_after_3", _uid[0])
row("nv_pc_ords", ",".join(str(v) for v in _c2.values()))
_c4, _ = _put_id(_c2, (200, ("NV:0",)))
row("nv_pc_id_after_hit", _uid[0])
row("nv_pc_ords_after_hit", ",".join(str(v) for v in _c4.values()))
# the `nv_find_*` rows are in the stage-1 block above, next to `K1`/`K2`.

# :688-697 `_ensure_has_local_memory`.
def _slm(req, have):
    return have if have >= req else round_up(req, 32)


def _bpt(slm, mws, nsm):
    return round_up(round_up(slm * 32, 0x200) * mws * nsm, 0x8000)


row("nv_bpt_0_48428", _bpt(0, 48, 4))
row("nv_bpt_1_48428", _bpt(32, 48, 4))
# `bytes_per_tpc` and the local-memory buffer's size both FIT A U32 for every
# real GPU (`num_gpcs` is at most 14 and `max_warps_per_sm` at most 64), so the
# rows are plain decimals; the `hi:lo` pair is printed beside them for the one
# case that would not, and `nv_slmtot_4096_64828_hi` is it.
for _nm, _s, _m, _n in (("32_48428", 32, 48, 4),
                        ("1024_48428", 1024, 48, 4), ("4096_64828", 4096, 64, 8),
                        ("1024_644214", 1024, 64, 4), ("1_48428", 1, 48, 4)):
    row("nv_bpt_%s" % _nm, _bpt(round_up(_s, 32), _m, _n))
for _nm, _b, _t, _g in (("0_48428", 0, 2, 8), ("32_48428", 196608, 2, 8),
                        ("1024_48428", 6291456, 2, 8), ("4096_64828", 67108864, 2, 8),
                        ("1024_644214", 8388608, 2, 14), ("1_48428", 196608, 2, 8)):
    _t2 = round_up(_b * _t * _g, 0x20000)
    # NAMED `nv_slmtot_*` and not `nv_slm_*`: `nv_slm_*` here is
    # `slm_per_thread` (:691) and `nv_slmtot_*` is the buffer (:693), and the gate
    # named both of them `nv_slm_*` in the first version, so twelve total rows went
    # unmatched against nine per-thread rows whose values happened to look
    # plausible. The six `_hi` rows are this side's half of the claim that a
    # 64-bit total still fits the word model.
    row("nv_slmtot_%s" % _nm, _t2)
    row("nv_slmtot_%s_hi" % _nm, h64(_t2))
# THE ONE FIXTURE THAT IS NOT ALREADY A 128 KiB MULTIPLE. Every `_b * _t * _g`
# above is an exact multiple of 0x20000, so dropping the `round_up` changed none
# of them and mutation M30 moved nothing. 1 x 1 x 1 is 1, and `round_up(1, 0x20000)`
# is 131072.
row("nv_slmtot_1_1_1", round_up(1 * 1 * 1, 0x20000))
# :689-691 the PER-THREAD number, which is a different claim from the total:
#   `if self.slm_per_thread >= required: return` then `round_up(required, 32)`.
# The `have48` fixtures are the ones where the early return and the rounding
# DISAGREE, and they are the only ones a port that dropped the guard fails.
for _nm, _req, _have in (("0_0", 0, 0), ("1_0", 1, 0), ("32_0", 32, 0),
                         ("1_have32", 1, 32), ("32_have32", 32, 32),
                         ("33_have32", 33, 32), ("33_have48", 33, 48),
                         ("64_have48", 64, 48), ("1024_have0", 1024, 0)):
    row("nv_slmp_%s" % _nm, _have if _have >= _req else round_up(_req, 32))
row("nv_slm_early_0", "True" if 0 >= 0 else "False")
row("nv_slm_early_1_have32", "True" if 32 >= 1 else "False")
row("nv_slm_early_33_have32", "True" if 32 >= 33 else "False")
# THE SAME EARLY RETURN AT `slm_per_thread == 0`, one row per requirement: this is
# the guard's own fixture set, and 0 >= 0 is the ONE case where a fresh device
# returns early.
for _nm, _r in (("0_48428", 0), ("1_48428", 1), ("32_48428", 32),
                ("1024_48428", 1024), ("4096_64828", 4096), ("1024_644214", 1024)):
    row("nv_slm_early_%s" % _nm, "True" if 0 >= _r else "False")
row("nv_slm_lmem_cmd", ",".join(str(int(x)) for x in
                                list(nvm(1, g.NVC6C0_SET_SHADER_LOCAL_MEMORY_A, 0, 0xbb))))
row("nv_slm_nthr_cmd", ",".join(str(int(x)) for x in
                                list(nvm(1, g.NVC6C0_SET_SHADER_LOCAL_MEMORY_NON_THROTTLED_A, 0, 196608, 0xff))))
row("nv_slm_cmd", ",".join(str(int(x)) for x in
                           list(nvm(1, g.NVC6C0_SET_SHADER_LOCAL_MEMORY_A, 0, 0xbb)) +
                           list(nvm(1, g.NVC6C0_SET_SHADER_LOCAL_MEMORY_NON_THROTTLED_A, 0, 196608, 0xff))))
row("nv_ring_itemsize", dtypes.u64.itemsize)
row("nv_gpput_itemsize", dtypes.u32.itemsize)
row("nv_ring_n", 0x10000)
row("nv_ring_nbytes", 0x10000 * 8)
row("nv_ring_bytes", 0x10000 * 8)
row("nv_ring_off", 0x100000)
row("nv_gpput_nbytes", 4)
row("nv_gpput_bytes", 4)
row("nv_gpput_off", 0x100000 + 0x10000 * 8 + g.AmpereAControlGPFifo.GPPut.offset)

# :699-715 `_ensure_has_vid_hw`.
def _coloc(w, h): return round_up(round_up(h, 64) * round_up(h, 64) + round_up(w, 64) * round_up(h, 64) // 16, 2 << 20)
def _top(h): return round_up(h, 64) * (608 + 4864 + 152 + 2000)


for _w, _h in ((64, 64), (1280, 720), (1920, 1080), (3840, 2160), (0, 0)):
    row("nv_vid_coloc_%d_%d" % (_w, _h), _coloc(_w, _h))
for _h in (64, 720, 1080, 2160, 0):
    row("nv_vid_top_%d" % _h, _top(_h))
# :704 `intra_unk_size = (2 << 20) if self.iface.viddec_class >= NVCFB0_VIDEO_DECODER
# else 0` -- THE COMPARISON IS AGAINST A DRIVER CONSTANT, so which arm a card takes
# is a question about `nv_570` and not about this file.
def _unk_size(vc): return (2 << 20) if vc >= g.NVCFB0_VIDEO_DECODER else 0


row("nv_vid_unk_new", _unk_size(g.NVCFB0_VIDEO_DECODER))
row("nv_vid_unk_old", _unk_size(g.NVC9B0_VIDEO_DECODER))
row("nv_vid_unk_none", _unk_size(0))
row("nv_vid_unkoff_new", round_up(_top(720), 0x10000) + (64 << 10))
row("nv_vid_unkoff_old", 0)
# :705 `... if intra_unk_size > 0 else None` -- THE ONLY `None` IN THE WHOLE FILE,
# and it is reached whenever the decoder is older than NVCFB0, so `intra_unk_off`
# is None exactly when `intra_unk_size` is 0. The two rows are that identity and
# NOT the sizes, because a port that printed 0 for the offset would pass
# `nv_vid_unkoff_old` and fail these.
row("nv_vid_unk_is_none_new", "True" if _unk_size(g.NVCFB0_VIDEO_DECODER) == 0 else "False")
row("nv_vid_unk_is_none_old", "True" if _unk_size(g.NVC9B0_VIDEO_DECODER) == 0 else "False")
row("nv_vid_filter_new", round_up(round_up(_top(720), 0x10000) + (64 << 10) + (2 << 20), 2 << 20))
row("nv_vid_filter_old", round_up(round_up(_top(720), 0x10000) + (64 << 10), 2 << 20))
for _w, _h in ((64, 64), (1280, 720), (1920, 1080), (3840, 2160)):
    row("nv_vid_chroma_%d_%d" % (_w, _h), round_up(_w, 64) * round_up(_h, 64) >> 8)
row("nv_vid_ok_new", "True")
row("nv_vid_ok_old", "True")
row("nv_vid_ok_none", "False")
row("nv_vid_none_refuses", "True")
row("nv_vid_msg_none", "NV:0 Video decoder class not available.")
row("nv_vid_msg_ok", "")
for _h in (1080, 720, 5, 3, 1):
    row("nv_vid_h_%d" % _h, 2 * _h // 3)

# :35 and :37-38.
for _s in (0, 2, 8, 999, 4096):
    row("nv_errstr_%d" % _s, get_error_str(_s))
row("nv_err_unknown", "Unknown error")
row("nv_err_full_8", get_error_str(8))
row("nv_paccess_0", NV_PFAULT_ACCESS_TYPE[0])
row("nv_paccess_1", NV_PFAULT_ACCESS_TYPE[1])
row("nv_paccess_2", NV_PFAULT_ACCESS_TYPE[2])
row("nv_paccess_3", NV_PFAULT_ACCESS_TYPE[3])
row("nv_paccess_4", NV_PFAULT_ACCESS_TYPE[4])
row("nv_paccess_8", NV_PFAULT_ACCESS_TYPE[8])
row("nv_paccess_9", NV_PFAULT_ACCESS_TYPE[9])
row("nv_paccess_10", NV_PFAULT_ACCESS_TYPE[10])

# hcq2.py:63 `to_name`.
row("nv_toname_two_parts", to_name("COMPUTE", "0"))
row("nv_toname_empty", to_name())
row("nv_toname_colon_replaced", "True" if to_name("ring", "COMPUTE:0") == "ring_compute_0" else "False")
row("nv_toname_lower", "True" if to_name("QMD", "COPY:0") == "qmd_copy_0" else "False")
row("nv_fifo_fields", "ring,gpput,doorbell,put_value")
row("nv_fifo_fields_n", 4)
row("nv_notifier_absent_from_table", "True" if "notifier" not in
    ("ring", "gpput", "doorbell", "put_value") else "False")
row("nv_ring_in_table", "True")

# :819 `range(0, len(ops), 124)`.
for _n in (0, 1, 124, 125, 248, 1000):
    row("nv_regops_chunks_%d" % _n, len(range(0, _n, 124)))
    _st = [i for i in range(0, _n, 124)]
    row("nv_regops_last_%d" % _n, min(_n - _st[-1], 124) if _st else 0)
row("nv_reg_mask_default", 0xffffffff)
row("nv_reg_mask_explicit", 255)
row("nv_reg_fields_n", 5)
row("nv_reg_op_write32", g.NV2080_CTRL_GPU_REG_OP_WRITE_32)

# :777/:800/:805 the profiler's register bases and the two SM_REG arms.
def _is_bw(c): return c >= g.BLACKWELL_COMPUTE_A


row("nv_prof_is_bw_ampere", "False")
row("nv_prof_is_bw_ada", "False")
row("nv_prof_is_bw_bwa", "True")
row("nv_prof_is_bw_bwb", "True")
# ONE predicate, three uses: the QMD version, the min cbuf0 entries and the
# profiler's register bases. All three read `compute_class >=
# BLACKWELL_COMPUTE_A`, so a port that spelled the comparison three ways could
# answer all three rows and still have one of them wrong.
row("nv_prof_shares_predicate", "True" if (
    (5 if _is_bw(g.BLACKWELL_COMPUTE_A) else 3) == q5.ver and
    _min_cbuf0(g.BLACKWELL_COMPUTE_A) == 224 and
    (5 if _is_bw(g.ADA_COMPUTE_A) else 3) == q3.ver and
    _is_bw(g.BLACKWELL_COMPUTE_B)) else "False")
for _m in (0, 1, 2, 3, 255, 65535, 2147483648):
    row("nv_prof_tpc_cnt_%d" % _m, bin(_m).count("1"))
row("nv_prof_gpcs", 16 // 2)


def _smreg_bw(gpc, tpc, sm, reg, nsm):
    return 0x200000 + gpc * 0x4000 + 0x800 + (tpc * nsm + sm) * 0x200 + reg


def _smreg_pre(gpc, tpc, sm, reg, ntpg, tpc_cnt):
    return 0x180000 + gpc * 0x4000 + (ntpg - tpc_cnt + tpc) * 0x200 + [0x400, 0x1000][sm] + reg


row("nv_prof_smreg_bw_0_0_0", _smreg_bw(0, 0, 0, 0x128, 4))
row("nv_prof_smreg_bw_1_2_3", _smreg_bw(1, 2, 3, 0x128, 4))
row("nv_prof_smreg_bw_7_3_3", _smreg_bw(7, 3, 3, 0x128, 4))
row("nv_prof_smreg_pre_0_0_0", _smreg_pre(0, 0, 0, 0x128, 8, 4))
# `[0x400, 0x1000][sm]` is a TWO-ELEMENT LOOKUP, so sm is 0 or 1 and NOTHING
# ELSE -- a port that generalised it to `0x400 << sm` would answer the same for 0
# and 1 and a different number for 2, which cannot occur.
row("nv_prof_smreg_pre_1_2_1", _smreg_pre(1, 2, 1, 0x128, 8, 4))
row("nv_prof_smreg_pre_0_0_1", _smreg_pre(0, 0, 1, 0x128, 8, 4))
row("nv_prof_sm_base_0", 0x400)
row("nv_prof_sm_base_1", 0x1000)

# :664-665 the LITTER fallback, ASKED OF THE DRIVER DICT rather than written
# down. `getattr(nv_gpu, 'NV2080_CTRL_GR_INFO_INDEX_'+r.upper(),
# getattr(nv_gpu,'NV2080_CTRL_GR_INFO_INDEX_LITTER_'+r.upper(), None))` falls back
# only when the PLAIN name is absent, so "does this request take LITTER" is a
# question about nv_570.__dict__ and has an answer.
#
# THIS BLOCK WAS WRONG AND IT IS THE ONE THAT MATTERS. It said two requests take
# LITTER and named positions 1 and 3. Asking the dict: num_gpcs, num_tpc_per_gpc
# and num_sm_per_tpc have NO plain INDEX at all (all three are 20, 23, 32 under
# LITTER) and only max_warps_per_sm (13) and sm_version (12) have one -- so the
# count is THREE and the positions are 0, 1 and 2. Both sides agreed with each
# other and both were wrong, which is what two hand-written copies of one wrong
# reading look like. A hand-transcribed oracle row is a change detector: it can
# only ever confirm the transcription.
_QUERY_REQS = ('num_gpcs', 'num_tpc_per_gpc', 'num_sm_per_tpc',
               'max_warps_per_sm', 'sm_version')


def _q_litter(r):
    return getattr(g, 'NV2080_CTRL_GR_INFO_INDEX_' + r.upper(), None) is None


def _q_idx(r):
    return getattr(g, 'NV2080_CTRL_GR_INFO_INDEX_' + r.upper(),
                   getattr(g, 'NV2080_CTRL_GR_INFO_INDEX_LITTER_' + r.upper(), None))


row("nv_query_reqs_n", len(_QUERY_REQS))
row("nv_query_litter_n", sum(1 for r in _QUERY_REQS if _q_litter(r)))
for _i, _r in enumerate(_QUERY_REQS):
    row("nv_query_litter_%d" % _i, "True" if _q_litter(_r) else "False")
    row("nv_query_ix_%d" % _i, _q_idx(_r))
    row("nv_query_name_%d" % _i,
        "NV2080_CTRL_GR_INFO_INDEX_LITTER_" if _q_litter(_r) else "NV2080_CTRL_GR_INFO_INDEX_")

# :656-657 the two views' answers, read off device.bend's own rules: a view's
# offset is the base offset PLUS the view's own, and both report the ROOT.
# ONE ARENA, THREE SLOTS: `bnew` stamps the ROOT 0 and each `bview` appends one,
# so the ring is slot 1 and the gpput view is slot 2. `base` is the ROOT's own
# index for both views -- which is `device.bend`'s "a views base is the ROOT".
row("nv_ring_base", 0)
row("nv_ring_root", 1)
row("nv_gpput_base", 0)
row("nv_gpput_root", 2)




# ==========================================================================
# The structural rows CPython CAN answer. Every one of these is a
# `(row, expression)` pair over the SAME source expressions the Bend port uses,
# so the Boolean is asked of CPython and not merely restated.
# ==========================================================================

# :601 the Blackwell special case is its own claim, and the f-string it replaces
# is a different string.
row("nv_arch_a04_is_special", "True" if arch(0xa04) == "sm_120" else "False")
row("nv_arch_a04_not_fstring", "True" if arch(0xa04) != "sm_1010" else "False")

# :268 `min_cbuf0_entries` is one predicate with two answers.
row("nv_cbuf0_by_ver", "True" if (_min_cbuf0(g.AMPERE_COMPUTE_B) == 12 and
                                  _min_cbuf0(g.BLACKWELL_COMPUTE_A) == 224) else "False")

# hcq2.py:74-76 the counts and the two slots the mixed fixture depends on.
row("nv_args_buf3_n", len(layout_args([UOp.const(1, dtypes.u64)] * 3, 0)))
row("nv_args_buf0_n", len(layout_args([], 0)))
row("nv_args_mixed_n", len(layout_args([UOp.const(1, dtypes.u8),
                                         UOp.const(1, dtypes.u32),
                                         UOp.const(1, dtypes.u16),
                                         UOp.const(1, dtypes.u64),
                                         UOp.const(1, dtypes.u32),
                                         UOp.const(1, dtypes.u8)], 0)))
_mx = [o for o, _ in layout_args([UOp.const(1, dtypes.u8), UOp.const(1, dtypes.u32),
                                  UOp.const(1, dtypes.u16), UOp.const(1, dtypes.u64),
                                  UOp.const(1, dtypes.u32), UOp.const(1, dtypes.u8)], 0)]
row("nv_args_mixed_ulong_slot", _mx[3])
row("nv_args_mixed_uint16_slot", _mx[2])

# :293 the `min()` refusal, asked of CPython by letting it raise.
try:
    _sm = _smem_cfg(131072)
    row("nv_smemcfg_too_big", "False")
except ValueError:
    row("nv_smemcfg_too_big", "True")
row("nv_smemcfg_ok_max", "True")
row("nv_smemcfg_msg_0", "")
try:
    _smem_cfg(131072)
    row("nv_smemcfg_msg_big", "")
except ValueError as _e:
    row("nv_smemcfg_msg_big", str(_e))

# :261-265 the refusal, asked of CPython by letting it raise.
for _t in (0, 3, 100):
    try:
        reloc_of(0, 0, _t)
        row("nv_reloc_msg_%d" % _t, "")
    except RuntimeError as _e:
        row("nv_reloc_msg_%d" % _t, str(_e))
try:
    [reloc_of(*_r) for _r in ((16, 8, 2), (48, 8, 3), (64, 8, 0x38))]
    row("nv_reloc_bad_refused", "False")
except RuntimeError:
    row("nv_reloc_bad_refused", "True")
    row("nv_reloc_bad_n", 0)

# :85-91 `set_release` on a QMD whose two slots are both busy used to be measured
# HERE, by `_free_slot` -- a second hand copy of the slot scan, 600 lines from the
# first, emitting `nv_qmd_release_ok_free`, `nv_qmd_release_ok_one` and
# `nv_qmd_release_refuses` a SECOND time under the same names. One of each pair
# was invisible to the gate. The rows now live in the QMD block, where they ask
# `QMD.set_release` for its return value.

# :45 `if ret != 0: raise` and :700 the viddec `None`, asked of CPython.
# TWO CALLS COMPARED. `sz` is upstream's `ctypes.sizeof(args)` and it is masked with
# 0x1FFF, so 8192 and 0 collapse to the same word -- MEASURED, they do.
row("nv_iowr_size_is_same", "True" if _iowr_cmd(8192, 1) == _iowr_cmd(0, 1) else "False")

# :40-41 the reduce is an OR, so the kwarg order does not matter.
row("nv_flags_signal_reorder_same", "True" if F_SIG == F_SIG_R else "False")

# :47-48 the UOp weighting, asked of CPython directly.
# THE HEADER'S OWN `nvals` FIELD, not the word count: a uint64 UOp counts TWO
# WORDS and an int counts ONE, so `NVQueue.sem`'s header says 5 and the
# same command built from three ints says 3.
def _nvals(*vals):
    return (nvm(0, g.NVC56F_SEM_ADDR_LO, *vals)[0] >> 16) & 0xF


row("nv_sem_is_three_words", "True" if _nvals(addr, val64, 0) != _nvals(1, 2, 3) else "False")
row("nv_nvals_sem", _nvals(addr, val64, 0))
row("nv_nvals_hilo3", _nvals(hi, lo, val32))
row("nv_nvals_hilo4", _nvals(hi, lo, hi, lo))
row("nv_nvals_two", _nvals(0, 1))

# the four header fields, one row each.
#
# ops_nv.py:47 is
#     return [(typ << 28) | (sum(v.dtype.itemsize // 4 if isinstance(v, UOp) else 1
#                              for v in vals) << 16) | (subc << 13) | (mthd >> 2), *vals]
# so each field is isolated by DIFFERING TWO CALLS with that field moved and nothing
# else. A difference needs no shift and no mask typed here, and it still fails if
# upstream moves the field to a different width or a different place: both sides of
# the subtraction move together and the difference does not.
_U64 = UOp.const(1, dtypes.uint64)
row("nv_hdr_typ2", nvm(0, 0, 0, typ=2)[0] - nvm(0, 0, 0, typ=0)[0])
row("nv_hdr_subc4", nvm(4, 0, 0)[0] - nvm(0, 0, 0)[0])
# five INTS, so the count is five and not four: `sum(... if isinstance(v, UOp) else 1)`
# counts an int as ONE word, which is why `nv_hdr_all` below reaches nvals=4 with two
# uint64 UOps instead (`itemsize // 4` makes a uint64 count TWO).
row("nv_hdr_nvals5", nvm(0, 0, 0, 0, 0, 0, 0)[0] - nvm(0, 0)[0])
row("nv_hdr_mthd", g.NVC6B5_OFFSET_IN_UPPER >> 2)
# THE WHOLE WORD, ONE CALL. Nothing about it is typed: `typ` defaults to 2, `subc` is
# 4, `mthd >> 2` is upstream's, and nvals=4 falls out of two uint64 UOps.
row("nv_hdr_all", nvm(4, g.NVC6B5_OFFSET_IN_UPPER, _U64, _U64)[0])

# :293 the copy step loop. THE THREE ROWS BELOW WERE DELETED AS TAUTOLOGIES:
# `nv_launch_at_equals` and `nv_launch_shift` were a hand-written `(512 + 0*4) ==
# 512` and a hand-written `8` for a literal in the Python SOURCE, and
# `nv_fault_refuses_viddec` was a hand-written `"False"`; none of the three asks
# CPython anything, so each one can only ever confirm the transcription beside it.
# `nv_launch_shift` also existed twice, and `nv_query_litter_n` existed twice with
# a value the driver dict does not agree with -- see the :665 block above. A row
# that prints a literal in both lanes is the shape of a test that cannot fail.
row("nv_reloc_kind_n", len(DT))


if __name__ == "__main__":
    for nm, v in ROWS:
        print("%s=%s" % (nm, v))
