#!/usr/bin/env python3
"""
nv_ip_build.py -- assemble tinybendygrad/runtime/support/nv/ip.bend from its
PARTS, so the file is reproducible instead of the result of forty hand patches.

    .agents/slop/nv_ip_head.bend      the header (hand-written, this is the prose)
    .agents/slop/nv_ip_tables.bend    GENERATED by nv_ip_gen.py
    .agents/slop/nv_ip_tail_b.bend    the STAGE B lookups + row printers
    .agents/slop/nv_ip_tail_c.bend    the STAGE C defs (arithmetic)
    .agents/slop/nv_ip_rows_c.bend    the STAGE C gate rows
    .agents/slop/nv_ip_tail_d.bend    the STAGE D defs (the trace)   [optional]
    .agents/slop/nv_ip_rows_d.bend    the STAGE D gate rows           [optional]

then a stable topological reorder, then `--check-only`.

    python3 .agents/slop/nv_ip_gen.py       # tables + stage B rows
    python3 .agents/slop/nv_ip_oracle.py    # stage C/D/E rows
    python3 .agents/slop/nv_ip_build.py
"""
import os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
IP = os.path.join(ROOT, 'tinybendygrad/runtime/support/nv/ip.bend')

PARTS = ['nv_ip_head.bend', 'nv_ip_tables.bend', 'nv_ip_tail_b.bend', 'nv_ip_prims.bend', 'nv_ip_tail_c.bend',
         'nv_ip_rows_c.bend', 'nv_ip_tail_d.bend', 'nv_ip_rows_d.bend',
         'nv_ip_rows_e.bend', 'nv_ip_main.bend']


def main():
  out = []
  for name in PARTS:
    p = os.path.join(HERE, name)
    if not os.path.exists(p):
      print('  (skipping %s -- not written yet)' % name)
      continue
    body = open(p).read().rstrip('\n')
    print('  + %-24s %6d B' % (name, len(body)))
    out.append(body)
  open(IP, 'w').write('\n\n'.join(out) + '\n')
  r = subprocess.run([sys.executable, os.path.join(HERE, 'nv_ip_order.py'), IP],
                     capture_output=True, text=True)
  print(r.stdout.strip() or r.stderr.strip())
  r = subprocess.run([os.path.join(ROOT, 'bin', 'bend'), IP, '--check-only'],
                     capture_output=True, text=True, cwd=ROOT)
  print(r.stdout.strip()[:3000])
  print('ip.bend is %d B, %d defs' % (os.path.getsize(IP),
      sum(1 for l in open(IP) if l.startswith('def ') or l.startswith('type '))))
  return r.returncode


if __name__ == '__main__':
  sys.exit(main())