#!/usr/bin/env python3
"""
nv_ip_gen.py -- GENERATE the nv/ip.bend DATA TABLES and the CPython rows that
gate them.  NOTHING in the generated rows is typed by hand: every expectation is
produced by importing tinygrad's autogen nv modules and reading the real
`_real_fields_`, the real module constants and the real `rpc_fns`/`rpc_events`
dicts, with no device present.

Writes (all under .agents/slop/, never $TMPDIR, so the comparison is
reproducible after the commit):
  nv_ip_tables.bend   the Bend fragment that goes into ip.bend
  nv_ip_rows.txt      the expected rows

Usage:  python3 .agents/slop/nv_ip_gen.py
"""
import sys, re, os, ctypes, textwrap
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
from tinygrad.runtime.autogen import nv, nv_570 as nv_gpu, pci

HERE = os.path.dirname(os.path.abspath(__file__))
PY = 'tinygrad/runtime/support/nv/ip.py'
src = open(PY).read()
MODS = (('nv', nv), ('nv_gpu', nv_gpu), ('pci', pci))
R = []


def lookup(n):
  for tag, mod in MODS:
    if hasattr(mod, n):
      return tag, getattr(mod, n)
  return '??', None


def fsz(t):
  """byte width of a registered field's ctype.

  `ctypes.sizeof` and NOT `t.size`: on a ctypes CLASS `size` is a getset
  DESCRIPTOR (a `ctypes.CField`), not a number.  Measured, not read."""
  return ctypes.sizeof(t)


def flds(o):
  return [(f[0], f[2], fsz(f[1])) for f in o._real_fields_]


def wrap(frag, indent='    ', width=110, per=3):
  """`List.concat` wants a list OF LISTS (`[[a, b], [c]]`), not a flat one, so the
  fragments are emitted in groups of `per`.  Measured: a flat list is
  "expected : List<&2, Cn>, observed : Cn"."""
  out = []
  for i in range(0, len(frag), per):
    out.append('[' + ', '.join(frag[i:i + per]) + ']')
  return '\n'.join(textwrap.wrap(', '.join(out) + ',', width=width,
                                 initial_indent=indent, subsequent_indent=indent,
                                 break_long_words=False, break_on_hyphens=False))


# every `nv.X` / `nv_gpu.X` / `pci.X` name ip.py touches, in FIRST-OCCURRENCE
# order, so the two tables below are two readings of ONE list.
touch, seen = [], set()
for n in re.findall(r'\b(?:nv|nv_gpu|pci)\.([A-Za-z_][A-Za-z0-9_]*)', src):
  if n not in seen:
    seen.add(n)
    touch.append(n)

STRUCTS = [(n, lookup(n)[0], lookup(n)[1]) for n in touch
           if lookup(n)[1] is not None and hasattr(lookup(n)[1], '_real_fields_')]
CONSTS = sorted([(n, lookup(n)[0], lookup(n)[1]) for n in touch if isinstance(lookup(n)[1], int)],
                key=lambda t: t[0])
IN32 = [(n, t, v) for n, t, v in CONSTS if v <= 0xffffffff]
cn_order = [(n, v) for n, t, v in IN32]
OVER64 = [(n, t, v) for n, t, v in CONSTS if v > 0xffffffff]
ONCE1 = [n for n, t, v in IN32 if v == 1]

L = []
A = L.append
A('# ' + '=' * 74)
A('# GENERATED by .agents/slop/nv_ip_gen.py. DO NOT HAND-EDIT -- if a row and this')
A('# table disagree, one of the two is a transcription error and the differ says which.')
A('# Every value below was read out of tinygrad/runtime/autogen/{nv,nv_570,pci}.py')
A('# by that script, with NO DEVICE PRESENT.')
A('# ' + '=' * 74)

# ------------------------------------------------------------- constants ----
A('')
A('# The %d integer constants ip.py names that FIT a U32. A %d-th does not and is' % (len(IN32), len(OVER64)))
A('# the 64-BIT WALL -- see THE WALLS in the file header. `Cn` IS the table, so the')
A('# gate can ask for a value FROM a name and a name FROM a value over ONE transcription.')

A('#')
A('# The reverse arm is FIRST-WINS, and %d names share the value 1:' % len(ONCE1))
for _o in ONCE1: A('#   %s' % _o)
A('# so the generated (name-sorted) order is load-bearing for `const_name`.')
A('# `ip_nm_first` pins the winner and `ip_nm_one_n` pins how many it beat.')
A('type Cn is Data:')
A('  Cn{name: String, v: U32}')
A('')
A('def Cn.of(n: String, v: U32) -> Cn:')
A('  Cn{n, v}')
A('')
A('def Cn.name(c: Cn) -> String:')
A('  match c:')
A('    case Cn{+name, v}: name')
A('')
A('def Cn.v(c: Cn) -> U32:')
A('  match c:')
A('    case Cn{name, +v}: v')
A('')
A('def cn_table() -> List<&2, Cn>:')
A('  List.concat(&2, Cn, [')
A(wrap(['Cn.of("%s", %d)' % (n, v) for n, t, v in IN32], indent='    '))
A('  ])')

# --------------------------------------------------------------- structs ----
A('')
A('# ONE ctypes struct ip.py names: SIZE, the field COUNT, and the fields as')
A('# "name@offset:bytes" IN DECLARATION ORDER.')
A('#')
A('# ORDER AND WIDTH ARE THE WHOLE POINT. A transposed pair is a silently wrong')
A('# register write, and a COUNT gate cannot see a transposition -- which is why')
A('# each struct is one row carrying names, order, offsets AND widths at once, and')
A('# `nf` is a SECOND, INDEPENDENT transcription of the field count (so a dropped')
A('# or duplicated name in the string is caught by the count row and vice versa).')
A('type St is Data:')
A('  St{nm: String, nf: U32, size: U32, fields: String}')
A('')
A('def St.nm(s: St) -> String:')
A('  match s:')
A('    case St{+nm, nf, size, fields}: nm')
A('')
A('def St.fields(s: St) -> String:')
A('  match s:')
A('    case St{nm, nf, size, +fields}: fields')
A('')
A('def St.nf(s: St) -> U32:')
A('  match s:')
A('    case St{nm, +nf, size, fields}: nf')
A('')
A('def St.size(s: St) -> U32:')
A('  match s:')
A('    case St{nm, nf, +size, fields}: size')
A('')
for n, tag, o in STRUCTS:
  body = ','.join('%s@%d:%d' % f for f in flds(o))
  A('')
  A('def st_%s() -> St:' % n)
  A('  St{"%s", %d, %d, "%s"}' % (n, len(o._real_fields_), o.SIZE, body))

# -------------------------------------------------------- dispatch tables ----
A('')
A('# nv.rpc_fns (%d) and nv.rpc_events (%d) as (id, name) IN INSERTION ORDER, which' % (len(nv.rpc_fns), len(nv.rpc_events)))
A('# is the order :81\'s `.get` resolves against. The id spaces are DISJOINT --')
A('# functions are %d..%d and events %d..%d, overlap %d -- so `rpc_fns.get(f,' % (min(nv.rpc_fns), max(nv.rpc_fns), min(nv.rpc_events), max(nv.rpc_events), len(set(nv.rpc_fns) & set(nv.rpc_events))))
A('# rpc_events.get(f, ...))` reaches its second arm for EVERY event id and its')
A('# third arm for every id neither table has. `ip_d_*` pins all three arms.')
A('type Ce is Data:')
A('  Ce{id: U32, name: String}')
A('')
A('def Ce.of(i: U32, n: String) -> Ce:')
A('  Ce{i, n}')
A('')
A('def Ce.id(c: Ce) -> U32:')
A('  match c:')
A('    case Ce{+id, name}: id')
A('')
A('def Ce.name(c: Ce) -> String:')
A('  match c:')
A('    case Ce{id, +name}: name')
A('')
for tag, tbl in (('fns', nv.rpc_fns), ('events', nv.rpc_events)):
  A('def d_%s() -> List<&2, Ce>:' % tag)
  A('  List.concat(&2, Ce, [')
  A(wrap(['Ce.of(%d, "%s")' % (k, v) for k, v in tbl.items()], indent='    '))
  A('  ])')

# `st_field_list` LAST: it calls every `st_*`, and a def may only call defs
# declared ABOVE it ("an unfilled law is a dead claim").
A('')
A('# The 54 layouts as one list, in the order the generator found them. `st_nth`')
A('# indexes it, so the gate can ask for the n-th layout and the ORDER of the')
A('# table is itself checkable against `ip_st_order`.')
A('def st_field_list() -> List<&2, St>:')
A('  List.concat(&2, St, [')
A(wrap(['st_%s()' % n for n, t, o in STRUCTS], indent='    '))
A('  ])')

open(os.path.join(HERE, 'nv_ip_tables.bend'), 'w').write('\n'.join(L) + '\n')

# ------------------------------------------------------------- the rows -----
for n, tag, v in IN32:
  R.append('ip_c_%s=%d' % (n, v))
for n, tag, o in STRUCTS:
  R.append('ip_st_%s=%s' % (n, ','.join('%s@%d:%d' % f for f in flds(o))))
  R.append('ip_st_%s_sz=%d' % (n, o.SIZE))
  R.append('ip_st_%s_nf=%d' % (n, len(o._real_fields_)))
R.append('ip_st_count=%d' % len(STRUCTS))
R.append('ip_st_order=%s' % ''.join('%s,' % n for n, t, o in STRUCTS))
R.append('ip_c_order=%s' % ''.join('%s,' % n for n, t, v in IN32))
R.append('ip_st_total_fields=%d' % sum(len(o._real_fields_) for _, _, o in STRUCTS))
R.append('ip_st_total_bytes=%d' % sum(o.SIZE for _, _, o in STRUCTS))
R.append('ip_c_count=%d' % len(IN32))
# the BOTH-DIRECTIONS rows and the three arms of :81
def first_name(v):
  # `cn_order` is [(name, value)], so the NAME is `k`.  The first version of
  # this returned `n` -- the VALUE -- and the differ reported
  # `ip_c_one_first oracle: 1 / port: GSP_DMA_TARGET_COHERENT_SYSTEM`.  That is
  # the `nv_query_litter` failure exactly: an oracle that is wrong in the SAME
  # DIRECTION as nothing still disagrees with a correct port, and a hand-typed
  # oracle would have agreed with a hand-typed port over the error.
  for k, n in cn_order:
    if n == v:
      return k
  return ''

def first_n(v):
  return sum(1 for k, n in cn_order if n == v)

def label(f):
  return nv.rpc_fns.get(f, nv.rpc_events.get(f, 'ev:%x' % f))

def arm(f):
  return 1 if f in nv.rpc_fns else (2 if f in nv.rpc_events else 3)

for v in (0, 4, 72, 4097):
  R.append('ip_c_n%d=%s' % (v, first_name(v)))
R.append('ip_c_n_big=%s' % first_name(545259819))
R.append('ip_c_n_miss=%s' % first_name(999999))
R.append('ip_c_one_n=%d' % first_n(1))
R.append('ip_c_one_first=%s' % first_name(1))
R.append('ip_c_n0_k=%d' % first_n(0))
R.append('ip_c_n4_k=%d' % first_n(4))
R.append('ip_c_n72_k=%d' % first_n(72))
R.append('ip_c_n4097_k=%d' % first_n(4097))
R.append('ip_c_n_big_k=%d' % first_n(545259819))
R.append('ip_c_n_miss_k=%d' % first_n(999999))
for f in (4, 0, 4097, 4131, 4132, 999, 4135):
  R.append('ip_d_lbl_%s=%s' % ({4: 'fn', 0: 'fn0', 4097: 'ev', 4131: 'ev_max',
                                4132: 'miss', 999: 'miss2', 4135: 'miss_hex'}[f], label(f)))
R.append('ip_d_arm_fn=%d' % arm(4))
R.append('ip_d_arm_ev=%d' % arm(4097))
R.append('ip_d_arm_miss=%d' % arm(4132))
R.append('ip-done=1')
R.append('ip_c_over64=%s' % ','.join('%s@%s' % (n, t) for n, t, v in OVER64))
R.append('ip_c_over64_n=%d' % len(OVER64))
R.append('ip_d_fns_n=%d' % len(nv.rpc_fns))
R.append('ip_d_events_n=%d' % len(nv.rpc_events))
R.append('ip_d_overlap=%d' % len(set(nv.rpc_fns) & set(nv.rpc_events)))
R.append('ip_d_fns_min=%d' % min(nv.rpc_fns))
R.append('ip_d_fns_max=%d' % max(nv.rpc_fns))
R.append('ip_d_ev_min=%d' % min(nv.rpc_events))
R.append('ip_d_ev_max=%d' % max(nv.rpc_events))
for k, v in nv.rpc_fns.items():
  R.append('ip_d_fns_%d=%s' % (k, v))
for k, v in nv.rpc_events.items():
  R.append('ip_d_ev_%d=%s' % (k, v))
open(os.path.join(HERE, 'nv_ip_rows.txt'), 'w').write('\n'.join(R) + '\n')

print('structs %d  fields %d  bytes %d  names %d' % (
    len(STRUCTS), sum(len(o._real_fields_) for _, _, o in STRUCTS),
    sum(o.SIZE for _, _, o in STRUCTS), max(len(n) for n, _, o in STRUCTS)))
print('consts %d (over64 %d, sharing 1: %d)  fns %d  events %d' % (
    len(IN32), len(OVER64), len(ONCE1), len(nv.rpc_fns), len(nv.rpc_events)))
print('rows %d  tables %d B' % (len(R), os.path.getsize(os.path.join(HERE, 'nv_ip_tables.bend'))))