#!/usr/bin/env python3
# .agents/slop/nv_nvdev_gen.py -- emit the Bend REGISTER TABLE from the oracle.
#
# The table below is a TRANSCRIPTION, and transcriptions are where this project
# has been bitten five times (see agent-core.md). So it is GENERATED from
# `.agents/slop/nv_nvdev_oracle.py`'s output, which itself calls the real
# CPython `NVReg` over the real `tinygrad/runtime/autogen/nv_regs/` tables.
#
#   .venv/bin/python .agents/slop/nv_nvdev_oracle.py | python3 .agents/slop/nv_nvdev_gen.py
#
# Run it, do not edit its output by hand. If a row disagrees with the file, the
# file is wrong and this is the reason.

import sys, re

rows = {}
for line in sys.stdin:
    line = line.rstrip("\n")
    if "=" not in line: continue
    k, v = line.split("=", 1)
    rows[k] = v

REGS = [
  ("boot0",   "NV_PMC_BOOT_0"),
  ("boot42",  "NV_PMC_BOOT_42"),
  ("wpr2",    "NV_PFB_PRI_MMU_WPR2_ADDR_HI"),
  ("scratch", "NV_PGC6_AON_SECURE_SCRATCH_GROUP_42"),
  ("inval",   "NV_VIRTUAL_FUNCTION_PRIV_MMU_INVALIDATE"),
  ("v2_pte",  "NV_MMU_VER2_PTE"),
  ("v2_pde",  "NV_MMU_VER2_PDE"),
  ("v2_dpd",  "NV_MMU_VER2_DUAL_PDE"),
  ("v3_pte",  "NV_MMU_VER3_PTE"),
  ("v3_pde",  "NV_MMU_VER3_PDE"),
  ("v3_dpd",  "NV_MMU_VER3_DUAL_PDE"),
]

def need(k):
  if k not in rows:
    print(f"MISSING {k} -- the oracle did not emit it", file=sys.stderr); sys.exit(1)
  return rows[k]

print("# GENERATED by .agents/slop/nv_nvdev_gen.py from the CPython oracle. DO NOT HAND-EDIT.")
for tag, name in REGS:
  base = int(need(f"nv_reg_{name}_base")); off = int(need(f"nv_reg_{name}_off"))
  raw = need(f"nv_reg_{name}_ranges")
  fs = []
  for part in [p for p in raw.split(";") if p]:
    n, se = part.split("=")
    s, e = se.split(":")
    fs.append(f'Fld.of("{n}", {s}, {e})')
  body = ("[" + ", ".join(fs) + "]") if fs else "Nil{}"
  has = int(need(f"nv_reg_{name}_has_addr"))
  print(f"def nv.reg_{tag}() -> Rgv: Rgv.of({base}, {off}, {body})")
  print(f"def nv.addr_{tag}() -> U32: {has}")   # 1 = nvdev.py may READ it; 0 = descriptor only
  print(f"def nv.tag_{tag}() -> String: \"{name}\"")
  print(f"def nv.mmcnt_{tag}() -> U32: {need(f'nv_reg_{name}_nf')}")
  print(f"def nv.maxw_{tag}() -> U32: {need(f'nv_reg_{name}_maxw')}")
  print(f"def nv.wide_{tag}() -> U32: {need(f'nv_reg_{name}_wide')}")
print(f"# total fields across the eleven registers: {sum(int(need(f'nv_reg_{n}_nf')) for _, n in REGS)}")
print(f"# total fields WIDER THAN 32 bits: {sum(int(need(f'nv_reg_{n}_wide')) for _, n in REGS)}")