#!/usr/bin/env python3
"""rebase-control-new-oracles.py -- ONE control per gate this unit wired.

WHY A SEPARATE SCRIPT. rebase-plant-disagreement.py proves the same thing for ONE hardcoded
pair (ops_nv / nv-oracle.py) by EDITING BASE_ORACLES in rebase-gate.py and restoring it in a
`finally`. That is the only way it can reach a non-default pairing, because the gate has no
`--oracle` flag -- the script says so itself. Editing the gate source to run a control is
untenable in a tree where other agents are reading that file (one of my own six oracle files
was rewritten underneath me mid-session), so this drives `verdict()` DIRECTLY with the mutant
oracle as an argument. `verdict()` is the same decision function `main()` calls, it takes the
oracle list as a parameter, and nothing on disk is modified except the mutant, which this
script creates and deletes.

For each wired gate, three states are required, and all three are asserted:

    CLEAN             verdict != BROKEN, and the CPython lane carried >1 row
    ONE PLANTED ROW   verdict == BROKEN, and `disagreements` NAMES the planted row
    RESTORED          mutant deleted, the real oracle back on disk byte for byte

THE PLANT IS A SOURCE COPY WITH EXACTLY ONE PRINT CHANGED, and the substitution COUNT is
asserted to be 1. Appending a `print` shim does not work -- these oracles print from a
`main()` at the BOTTOM of the file, so a shim appended after it is installed after the rows
have already been printed. That shim "succeeded" once and emitted the UNMUTATED oracle, which
is the worst shape a mutation can have. So the mutation is the print expression itself.

  usage: python3 .agents/slop/rebase-control-new-oracles.py
         python3 .agents/slop/rebase-control-new-oracles.py --clean
"""
import hashlib, pathlib, sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SLOP = REPO / ".agents" / "slop"
MARK = "# PLANTED DISAGREEMENT -- generated by rebase-control-new-oracles.py"

# (port, oracle spec, the ONE print line to rewrite, that print line with the mutation in it,
#  the row to corrupt -- chosen as a row the PORT also prints, since a row the port does not
#  print would be invisible to GUARD 4 and would prove nothing)
CASES = [
  ("tinybendygrad/runtime/ops_qcom.bend", ".agents/slop/qcom-oracle.py",
   '    print(f"{name}={value}")',
   '    print(f"{name}=" + ("PLANTED-NOT-" + str(value) if name == "qc_ctz_00000001" else str(value)))',
   "qc_ctz_00000001"),
  ("tinybendygrad/schedule/indexing.bend", ".agents/slop/indexing-oracle.py",
   '    print(f"{name}={value}")',
   '    print(f"{name}=" + ("PLANTED-NOT-" + str(value) if name == "bax4" else str(value)))',
   "bax4"),
  ("tinybendygrad/runtime/ops_null.bend", ".agents/slop/null-oracle.py",
   '    print(f"{name}={value}")',
   '    print(f"{name}=" + ("PLANTED-NOT-" + str(value) if name == "nr_exec" else str(value)))',
   "nr_exec"),
  ("tinybendygrad/engine/jit.bend", ".agents/slop/jit-oracle.py",
   '        print(f"{k}={v}")',
   '        print(f"{k}=" + ("PLANTED-NOT-" + str(v) if k == "dt_repr_f32" else str(v)))',
   "dt_repr_f32"),
  ("tinybendygrad/schedule/rangeify.bend", ".agents/slop/rangeify-oracle.py",
   '        print(f"{k.strip()}={v.strip()}")',
   '        print(f"{k.strip()}=" + ("PLANTED-NOT-" + v.strip() if k.strip() == "rb_len" else v.strip()))',
   "rb_len"),
]


def load_gate(tag):
  """The gate as a MODULE, so verdict() is called directly and BASE_ORACLES on disk is
  never edited. sys.path is seeded with SLOP because that is where rebase-gate.py lives."""
  import importlib.util
  sys.path.insert(0, str(SLOP))
  spec = importlib.util.spec_from_file_location(tag, SLOP / "rebase-gate.py")
  mod = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(mod)
  return mod


def digest(p):
  return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()


def plant(spec, printer, mutated, target):
  real = REPO / spec
  src = real.read_text()
  assert src.count(printer) == 1, \
    f"{spec}: expected exactly ONE {printer!r}, found {src.count(printer)} -- a substitution " \
    "that hits 0 or 2 places is not a one-row plant"
  out = SLOP / (pathlib.Path(spec).stem + "-ctl.py")
  out.write_text(f"{MARK}\n# One print expression rewritten, so the mutant and {real.name} differ\n"
                f"# only in the bytes that reach the gate. Corrupts row {target!r}.\n"
                + src.replace(printer, mutated))
  return out


def verdict_for(g, port, spec, native=False):
  """gate_port()'s inputs, with NO baseline: the honest state for a port that has never been
  recorded is NOT-STARTED, and it is reached only AFTER GUARD 4 has compared every lane pair
  and found no disagreement. So NOT-STARTED here is a positive claim, not silence."""
  v, _ = g.gate_port(REPO / port, [spec], None, native)
  return v


def main():
  if "--clean" in sys.argv:
    for _, spec, *_ in CASES:
      m = SLOP / (pathlib.Path(spec).stem + "-ctl.py")
      m.unlink(missing_ok=True)
    print("mutants removed")
    return 0

  g = load_gate("rebase_gate_control")
  ok = True

  def check(label, cond, detail=""):
    nonlocal ok
    ok = ok and bool(cond)
    print(f"  {'PASS' if cond else 'FAIL'}  {label}" + (f"\n        {detail}" if detail else ""))

  for port, spec, printer, mutated, target in CASES:
    name = pathlib.Path(spec).name
    print(f"\n=== {port}  <-  {name}  (planting {target!r})")
    real_path = REPO / spec
    before = digest(real_path)

    clean = verdict_for(g, port, spec)
    check(f"{name}: CLEAN is not BROKEN", clean["state"] != "BROKEN",
          f"{clean['state']}: {clean['why'][:110]}")
    check(f"{name}: the clean lane really carried rows",
          clean.get("row_counts", {}).get(f"cpython:{real_path.stem}", 0) > 1,
          str(clean.get("row_counts")))

    mutant = plant(spec, printer, mutated, target)
    try:
      bad = verdict_for(g, port, f".agents/slop/{mutant.name}")
      check(f"{name}: ONE planted row -> BROKEN", bad["state"] == "BROKEN",
            f"{bad['state']}: {bad['why'][:110]}")
      named = [d for d in bad.get("disagreements", []) if d[2] == target]
      check(f"{name}: and it NAMES {target!r}", bool(named), f"disagreements={bad.get('disagreements')}")
      check(f"{name}: and names ONLY that row",
            {d[2] for d in bad.get("disagreements", [])} == {target},
            f"{sorted({d[2] for d in bad.get('disagreements', [])})}")
    finally:
      mutant.unlink(missing_ok=True)

    after = verdict_for(g, port, spec)
    check(f"{name}: RESTORED is not BROKEN", after["state"] != "BROKEN", f"{after['state']}")
    check(f"{name}: the real oracle is byte-identical to before the control",
          digest(real_path) == before, f"sha256 {digest(real_path)[:16]}")
    check(f"{name}: the mutant is gone", not mutant.exists(), str(mutant))

  print("\n" + ("all controls PASS" if ok else "CONTROL FAILURES ABOVE"))
  return 0 if ok else 1


if __name__ == "__main__":
  sys.exit(main())