#!/usr/bin/env python3
"""rebase-plant-disagreement.py -- PROVE the gate reports a DISAGREEMENT that exists.

A gate never seen red is not known to work. This takes a REAL oracle that agrees with a REAL
port on every shared row (measured: ops_nv, 543 shared rows, 0 disagreements), corrupts
EXACTLY ONE row value in the output, and writes the mutant as a new oracle script. Wiring that
mutant in must move the verdict to BROKEN and name the row -- and the same pair with the
uncorrupted oracle must read UNCHANGED. Both halves are asserted here, so the proof is not
"the tool went red", which a broken tool would also do.

  usage: python3 .agents/slop/rebase-plant-disagreement.py            # plant + verify
         python3 .agents/slop/rebase-plant-disagreement.py --clean    # remove the mutant
"""
import json, pathlib, subprocess, sys

REPO = pathlib.Path(__file__).resolve().parents[2]
GATE = REPO / ".agents" / "slop" / "rebase-gate.py"
PORT = "tinybendygrad/runtime/ops_nv.bend"
REAL = ".agents/slop/nv-oracle.py"
MUTANT = REPO / ".agents" / "slop" / "nv-oracle-planted.py"
MUTANT_SPEC = ".agents/slop/nv-oracle-planted.py"
MARK = "# PLANTED DISAGREEMENT"


def run(cmd):
  return subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, timeout=2400)


def rows_of(spec):
  r = run([sys.executable, *spec.split()])
  out = {}
  for line in r.stdout.splitlines():
    if "=" in line:
      k, v = line.split("=", 1)
      out[k.strip()] = v.strip()
  return out


PRINT_LOOP = '        print("%s=%s" % (nm, v))'


def plant(row_name):
  """Copy the real oracle, changing EXACTLY ONE LINE: the printer inside its __main__ block.

  A `print` monkeypatch appended at the end of the file does not work, and the reason is the
  shape of every oracle here: the rows are collected into ROWS as the module is imported and
  printed from an `if __name__ == "__main__":` block at the BOTTOM, so a shim appended after
  it is installed after the printing already happened. It "succeeded" and printed the
  unmutated oracle, which is the worst shape a mutation script can have. So the mutation is
  the print expression itself, and the substitution COUNT is asserted to be 1."""
  src = (REPO / REAL).read_text()
  assert src.count(PRINT_LOOP) == 1, f"expected exactly one printer, found {src.count(PRINT_LOOP)}"
  mutated = src.replace(
    PRINT_LOOP,
    f'        print("%s=%s" % (nm, "PLANTED-NOT-" + v if nm == {row_name!r} else v))')
  MUTANT.write_text(
    f"# {MARK} -- generated by rebase-plant-disagreement.py, then DELETED by it.\n"
    "# One row of the REAL oracle's output is rewritten at print time, so the mutant and\n"
    "# nv-oracle.py differ in exactly the bytes that reach the gate and in nothing else.\n"
    + mutated)


def gate_wired(spec):
  """Point PORT at `spec` by editing BASE_ORACLES, run the gate, restore. The edit is the
  only way to reach a non-default pairing, which is itself the finding: the gate has no
  --oracle flag, so proving a disagreement requires a source edit. Named, not hidden."""
  text = GATE.read_text()
  old = f'"{PORT}": ["{REAL}"],'
  assert old in text, "BASE_ORACLES no longer holds the pair this script plants against"
  GATE.write_text(text.replace(old, f'"{PORT}": ["{spec}"],'))
  try:
    r = run([sys.executable, str(GATE), "--port", PORT, "--no-native", "--json"])
    return json.loads(r.stdout)["verdicts"][0], r.returncode
  finally:
    GATE.write_text(text)


def main():
  if "--clean" in sys.argv:
    MUTANT.unlink(missing_ok=True)
    print(f"removed {MUTANT}")
    return 0

  real = rows_of(REAL)
  plant_rows = rows_of(MUTANT_SPEC) if MUTANT.exists() else {}
  names = [k for k in real if not plant_rows or k in plant_rows]
  if not names:
    print("cannot plant: the mutant produced no rows"); return 1
  target = sorted(names)[len(names) // 2]
  if not plant_rows:
    plant(target)
    plant_rows = rows_of(MUTANT_SPEC)
  diff = [k for k in set(real) & set(plant_rows) if real[k] != plant_rows[k]]
  print(f"planted ONE row: {target}\n  real    {target}={real[target]!r}\n"
        f"  mutant  {target}={plant_rows[target]!r}")
  print(f"rows differing between the two oracles: {len(diff)} {diff[:3]}")

  ok = True

  def check(name, cond, detail):
    nonlocal ok
    ok = ok and cond
    print(f"  {'PASS' if cond else 'FAIL'}  {name}\n        {detail}")

  v, rc = gate_wired(MUTANT_SPEC)
  check("the MUTANT is BROKEN and NAMES the row", v["state"] == "BROKEN", v["why"][:200])
  named = [d for d in v.get("disagreements", []) if d[2] == target]
  check("the planted row is the one it names",
        bool(named) and named[0][0] == "interpreted",
        f"disagreements[0]={v.get('disagreements', [None])[0]}")
  check("the exit code is 1 on BROKEN", rc == 1, f"rc={rc}")

  v2, rc2 = gate_wired(REAL)
  check("the SAME pair with the UNCORRUPTED oracle is not BROKEN", v2["state"] != "BROKEN",
        f"{v2['state']}: {v2['why'][:160]}")
  check("and it is not a pass by accident -- it names its rows",
        v2.get("row_counts", {}).get("cpython:nv-oracle", 0) > 1, str(v2.get("row_counts")))

  MUTANT.unlink(missing_ok=True)
  print(f"\nmutant removed: {not MUTANT.exists()}")
  return 0 if ok else 1


if __name__ == "__main__":
  sys.exit(main())