#!/usr/bin/env python3
"""STAGE 2 -- build `.agents/slop/sched-fixture.bend` from `sched-emit.py`.

One Bend file with one `<spec>.build` def per spec and one row per FIELD, so the
comparison is a diff of printed `name=value` lines against
`.agents/slop/sched-oracle.txt` and never a count.

FIELDS PER SPEC. CPython's field name is kept, so the diff is name-to-name:

  <spec>_gated   port `sc_topo_of` length                 <- CPython `sink_n`
  <spec>_root_op port READS the root's op                  <- CPython `sink_op`
  <spec>_lin_n   LINEAR arity                             <- CPython `lin_nsrc`
  <spec>_lin_op  LINEAR op, READ not assumed              <- CPython `lin_op`
  <spec>_ksrc    per-kernel src op SEQUENCE, LINEAR order <- CPython `lin_ksrc`
  <spec>_ksrc_n  the untruncated length of that sequence
  <spec>_knsrc   per-kernel arity                         <- CPython `lin_knsrc`
  <spec>_ktop    per-kernel body op                       <- CPython `lin_ktop`
  <spec>_kmark   per-kernel STORE-value op                <- CPython `lin_kmark`
  <spec>_cyc     in_degree keys never zeroed AFTER the loop  <- CPython's RAISE

THE THREE VERDICTS, kept apart because the brief is explicit that a fuel bound,
a cycle and a raise are three different answers:

  `_lin_n`    the LINEAR's arity. Zero is AMBIGUOUS ALONE: CPython answers
              `UOp(Ops.LINEAR, src=())` for an empty SINK, for an AFTER, and for
              a real sink with no reachable kernels, and sched-stage1.md
              measures all three. So `_cyc` and `_ksrc_n` are printed beside it
              and a reader is expected to consult both.
  `_cyc`      THE RAISE. CPython raises `RuntimeError("cycle detected in assign
              graph")` at `__init__.py:79` exactly when this is non-zero. The
              port cannot raise, so the COUNT is the observable, and it is its
              own row rather than folded into `_lin_n`.
  `_ksrc_n`   the number of src ops actually packed. `_ksrc` is a base36 integer
              and WRAPS at 2^32, so past 7 ops it would compare equal on a
              suffix. Printing the untruncated count makes that visible instead
              of silent.

RUN:
  env -u PYTHONPATH LC_ALL=C DEV=NONE .venv/bin/python .agents/slop/sched-fixture.py
  ./bin/bend .agents/slop/sched-fixture.bend | tee .agents/slop/sched-port.txt
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = "/Users/cyberistic/src/tries/2026-09-30-tinybendygrad"
sys.path.insert(0, ROOT)
sys.path.insert(0, HERE)

import importlib.util
_o = importlib.util.spec_from_file_location("se", os.path.join(HERE, "sched-emit.py"))
SE = importlib.util.module_from_spec(_o)
_o.loader.exec_module(SE)
SO = SE.SO

HEADER = r'''# sched-fixture.bend -- GENERATED by .agents/slop/sched-fixture.py. Do not hand-edit.
#
# Every `+nK = O.UOp.new(...)` below is EMITTED from CPython's own object graph
# by sched-emit.py, so no node here is transcribed and no expectation is typed.
# The rows it prints are the fields `.agents/slop/sched-oracle.txt` records for
# the same spec.
#
# WHAT THIS FILE IS NOT: it is not a claim that the port reproduces tinygrad's
# SCHEDULER. It hands the port's `create_schedule` (named `schedule`) the exact
# sched_sink CPython built and compares the LINEAR field by field. Everything
# upstream of that -- rangeify, prepare, callify -- is `__init__.py:82-301` and is
# still deferred.
import Base
import ./../../tinybendygrad/helpers.bend as H
import ./../../tinybendygrad/LAWS/spec.bend as S
import ./../../tinybendygrad/uop/ops.bend as O
import ./../../tinybendygrad/schedule/__init__.bend as SC

# BOOL LITERALS ARE PATTERNS, NOT TERMS. `False{}` compiles in a `case` arm and
# is REFUSED in a term position ("expected : a defined name, observed : False"),
# which is how the first emitted `ParamArg` died. The port never needs a Bool
# literal term either -- `graphcmp.bend:824` forwards a `vol: Bool` parameter --
# so these two defs are the cheapest honest spelling.
def bfalse() -> Bool: U32.is_eq(1, 0)
def btrue() -> Bool: U32.is_eq(0, 0)

def row(nm: String, v: U32) -> IO(Unit):
  IO.print(String.concat([nm, "=", U32.show(v), "\n"]))

# ---------------------------------------------------------------------------
# THE SHAPE, AND WHY EVERY RECURSIVE DEF BELOW IS SPLIT IN TWO.
#
# AN ARENA PARAMETER MAY BE CONSUMED ONCE. Measured twice: a `+ar` read twice is
# "expected : u / observed : u (consumed more than once)", and so is a NON-`+`
# `ar` that is both read and handed to its own self-call. So the schedule file's
# idiom applies -- a `.go` computes everything it needs from the arena FIRST, as
# VALUES, and the recursive `def` only threads them:
#
#     def f(ar, ss, acc)      -> match ss: Nil => acc | s<>rest => f.go(ar, rest, acc, dig(ar, s))
#     def f.go(ar, ss, acc, d)-> f(ar, ss, acc*36 + d)
#
# THE ORDER IS ALSO LOAD-BEARING: `def f` is declared BEFORE `def f.go` because
# `f.go`'s body calls `f`, and a body that calls an UNFILLED def is refused with
# "expected : a filled definition (an unfilled law is a dead claim)". This is the
# same bill `Kahn`/`Sized` pay at schedule/__init__.bend:895-901.
# ---------------------------------------------------------------------------

# THE PACKING. `dig` is `gate.code` (schedule/__init__.bend:1226) widened to the
# ops sched-emit.py EMITS; a list of ops packs base36 so the LAST op is the LAST
# digit and a whole sequence is ONE comparable token. Digit 0 means "no code", so
# an uncoded op is visible rather than a silent leading zero.
#
# THE OPS ARE THE ONES ACTUALLY EMITTED. The first list at this position
# included `O.OpsDIV{}` and FAILED TO COMPILE -- "a declared constructor
# (unknown: OpsDIV)": ops.bend has NO DIV variant at all, so DIV is NOT PORTED in
# this tree. sched-stage2.md records which specs need it.
def dig(op: O.Op) -> U32:
  match op:
    case O.OpsAFTER{}  : 1
    case O.OpsCALL{}   : 2
    case O.OpsEND{}    : 3
    case O.OpsSTORE{}  : 4
    case O.OpsSINK{}   : 5
    case O.OpsPARAM{}  : 6
    case O.OpsBUFFER{} : 7
    case O.OpsALLOC{}  : 8
    case O.OpsLINEAR{} : 9
    case O.OpsCONST{}  : 10
    case O.OpsRANGE{}  : 11
    case O.OpsMUL{}    : 12
    case O.OpsADD{}    : 13
    case O.OpsINDEX{}  : 14
    case O.OpsREDUCE{} : 15
    case O.OpsMAX{}    : 16
    case O.OpsCAST{}   : 17
    case _             : 0

def lin_nsrc(l: SC.Lin) -> U32:
  U32.from_nat(List.length(&2, U32, SC.Lin.out(l)))

def l_out(l: SC.Lin) -> List<&2, U32>: SC.Lin.out(l)

# ---------------------------------------------------------------------------
# THE FOLDS. Every reader is TWO defs: one that reads the ARENA and builds a
# `List<&2, U32>` of codes, and one arena-FREE fold that packs that list. The
# split is forced by two measured rules and it is worth naming both:
#
# 1. A PARAMETER MAY BE CONSUMED ONCE. A non-`+` `ar` that is both read and
#    handed to its own self-call is "expected : ar / observed : ar (consumed more
#    than once)". A `+ar` may be duplicated -- `wt_go` at
#    schedule/__init__.bend:865 passes it twice in one call -- so the arena
#    readers below all take `+ar`.
# 2. MUTUAL RECURSION NEEDS A FORWARD REFERENCE AND THE COMPILER REFUSES IT
#    ("expected : a filled definition"). `wt_go`/`wt` is NOT mutual: `wt` is a
#    plain def above the loop. So each fold here is a SINGLE self-recursive def
#    that builds a list, and the packing is a second, arena-free recursion.
#    That is rule 1 of the schedule file's own header ("put the decision in a
#    PARAMETER ... or split the def in two") in the only shape that composes with
#    an arena.
#
# `List.append(x, A, xs, ys)` is `xs ++ ys` (the head/tail trap in agent-core), so
# every append below puts the NEW element in the SECOND list and reads as
# "accumulate at the tail", which is Python's order.
# ---------------------------------------------------------------------------

# CPython `lin_ksrc`: every kernel's src ops, kernels in LINEAR order.
#
# THE ENCODING IS THE FLATTENED SEQUENCE IN BASE36 -- not one field per kernel.
# The first attempt multiplied by `36^nsrc(k)` per kernel, which is right and
# which Bend REFUSES: there is no `pow` ("expected : a defined name"). The flat
# fold needs no exponent and still agrees with CPython, because `lin_ksrc` IS the
# flat concatenation.
#
# THE ORDER IS THE WHOLE POINT OF THIS ROW, AND IT IS EASY TO INVERT -- so the bug
# is recorded rather than fixed silently. The first version read
# `List.append(&2, U32, srcs.of(ar, rest), [dig(...)])`: the recursive call FIRST.
# `List.append(x, A, xs, ys)` is `xs ++ ys`, so that PREPENDS, and `matmul_ksrc`
# came out 287933 = base36 `6665` = `[PARAM,PARAM,PARAM,SINK]` where CPython reads
# `['SINK','PARAM','PARAM','PARAM']`. This is the head/tail swap agent-core warns
# about, reached again, and only a SEQUENCE row catches it -- a count would not.
def srcs.of(+ar: O.Arena, ss: List<&2, U32>, acc: List<&2, U32>) -> List<&2, U32>:
  match ss:
    case Nil{}     : acc
    case s <> rest : srcs.of(ar, rest, List.append(&2, U32, acc, [dig(SC.sc_op(ar, s))]))

def srcs.of1(+ar: O.Arena, ss: List<&2, U32>) -> List<&2, U32>:
  srcs.of(ar, ss, Nil{})

def srcs.all(+ar: O.Arena, ks: List<&2, U32>, acc: List<&2, U32>) -> List<&2, U32>:
  match ks:
    case Nil{}     : acc
    case k <> rest : srcs.all(ar, rest, List.append(&2, U32, acc, srcs.of1(ar, SC.sc_srcs(ar, k))))

def pack(xs: List<&2, U32>, acc: U32) -> U32:
  match xs:
    case Nil{}     : acc
    case x <> rest : pack(rest, U32.add(U32.mul(acc, 36), x))

def ksrc(+ar: O.Arena, ks: List<&2, U32>) -> U32:
  pack(srcs.all(ar, ks, Nil{}), 0)

# THE UNTRUNCATED COUNT, so `_ksrc`'s 2^32 wrap can never be silent.
def ksrc_n(ar: O.Arena, ks: List<&2, U32>) -> U32:
  U32.from_nat(List.length(&2, U32, srcs.all(ar, ks, Nil{})))

# CPython `lin_knsrc`: the per-kernel arity, LINEAR order, base 16 so an arity of
# 15+ cannot collide with the next field.
def ns.all(+ar: O.Arena, ks: List<&2, U32>, acc: List<&2, U32>) -> List<&2, U32>:
  match ks:
    case Nil{}     : acc
    case k <> rest : ns.all(ar, rest, List.append(&2, U32, acc, [SC.sc_nsrc(ar, k)]))

def pack16(xs: List<&2, U32>, acc: U32) -> U32:
  match xs:
    case Nil{}     : acc
    case x <> rest : pack16(rest, U32.add(U32.mul(acc, 16), x))

def knsrc(+ar: O.Arena, ks: List<&2, U32>) -> U32:
  pack16(ns.all(ar, ks, Nil{}), 0)

# CPython `lin_ktop`: the per-kernel BODY op. `k.src[0]` is `k.body` for a CALL.
def top.all(+ar: O.Arena, ks: List<&2, U32>, acc: List<&2, U32>) -> List<&2, U32>:
  match ks:
    case Nil{}     : acc
    case k <> rest : top.all(ar, rest, List.append(&2, U32, acc, [dig(SC.sc_op(ar, SC.sc_src0(ar, k)))]))

def ktop(+ar: O.Arena, ks: List<&2, U32>) -> U32:
  pack(top.all(ar, ks, Nil{}), 0)

# CPython `lin_kmark`, GENERALISED. The port's `gate.mark`
# (schedule/__init__.bend:1268) reads `k.src[0].src[0].src[1].val` -- the STORE's
# value CONST -- and codes 1/2/3, answering 0 otherwise. Every real graph stores a
# rewritten EXPRESSION, so `gate.mark` is 0 on all six specs (sched-stage1.md
# records the measurement). The row that carries information is therefore the OP of
# that value: walk to the STORE under the kernel and code `store.src[1]`.
def mk.put(store: Bool, acc: U32, hit: U32) -> U32:
  match store:
    case True{} : hit
    case False{}: acc

# `u` MUST BE `+` HERE. A non-`+` `u` read twice is "expected : u / observed : u
# (consumed more than once)" -- and this body reads it twice, once for the STORE
# test and once for the src index. `+` is not a promise to mutate; it is the
# marker that says "this parameter may be consumed more than once", which is
# exactly `wt_go`'s arrangement at schedule/__init__.bend:865.
def mk.of(+ar: O.Arena, +u: U32, acc: U32) -> U32:
  mk.put(SC.sc_is(ar, u, O.OpsSTORE{}), acc, dig(SC.sc_op(ar, SC.sc_src(ar, u, 1))))

# THE SUBGRAPH, NOT THE DIRECT SRCS. The first version walked `sc_srcs(ar, k)`
# -- the kernel's own srcs -- and so never reached the STORE, which lives under
# `k.src[0]`, the body. `kmark` answered 0 on all six specs, and 0 is also what
# `gate.mark` returns for an uncoded value, so the bug was invisible in
# isolation. `O.UOp.toposort` (ops.bend:2839) is the port's UNGATED walk and it
# enters calls, which is what makes the STORE reachable.
def mk.go(+ar: O.Arena, us: List<&2, U32>, acc: U32) -> U32:
  match us:
    case Nil{}     : acc
    case u <> rest : mk.go(ar, rest, mk.of(ar, u, acc))

def kmark.go(+ar: O.Arena, ks: List<&2, U32>, acc: List<&2, U32>) -> List<&2, U32>:
  match ks:
    case Nil{}     : acc
    case k <> rest : kmark.go(ar, rest, List.append(&2, U32, acc,
      [mk.go(ar, O.UOp.toposort(O.Arena.budget(ar), ar, k), 0)]))

def kmark.go1(+ar: O.Arena, ks: List<&2, U32>) -> List<&2, U32>:
  kmark.go(ar, ks, Nil{})

def kmark(+ar: O.Arena, ks: List<&2, U32>) -> U32:
  pack(kmark.go1(ar, ks), 0)

# `sc_topo_of(fuel, +ar, +self)` is the ONE port def here that needs a `+` arena,
# and it is called once, so it needs no split -- but it cannot share an arena with
# the readers above, so each spec gets its OWN `+`-threaded build for it.
def gated(+ar: O.Arena, t: U32) -> U32:
  U32.from_nat(List.length(&2, U32, SC.sc_topo_of(O.Arena.budget(ar), ar, t)))
'''

MAIN = r'''
# ---------------------------------------------------------------------------
# THE ROWS. `_cyc` is THE RAISE: CPython raises `RuntimeError("cycle detected in
# assign graph")` (`__init__.py:79`) exactly when it is non-zero, and the port
# cannot raise, so the count is the observable. `_ksrc_n` is the third verdict:
# it says whether `_ksrc`'s base36 integer held every digit.
def main() -> IO(Unit):
  do IO<Unit>:
'''


def main():
  body, names = [], []
  for name, fn in SO.SPECS:
    SO._reset()
    SO._CAPTURED.clear()
    fn()
    if not SO._CAPTURED:
      print(f"# {name}: no create_schedule call", file=sys.stderr)
      continue
    sink, lin = SO._CAPTURED[-1]
    code, full, gnodes = SE.emit(name, sink)
    lines = [ln for ln in code.split("\n") if not ln.startswith("#")]
    body.append(f"def {name}.build() -> O.Found:")
    body.extend("  " + ln for ln in lines)
    # The node ITSELF, not its arena: `build` returns `O.Found`, and returning
    # `O.Found.ar(...)` is "expected : O.Found / observed : O.Arena".
    body.append(f"  n{len(full) - 1}")
    body.append("")
    # WHY SEPARATE ACCESSORS AND NOT BINDS IN `main`. Inside `do IO<Unit>:` every
    # bind is an IO action -- `+r = <pure>` is refused with "expected : a pattern
    # ... observed : {r : IO(Unit)}" -- and there is no `let`. So the pure work
    # lives in its own defs and `main` only prints. The cost is that some
    # accessors REBUILD the spec; at 20-65 nodes that is cheaper than a `let`.
    #
    # `lar` is the arena AFTER `SC.linear`, and every reader uses it: `linear`
    # interns one node, so reading the LINEAR's index out of the PRE-linear arena
    # would hit `Arena.node`'s TOTAL fallback and read back as NOOP. That is the
    # stale-index wall codegen/__init__.bend:20-24 records, and this is the shape
    # that walks into it.
    body.append(f"def {name}.sched() -> SC.Lin:")
    body.append(f"  +r = {name}.build()")
    body.append(f"  SC.schedule(O.Found.ar(r), O.Found.i(r))")
    body.append(f"def {name}.lf() -> O.Found: SC.linear({name}.sched())")
    body.append(f"def {name}.lar() -> O.Arena: O.Found.ar({name}.lf())")
    body.append(f"def {name}.root() -> U32: O.Found.i({name}.build())")
    body.append(f"def {name}.out() -> List<&2, U32>: SC.Lin.out({name}.sched())")
    body.append(f"def {name}.cyc() -> U32: U32.from_nat(SC.cycles(SC.Lin.c({name}.sched())))")
    body.append(f"def {name}.linop() -> U32: dig(SC.sc_op({name}.lar(), O.Found.i({name}.lf())))")
    body.append(f"def {name}.gated() -> U32:")
    body.append(f"  +r = {name}.build()")
    body.append(f"  gated(O.Found.ar(r), O.Found.i(r))")
    body.append("")
    names.append(name)

  rows = []
  for name in names:
    rows.append(f'    row("{name}_gated", {name}.gated())')
    rows.append(f'    row("{name}_root_op", dig(SC.sc_op({name}.lar(), {name}.root())))')
    rows.append(f'    row("{name}_lin_n", lin_nsrc({name}.sched()))')
    rows.append(f'    row("{name}_lin_op", {name}.linop())')
    rows.append(f'    row("{name}_ksrc", ksrc({name}.lar(), {name}.out()))')
    rows.append(f'    row("{name}_ksrc_n", ksrc_n({name}.lar(), {name}.out()))')
    rows.append(f'    row("{name}_knsrc", knsrc({name}.lar(), {name}.out()))')
    rows.append(f'    row("{name}_ktop", ktop({name}.lar(), {name}.out()))')
    rows.append(f'    row("{name}_kmark", kmark({name}.lar(), {name}.out()))')
    rows.append(f'    row("{name}_cyc", {name}.cyc())')
  out = HEADER + "\n" + "\n".join(body) + MAIN + "\n".join(rows) + "\n"
  p = os.path.join(HERE, "sched-fixture.bend")
  with open(p, "w") as f:
    f.write(out)
  print(f"# wrote {p}: {len(out.splitlines())} lines, specs={names}")


if __name__ == "__main__":
  main()