#!/usr/bin/env python3
"""GENERATE the packet-class tables and gate rows of `renderer/amd/sqtt.bend`.

WHY A GENERATOR, TWICE OVER. The first reason is that `sqtt.py`'s payload is
almost entirely TABLES -- three opcode tables, ~40 field layouts, three 256-byte
state tables -- and a table typed by hand drifts from its oracle the moment
either side is edited. The second reason is SHARED NAMES: `WAVEEND` and
`WAVEEND_RDNA4` differ in one field (`wgp` at [13:11] vs [14:11]) and `cu` shifts
from 3 to 4 because of it, so a lookup keyed by the SHORT name silently answers
the RDNA3 answer for an RDNA4 packet.

EVERY value that CAN come from CPython comes from CPython: the field layouts, the
`_size_nibbles`, the `encoding.mask` / `encoding.default`, and the opcode tables
are all read out of the live `sqtt.py` classes. Nothing here is transcribed.

    usage: .venv/bin/python .agents/slop/sqtt_gen.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from tinygrad.renderer.amd import sqtt  # noqa: E402

PORT = ROOT / "tinybendygrad/renderer/amd/sqtt.bend"
MARK = "# ==== GATE BODY (generated by .agents/slop/sqtt_gen.py) ===="

TABLES = [("RDNA3", sqtt.PACKET_TYPES_RDNA3), ("RDNA4", sqtt.PACKET_TYPES_RDNA4),
          ("CDNA", sqtt.PACKET_TYPES_CDNA)]


def class_list():
  out, seen = [], set()
  for _, tbl in TABLES:
    for op in sorted(tbl):
      c = tbl[op]
      if c.__name__ not in seen:
        seen.add(c.__name__)
        out.append((op, c))
  return out


CLASSES = class_list()


def emit():
  L = []
  a = L.append
  a('\n# --- T  THE THREE OPCODE TABLES, BOTH DIRECTIONS ' + "-" * 20)
  for tag, tbl in TABLES:
    # ONE list literal per table: a table written as N one-element lists is N
    # defs and a lookup that can only see the first, which is a wrong answer that
    # looks like a short table.
    items = ",".join(f'Pn{{"{tbl[op].__name__}", {op}}}' for op in sorted(tbl))
    a(f'def tbl_{tag}() -> List<&2, Pn>: [{items}]')
    a(f'def tbl_{tag}_n() -> Nat: {len(tbl)}n')

  a('\n# --- L / S / E  EVERY CLASS: fields BY NAME IN ORDER, nibbles, encoding ' + "-" * 3)
  for _, c in CLASSES:
    nm = c.__name__
    fs = ";".join(f"{k}:{f.hi}:{f.lo}" for k, f in c._fields.items())
    a(f'def fields_{nm}() -> String: "{fs}"')
    a(f'def field_order_{nm}() -> String: "{",".join(c._fields)}"')
    a(f'def cls_{nm}() -> U32: {c._size_nibbles}')
    e = c._fields.get("encoding")
    a(f'def mask_{nm}() -> U32: {e.mask if e else 0}')
    a(f'def dflt_{nm}() -> U32: {e.default if e else 0}')
    a(f'def himax_{nm}() -> U32: {max((f.hi for f in c._fields.values()), default=0)}')
    a(f'def hasdelta_{nm}() -> String: "{"yes" if "delta" in c._fields else "no"}"')
    if "delta" in c._fields:
      d = c._fields["delta"]
      a(f'def dlo_{nm}() -> U32: {d.lo}')
      # THE 64-BIT WORD WALL. `TS_DELTA_OR_MARK.delta = bits[47:12]` is 36 bits,
      # so the mask does not fit a U32. The port stores it MOD 2**32 and the
      # overflow flag is a gate row, so the clamp is visible instead of silent.
      a(f'def dmask_{nm}() -> U32: {d.mask % (2 ** 32)}')
      a(f'def dmask_over_{nm}() -> U32: {1 if d.mask > 0xFFFFFFFF else 0}')

  a('\n# --- THE CLASS NAME LIST ' + "-" * 48)
  a('def CLS_NAMES() -> List<&2, String>: [' + ",".join(f'"{c.__name__}"' for _, c in CLASSES) + ']')
  a('def str_list_text(xs: List<&2, String>) -> String: str_list_text.go(xs, "")')
  a('def str_list_text.go(xs: List<&2, String>, +acc: String) -> String:')
  a('  match xs:')
  a('    case Nil{}: acc')
  a('    case x <> t: str_list_text.go(t, String.concat([acc, x, ","]))')
  a('\n# --- THE WIDTH FORMULA ' + "-" * 50)
  a('# `cls._size_nibbles = ((max(f.hi) for f in cls._fields.values()) + 4) // 4`')
  a('# (:186) -- the packet WIDTH in NIBBLES, and it is what the nibble reader')
  a('# consumes, so a wrong one desynchronises every packet after it rather than')
  a('# misreading one. `cls_X()` holds the value and `nibs_of` recomputes it from')
  a('# the widest field, so the gate compares the FORMULA against CPython.')
  a('def nibs_of(hi_max: U32) -> U32: NIB_ROUND(hi_max)')
  a('def NIB_ROUND(hi_max: U32) -> U32: NIB_DIV(U32.add(hi_max, NIB_NUM()))')
  a('def NIB_DIV(v: U32) -> U32: U32.div(v, NIB_DEN())')
  a('def NIB_NUM() -> U32: 4')
  a('def NIB_DEN() -> U32: 4')
  a('\n# --- E  THE SORT THAT DECIDES THE STATE TABLE ' + "-" * 30)
  a('# `sorted(packet_types.items(), key=lambda x: (-bin(mask).count("1"), x[0] == 16))`')
  a('# (:557). TWO keys, and the second is what puts NOP -- opcode 16 -- LAST, so')
  a('# a byte with no match falls through to NOP rather than to whichever 4-bit')
  a('# pattern happened to be visited first. A port that sorts on specificity')
  a('# alone puts NOP FIRST and every unmatched byte decodes as a NOP of the')
  a('# wrong width.')
  for tag, tbl in TABLES:
    srt = sorted(tbl.items(), key=lambda x: (-bin(x[1].encoding.mask).count('1'), x[0] == 16))
    a(f'def spec_order_{tag}() -> String: "{",".join(str(bin(c.encoding.mask).count("1")) for _, c in srt)}"')
    a(f'def op_order_{tag}() -> String: "{",".join(str(o) for o, _ in srt)}"')
    a(f'def nop_last_{tag}() -> U32: {1 if srt[-1][0] == 16 else 0}')

  a('\n# --- B  THE THREE 256-BYTE STATE TABLES ' + "-" * 34)
  for tag, st in [("RDNA3", sqtt._STATE_TABLE_RDNA3), ("RDNA4", sqtt._STATE_TABLE_RDNA4),
                  ("CDNA", sqtt._STATE_TABLE_CDNA)]:
    a(f'def state_{tag}() -> List<&2, U32>: [{",".join(str(b) for b in st)}]')
    a(f'def state_{tag}_n() -> Nat: {len(st)}n')

  a('\n# --- D  THE DECODE INFO: nib_count, delta_lo, delta_mask, delta_mul, special ' + "-" * 5)
  a('# `special`: 0 none, 1 TS_DELTA_OR_MARK, 2 TS_DELTA_SHORT (+4), 4 CDNA_TIMESTAMP.')
  a('# The DELTA defaults differ per arch -- CDNA uses bits[4:4] with a multiplier')
  a('# of 4, RDNA uses None with a multiplier of 1 (:558) -- and that is the whole')
  a('# reason a CDNA timestamp and an RDNA delta are not the same number.')
  for tag, di in [("RDNA3", sqtt._DECODE_INFO_RDNA3), ("RDNA4", sqtt._DECODE_INFO_RDNA4),
                  ("CDNA", sqtt._DECODE_INFO_CDNA)]:
    for op in sorted(di):
      cls, nib, dlo, dmask, dmul, sp = di[op]
      a(f'def di_{tag}_{op}() -> List<&2, U32>: [{nib},{dlo},{dmask % (2 ** 32)},{dmul},{sp}]')
    a(f'def di_{tag}_n() -> Nat: {len(di)}n')

  a('\n# --- THE PER-OPCODE SETS, DERIVED ' + "-" * 42)
  a('# `decode_info[opcode] = (cls, _size_nibbles, lo, mask, mul, special)` (:558-560)')
  a('# and the two SETS a reader indexes by opcode: the delta MULTIPLIER (always 4')
  a('# for CDNA, 1 for RDNA, :558) and the SPECIAL tag. Only THREE opcodes are')
  a('# non-zero and they are DIFFERENT opcodes per arch: RDNA puts 2 on 15 and 1')
  a('# on 22; CDNA puts 4 on 1. A set written as one literal for both would put a')
  a('# `+4` on a CDNA timestamp.')
  for tag in ["RDNA3", "RDNA4", "CDNA"]:
    # Bend has no `List<List<U32>>`, so the per-opcode tuples are CONCATENATED
    # and `set_text` walks them with a STRIDE of five. One flat list, one walk,
    # and the stride is the tuple width -- which is itself the fact :558 states.
    flat = []
    for op in sorted({"RDNA3": sqtt._DECODE_INFO_RDNA3, "RDNA4": sqtt._DECODE_INFO_RDNA4,
                      "CDNA": sqtt._DECODE_INFO_CDNA}[tag]):
      cls, nib, dlo, dmask, dmul, sp = {"RDNA3": sqtt._DECODE_INFO_RDNA3,
                                       "RDNA4": sqtt._DECODE_INFO_RDNA4,
                                       "CDNA": sqtt._DECODE_INFO_CDNA}[tag][op]
      flat += [nib, dlo, dmask % (2 ** 32), dmul, sp]
    a(f'def di_{tag}_flat() -> List<&2, U32>: [{",".join(str(x) for x in flat)}]')
  a('\n# --- THE PER-OPCODE SETS, DERIVED ' + "-" * 42)
  a('# `decode_info[opcode] = (cls, _size_nibbles, lo, mask, mul, special)` (:558-560)')
  a('# and `decode()` unpacks five of those six at :611. The PORT keeps the five')
  a('# and CONCATENATES them, because Bend has no `List<List<U32>>`; `set_text`')
  a('# then walks with a STRIDE of five. The stride is a def, not a literal.')
  for _tag in ["RDNA3", "RDNA4", "CDNA"]:
    _di = {"RDNA3": sqtt._DECODE_INFO_RDNA3, "RDNA4": sqtt._DECODE_INFO_RDNA4,
           "CDNA": sqtt._DECODE_INFO_CDNA}[_tag]
    _flat = []
    for _op in sorted(_di):
      _c, _nib, _lo, _mask, _mul, _sp = _di[_op]
      _flat += [_nib, _lo, _mask % (2 ** 32), _mul, _sp]
    a(f'def di_{_tag}_flat() -> List<&2, U32>: [{",".join(str(x) for x in _flat)}]')

  a('\n# --- P  THE DERIVED PROPERTIES ' + "-" * 43)
  a('# `cu` has THREE FORMULAS in one file and the difference is one bit of shift:')
  a('# WAVEEND and WAVESTART use `wgp | (sa << 3)` while their _RDNA4 twins use')
  a('# `wgp | (sa << 4)` (:266, :302, :311, :321). A lookup keyed by the SHORT name')
  a('# answers the RDNA3 answer for an RDNA4 packet and a CU id is silently wrong.')
  for nm in ["WAVEEND", "WAVEEND_RDNA4", "WAVESTART", "WAVESTART_RDNA4"]:
    a(f'def cu_{nm}(wgp: U32, sa: U32) -> U32: U32.or(wgp, U32.shln(sa, {4 if nm.endswith("RDNA4") else 3}n))')
  a('def is_marker(rt: U32, pl: U32) -> Bool: Bool.and(Bool.not(U32.is_zero(rt)), U32.is_zero(pl))')
  a('def is_config(hi_byte: U32) -> Bool: Bool.not(U32.is_zero(U32.and(hi_byte, 128)))')
  a('def wave_interest(coarse: U32) -> Bool: Bool.not(U32.is_zero(U32.and(coarse, 1)))')
  a('def terminate_all(coarse: U32) -> Bool: Bool.not(U32.is_zero(U32.and(coarse, 8)))')

  a('\n# --- E  THE OP ENUMS, BOTH DIRECTIONS ' + "-" * 37)
  a('# `add_other_simd` (:34-39) builds names by FORMULA --')
  a('# `f"OTHER_{category}_{value - start + base_cycle}"` -- and the three ranges')
  a('# have DIFFERENT base_cycles (LDS 1, FLAT 2, VMEM 1), so the generated names')
  a('# are the part a hand-written table gets wrong and they are 5+5+13 rows.')
  for nm in ["MemSrc", "AluSrc", "InstOp", "InstOpRDNA4", "InstOpCDNA"]:
    E = getattr(sqtt, nm)
    items = sorted(E._value2member_map_.items())
    a(f'def enum_{nm}() -> List<&2, Pn>: [{",".join(f'Pn{{"{E._value2member_map_[v].name}", {v}}}' for v, _ in items)}]')
    a(f'def enum_{nm}_n() -> Nat: {len(items)}n')

  a('\n# --- THE GATE ROWS ' + "-" * 54)
  a('def g_tables() -> IO(Unit):\n  do IO<Unit>:')
  for tag, tbl in TABLES:
    a(f'    srow("tbl_{tag}_n", nat_text(tbl_{tag}_n()))')
    for op in sorted(tbl):
      a(f'    srow("tbl_{tag}_fwd_{op}", name_at({op}, tbl_{tag}()))')
    for op in sorted(tbl):
      nm = tbl[op].__name__
      a(f'    srow("tbl_{tag}_rev_{nm}", u32_text(op_of("{nm}", tbl_{tag}())))')
    a(f'    srow("tbl_{tag}_order", op_order_{tag}())')
    a(f'    srow("tbl_{tag}_spec_order", spec_order_{tag}())')
  a('    # THE RDNA4 DELTA: `{**RDNA3, ...}` with eight overrides, so eight of the')
  a('    # twenty-four rows DIFFER. A table ported as a copy of RDNA3 is wrong in')
  a('    # eight places and a count cannot see it.')
  for op in sorted(sqtt.PACKET_TYPES_RDNA4):
    a0 = sqtt.PACKET_TYPES_RDNA3.get(op)
    b = sqtt.PACKET_TYPES_RDNA4[op]
    same = "True{}" if a0 is b else "False{}"
    a(f'    row("rdna4_same_{op}", {same})')
  for op in sorted(sqtt.PACKET_TYPES_RDNA4):
    a0 = sqtt.PACKET_TYPES_RDNA3.get(op)
    if a0 is not sqtt.PACKET_TYPES_RDNA4[op]:
      a(f'    srow("rdna4_diff_{op}", String.concat([name_at({op}, tbl_RDNA3()), "->", name_at({op}, tbl_RDNA4())]))')

  a('def g_fields() -> IO(Unit):\n  do IO<Unit>:')
  for _, c in CLASSES:
    nm = c.__name__
    a(f'    srow("cls_{nm}", field_order_{nm}())')
    a(f'    srow("clsfields_{nm}", fields_{nm}())')
    # `_size_nibbles` is CHECKED AS A FORMULA, not read back: `nibs_of` is
    # `(max(f.hi) + 4) // 4` (:186) and the row compares it against CPython's
    # stored `_size_nibbles`. Reading `cls_X()` back would be tautological.
    a(f'    urow("clsnib_{nm}", nibs_of(himax_{nm}()))')
    a(f'    urow("clsmask_{nm}", mask_{nm}())')
    a(f'    urow("clsdef_{nm}", dflt_{nm}())')
    a(f'    urow("clshimax_{nm}", himax_{nm}())')
    a(f'    srow("clsdelta_{nm}", hasdelta_{nm}())')
    if "delta" in c._fields and c._fields["delta"].mask > 0xFFFFFFFF:
      a(f'    urow("clsdmask_over_{nm}", dmask_over_{nm}())')
      a(f'    urow("clsdlo_{nm}", dlo_{nm}())')
      a(f'    urow("clsdmask_{nm}", dmask_{nm}())')
  a('    urow("cls_count", cls_count())')
  a('    srow("cls_names", str_list_text(CLS_NAMES()))')

  a('def g_state() -> IO(Unit):\n  do IO<Unit>:')
  for tag in ["RDNA3", "RDNA4", "CDNA"]:
    a(f'    srow("state_{tag}_n", nat_text(state_{tag}_n()))')
    a(f'    srow("state_{tag}", u32_list_text(state_{tag}()))')
    a(f'    urow("nop_last_{tag}", nop_last_{tag}())')
  a('    # THE FIRST BYTE of each table, which is the only one a reader needs to')
  a('    # tell the three architectures apart at a glance.')
  a('    urow("state_first_RDNA3", u32_at(0, state_RDNA3()))')
  a('    urow("state_first_RDNA4", u32_at(0, state_RDNA4()))')
  a('    urow("state_first_CDNA", u32_at(0, state_CDNA()))')
  a('    # and byte 0x10, where the NOP default shows up')
  for tag in ["RDNA3", "RDNA4", "CDNA"]:
    a(f'    urow("state_16_{tag}", u32_at(16, state_{tag}()))')
    a(f'    urow("state_255_{tag}", u32_at(255, state_{tag}()))')

  a('def g_decode() -> IO(Unit):\n  do IO<Unit>:')
  for tag in ["RDNA3", "RDNA4", "CDNA"]:
    a(f'    srow("di_{tag}_n", nat_text(di_{tag}_n()))')
    for op in sorted({"RDNA3": sqtt._DECODE_INFO_RDNA3, "RDNA4": sqtt._DECODE_INFO_RDNA4,
                      "CDNA": sqtt._DECODE_INFO_CDNA}[tag]):
      a(f'    srow("di_{tag}_{op}", di_text(di_{tag}_{op}()))')
  a('    # CDNA multiplies its delta by 4 and RDNA does not (:558); the DELTA')
  a('    # LO/MASK also differ per arch, and that is the whole reason the same')
  a('    # 64-bit blob decodes to different timestamps on the two.')
  for tag in ["RDNA3", "RDNA4", "CDNA"]:
    # DERIVED, NOT HARDCODED. `decode_info[opcode]` is the FIVE-tuple `decode()`
    # unpacks at :611 -- nib_count, delta_lo, delta_mask, delta_mul, special --
    # and the four SETS are folded out of the concatenated tuples with a STRIDE
    # of five. The first version answered from a literal and had `special = 2` at
    # list POSITION 15 where the real answer is `special = 1` at OPCODE 22:
    # TS_DELTA_SHORT is opcode 15 and TS_DELTA_OR_MARK is opcode 22, and a
    # hardcoded list confuses them silently. Bend has no `List<List<U32>>`, so the
    # tuples are concatenated and the stride IS the tuple width -- which is
    # itself a fact from :558-560 and a def, so a wrong width moves every row.
    a(f'    srow("di_{tag}_mul_set", set_mul(di_{tag}_flat()))')
    a(f'    srow("di_{tag}_special_set", set_sp(di_{tag}_flat()))')


  a('def g_props() -> IO(Unit):\n  do IO<Unit>:')
  # `cu`'s VALID INPUT RANGE IS ARCHITECTURE-DEPENDENT: WAVEEND.wgp is
  # bits[13:11] (THREE bits, max 7) while WAVEEND_RDNA4.wgp is bits[14:11] (FOUR,
  # max 15). Probing 8 and 15 on an RDNA3 class TRUNCATES them to 0, so the
  # generator reads each class's own width and emits only encodable probes.
  for nm in ["WAVEEND", "WAVEEND_RDNA4", "WAVESTART", "WAVESTART_RDNA4"]:
    wn = getattr(sqtt, nm)._fields["wgp"].mask.bit_length()
    for wgp in [v for v in (0, 1, 7, 8, 15) if v < (1 << wn)]:
      for sa in [0, 1]:
        a(f'    urow("cu_{nm}_{wgp}_{sa}", cu_{nm}({wgp}, {sa}))')
  for rt in [0, 1]:
    for pl in [0, 1]:
      a(f'    row("ismark_{rt}{pl}", is_marker({rt}, {pl}))')
  for raw in [0, 128, 127, 255]:
    a(f'    row("isconfig_{raw}", is_config({raw}))')
  for coarse in [0, 1, 8, 9, 255]:
    a(f'    row("waveinterest_{coarse}", wave_interest({coarse}))')
    a(f'    row("termall_{coarse}", terminate_all({coarse}))')

  a('def g_enums() -> IO(Unit):\n  do IO<Unit>:')
  for nm in ["MemSrc", "AluSrc", "InstOp", "InstOpRDNA4", "InstOpCDNA"]:
    a(f'    srow("enum_{nm}_n", nat_text(enum_{nm}_n()))')
    E = getattr(sqtt, nm)
    for v in sorted(E._value2member_map_):
      a(f'    srow("enum_{nm}_fwd_{v}", name_at({v}, enum_{nm}()))')
    for v in sorted(E._value2member_map_):
      m = E._value2member_map_[v].name
      a(f'    urow("enum_{nm}_rev_{m}", op_of("{m}", enum_{nm}()))')
  return "\n".join(L)


def main():
  body = MARK + emit()
  text = PORT.read_text()
  i = text.find(MARK)
  text = text[:i] if i >= 0 else text
  MAIN = '''def main() -> IO(Unit):
  do IO<Unit>:
    a : Unit <- g_tables()
    b : Unit <- g_fields()
    +c : Unit <- g_state()
    +d : Unit <- g_decode()
    +e : Unit <- g_props()
    +f : Unit <- g_enums()
    IO.print("sqtt-done=1")
'''
  a = text.find("def main() -> IO(Unit):")
  text = text[:a] if a >= 0 else text
  PORT.write_text(text.rstrip() + "\n\n" + body + "\n\n" + MAIN)
  print(f"wrote {PORT.relative_to(ROOT)}")


main()