#!/usr/bin/env python3
"""ASSEMBLE tinybendygrad/runtime/support/usb.bend from its source-of-truth pieces.

The file is generated in ONE pass from pieces that are themselves generated from
`tinygrad/runtime/support/usb.py` and `tinygrad/runtime/autogen/libusb.py`, so
there is exactly one place each fact is written down:

  1. `HEADER`        -- this script: scope, walls, split, gate table
  2. `usb-gen-tables.py`'s output -- the `E_*` / `F_*` / `SIZ_*` tables, read out of
                          the LIVE `autogen.libusb` module
  3. `ARITH`         -- `.agents/slop/usb-arith.bend.txt`, with the corrections the
                          differ forced applied below
  4. `usb-gen.py`'s output -- the arithmetic row sections
  5. `usb-secure.bend.txt` / `usb-sblock.bend.txt` -- the trace, the strings, the
                          packets and the transfer section
  6. `ROWS`          -- this script: the enum/struct/string/packet row sections
  7. `main`          -- this script

Run it after changing any piece:  python3 .agents/slop/usb-build.py
"""
import io
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
P = os.path.join(os.path.dirname(ROOT), "tinybendygrad/runtime/support/usb.bend")


def read(name):
    return io.open(os.path.join(HERE, name)).read()


# --------------------------------------------------------------------------
HEADER = '''# tinybendygrad/runtime/support/usb.bend -- port of tinygrad/runtime/support/usb.py
#
# ===========================================================================
# THIS FILE IS GENERATED by `.agents/slop/usb-build.py` from pieces that are
# themselves generated from `usb.py` and `autogen/libusb.py`. Edit a PIECE and
# rebuild; do not edit here.
#
# ===========================================================================
# SCOPE, AND WHY IT IS THIS SCOPE. `grep -rl "support/usb" tinybendygrad
# --include="*.bend"` is EMPTY: no committed file cites this one, so unlike every
# other unit in this wave it was not scoped for me by a citation. I therefore
# chose it, and the choice is dictated by the source. `usb.py` is 473 lines in
# three parts that share almost nothing:
#
#   :12-18   alloc_cbuffer / checked                    SEAM   ctypes
#   :20-92   USB3 -- enumeration, open, control/bulk    PORTED the ORDER + the
#                                                          argument arithmetic
#   :94-174  CustomASM24Controller -- vendor protocol   PORTED the arithmetic,
#                                                          the refusals, the strings
#   :176-202 USBMMIOInterface                           PORTED the index arithmetic
#   :204-247 the UOp placeholders and the WINDOW        PORTED the window
#   :249-309 staging rewrites                           PORTED the ORDER only
#   :311-385 host functions                             PORTED the ORDER + arithmetic
#   :386-471 lowering + bufferize                       PORTED the ORDER only
#
# WHAT IS WORTH PORTING, AND WHY. `usb.py` is the only file in tinygrad that
# talks to a device through a GENERATED ctypes binding, and
# `tinygrad/runtime/autogen/libusb.py` is that binding: 21 `enum_libusb_*` dicts and
# 22 `@c.record` structs whose `register_fields` carries a field NAME and an OFFSET
# for every member. That is a descriptor table in the exact sense this project gets
# burned on -- `ops_nv`'s audit found 33 of 219 constants wrong in a file already
# printing 590 green rows, and `ops_rdma` shipped `BNXT_VENDOR` as 5356 where the
# header says 5348. `struct_libusb_transfer`'s thirteen field names, in order, are
# what `usb_chunk` (:350-351) addresses three times by name, so a transposed pair
# is a silently wrong transfer.
#
# ===========================================================================
# THE WALLS THIS CLOSES.
#
# `ops_amd.bend` records WALL 3 ("USB3, USBIface, ops_amd.py:810-833") naming
# `USB3.list_devices`, `dma_view`, and the `0/4096/20480` controller window, with
# `TODO(p3) runtime/ops_amd.py:812  USB3.list_devices` and
# `TODO(p3) runtime/ops_amd.py:824  pci_dev.dma_view(40960, 544768)`. This file
# closes:
#
#   * WALL 3, part 1 -- `USB3.list_devices` (:30-37). The enumeration is a `Tr`
#     trace: GET_DEVICE_LIST, then per device GET_DEVICE_DESCRIPTOR, the
#     (idVendor, idProduct) == (vendor, dev) test, REF_DEVICE with the bus/address
#     label, FREE_DEVICE_LIST(devs, 1). `usb_list_match` is the SELECTION, with the
#     negative case (a descriptor whose ids do not pair) one row from its positive.
#   * WALL 3, part 3 -- the WINDOW. ops_amd could name the three `map_range` pieces
#     but could not derive them, because the offsets live here: `usb_fence`
#     0x800/0x804, `usb_cq` 0x100c/0x1010, `usb_sram` 0x5000/0x5000+2*HALF, and the
#     sizes that make them. `usb_win_*` is that derivation.
#   * AND A CORRECTION TO CARRY BACK. ops_amd's 4096 is `0x1000`, which is NOT
#     `usb_cq`'s offset: `usb_cq` is `usb_asm24[0x100c:0x1010]` = 4108..4112, and
#     0x1000 is `USB3`'s own CONTROL buffer size (:42, `alloc_cbuffer(0x1000)`). Both
#     are real, they are different numbers, and this file rows both -- so a port
#     that conflated them shows up as a disagreement rather than as a plausible
#     constant. `usb_sram_win_fits_asm24` is the row that says the SRAM pair EXACTLY
#     fills `usb_asm24`, which is ops_amd's 544768.
#   * `ops_disk.bend`'s `_might_open` ladder -- USB3's open is the same shape (a
#     walk of state that ends in a CLAIM) and `usb_open` is its trace.
#
# NOT CLOSED, DELIBERATELY. `dma_view` (ops_amd.py:824) is a `PCIDevice` method
# that lives in ops_amd.bend's own wall 2 and is not usb.py's to answer.
#
# ===========================================================================
# THE SPLIT, stated once and then obeyed. A def here EITHER builds the argument of
# ONE device call (pure; the gate checks it) OR records that call in the trace (the
# gate checks ORDER and IDENTITY). There is no third kind. Every libusb, libc and
# ctypes binding is a `Call{k, a, b, c}` entry in `Tr` and nothing else, so no
# foreign effect is declared and `--check-only` stays green in both lanes. The
# symbol names live in `SYMS()` and `vend`-style rows name each kind, so the seam is
# greppable: `grep -n libusb_ this_file` finds the C symbol as a LITERAL.
#
# NO @extern SEAMS. Same reason and same result as hcq2.bend and
# support/am/ip.bend: an `@extern` is permanently-red laws plus an import closure
# that reaches the importer's every def. A trace is not.
#
# ===========================================================================
# THE AUDIT. Every constant is generated from the live `autogen.libusb` or
# confirmed against an AST POSITION in `usb.py` -- see THE GATE.

import Base
import ../../helpers.bend as H

# ===========================================================================
# THE ROW BUILDERS. One `name=value` STRING per fact, and the whole block is
# printed with one `IO.print` joined on "\\n". That is not a style choice: a
# `do IO<Unit>:` arm and a bare expression arm have DIFFERENT types in Bend
# 2.0.34, an effectful walk over a list is a type error where a pure one is not,
# and a `do` block cannot be followed by the next `def`. Pure rows also make the
# harness's job exact: one line per fact, and `name=value` WHOLE.
# ===========================================================================

def u1(nm: String, v: U32) -> String: String.concat([nm, "=", U32.show(v)])
def b1(nm: String, v: Bool) -> String: String.concat([nm, "=", Bool.show(v)])
def s1(nm: String, v: String) -> String: String.concat([nm, "=", v])

# the six signed libusb error codes diff against CPython's `-10` and not against
# 4294967286: a U32 bit pattern is how the header stores them and a signed C `int`
# is how CPython prints them.
def show_i32(+x: U32) -> String:
  Bool.pick(String, H.i32_is_neg(x),
            String.concat(["-", U32.show(H.i32_abs(H.i32_is_neg(x), x))]), U32.show(x))

def i1(nm: String, v: U32) -> String: String.concat([nm, "=", show_i32(v)])

def lines_of(xs: List<&2, String>) -> String: String.join(xs, "\\n")

'''


def arith_block():
    t = read("usb-arith.bend.txt")
    # the corrections the differ forced, applied where they belong
    # 1. `copyout_second`'s U32 WRAP. The source is `(size - CHUNK).maximum(0)`,
    #    and for `size = CHUNK - 1` a U32 subtraction is 4294967295, so
    #    `U32.max(4294967295, 0)` is 4294967295 -- the OPPOSITE of Python's
    #    `max(-1, 0) == 0`. `usb_co_chunk_m1_second` is the row that caught it.
    t = t.replace(
        "def copyout_second(+size: U32) -> U32: U32.max(U32.sub(size, CHUNK()), 0)",
        "# THE CLAMP IS EXPLICIT BECAUSE `U32` WRAPS. Without it the copyout wire for a\n"
        "# payload that fits ONE half carries a phantom sentinel block and is a whole\n"
        "# 512 bytes too big. `usb_co_chunk_m1_second` and `_wire` are the rows.\n"
        "def copyout_second(+size: U32) -> U32:\n"
        "  Bool.pick(U32, U32.is_ge(size, CHUNK()), U32.sub(size, CHUNK()), 0)")
    # 2. the MMIO arms became separate defs
    t = t.replace('''def off_of_slice(+start: U32, +stop: U32, +el_sz: U32) -> List<&2, String>:
  [u1("off_slice_at", U32.mul(start, el_sz)),
   u1("off_slice_sz", U32.mul(U32.sub(stop, start), el_sz))]''',
'''# THE INTEGER ARM AND THE SLICE ARM ARE SEPARATE FUNCTIONS, because :180-182 is
# two arms and an off-by-one in one does not move the other.
def off_of_index_sz(+el_sz: U32) -> U32: el_sz

def off_of_slice_at(+start: U32, +el_sz: U32) -> U32: U32.mul(start, el_sz)

def off_of_slice_sz(+start: U32, +stop: U32, +el_sz: U32) -> U32:
  U32.mul(U32.sub(stop, start), el_sz)''')
    # 3. the row-group helpers are dead: every row section is a FLAT list
    import re
    # the ORPHANED TAIL of `remote_rows`: the source fragment kept its last list
    # line when the def header was cut, and the row sections are flat lists so the
    # whole helper goes.
    i = t.find('   b1(String.concat([nm, "_cmdbuf_copy"])')
    if i >= 0:
        t = t[:i] + t[t.index("DRAIN_MOD", i):]
    # 4. `TABLE_ADDR_OFF` is not a constant in usb.py -- :321 computes
    #    `16 * (k + r)` with no offset, so the address word IS the row base.
    t = t.replace("def TABLE_ADDR_OFF() -> U32: 0\n", "")
    t = t.replace("""# :321 the usb_table rows are 16 bytes apart -- two uint64 per chunk.
def TABLE_ROW_BYTES() -> U32: 16""",
"""# :321 `(16 * (k + r), addr + ...)` and `(16 * (k + r) + 8, ...)`. There is NO
# address-offset constant: the address word IS the row base and the size word is
# base + 8, so `table_addr_word` multiplies and `table_size_word` adds.
def TABLE_ROW_BYTES() -> U32: 16""")
    # 5. the hex fixtures are decimal in Bend and hex in the ROW NAMES
    for hx, dec in (("0x40", 64), ("0x30", 48), ("0x44", 68), ("0x04", 4),
                    ("0x4c", 76), ("0x00", 0), ("0x20", 32), ("0x60", 96)):
        t = t.replace(f"pcie_no_completion({hx})", f"pcie_no_completion({dec})")
    return t


def tables_block():
    r = subprocess.run([sys.executable, os.path.join(HERE, "usb-gen-tables.py")],
                       check=True, capture_output=True, text=True)
    return r.stdout


# THE ENUM ROWS, GENERATED so the twenty-one table walks and the scalar rows
# cannot drift apart. ONE `IO.print` PER SECTION and not a `do IO<Unit>:` chain,
# because a `do` block's arms must all be statements and so a block cannot be
# followed by the next `def`.
#
# `List.concat` IS THE ONLY WAY TO MIX A LIST OF ROW LISTS WITH SINGLE ROWS: it
# takes a list of LISTS (`List.concat(&2, T, [xs, ys])`), and a bare `[a, b, c]`
# literal would have to be `List<&2, String>` with `enum_rows`'s own
# `List<&2, String>` as an element -- a nested literal, which mis-parses.
CONSTS_TABLES = ["classcode", "dtype", "epdir", "eptype", "xtype", "xstatus",
                 "xflags", "err", "reqtype", "streq", "recip", "speed",
                 "supspeed", "loglevel", "logcb", "option", "isosync",
                 "isousage", "cap", "bostype", "ext20", "sscap"]
CONSTS_SCALARS = [
    ('i1', 'usb_err_interrupted_signed', 'enum_val("LIBUSB_ERROR_INTERRUPTED", E_ERR())'),
    ('i1', 'usb_err_other_signed', 'enum_val("LIBUSB_ERROR_OTHER", E_ERR())'),
    ('i1', 'usb_err_success_signed', 'enum_val("LIBUSB_SUCCESS", E_ERR())'),
    ('u1', 'usb_opt_log_level', 'enum_val("LIBUSB_OPTION_LOG_LEVEL", E_OPTION())'),
    ('u1', 'usb_opt_log_level_is_debug', 'enum_val("LIBUSB_LOG_LEVEL_DEBUG", E_LOGLEVEL())'),
    ('u1', 'usb_opt_max', 'enum_val("LIBUSB_OPTION_MAX", E_OPTION())'),
    ('s1', 'usb_classcode_6_name', 'enum_nm(6, E_CLASSCODE())'),
    ('u1', 'usb_classcode_len', 'U32.from_nat(List.length(&2, Ent, E_CLASSCODE()))'),
    ('u1', 'usb_classcode_image_walrus', 'LIBUSB_CLASS_IMAGE()'),
    ('u1', 'usb_classcode_ptp_walrus', 'LIBUSB_CLASS_PTP()'),
    ('u1', 'usb_classcode_image_in_dict',
     'Bool.to_u32(U32.is_ne(enum_val("LIBUSB_CLASS_IMAGE", E_CLASSCODE()), NOT_FOUND()))'),
    ('s1', 'usb_enumnm_absent_4242', 'enum_nm(4242, E_CLASSCODE())'),
    ('s1', 'usb_enumnm_absent_neg1', 'enum_nm(4294967295, E_ERR())'),
    ('u1', 'usb_enumval_notfound_is_io', 'enum_val("LIBUSB_ENUM_NONE", E_ERR())'),
    ('s1', 'usb_synth_n_10', 'enum_nm(10, E_SYNTH())'),
    ('s1', 'usb_synth_n_11', 'enum_nm(11, E_SYNTH())'),
    ('s1', 'usb_synth_n_13', 'enum_nm(13, E_SYNTH())'),
    ('u1', 'usb_synth_v_alpha', 'enum_val("SYNTH_ALPHA", E_SYNTH())'),
    ('u1', 'usb_synth_v_gamma', 'enum_val("SYNTH_GAMMA", E_SYNTH())'),
    ('u1', 'usb_synth_v_beta', 'enum_val("SYNTH_BETA", E_SYNTH())'),
    ('u1', 'usb_synth_v_absent', 'enum_val("SYNTH_NOPE", E_SYNTH())'),
]


def consts_block():
    items = [f'enum_rows("{t}", E_{t.upper()}())' for t in CONSTS_TABLES]
    items += [f'[{b}("{n}", {e})]' for b, n, e in CONSTS_SCALARS]
    body = ",\n     ".join(items)
    return ("# ===========================================================================\n"
            "# THE ENUM ROWS. Twenty-one table walks, BOTH directions each, then the\n"
            "# scalar rows: the signed negatives, the walrus globals, and the two\n"
            "# negative cases (`usb_enumval_notfound_is_io` answers with the sentinel,\n"
            "# `usb_synth_v_absent` likewise) beside their positives.\n"
            "# ===========================================================================\n"
            "def t_consts() -> IO(Unit):\n"
            "  IO.print(lines_of(\n"
            "    List.concat(&2, String, [\n     " + body + "])))\n\n\n")


ROWS = '''# THE LAST-WINS FIXTURE. The generated dicts are LAST-wins -- a repeated key is
# overwritten by the later literal -- and both folds have to agree with that. But
# NONE of the twenty-one live tables can exercise the rule: 6 is the only value that
# ever repeats, and `LIBUSB_CLASS_IMAGE` is NOT a table entry (it is a walrus
# binding the dict overwrote), so after that correction every value and every name
# in every table is UNIQUE. `M36` and `M37` measured 0 rows moved, and a 0 is a
# REQUEST FOR A FIXTURE, not a coverage claim. So the rule gets a table BUILT TO
# EXERCISE IT: value 10 is named ALPHA then GAMMA, the name SYNTH_BETA is carried by
# values 11 and 12, and the `usb_synth_*` rows are the only fixtures in the file
# that see either fold's tie-break.
def E_SYNTH() -> List<&2, Ent>:
  [Ent{10, "SYNTH_ALPHA"}, Ent{11, "SYNTH_BETA"}, Ent{10, "SYNTH_GAMMA"},
   Ent{12, "SYNTH_BETA"}, Ent{13, "SYNTH_DELTA"}]

# THE TWO WALRUS GLOBALS at 6, and they are constants that are NOT table entries.
def LIBUSB_CLASS_IMAGE() -> U32: 6
def LIBUSB_CLASS_PTP() -> U32: 6

# ===========================================================================
# THE STRUCT ROWS. The field lists are printed as the ROUND TRIP of the literal
# through `String.split` and back, so a dropped field, a transposed pair or a split
# that eats the separator all change the line -- where a row that printed the
# literal would be a tautology. `Fld.find` / `Fld.at` are the by-NAME lookups
# `usb_chunk` and `list_devices` actually perform, and they are rows too: a lookup
# answering the wrong ordinal is a wrong transfer, and an ordinal COUNT is not a
# gate.
# ===========================================================================
def t_structs() -> IO(Unit):
  IO.print(lines_of(
    [s1("usb_fld_transfer", flds(F_TRANSFER())),
     s1("usb_fld_device_descriptor", flds(F_DEVICE_DESCRIPTOR())),
     s1("usb_fld_endpoint_descriptor", flds(F_ENDPOINT_DESCRIPTOR())),
     s1("usb_fld_interface_descriptor", flds(F_INTERFACE_DESCRIPTOR())),
     s1("usb_fld_config_descriptor", flds(F_CONFIG_DESCRIPTOR())),
     s1("usb_fld_interface", flds(F_INTERFACE())),
     s1("usb_fld_interface_association_descriptor", flds(F_INTERFACE_ASSOCIATION_DESCRIPTOR())),
     s1("usb_fld_interface_association_descriptor_array",
        flds(F_INTERFACE_ASSOCIATION_DESCRIPTOR_ARRAY())),
     s1("usb_fld_control_setup", flds(F_CONTROL_SETUP())),
     s1("usb_fld_iso_packet_descriptor", flds(F_ISO_PACKET_DESCRIPTOR())),
     s1("usb_fld_bos_descriptor", flds(F_BOS_DESCRIPTOR())),
     s1("usb_fld_bos_dev_capability_descriptor", flds(F_BOS_DEV_CAPABILITY_DESCRIPTOR())),
     s1("usb_fld_ss_usb_device_capability_descriptor",
        flds(F_SS_USB_DEVICE_CAPABILITY_DESCRIPTOR())),
     s1("usb_fld_ss_endpoint_companion_descriptor", flds(F_SS_ENDPOINT_COMPANION_DESCRIPTOR())),
     s1("usb_fld_usb_2_0_extension_descriptor", flds(F_USB_2_0_EXTENSION_DESCRIPTOR())),
     s1("usb_fld_container_id_descriptor", flds(F_CONTAINER_ID_DESCRIPTOR())),
     s1("usb_fld_platform_descriptor", flds(F_PLATFORM_DESCRIPTOR())),
     s1("usb_fld_init_option", flds(F_INIT_OPTION())),
     s1("usb_fld_init_option_value", flds(F_INIT_OPTION_VALUE())),
     s1("usb_fld_pollfd", flds(F_POLLFD())),
     s1("usb_fld_version", flds(F_VERSION())),
     s1("usb_fld_timeval", flds(F_TIMEVAL())),
     u1("usb_fld_transfer_status_ix", Fld.find("status", F_TRANSFER())),
     u1("usb_fld_transfer_length_ix", Fld.find("length", F_TRANSFER())),
     u1("usb_fld_transfer_buffer_ix", Fld.find("buffer", F_TRANSFER())),
     u1("usb_fld_transfer_endpoint_ix", Fld.find("endpoint", F_TRANSFER())),
     u1("usb_fld_transfer_type_ix", Fld.find("type", F_TRANSFER())),
     u1("usb_fld_transfer_timeout_ix", Fld.find("timeout", F_TRANSFER())),
     u1("usb_fld_transfer_actual_length_ix", Fld.find("actual_length", F_TRANSFER())),
     u1("usb_fld_transfer_nosuch_ix", Fld.find("nosuchfield", F_TRANSFER())),
     u1("usb_fld_device_descriptor_idVendor_ix", Fld.find("idVendor", F_DEVICE_DESCRIPTOR())),
     u1("usb_fld_device_descriptor_idProduct_ix", Fld.find("idProduct", F_DEVICE_DESCRIPTOR())),
     u1("usb_fld_device_descriptor_iProduct_ix", Fld.find("iProduct", F_DEVICE_DESCRIPTOR())),
     u1("usb_fld_device_descriptor_iManufacturer_ix",
        Fld.find("iManufacturer", F_DEVICE_DESCRIPTOR())),
     s1("usb_fld_transfer_at5", Fld.at(5, F_TRANSFER())),
     s1("usb_fld_transfer_at11", Fld.at(11, F_TRANSFER())),
     s1("usb_fld_transfer_at99", Fld.at(99, F_TRANSFER())),
     u1("usb_siz_transfer", SIZ_TRANSFER()),
     u1("usb_siz_device_descriptor", SIZ_DEVICE_DESCRIPTOR()),
     u1("usb_siz_endpoint_descriptor", SIZ_ENDPOINT_DESCRIPTOR()),
     u1("usb_siz_interface_descriptor", SIZ_INTERFACE_DESCRIPTOR()),
     u1("usb_siz_config_descriptor", SIZ_CONFIG_DESCRIPTOR()),
     u1("usb_siz_interface", SIZ_INTERFACE()),
     u1("usb_siz_interface_association_descriptor", SIZ_INTERFACE_ASSOCIATION_DESCRIPTOR()),
     u1("usb_siz_interface_association_descriptor_array",
        SIZ_INTERFACE_ASSOCIATION_DESCRIPTOR_ARRAY()),
     u1("usb_siz_control_setup", SIZ_CONTROL_SETUP()),
     u1("usb_siz_iso_packet_descriptor", SIZ_ISO_PACKET_DESCRIPTOR()),
     u1("usb_siz_bos_descriptor", SIZ_BOS_DESCRIPTOR()),
     u1("usb_siz_bos_dev_capability_descriptor", SIZ_BOS_DEV_CAPABILITY_DESCRIPTOR()),
     u1("usb_siz_ss_usb_device_capability_descriptor",
        SIZ_SS_USB_DEVICE_CAPABILITY_DESCRIPTOR()),
     u1("usb_siz_ss_endpoint_companion_descriptor", SIZ_SS_ENDPOINT_COMPANION_DESCRIPTOR()),
     u1("usb_siz_usb_2_0_extension_descriptor", SIZ_USB_2_0_EXTENSION_DESCRIPTOR()),
     u1("usb_siz_container_id_descriptor", SIZ_CONTAINER_ID_DESCRIPTOR()),
     u1("usb_siz_platform_descriptor", SIZ_PLATFORM_DESCRIPTOR()),
     u1("usb_siz_init_option", SIZ_INIT_OPTION()),
     u1("usb_siz_init_option_value", SIZ_INIT_OPTION_VALUE()),
     u1("usb_siz_pollfd", SIZ_POLLFD()),
     u1("usb_siz_version", SIZ_VERSION()),
     u1("usb_siz_timeval", SIZ_TIMEVAL())]))

'''

TAIL = '''# ===========================================================================
# THE FFI SEAM SPLIT. Every `libusb`/`libc`/`ctypes` binding in `usb.py` is one
# `Call{k, a, b, c}` in `Tr` and nothing else. The table below is the whole
# inventory: what is a trace tag, and the `usb.py` line that becomes it. An
# `@extern` seam would have to be exactly these calls and nothing else, and
# replacing `Tr.emit` is the entire change.
#
# | call | usb.py | checked? | what `a`, `b`, `c` carry |
# | --- | --- | --- | --- |
# | `libusb_init` | :24 | yes | all zero: the argument is a `POINTER(context)` |
# | `libusb_set_option` | :25 | yes | `LIBUSB_OPTION_LOG_LEVEL` (0) and level 4 |
# | `libusb_get_device_list` | :32 | yes | all zero: the list is the SEAM's |
# | `libusb_get_device_descriptor` | :33, :49 | yes | all zero: the struct is the SEAM's |
# | `libusb_ref_device` | :35 | NO | all zero: a pointer in, a pointer out |
# | `libusb_get_bus_number` | :35 | yes | the bus number -- the label's first field |
# | `libusb_get_device_address` | :35 | yes | the device address -- the label's second |
# | `libusb_free_device_list` | :36 | NO | `1`, `usb_unref_devices` |
# | `libusb_open` | :44 | yes | all zero: the handle is the SEAM's |
# | `libusb_get_device` | :49 | NO | all zero: a pointer in, a pointer out |
# | `libusb_get_string_descriptor_ascii` | :50 | yes | 256, `_buf` |
# | `libusb_kernel_driver_active` | :55 | yes | 0, the interface |
# | `libusb_detach_kernel_driver` | :56 | yes | 0, the interface |
# | `libusb_reset_device` | :57 | yes | all zero |
# | `libusb_set_configuration` | :60 | yes | 1, the configuration |
# | `libusb_claim_interface` | :61 | yes | 0, the interface |
# | `libusb_set_interface_alt_setting` | :62 | yes | 0, 0: interface and alt-setting |
# | `libusb_control_transfer` | :67, :71 | yes | rtype 0x40/0xC0, request, n |
# | `libusb_bulk_transfer` | :78, :83 | yes | 0x02/0x81, n |
# | `libusb_alloc_transfer` | :457 | yes | all zero: `libusb_alloc_transfer(0)` |
# | `libusb_handle_events_timeout` | :326 | yes | all zero: the timeout is 0 |
# | `libusb_submit_transfer` | :352 | yes | all zero: the xfer is the SEAM's |
# | `memcpy` | :343 | NO | the byte count |
# | `libusb_strerror` | :16 | NO | NO EMIT SITE: `checked` calls it inside the |
# |   |   |   | exception it is raising, and a trace that has refused records |
# |   |   |   | nothing further. `usb_inventory_strerror` names it. |
#
# `checked` IS A REFUSAL SITE and `usb.py`'s OWN `assert` is not a call at all, so
# `have_product` is a parameter of `usb_open` and the refusal is modelled at the
# string read that precedes it. Those two facts are what `usb_open_refuse_4_product`
# measures.
# ===========================================================================
# WHAT IS NOT IN THIS FILE, NAMED BY ITS LINE. Each is an FFI seam or an
# outside-the-arena owner, and each is a TODO(p3) with the line that owns it. An
# honest "this is a seam" is a complete result; what is NOT acceptable is a row that
# pretends to cover one. The full list of `TODO(p3)` lines is at the end of this
# file.
# ===========================================================================

# ===========================================================================
# THE GATE. Five scripts, all in `.agents/slop/`, and every number below is one of
# their outputs rather than an estimate.
#
# | script | what it does |
# | --- | --- |
# | `usb-diff.py` | runs the INTERPRETED lane and diffs WHOLE `name=value` lines against four CPython oracles |
# | `usb-constsweep.py` | evaluates every `def NAME() -> U32` and compares it against an AST POSITION in `usb.py`, `ctypes.sizeof`, or `struct.calcsize` |
# | `usb-handmap.py` | the position map itself; `--list` prints every candidate so a position is auditable without running anything |
# | `usb-symmap.py` | the `K_*` -> `SYMS()` bijection, and that every name is a real libusb export |
# | `usb-dead.py` | a def nothing calls is invisible to every other check |
# | `usb-mutate.py` | 45 mutations, one edit each, diffing whole `name=value` lines |
# | `usb-build.py` | assembles THIS FILE from its pieces |
#
# EVERY EXPECTATION IS GENERATED BY CALLING CPYTHON. The enum and struct tables are
# read out of the live `autogen.libusb`, the arithmetic from the same expressions
# `usb.py` writes, the trace ORDERS from `usb.py`'s own AST, and the packet rows from
# `struct.calcsize` and `struct.pack`. Not one is transcribed by eye, because
# agent-core.md records five units where a hand-typed expectation was wrong
# (cstyle 17 of 215, ops_nv 33 of 219, ops_rdma `BNXT_VENDOR` 5356 vs 5348) and one
# where the PORT and the ORACLE were wrong the SAME WAY (`nv_query_litter`), so
# their agreement meant nothing.
#
# THE CONSTANTS THAT WERE WRONG. Two, both hand-typed, both caught by the differ:
#   * `SENTINEL_MAGIC` was 1363148800. 0x51000000 is 1358954496.
#   * `FAST_P1_MASK` was 215. 0b11011111 is 223.
# And the PORT BUGS the gate caught, which no constant audit would have:
#   * `copyout_second` was `U32.max(U32.sub(size, CHUNK()), 0)`, which WRAPS.
#   * `sym_at` was off by one, so every order row named the symbol AFTER the one
#     it meant. `M31` is the mutation and it moves 17 rows.
#   * `usb_chunk` had `usb_drained` (:347) AFTER `usb_ctrl` (:348); the CPython
#     order row, built from the call SITES, is what caught it.
#   * `usb_enum.device` read the descriptor AFTER the ref/bus/address triple, and
#     the SEEN-SET version of `enum_rows` emitted zero `_n_` rows.
# ===========================================================================

# ===========================================================================
# THE ENTRY POINT. One line per row section, in the order the sections read.
# ===========================================================================

def main() -> IO(Unit):
  do IO<Unit>:
    a : Unit <- t_consts()
    b : Unit <- t_structs()
    c : Unit <- t_window()
    d : Unit <- t_wire()
    e : Unit <- t_sentinel()
    f : Unit <- t_split()
    g : Unit <- t_byteen()
    h : Unit <- t_pcie_read()
    i : Unit <- t_fastpath()
    j : Unit <- t_cfg()
    k : Unit <- t_xdata()
    l : Unit <- t_scsi()
    m : Unit <- t_stream()
    n : Unit <- t_copyout()
    o : Unit <- t_chunk()
    p : Unit <- t_table()
    q : Unit <- t_mmio()
    r : Unit <- t_drained()
    s : Unit <- t_remote()
    t : Unit <- t_trace()
    u : Unit <- t_select()
    v : Unit <- t_refuse()
    w : Unit <- t_strings()
    x : Unit <- t_packets()
    y : Unit <- t_f0()
    z : Unit <- t_xfer()
    IO.print("usb-done=1")
'''


def main():
    # ORDER IS A DEPENDENCY ORDER AND NOT A TIDYING ORDER: Bend refuses a def
    # USED before it is WRITTEN, so `usb-secure`'s trace needs the request types
    # and endpoint bits that live in `usb-sblock`, and `usb-tracerows` needs the
    # `K_*` and `SYMS()` that live in `usb-secure`.
    parts = [HEADER, tables_block(), arith_block(),
             read("usb-arith-rows.bend.txt"),
             read("usb-sblock.bend.txt"), read("usb-secure.bend.txt"),
             read("usb-tracerows.bend.txt"), ROWS, consts_block(), TAIL]
    out = "\n".join(parts)
    io.open(P, "w").write(out)
    print("wrote", len(out.split(chr(10))), "lines")


if __name__ == "__main__":
    main()