#!/usr/bin/env python3
"""REGENERATE the `E_*` / `F_*` / `SIZ_*` tables of usb.bend FROM CPYTHON.

The tables are the header's own data, so they are GENERATED by reading
`tinygrad.runtime.autogen.libusb` -- `enum_libusb_*` dicts, the `@c.record`
classes' `__annotations__` in declaration order, and `ctypes.sizeof` -- rather
than transcribed. That is the whole point of `usb-constsweep.py`: two
hand-typed constants in this file were wrong and both were caught by comparing
against the live module.
"""
import ctypes
import io
import os
import sys

sys.path.insert(0, os.getcwd())
from tinygrad.runtime.autogen import libusb  # noqa: E402

P = "tinybendygrad/runtime/support/usb.bend"
OUT = []

TAGS = [("classcode", "enum_libusb_class_code"), ("dtype", "enum_libusb_descriptor_type"),
        ("epdir", "enum_libusb_endpoint_direction"),
        ("eptype", "enum_libusb_endpoint_transfer_type"), ("xtype", "enum_libusb_transfer_type"),
        ("xstatus", "enum_libusb_transfer_status"), ("xflags", "enum_libusb_transfer_flags"),
        ("err", "enum_libusb_error"), ("reqtype", "enum_libusb_request_type"),
        ("streq", "enum_libusb_standard_request"), ("recip", "enum_libusb_request_recipient"),
        ("speed", "enum_libusb_speed"), ("supspeed", "enum_libusb_supported_speed"),
        ("loglevel", "enum_libusb_log_level"), ("logcb", "enum_libusb_log_cb_mode"),
        ("option", "enum_libusb_option"), ("isosync", "enum_libusb_iso_sync_type"),
        ("isousage", "enum_libusb_iso_usage_type"), ("cap", "enum_libusb_capability"),
        ("bostype", "enum_libusb_bos_type"),
        ("ext20", "enum_libusb_usb_2_0_extension_attributes"),
        ("sscap", "enum_libusb_ss_usb_device_capability_attributes")]

OUT.append('''type Ent is Data:
  Ent{val: U32, name: String}

# ===========================================================================
# THE libusb CONSTANT TABLES, GENERATED FROM `autogen.libusb` -- see
# `usb-gen-tables.py`. Both directions come from ONE list and two folds, because
# that is how the header has them: `enum_libusb_class_code` is a `dict[int, str]`,
# so `enum_nm` is the dict and `enum_val` is its inverse. Keeping them as ONE list
# and two folds is what makes both directions testable over the same data -- a
# table written twice is two tables and one of them is wrong.
#
# `val` is the C bit pattern in a U32, so the six negative libusb error codes are
# stored two's-complement and PRINTED signed by `show_i32`: `usb.py` compares
# against `LIBUSB_ERROR_INTERRUPTED` and the gate has to diff CPython's `-10` and
# not 4294967286.
# ===========================================================================''')

for tag, attr in TAGS:
    tbl = getattr(libusb, attr)
    note = ""
    if tag == "classcode":
        note = ("\n# `enum_libusb_class_code` binds LIBUSB_CLASS_IMAGE to 6 and then\n"
                "# LIBUSB_CLASS_PTP to 6, so the TABLE has one name for 6 and the walrus\n"
                "# leaves `LIBUSB_CLASS_IMAGE` a module global that is not a dict value\n"
                "# at all. The constant, the table length and the membership test are\n"
                "# three separate rows because they are three separate facts.")
    OUT.append(f"# `autogen/libusb.py`'s `{attr}`{note}")
    OUT.append(f"def E_{tag.upper()}() -> List<&2, Ent>:")
    # the SIX NEGATIVE ERROR CODES are stored two's-complement, because Bend has no
    # signed integer literal and `usb.py` compares against -10.
    items = [f'   Ent{{{v & 0xFFFFFFFF}, "{n}"}}' for v, n in tbl.items()]
    OUT.append("  [" + (",\n    ".join(items)) + "]")
    OUT.append("")

OUT.append('''# ===========================================================================
# THE TWO FOLDS, ONE TABLE EACH. `enum_nm` is the dict and `enum_val` is its
# inverse, so both directions come off ONE walk over the same data.
# ===========================================================================

# value -> name, LAST match wins: `enum_libusb_class_code` gives 6 TWO names and
# the generated dict keeps the LAST, so a first-wins fold is wrong and the differ
# says so on `usb_classcode_6_name`.
def enum_nm.go(n: Nat, +v: U32, es: List<&2, Ent>, hit: String) -> String:
  match n:
    case 0n: hit
    case 1n+m:
      match es:
        case Nil{}: hit
        case Ent{vv, nn} <> t: enum_nm.go(m, v, t, Bool.pick(String, U32.is_eq(vv, v), nn, hit))

def enum_nm(+v: U32, +es: List<&2, Ent>) -> String:
  enum_nm.go(List.length(&2, Ent, es), v, es, "LIBUSB_ENUM_NONE")

# name -> value, LAST match wins for the same reason. A NAME no entry has is
# `NOT_FOUND` and never 0: 0 is LIBUSB_SUCCESS's and LIBUSB_REQUEST_TYPE_STANDARD's
# and LIBUSB_TRANSFER_COMPLETED's value, so a silent 0 would be indistinguishable
# from a real constant. 4294967295 is LIBUSB_ERROR_IO's bit pattern, and
# `usb_enumval_absent_not_found` is the row that says which one it is.
def enum_val.go(n: Nat, +nm: String, es: List<&2, Ent>, hit: U32) -> U32:
  match n:
    case 0n: hit
    case 1n+m:
      match es:
        case Nil{}: hit
        case Ent{vv, nn} <> t: enum_val.go(m, nm, t, Bool.pick(U32, String.eq(nn, nm), vv, hit))

# PORT-INTERNAL, and the only constant in this file with no line in `usb.py`. It
# is 0xFFFFFFFF so that it cannot be confused with a real `enum_libusb_*` value:
# the negative error codes are the only ones in that range and the largest is -1,
# which is LIBUSB_ERROR_IO. `usb_enumval_absent_not_found` is the row.
def NOT_FOUND() -> U32: 4294967295

def enum_val(+nm: String, +es: List<&2, Ent>) -> U32:
  enum_val.go(List.length(&2, Ent, es), nm, es, NOT_FOUND())

# ONE entry, BOTH rows, from ONE walk.
#
# TWO LISTS, ON PURPOSE. `enum_rows.go` MATCHES `r` (the walk) and folds over `es`
# (the whole table), so `es` is never matched and so is never consumed -- the
# version that matched the table and kept SEEN SETS instead handed each `+` slot to
# `List.contains`, which MOVES it, and the cons after it built an empty list. That
# is the whole bug the differ found: zero `_n_` rows and every seen set already
# full.
#
# THE CONS ORDER IS THE HEADER'S OWN: the walk goes FORWARD and each entry conses
# its `_n_` row before its `_v_` row, so the accumulator is already in order and
# needs no `List.reverse` anywhere. Walking the REVERSED table instead does not
# help -- a cons fold over a reversed walk builds the accumulator backwards, and
# every `usb_*_n_`/`_v_` pair is a whole-value string in the wrong sequence.
def enum_rows.go(+tag: String, +es: List<&2, Ent>, r: List<&2, Ent>,
                 +acc: List<&2, String>) -> List<&2, String>:
  match r:
    case Nil{}: acc
    case Ent{v, nm} <> t:
      +vv = v
      +nn = nm
      s1(String.concat(["usb_", tag, "_n_", nn]), enum_nm(vv, es))
        <> (i1(String.concat(["usb_", tag, "_v_", nn]), enum_val(nn, es)) <> enum_rows.go(tag, es, t, acc))

def enum_rows(+tag: String, +es: List<&2, Ent>) -> List<&2, String>:
  enum_rows.go(tag, es, es, Nil{})

''')

OUT.append('''# ===========================================================================
# THE STRUCT FIELD LISTS, BY NAME AND IN ORDER. `usb.py` addresses
# `struct_libusb_transfer` THREE TIMES BY NAME (:350-351 `field("status")`,
# `field("length")`, `field("buffer")`) and reads
# `struct_libusb_device_descriptor` FOUR times (:34 `idVendor`/`idProduct`, :50
# `iProduct`), and `usb_xfer` (:218) sizes its placeholder with
# `ctypes.sizeof(struct_libusb_transfer)`. So the field lists are not background:
# they are the arguments.
#
# Each struct is ONE space-separated String in DECLARATION ORDER, which is what
# `__annotations__` preserves and what `register_fields` writes out in the same
# order. A String and not a list of records because a list of records is N
# constructions whose ORDER a diff of `name=value` lines cannot see, while
# `String.concat` drops a literal silently -- so the gate diffs these Strings
# WHOLE against the header's field names, through `String.split` and back.
# ===========================================================================

type Fld is Data:
  Fld{ix: U32, name: String}

def Fld.name(x: Fld) -> String:
  match x:
    case Fld{ix, name}: name

# THE ORDINAL OF A FIELD NAME IN A LIST, and `NOT_FOUND` when absent. :350's
# `field("status")` is this lookup, and its index is the byte offset divisor in
# `usb_chunk` (:344 `end // 4 - 1`), so a lookup answering the wrong ordinal is a
# wrong transfer.
def Fld.find(+nm: String, fs: List<&2, Fld>) -> U32:
  match fs:
    case Nil{}: NOT_FOUND()
    case Fld{ix, fn} <> t: Bool.pick(U32, String.eq(fn, nm), ix, Fld.find(nm, t))

def Fld.at(+ix: U32, fs: List<&2, Fld>) -> String:
  match fs:
    case Nil{}: ""
    case Fld{fx, fn} <> t: Bool.pick(String, U32.is_eq(fx, ix), fn, Fld.at(ix, t))

# THE LIST IS THE FIRST ARGUMENT because a decreasing self-call is read left to
# right, each argument passing unchanged until one shrinks -- so the argument that
# shrinks has to come first, and the counter comes second.
def fields.go(rest: List<&2, String>, +ix: Nat) -> List<&2, Fld>:
  match rest:
    case Nil{}: Nil{}
    case head <> t: List.append(&2, Fld, [Fld{U32.from_nat(ix), head}], fields.go(t, Nat.add(ix, 1n)))

def fields(s: String) -> List<&2, Fld>: fields.go(String.split(s, Char.from_u32(32)), 0n)

# THE ROUND TRIP, and that is the point: a row that printed the literal String
# would be a tautology, so the gate diffs what `String.split` and `fields` actually
# produced. A dropped field, a transposed pair or a split that eats the separator
# all change this line.
def flds.go(fs: List<&2, Fld>) -> List<&2, String>:
  match fs:
    case Nil{}: Nil{}
    case f <> t: Fld.name(f) <> flds.go(t)

def flds(fs: List<&2, Fld>) -> String: String.join(flds.go(fs), " ")''')

STRUCTS = [("TRANSFER", "struct_libusb_transfer"), ("DEVICE_DESCRIPTOR", "struct_libusb_device_descriptor"),
           ("ENDPOINT_DESCRIPTOR", "struct_libusb_endpoint_descriptor"),
           ("INTERFACE_DESCRIPTOR", "struct_libusb_interface_descriptor"),
           ("CONFIG_DESCRIPTOR", "struct_libusb_config_descriptor"), ("INTERFACE", "struct_libusb_interface"),
           ("INTERFACE_ASSOCIATION_DESCRIPTOR", "struct_libusb_interface_association_descriptor"),
           ("INTERFACE_ASSOCIATION_DESCRIPTOR_ARRAY", "struct_libusb_interface_association_descriptor_array"),
           ("CONTROL_SETUP", "struct_libusb_control_setup"),
           ("ISO_PACKET_DESCRIPTOR", "struct_libusb_iso_packet_descriptor"),
           ("BOS_DESCRIPTOR", "struct_libusb_bos_descriptor"),
           ("BOS_DEV_CAPABILITY_DESCRIPTOR", "struct_libusb_bos_dev_capability_descriptor"),
           ("SS_USB_DEVICE_CAPABILITY_DESCRIPTOR", "struct_libusb_ss_usb_device_capability_descriptor"),
           ("SS_ENDPOINT_COMPANION_DESCRIPTOR", "struct_libusb_ss_endpoint_companion_descriptor"),
           ("USB_2_0_EXTENSION_DESCRIPTOR", "struct_libusb_usb_2_0_extension_descriptor"),
           ("CONTAINER_ID_DESCRIPTOR", "struct_libusb_container_id_descriptor"),
           ("PLATFORM_DESCRIPTOR", "struct_libusb_platform_descriptor"),
           ("INIT_OPTION", "struct_libusb_init_option"),
           ("INIT_OPTION_VALUE", "struct_libusb_init_option_value"),
           ("POLLFD", "struct_libusb_pollfd"), ("VERSION", "struct_libusb_version"),
           ("TIMEVAL", "struct_timeval")]

OUT.append("")
for name, sname in STRUCTS:
    names = list(getattr(libusb, sname).__annotations__.keys())
    sz = ctypes.sizeof(getattr(libusb, sname))
    OUT.append(f"def F_{name}() -> List<&2, Fld>: fields(\"{' '.join(names)}\")")
OUT.append("")

OUT.append('''# ===========================================================================
# STRUCT SIZES. `ctypes.sizeof` is the SEAM's value, so these are constants read
# out of the header rather than derived -- and `usb_xfer` (:218) makes one of them
# the ELEMENT COUNT of a UOp placeholder, which makes it arithmetic and not a
# comment. `usb-constsweep.py` confirms every one of them by calling
# `ctypes.sizeof`.
# ===========================================================================''')
for name, sname in STRUCTS:
    sz = ctypes.sizeof(getattr(libusb, sname))
    OUT.append(f"def SIZ_{name}() -> U32: {sz}")

OUT.append('''# THE FOUR OPAQUE STRUCTS -- `struct_libusb_context`, `struct_libusb_device`,
# `struct_libusb_device_handle` and `dll` -- have `sizeof` 0 in the generated
# binding, and that is WHY `usb.py` treats them as POINTERS (:32,:39,:44,:49).''')

sys.stdout.write("\n".join(OUT) + "\n")