#!/usr/bin/env python3
"""THE HAND MAP for `runtime/ops_webgpu.bend`'s 67 numeric constant defs.

WHY A FILE AND NOT A FLAG. `.agents/slop/const-audit.py` matches by NAME, and on
this file the port RENAMES the autogen enum members (`USAGE_MAP_READ` against
`WGPUBufferUsage_MapRead`, `MAP_MAPPED` against `WGPUBufferMapState_Mapped`) and
`CALL_*`/`OBJ_*`/`SYNC_*` are PORT-INTERNAL tag spaces with no Python counterpart
at all. A name-matching audit reaches none of them.

WHAT THIS IS. Every constant NAME mapped to the AUTHORITY that answers for it,
with every value GENERATED BY CALLING CPython:

  * `hdr` -- `getattr` on `tinygrad.runtime.autogen.webgpu`, the generated ctypes
             module. THE authority for 19 of the 67.
  * `src` -- an int literal CPython's own `ast` extracts from `ops_webgpu.py` at
             a NAMED line, selected by position or by a regex. A line carrying
             several ints must say which one.
  * `emit` -- NOT a value. `CALL_*` is a tag space; its authority is the
             NAME -> (python line, symbol) map, checked here and again by
             `wg_emit_map.py`.
  * `live` -- measured on this machine / off a real dict.
  * `dead` -- the def exists and NOTHING reads it.

Run: .venv/bin/python .agents/slop/wg_constmap.py [port.bend]
"""
import ast, importlib.util, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OPS = ROOT / "tinygrad/runtime/ops_webgpu.py"
PORT = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "tinybendygrad/runtime/ops_webgpu.bend"
SRC = OPS.read_text()
SLINES = SRC.splitlines()
TREE = ast.parse(SRC)
BEND_CONST = re.compile(r"^def\s+([A-Za-z_][A-Za-z_0-9]*)\(\)\s*->\s*\w+:\s*(-?\d+)\s*$")
WGPU = None

_IDX = {}


def _ints(n):
  """every int literal SPANNING line n, in SOURCE order, by CPython's AST. A
  number inside a STRING is not a number, so this is the AST and not a regex."""
  if not _IDX:
    out = {}
    for x in ast.walk(TREE):
      if isinstance(x, ast.Constant) and isinstance(x.value, int) and not isinstance(x.value, bool):
        for ln in range(x.lineno, (x.end_lineno or x.lineno) + 1):
          out.setdefault(ln, []).append(x)
    _IDX.update({ln: sorted(v, key=lambda x: (x.lineno, x.col_offset)) for ln, v in out.items()})
  return _IDX.get(n, [])


def src(n, at=None, rx=None):
  if rx is not None:
    m = re.search(rx, SLINES[n - 1])
    assert m, f"ops_webgpu.py:{n} does not match {rx!r}: {SLINES[n - 1].strip()!r}"
    return int(m.group(1))
  vals = [x.value for x in _ints(n)]
  if at is None:
    assert len(vals) == 1, f"ops_webgpu.py:{n} has {vals}, not one int"
    return vals[0]
  return vals[at]


def hdr(name):
  """the authority is an attribute of the REAL generated ctypes module."""
  global WGPU
  if WGPU is None:
    import tinygrad.runtime.autogen.webgpu as m
    WGPU = m
  return getattr(WGPU, name)


def emit(*sites):
  """NOT a value. The authority for a CALL_* tag is that this python line really
  names that wgpu symbol -- the NAME -> meaning map, which is the part that can be
  wrong the way `CLASS_BLACKWELL_COMPUTE_A` was in ops_nv. Several sites are
  accepted because the `synchronous` WRAPPER at :45-50 rebinds six wgpu entry
  points to Python names (`BufferMapAsync` IS `wgpuBufferMapAsync2`), so a tag's
  symbol appears on the wrapper's definition line and its use elsewhere. Both are
  asserted where both exist.
  """
  for n, needle in sites:
    if needle in SLINES[n - 1]: return n
  raise AssertionError(f"no site among {sites} names its symbol: "
                       + "; ".join(f":{n}={SLINES[n - 1].strip()[:60]!r}" for n, _ in sites))


def _wrapper(n):
  """the `synchronous(...)` DECORATOR call inside an assignment, or None.
  `X = synchronous(enum, True)(webgpu.f)` is a Call whose FUNC is a Call whose own
  func is the Name `synchronous`, so looking only at `n.value.func.id` finds
  nothing -- which is how a checker reports an EMPTY list where six wrappers are."""
  if not (isinstance(n, ast.Assign) and isinstance(n.value, ast.Call)): return None
  inner = n.value.func
  if isinstance(inner, ast.Call) and getattr(inner.func, "id", None) == "synchronous":
    return inner
  return None


def sync_ids():
  """the six `synchronous(...)(webgpu.f)` wrapper defs at :45-50, in SOURCE
  ORDER. The port's SYNC_* ids ARE that order, so the authority for
  SYNC_MAP_ASYNC..SYNC_WORK_DONE is the definition order, read off the AST."""
  return [(n.lineno, [t.id for t in n.targets],
           getattr(n.value.args[0], "attr", None))
          for n in TREE.body if (d := _wrapper(n))]


def has_emsg_flags():
  """`synchronous(enum, True)` vs `synchronous(enum)`. The port's SYNC_HAS_EMSG /
  SYNC_NO_EMSG is a two-value tag, and what is checkable is the PATTERN: which of
  the six carry the `True`. Read off the AST's argument count of the decorator."""
  out = []
  for n in TREE.body:
    d = _wrapper(n)
    if d is None: continue
    a = d.args[1] if len(d.args) > 1 else None
    out.append(not (a is None or (isinstance(a, ast.Constant) and a.value is False)))
  return out


# ---------------------------------------------------------------------------- map
MAP = {
  # ---- autogen/webgpu.py: the C enums, by getattr ------------------------
  "BIND_UNIFORM": ("hdr", lambda: hdr("WGPUBufferBindingType_Uniform"), "autogen/webgpu.py:135, :76"),
  "BIND_STORAGE": ("hdr", lambda: hdr("WGPUBufferBindingType_Storage"), "autogen/webgpu.py:135, :78"),
  "FILTER_VALIDATION": ("hdr", lambda: hdr("WGPUErrorFilter_Validation"), "autogen/webgpu.py:1550, :62/80/89/100"),
  "MAP_UNMAPPED": ("hdr", lambda: hdr("WGPUBufferMapState_Unmapped"), "autogen/webgpu.py:1545"),
  "MAP_PENDING": ("hdr", lambda: hdr("WGPUBufferMapState_Pending"), "autogen/webgpu.py:1545"),
  "MAP_MAPPED": ("hdr", lambda: hdr("WGPUBufferMapState_Mapped"), "autogen/webgpu.py:1545, :196"),
  "FEATURE_TIMESTAMP_QUERY": ("hdr", lambda: hdr("WGPUFeatureName_TimestampQuery"), "autogen/webgpu.py:833, :71/174"),
  "FEATURE_SHADER_F16": ("hdr", lambda: hdr("WGPUFeatureName_ShaderF16"), "autogen/webgpu.py:833, :174/190"),
  "USAGE_MAP_READ": ("hdr", lambda: hdr("WGPUBufferUsage_MapRead"), "autogen/webgpu.py:2574, :209"),
  "USAGE_COPY_SRC": ("hdr", lambda: hdr("WGPUBufferUsage_CopySrc"), "autogen/webgpu.py:2576, :115/153"),
  "USAGE_COPY_DST": ("hdr", lambda: hdr("WGPUBufferUsage_CopyDst"), "autogen/webgpu.py:2577, :115/153/203/209"),
  "USAGE_UNIFORM": ("hdr", lambda: hdr("WGPUBufferUsage_Uniform"), "autogen/webgpu.py:2580, :203"),
  "USAGE_STORAGE": ("hdr", lambda: hdr("WGPUBufferUsage_Storage"), "autogen/webgpu.py:2581, :153"),
  "USAGE_QUERY_RESOLVE": ("hdr", lambda: hdr("WGPUBufferUsage_QueryResolve"), "autogen/webgpu.py:2583, :115"),

  # ---- ops_webgpu.py: int literals at a NAMED line ------------------------
  # :40 `if status != 1` is the port's STATUS_SUCCESS, and the header's own
  # WGPUWaitStatus_Success is ALSO 1 -- both authorities are asserted so a header
  # change and a source change cannot disagree silently.
  "STATUS_SUCCESS": ("both", lambda: (src(40, rx=r"status != (\d+)"), hdr("WGPUWaitStatus_Success")),
                     ":40 the literal `1`, and WGPUWaitStatus_Success"),
  "BIND_GROUP_INDEX": ("src", lambda: src(122, at=0), ":122 SetBindGroup(compute_pass, 0, ...), the group index"),
  "UNIFORM_SIZE": ("src", lambda: src(203, rx=r"size=(\d+)"), ":203 WGPUBufferDescriptor(size=4)"),
  "QUERY_COUNT": ("src", lambda: src(113, rx=r"count=(\d+)"), ":113 WGPUQuerySetDescriptor(count=2)"),
  "QUERY_BUF_SIZE": ("src", lambda: src(115, rx=r"size=(\d+)"), ":115 WGPUBufferDescriptor(size=16)"),

  # ---- tag spaces: NOT values -------------------------------------------
  # SYNC_* ids ARE the definition order of the six wrappers at :45-50.
  "SYNC_MAP_ASYNC": ("tag", lambda: 1, "the FIRST `synchronous(...)` def, :45"),
  "SYNC_POP_ERROR_SCOPE": ("tag", lambda: 2, ":46"),
  "SYNC_CREATE_PIPELINE": ("tag", lambda: 3, ":47"),
  "SYNC_REQUEST_ADAPTER": ("tag", lambda: 4, ":48"),
  "SYNC_REQUEST_DEVICE": ("tag", lambda: 5, ":49"),
  "SYNC_WORK_DONE": ("tag", lambda: 6, ":50"),
  # SYNC_HAS_EMSG / SYNC_NO_EMSG is a TWO-value tag for True/False, and the
  # checkable property is the PATTERN of which ids are True.
  "SYNC_HAS_EMSG": ("tag", lambda: 1, "the TRUE arm: ids 1,3,4,5"),
  "SYNC_NO_EMSG": ("tag", lambda: 2, "the FALSE arm: ids 2,6"),
  # the :41 collapse's three arms
  "SYNC_NONE": ("tag", lambda: 0, ":41 `else None`"),
  "SYNC_ONE": ("tag", lambda: 1, ":41 `payload[0] if len(payload)==1`"),
  "SYNC_MANY": ("tag", lambda: 2, ":41 `payload if len(payload) > 1`"),
  # OBJ_* is the object-kind tag space and CALL_* the call-kind tag space. Both
  # are checked as a dense 0..n-1 space AND, in wg_emit_map.py, as a
  # NAME -> (python line, symbol) map.
  "OBJ_INSTANCE": ("tag", lambda: 0, ":11 wgpuCreateInstance"),
  "OBJ_ADAPTER": ("tag", lambda: 1, ":168 InstanceRequestAdapter"),
  "OBJ_DEVICE": ("tag", lambda: 2, ":184 AdapterRequestDevice"),
  "OBJ_QUEUE": ("tag", lambda: 3, ":185 wgpuDeviceGetQueue"),
  "OBJ_SHADER_MODULE": ("tag", lambda: 4, ":63 wgpuDeviceCreateShaderModule"),
  "OBJ_BIND_GROUP_LAYOUT": ("tag", lambda: 5, ":81 wgpuDeviceCreateBindGroupLayout"),
  "OBJ_PIPELINE_LAYOUT": ("tag", lambda: 6, ":90 wgpuDeviceCreatePipelineLayout"),
  "OBJ_BIND_GROUP": ("tag", lambda: 7, ":101 wgpuDeviceCreateBindGroup"),
  "OBJ_COMPUTE_PIPELINE": ("tag", lambda: 8, ":107 DeviceCreateComputePipeline"),
  "OBJ_COMMAND_ENCODER": ("tag", lambda: 9, ":109 wgpuDeviceCreateCommandEncoder"),
  "OBJ_COMPUTE_PASS": ("tag", lambda: 10, ":120 wgpuCommandEncoderBeginComputePass"),
  "OBJ_COMMAND_BUFFER": ("tag", lambda: 11, ":128 wgpuCommandEncoderFinish"),
  "OBJ_QUERY_SET": ("tag", lambda: 12, ":113 wgpuDeviceCreateQuerySet"),
  "OBJ_BUFFER": ("tag", lambda: 13, ":114 wgpuDeviceCreateBuffer (the query buffer)"),
  "CALL_WAIT": ("emit", lambda: emit((37, "wgpuInstanceWaitAny")), ":37, inside `synchronous`"),
  "CALL_MAP_ASYNC": ("emit", lambda: emit((18, "wgpuBufferMapAsync2"), (45, "wgpuBufferMapAsync2")),
                     ":18 buf_to_mv calls the :45 wrapper, which IS wgpuBufferMapAsync2"),
  "CALL_MAPPED_RANGE": ("emit", lambda: emit((19, "wgpuBufferGetConstMappedRange")), ":19 buf_to_mv"),
  "CALL_WRITE": ("emit", lambda: emit((221, "wgpuQueueWriteBuffer")), ":221 write_buffer"),
  "CALL_COPY": ("emit", lambda: emit((213, "wgpuCommandEncoderCopyBufferToBuffer")), ":213 _readable_buffer"),
  "CALL_BEGIN": ("emit", lambda: emit((120, "wgpuCommandEncoderBeginComputePass")), ":120"),
  "CALL_SET_PIPELINE": ("emit", lambda: emit((121, "wgpuComputePassEncoderSetPipeline")), ":121"),
  "CALL_SET_BIND_GROUP": ("emit", lambda: emit((122, "wgpuComputePassEncoderSetBindGroup")), ":122"),
  "CALL_DISPATCH": ("emit", lambda: emit((123, "wgpuComputePassEncoderDispatchWorkgroups")), ":123"),
  "CALL_END": ("emit", lambda: emit((124, "wgpuComputePassEncoderEnd")), ":124"),
  "CALL_RESOLVE": ("emit", lambda: emit((126, "wgpuCommandEncoderResolveQuerySet")), ":126"),
  "CALL_FINISH": ("emit", lambda: emit((128, "wgpuCommandEncoderFinish")), ":128"),
  "CALL_SUBMIT": ("emit", lambda: emit((129, "wgpuQueueSubmit"), (215, "wgpuQueueSubmit")), ":129/215"),
  "CALL_UNMAP": ("emit", lambda: emit((196, "wgpuBufferUnmap")), ":196 free"),
  "CALL_DESTROY": ("emit", lambda: emit((197, "wgpuBufferDestroy")), ":197 free"),
  "CALL_DESTROY_QUERY_SET": ("emit", lambda: emit((144, "wgpuQuerySetDestroy")), ":144"),
  "CALL_GET_FEATURES": ("emit", lambda: emit((172, "wgpuAdapterGetFeatures")), ":172"),
  "CALL_FREE_FEATURES": ("emit", lambda: emit((175, "wgpuSupportedFeaturesFreeMembers")), ":175"),
  "CALL_GET_LIMITS": ("emit", lambda: emit((180, "wgpuAdapterGetLimits")), ":180"),
  "CALL_POP": ("emit", lambda: emit((200, "DevicePopErrorScope"), (46, "wgpuDevicePopErrorScope2")),
               ":200 pop_error calls the :46 wrapper, which IS wgpuDevicePopErrorScope2"),
  "CALL_PUSH": ("emit", lambda: emit((62, "wgpuDevicePushErrorScope"), (80, "wgpuDevicePushErrorScope")),
                ":62/80/89/100, four sites, all the same call"),
  "CALL_RELEASE": ("emit", lambda: emit((67, "wgpuShaderModuleRelease"), (132, "wgpuBindGroupLayoutRelease")),
                   ":67/132-138, seven releases"),
  "CALL_CREATE": ("emit", lambda: emit((11, "wgpuCreateInstance")), ":11, the module-level instance"),
}

NO_AUTH = {}


def bend_consts(path):
  out = {}
  for i, line in enumerate(Path(path).read_text().splitlines(), 1):
    m = BEND_CONST.match(line)
    if m: out[m.group(1)] = (i, int(m.group(2)))
  return out


def main():
  port = bend_consts(PORT)
  kinds, wrong, noauth, unmapped, unknown = {}, [], [], [], []
  for name, (ln, val) in sorted(port.items()):
    if name in NO_AUTH:
      kinds.setdefault("no-auth", []).append(name); noauth.append((name, val, ln)); continue
    if name not in MAP:
      unknown.append((name, val, ln)); continue
    kind, fn, why = MAP[name]
    kinds.setdefault(kind, []).append(name)
    if kind in ("dead", "fix", "tag"): continue
    got = fn()
    if kind == "both":
      got = got[0]
      if got != hdr("WGPUWaitStatus_Success"):
        wrong.append((name, val, f"{got} vs header {hdr('WGPUWaitStatus_Success')}", ln, why))
      continue
    if kind == "emit":
      try: fn()
      except AssertionError as e: wrong.append((name, val, str(e), ln, why))
      continue
    if got != val: wrong.append((name, val, got, ln, why))
  for name in MAP:
    if name not in port: unmapped.append(name)
  total = len(port)
  checked = total - len(noauth) - len(unknown) - len(kinds.get("emit", [])) - len(kinds.get("tag", []))
  print(f"{PORT.name}: {total} numeric constant defs")
  print(f"  compared against a CPython authority : {checked}")
  print(f"  CALL_* name->(line,symbol) map       : {len(kinds.get('emit', []))}")
  print(f"  tag space (checked for DENSITY below): {len(kinds.get('tag', []))}")
  print(f"  NO AUTHORITY                          : {len(noauth)}")
  print(f"  WRONG                                 : {len(wrong)}")
  for n, p, g, ln, why in wrong:
    print(f"    WRONG {n}: port {p} at line {ln}, authority {g} -- {why}")
  for n, v, ln in noauth: print(f"    NO-AUTH {n}={v} at line {ln}: {NO_AUTH[n]}")
  for n, v, ln in unknown: print(f"    UNMAPPED {n}={v} at line {ln} -- ADD IT TO THE MAP")
  for n in unmapped: print(f"    MAP-ONLY {n}: in the map, not in the port")

  # ---- the tag spaces' one checkable property: DENSITY -------------------
  for pre, excludes in (("OBJ", ()), ("CALL", ()), ("SYNC", ("SYNC_HAS_EMSG", "SYNC_NO_EMSG",
                                                             "SYNC_NONE", "SYNC_ONE", "SYNC_MANY"))):
    vals = sorted(val for k, (_ln, val) in port.items() if k.startswith(pre + "_") and k not in excludes)
    # the six SYNC ids ARE the 1-BASED definition order of the wrappers at :45-50,
    # so SYNC's density is 1..6 and not 0..5. Asserting 0-based would be the
    # AUDIT's own bug, so the expectation is stated per space.
    want = list(range(1, len(vals) + 1)) if pre == "SYNC" else list(range(len(vals)))
    print(f"  {pre}_* tag values                     : {vals[0]}..{vals[-1]} n={len(vals)} "
          f"DENSE={vals == want} (want {'1..n' if pre == 'SYNC' else '0..n-1'})")
    if vals != want: print(f"    !! the {pre}_* tags do not have the required density")

  # ---- the two MEASURED facts behind the SYNC_* ids ----------------------
  ids = sync_ids()
  flags = has_emsg_flags()
  print(f"  MEASURED sync wrapper order           : {[ln for ln, _, _ in ids]}  (expect [45,46,47,48,49,50])")
  print(f"  MEASURED wrapper targets              : {[s for _, _, s in ids]}")
  print(f"  MEASURED has_emsg per wrapper         : {flags}  "
        f"(port claims True for SYNC 1,3,4,5 and False for 2,6)")
  bad = 0
  if [ln for ln, _, _ in ids] != [45, 46, 47, 48, 49, 50]:
    print("    !! the six wrappers are not at :45-50"); bad += 1
  want = [True, False, True, True, True, False]
  if flags != want:
    print(f"    !! the port's SYNC_HAS_EMSG/NO_EMSG pattern is wrong: {flags} != {want}"); bad += 1
  # each SYNC id's SYMBOL is the wrapper's target, and the six targets must be
  # DISTINCT and must be the six wgpu entry points :45-50 really wrap. This is the
  # check that a duplicated or transposed SYNC id cannot pass.
  want_syms = ["wgpuBufferMapAsync2", "wgpuDevicePopErrorScope2", "wgpuDeviceCreateComputePipelineAsync2",
               "wgpuInstanceRequestAdapter2", "wgpuAdapterRequestDevice2", "wgpuQueueOnSubmittedWorkDone2"]
  # The PORT's own claim, id -> the wrapper it is. Hand-written, because the port
  # records only the NUMBER in `Call{CALL_WAIT, SYNC_X}` and nothing anywhere
  # binds that number to a symbol -- which is why the transposition control
  # (SYNC_MAP_ASYNC <-> SYNC_POP_ERROR_SCOPE) is invisible to the gate AND to a
  # density check, and only this map sees it.
  PORT_SYNC = {"SYNC_MAP_ASYNC": "wgpuBufferMapAsync2", "SYNC_POP_ERROR_SCOPE": "wgpuDevicePopErrorScope2",
               "SYNC_CREATE_PIPELINE": "wgpuDeviceCreateComputePipelineAsync2",
               "SYNC_REQUEST_ADAPTER": "wgpuInstanceRequestAdapter2",
               "SYNC_REQUEST_DEVICE": "wgpuAdapterRequestDevice2",
               "SYNC_WORK_DONE": "wgpuQueueOnSubmittedWorkDone2"}
  by_line = {ln: (sym, targets[0]) for ln, targets, sym in ids}
  print(f"  MEASURED wrapper order                 : "
        f"{ {targets[0]: by_line[ln][1] for ln, targets, _ in ids} }")
  print(f"  PORT CLAIMS                            : {PORT_SYNC}")
  for name, sym in sorted(PORT_SYNC.items()):
    # the port's id must be the 1-based index of the wrapper that wraps `sym`
    want_id = next((i for i, (_, _, s) in enumerate(ids, 1) if s == sym), None)
    got_id = port[name][1]
    if got_id != want_id:
      print(f"    WRONG SYNC ID {name}: port {got_id}, authority {want_id} "
            f"(the {want_id}th `synchronous` wrapper, ops_webgpu.py:{45 + want_id - 1}, is {sym})")
      bad += 1
  got_syms = [s for _, _, s in ids]
  if got_syms != want_syms:
    print(f"    !! the six wrappers target {got_syms}"); bad += 1

  # ---- OBJ_*'s ONE real authority: the release order at :132-138 ----------
  rel = [re.search(r"wgpu(\w+)Release", SLINES[i - 1]) for i in range(132, 139)]
  want_obj = ["BindGroupLayout", "PipelineLayout", "BindGroup", "ComputePipeline",
              "CommandEncoder", "ComputePassEncoder", "CommandBuffer"]
  got_obj = [m.group(1) for m in rel if m]
  print(f"  MEASURED release order :132-138        : {got_obj}")
  if got_obj != want_obj:
    print("    !! ops_webgpu.py:132-138 releases in another order than the port assumes")
    bad += 1
  obj_of = {"BindGroupLayout": "OBJ_BIND_GROUP_LAYOUT", "PipelineLayout": "OBJ_PIPELINE_LAYOUT",
            "BindGroup": "OBJ_BIND_GROUP", "ComputePipeline": "OBJ_COMPUTE_PIPELINE",
            "CommandEncoder": "OBJ_COMMAND_ENCODER", "ComputePassEncoder": "OBJ_COMPUTE_PASS",
            "CommandBuffer": "OBJ_COMMAND_BUFFER"}
  vals = [port[obj_of[o]][1] for o in got_obj if o in obj_of]
  print(f"  the OBJ ids in that order              : {vals}")
  if vals != sorted(vals):
    print("    !! the OBJ ids do NOT increase along the Python release order -- "
          "the trace would print the release of one object under another's kind")
    bad += 1
  return 1 if (wrong or unknown or unmapped or bad) else 0


if __name__ == "__main__":
  sys.exit(main())
