// M-2 halves.c -- the 16 bindings clangshim-gen.py refuses to emit, written
// over two U32 halves. GENERATED by .agents/slop/w64mile/emit_halves.py.
//
// THE PRELUDE IS clangshim-gen.py's, IMPORTED rather than copied: PTR, SBY,
// park, bend_cstr and io_str are the measured marshalling and a second copy of
// them is a second thing to keep in step.
//
// THE 64-BIT RETURN IS SPLIT, NOT TYPED. `_run` answers the HIGH word in the
// Term it returns and parks the LOW word in a global that `_lo_run` reads back.
// Two foreign defs per binding, because a Bend effect returns one Term and a
// `Nat` is linear -- one value cannot serve two calls. The low word is a Term,
// not a `Nat`, precisely so nothing has to be read back out through `Nat` (whose
// ceiling is 2^48-1, W-1/W-2).

// GENERATED by .agents/slop/clangshim/clangshim-gen.py -- do not edit.
//
// ONE file, N bindings, ONE import, ONE cc. There are no clang-c headers on this
// machine; every declaration below is written from the port's own committed
// bindings (.agents/slop/ag-libclang.tramp + tinygrad/runtime/autogen/
// libclang.py), so a committed SIGNATURE is the complete input for a call.
//
// THE MARSHALLING CONVENTION, once, for every function here:
//   int/uint        one Term word, low 32 bits. A NEGATIVE int crosses as its
//                   two's-complement bit pattern, not as a negative Nat.
//   any pointer     one Term word = the address. Bend has no U64; Nat is a
//                   working U64 to 2^51-1 (MEASURED, ffi-experiment/e8).
//   by-value struct the CALLER passes an address and the shim reads SIZE bytes;
//                   the shim returns an address of a parked copy. The struct is
//                   an OPAQUE union: right size, 8-byte aligned, no fields. So a
//                   shim can pass and return a libclang struct over the ABI and
//                   CANNOT read a field of it -- that is the honest boundary.
//   const char* IN  a Bend String is a cons list of code points, not a char*, so
//                   bend_cstr walks it. Written ONCE, used by every string
//                   parameter.
//   const char* OUT io_str, two lines.
//   void            term_pak(CID(Unit), 0).
//   int64/uint64/double and function pointers: NO LAW EMITTED. Named per
//                   function in the BLOCKED table at the foot of shim.bend.

#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <sys/wait.h>
#include <unistd.h>

#define PTR(t)   ((void*)(uintptr_t)(t))
#define SZ       256

// A parked struct is a value the callee returned by value; it must outlive the
// call, so it lives in a ring the shim owns rather than on the stack.
static unsigned char g_park[SZ][48];
static unsigned       g_park_n;
static void* park(const void* p, unsigned n) {
  void* q = g_park[g_park_n++ % SZ];
  memcpy(q, p, n);
  return q;
}

// A by-value struct parameter. f[i] == 0 is legal and means "a zeroed struct",
// so a caller with no object to pass is not a crash -- it is a wrong answer,
// which is the same thing every other zero argument is.
#define SBY(T, i) ({ T v_; if (PTR(f[i]) == 0) memset(&v_, 0, sizeof v_); \
                        else memcpy(&v_, PTR(f[i]), sizeof v_); v_; })

// Bend String -> char*. The cons walk, written once (MEASURED, e3).
static char* bend_cstr(Env e, Term t) {
  char* buf = (char*)malloc(4096);
  u32    n   = 0;
  while (term_aux(t) != CID(SNil)) {
    Term g[2];
    u64  sp = ctr_take(e, t, 2, g);
    buf[n++] = (char)g[0];
    t = g[1];
    spare_free(e, cls_fit(2), sp);
  }
  buf[n] = 0;
  return buf;
}

typedef union { unsigned char _b[32]; unsigned long long _a; double _d; } CXCursor;
extern long long clang_getEnumConstantDeclValue(CXCursor C);

static Term g_lo_clang_getEnumConstantDeclValue;
Term clang_getEnumConstantDeclValue_run(Env e, Term* f, IoWork* w) {
  CXCursor v0 = SBY(CXCursor, 0);
  long long r = clang_getEnumConstantDeclValue(v0);
  unsigned long long u = (unsigned long long)r;
  g_lo_clang_getEnumConstantDeclValue = (Term)(u64)(u32)u;
  return (Term)(u64)(u32)((u >> 16) >> 16);
}
Term clang_getEnumConstantDeclValue_lo_run(Env e, Term* f, IoWork* w) { return g_lo_clang_getEnumConstantDeclValue; }

static void __attribute__((constructor)) halves_use(void) {
  io_eff(CID(clang_getEnumConstantDeclValue), clang_getEnumConstantDeclValue_run, 0);
  io_eff(CID(clang_getEnumConstantDeclValue_lo), clang_getEnumConstantDeclValue_lo_run, 0);
}
