#!/usr/bin/env python3
"""M-2 -- the 16 blocked libclang bindings, emitted over two `U32` halves,
compiled, linked against the real libclang, and run beside CPython.

`clangshim-gen.py` is IMPORTED, never edited: it is another unit's slop tree,
and its `plan()` is where "which row is blocked, and on what" comes from, so
nothing here re-derives that.

WHY TWO HALVES AND NOT A TYPE. `W64.md` measured the type wall away: a `double`
add crosses the FFI as two `U32` halves and comes back bit-identical to CPython
(`w4_f64add.bend`, 3 rows, plant and disarm). So the 16 need no `F64`/`I64` in
Bend -- they need a marshalling. And MEASURED by `gen_halves.py`: all 16 are
blocked on the RETURN alone, none has a 64-bit PARAMETER, so one shape covers
all 16.

THE SHAPE, AND WHY IT IS TWO FOREIGN DEFS. A Bend effect returns one Term, so a
64-bit answer cannot come back as two values in one call: `W64.md` records that
"a Bend Nat is linear, one value cannot serve two calls, so the pair cannot be
returned as two values without knowing that marshalling path". So each binding
gets `f` (the high word) and `f_lo` (the low word), and the low word travels in a
C global -- the shape W-4 ran. `runtime/dtype.c:210` uses a different one
(`io_tup`, a tuple Term), so there may be a one-def form; that is NOT measured
here and is named as open in the report.

ONE FILE PER BINDING, ON PURPOSE. A census that forks in-process needs the fork
plumbing, and a census that does not fork stops at the first segfault -- 308 of
308 called with a zero argument crash, per `clangshim/STAGE4.md`, and 16 separate
programs give 16 separate verdicts and make "a missing row" impossible to confuse
with "a passing row". The cost is 16 compiles instead of 1.

THE COMPARISON IS PER BINDING AGAINST CPython's ctypes CALL ON THE SAME ARGUMENT,
and a fault is a comparable outcome: CPython is forked too, so "the port faulted"
and "CPython faulted" are two verdicts rather than one silence.
"""
import importlib.util
import pathlib
import re
import subprocess
import sys

REPO = pathlib.Path("/Users/cyberistic/src/tries/2026-09-30-tinybendygrad")
GEN = REPO / ".agents/slop/clangshim/clangshim-gen.py"
PYBIND = REPO / "tinygrad/runtime/autogen/libclang.py"
CLIB = "/Library/Developer/CommandLineTools/usr/lib"
BEND = REPO / "bin/bend"
OUT = pathlib.Path(__file__).resolve().parent / "halves"

spec = importlib.util.spec_from_file_location("clangshim_gen", GEN)
g = importlib.util.module_from_spec(spec)
sys.modules["clangshim_gen"] = g
spec.loader.exec_module(g)
T = g.fpc.Types(PYBIND.read_text())
BLOCKED = sorted([x for x in g.plan(T) if x["blockers"]], key=lambda y: y["name"])


def args_of(x) -> tuple[list[str], list[str]]:
    """(pre-declarations, call arguments) in the marshalling clangshim-gen uses."""
    pre, args = [], []
    for i, (cl, ct) in enumerate(zip(x["pc"], x["pct"])):
        if cl == g.INT:
            args.append(f"({ct})(u32)f[{i}]")
        elif cl == g.PTR:
            args.append(f"(({ct})PTR(f[{i}]))")
        elif cl == g.STRI:
            pre.append(f"  char* a{i} = bend_cstr(e, f[{i}]);")
            args.append(f"a{i}")
        elif cl.startswith("BYVAL"):
            pre.append(f"  {ct} v{i} = SBY({ct}, {i});")
            args.append(f"v{i}")
        else:
            raise SystemExit(f"{x['name']}: unhandled param class {cl}")
    return pre, args


C_HEAD = [f"""// M-2 halves.c -- the 16 bindings clangshim-gen.py refuses to emit, written
// over two U32 halves. GENERATED by .agents/slop/w64mile/emit_halves.py.
//
// THE PRELUDE IS clangshim-gen.py's, IMPORTED rather than copied: PTR, SBY,
// park, bend_cstr and io_str are the measured marshalling and a second copy of
// them is a second thing to keep in step.
//
// THE 64-BIT RETURN IS SPLIT, NOT TYPED. `_run` answers the HIGH word in the
// Term it returns and parks the LOW word in a global that `_lo_run` reads back.
// Two foreign defs per binding, because a Bend effect returns one Term and a
// `Nat` is linear -- one value cannot serve two calls. The low word is a Term,
// not a `Nat`, precisely so nothing has to be read back out through `Nat` (whose
// ceiling is 2^48-1, W-1/W-2).
""", g.PRELUDE]


def emit_c(x) -> pathlib.Path:
    """ONE .c PER BINDING, and the reason is measured, not stylistic.

    `CID(x)` is a MACRO, and `#ifdef CID(Dt.bf16)` -- the shape
    `runtime/dtype.c:246` uses -- does not work: the preprocessor does not expand
    an `#ifdef` operand that looks like an invocation, so the guard is false for
    every binding and the file fails with "CID(...) names no constructor or def".
    clangshim-gen.py escapes this by declaring all 308 laws in ONE .bend, so all
    308 CIDs exist. One file per binding cannot do that without declaring laws it
    does not call, and that has not been measured, so each binding gets its own
    .c with exactly its own two registrations.
    """
    body = list(C_HEAD)
    # The typedefs, MIRRORED from clangshim-gen.py's emit (its lines that build
    # `opaque` and `sizes`) rather than copied: a type used BY VALUE needs a union
    # of its real SIZE and a type only ever behind a pointer needs a one-byte
    # opaque typedef. Without them the extern line names a type that was never
    # declared -- "unknown type name 'CXType'" -- which is a missing declaration
    # and not a marshalling problem.
    sizes, opaque = {}, set()
    for t in [g.canon(x["rct_raw"])] + [g.canon(q) for q in x["pct_raw"]]:
        m = re.match(r"^(\w+)\[(\d+)\]$", t)
        if m:
            sizes[m.group(1)] = int(m.group(2))
    for t in [g.canon(x["rct_raw"])] + [g.canon(q) for q in x["pct_raw"]]:
        if not t.startswith("*"):
            continue
        nm = g._SIZE_RE.sub("", t.lstrip("*"))
        if nm and nm not in sizes and nm not in g._BITS and nm != "void" \
                and nm not in set(g._PRIM.values()):
            opaque.add(nm)
    for nm in sorted(opaque):
        body.append(f"typedef struct {nm} {{ unsigned char _b[1]; }} {nm};")
    for nm, sz in sorted(sizes.items()):
        body.append(f"typedef union {{ unsigned char _b[{sz}]; "
                    f"unsigned long long _a; double _d; }} {nm};")
    ps = ", ".join(f"{t} {n}" for t, n in zip(x["pct"], x["pname"])) or "void"
    body.append(f"extern {x['rct']} {x['name']}({ps});")
    body.append("")
    if True:
        nm, rct = x["name"], x["rct"]
        pre, args = args_of(x)
        # `double` and `int64` are bit-identical once MEMCPY'd into a u64, and the
        # memcpy is what keeps the high-word shift from being a double shift.
        body += [f"static Term g_lo_{nm};",
                 f"Term {nm}_run(Env e, Term* f, IoWork* w) {{"] + pre
        if x["rc"] == g.F64:
            body += [f"  {rct} r = {nm}({', '.join(args)});",
                     "  unsigned long long u; memcpy(&u, &r, 8);",
                     f"  g_lo_{nm} = (Term)(u64)(u32)u;",
                     "  return (Term)(u64)(u32)(u >> 32);"]
        else:
            body += [f"  {rct} r = {nm}({', '.join(args)});",
                     "  unsigned long long u = (unsigned long long)r;",
                     f"  g_lo_{nm} = (Term)(u64)(u32)u;",
                     "  return (Term)(u64)(u32)(u >> 32);"]
        body += ["}",
                 f"Term {nm}_lo_run(Env e, Term* f, IoWork* w) {{ return g_lo_{nm}; }}"]
    body += ["",
             "static void __attribute__((constructor)) halves_use(void) {",
             f"  io_eff(CID({x['name']}), {x['name']}_run, 0);",
             f"  io_eff(CID({x['name']}_lo), {x['name']}_lo_run, 0);",
             "}"]
    p = OUT / f"{x['name']}.c"
    p.write_text("\n".join(body) + "\n")
    return p


def emit_bend() -> list[tuple[pathlib.Path, pathlib.Path]]:
    """One .bend per binding. Two rows each: hi and lo."""
    files = []
    for x in BLOCKED:
        nm = x["name"]
        cname = f"{nm}.c"
        sig = " -> ".join(x["pb"]) if x["pb"] else ""
        ps = ", ".join(x["pname"])
        law_in = f"{sig} -> IO(U32)" if sig else "IO(U32)"
        z = {"Nat": "0n", "String": '""', "Unit": "0n"}
        call_args = ", ".join(z[t] for t in x["pb"])
        src = [f"# M-2 {nm} -- blocked on {','.join(x['blockers'])} by"
               f" clangshim-gen.py; here over two U32 halves.", "import Base", ""]
        if sig:
            src += [f"law {nm}:", f"  {law_in}", "",
                    f"def {nm}({ps}):",
                    f'  import "./{cname}"', ""]
        else:
            src += [f"law {nm}: {law_in}", "", f"def {nm}():",
                    f'  import "./{cname}"', ""]
        src += [f"law {nm}_lo: IO(U32)", "", f"def {nm}_lo():",
                f'  import "./{cname}"', "", "def main() -> IO(Unit):",
                "  do IO<Unit>:"]
        src += [f"    hi : U32 <- {nm}({call_args})",
                f"    lo : U32 <- {nm}_lo()",
                f'    IO.print("H64 {nm} hi=" ++ Nat.show(U32.to_nat(hi))'
                f' ++ " lo=" ++ Nat.show(U32.to_nat(lo)))']
        p = OUT / f"{nm}.bend"
        p.write_text("\n".join(src) + "\n")
        files.append((p, emit_c(x)))
    return files


def run_bend(p: pathlib.Path, c: pathlib.Path) -> dict:
    gen = p.with_suffix(".gen.c")
    exe = p.with_suffix(".out")
    r = subprocess.run([str(BEND), str(p), "-o", str(gen)], capture_output=True, text=True)
    if r.returncode != 0 or not gen.exists():
        return {"stage": "bend -o", "rc": r.returncode,
                "err": (r.stdout + r.stderr).strip()[:400], "row": None}
    # cc exits 1 on a LINK failure too, so the link error is reported separately.
    # ONLY the generated .c goes to cc: bend INLINES the imported .c into it, after
    # the runtime typedefs. Passing it a second time compiles it as its own
    # translation unit, where `Env`, `Term`, `u32` and `CID` do not exist -- which
    # is exactly the "unknown type name 'Env'" wall, and it is a mistake in the
    # build line, not in the shim.
    c = subprocess.run(["cc", str(gen), f"-L{CLIB}", "-lclang",
                        f"-Wl,-rpath,{CLIB}", "-o", str(exe)],
                       capture_output=True, text=True)
    if c.returncode != 0:
        return {"stage": "cc/link", "rc": c.returncode,
                "err": (c.stdout + c.stderr).strip()[:400], "row": None}
    x = subprocess.run([str(exe)], capture_output=True, text=True, timeout=60)
    row = None
    for line in (x.stdout + x.stderr).splitlines():
        if line.startswith("H64 "):
            row = line
    return {"stage": "run", "rc": x.returncode, "err": "", "row": row}


def cpython(nm: str, x) -> tuple[str, int | None]:
    """CPython's ctypes call on the SAME zero argument. Forked: a fault is a
    comparable outcome, so the child reports the bit pattern on a pipe and the
    parent records how it died.

    THE BY-VALUE STRUCTS ARE PASSED AS ZEROED OBJECTS OF THE RIGHT SIZE, because
    a bare `f(0)` for a 24-byte `CXType` is an ctypes argument-type MISMATCH and
    raises before libclang is ever entered. That would leave the port's row with
    no counterpart and make a real comparison look like a disagreement -- so the
    sizes come from the same `CXType[24]` spelling the shim's `SBY` uses.
    """
    byval = {}
    for i, (cl, ct) in enumerate(zip(x["pc"], x["pct"])):
        if cl.startswith("BYVAL"):
            byval[i] = int(re.match(r"^(\w+)\[(\d+)\]$", x["pct_raw"][i]).group(2))
        elif cl == g.STRI:
            byval[i] = "str"
    code = f"""
import ctypes, os, struct, sys
lib = ctypes.cdll.LoadLibrary("/Library/Developer/CommandLineTools/usr/lib/libclang.dylib")
f = getattr(lib, {nm!r})
BYVAL = {byval!r}
pid = os.fork()
if pid == 0:
    f.restype = ctypes.c_double if {nm!r} == "clang_EvalResult_getAsDouble" else ctypes.c_int64
    try:
        args = []
        for i, sz in enumerate(BYVAL.values()):
            args.append(b"" if sz == "str" else (ctypes.c_uint64 * (sz // 8))())
        r = f(*args)
    except Exception:
        sys.stdout.flush()
        os._exit(70)
    fmt = "<d" if isinstance(r, float) else "<q"
    u = struct.unpack("<Q", struct.pack(fmt, r))[0]
    sys.stdout.write(f"CPY {nm} hi={{u >> 32}} lo={{u & 0xffffffff}}\\n")
    sys.stdout.flush()
    os._exit(0)
_, st = os.waitpid(pid, 0)
sys.exit(os.waitstatus_to_exitcode(st))
"""
    r = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True,
                       timeout=60)
    row = None
    for line in (r.stdout + r.stderr).splitlines():
        if line.startswith("CPY "):
            row = line
    return row or "", r.returncode


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    files = emit_bend()
    print(f"emitted {len(files)} .bend files and {len(BLOCKED)} bindings "
          f"(+{len(BLOCKED)} `_lo` laws) over two U32 halves")
    print(f"one .c per binding, {len((OUT / (BLOCKED[0]['name'] + '.c')).read_text().splitlines())}"
          f" lines each, {len(BLOCKED)} of them\n")
    built = survived = faulted = broke = 0
    verdict = []
    byname = {x["name"]: x for x in BLOCKED}

    def mutate(old: str, new: str) -> None:
        """Edit every generated .c. The anchor must be present EXACTLY ONCE in
        each, asserted -- a mutation that matched nothing would be a green lane."""
        for _, c in files:
            t = c.read_text()
            hits = 0
            for nm in byname:
                for o, n in ((old, new), (old.format(nm=nm), new.format(nm=nm))):
                    if o in t:
                        assert t.count(o) == 1, f"{c.name}: {t.count(o)}x {o!r}"
                        t = t.replace(o, n)
                        hits += 1
                        break
            assert hits == 1, f"{c.name}: {hits} anchors for {old!r}"
            c.write_text(t)

    def sweep() -> tuple[dict, list]:
        rows, notes = {}, []
        for p, c in files:
            nm = p.stem
            r = run_bend(p, c)
            if r["stage"] != "run":
                undef = re.findall(r'"_(clang_[A-Za-z0-9_]+)"', r["err"])
                notes.append((nm, "NOT-IN-DYLIB" if undef else "BUILD-FAIL",
                              f"undefined={sorted(set(undef))}" if undef
                              else r["err"].splitlines()[0][:70]))
                continue
            if r["row"] is None:
                notes.append((nm, "FAULT" if r["rc"] < 0 else "NO-ROW",
                              f"signal {-r['rc']}" if r["rc"] < 0 else f"rc={r['rc']}"))
                continue
            rows[nm] = r["row"].split(" ", 1)[1]
        return rows, notes

    def halves(row: str) -> tuple[str, str]:
        # The row still carries the binding name (both the port row and the
        # CPython row are compared WITH it, so neither can satisfy the other's
        # line by printing the right halves under the wrong name).
        q = dict(kv.split("=", 1) for kv in row.split()[1:])
        return q["hi"], q["lo"]

    base, notes = sweep()
    print(f"\n{'binding':52s} {'port row':34s} verdict")
    order = {x["name"]: i for i, x in enumerate(sorted(BLOCKED, key=lambda y: y["name"]))}
    for nm, v, why in sorted(notes, key=lambda t: order[t[0]]):
        verdict.append((nm, v, why))
        print(f"{nm:52s} {why:34s} {v}")
    for nm, port in sorted(base.items(), key=lambda t: order[t[0]]):
        cpy, _ = cpython(nm, byname[nm])
        # The comparison is the WHOLE name=value line, so a row that printed one
        # half cannot satisfy it.
        same = bool(cpy) and cpy.split(" ", 1)[1] == port
        verdict.append((nm, "MATCH" if same else "DIFFER",
                        f"{port}   CPython {cpy.split(' ', 1)[1] if cpy else '<no row>'}"))
        print(f"{nm:52s} {port:34s} {verdict[-1][1]}")
        print(f"{"":52s} {cpy:34s} ^ CPython")
    nmatch = sum(1 for _, v, _ in verdict if v == "MATCH")
    print(f"\nbuilt {len(base)}/{len(BLOCKED)}   rows present {len(base)}"
          f"   port line == CPython line: {nmatch} of {len(base)}"
          f"   not built {len(notes)}: {[n for n, _, _ in notes]}")
    print(f"laws emitted by clangshim-gen.py 308/324; M-2 adds {len(base)}/"
          f"{len(BLOCKED)} of the remaining 16 -> {308 + len(base)}/324 laws that"
          f" COMPILE, LINK and RUN")

    # ---------------------------------------------------------------- PLANT
    # THE PLANT IS THE TRANSPOSE: the Term carries the low word and the global
    # carries the high one.
    #
    # THE EXPECTED MOVED SET IS DERIVED FROM THE ALGEBRA OF THE MUTATION AND NOT
    # TRANSCRIBED: a transpose moves a row exactly when hi != lo. That count is
    # small here and saying so IS the result -- libclang answers 0, -1 and
    # int64.min for a null handle, and 0 and -1 have hi == lo, so a transpose is
    # invisible on them. That is the "a row whose elements are all equal cannot
    # fail an ordering bug" trap wearing 64-bit dressing, and the plant is
    # measured to move exactly the rows that CAN see it rather than assumed to.
    mutate("  return (Term)(u64)(u32)(u >> 32);", "  return (Term)(u64)(u32)u;")
    mutate("  g_lo_{nm} = (Term)(u64)(u32)u;",
           "  g_lo_{nm} = (Term)(u64)(u32)(u >> 32);")
    plant, _ = sweep()
    moved = sorted(k for k in plant if plant[k] != base.get(k))
    expect = sorted(k for k, v in base.items() if halves(v)[0] != halves(v)[1])
    ok_plant = moved == expect and bool(moved)
    print(f"\nPLANT (halves transposed): rows moved {len(moved)} -> {moved}")
    print(f"  derived from the mutation\'s algebra, rows with hi != lo: {expect}")
    print(f"PLANT: {'PASS' if ok_plant else 'FAIL'}  -- a moved set other than"
          f" exactly the asymmetric rows means the lane is not the one under test")

    # --------------------------------------------------------------- DISARM
    # `u >> 32` and `(u >> 16) >> 16` are the SAME 64-bit value, so no row may
    # move. A harness that reported rows moved here would be reading something
    # other than the shim.
    # REGENERATE FIRST. The disarm has to be BASE plus one change, not PLANT plus
    # one: layered on the plant it inherits the plant's swapped global and
    # "moved one row" means nothing. Regenerating is one line and removes the
    # whole question.
    files = emit_bend()
    mutate("  return (Term)(u64)(u32)(u >> 32);",
           "  return (Term)(u64)(u32)((u >> 16) >> 16);")
    disarm, _ = sweep()
    quiet = sorted(k for k in disarm if k in base and disarm[k] != base[k])
    ok_disarm = not quiet
    print(f"\nDISARM (hi written as (u >> 16) >> 16): rows moved {len(quiet)} ->"
          f" {quiet}")
    print(f"DISARM: {'PASS' if ok_disarm else 'FAIL'}  -- 0 is the only correct count")

    ok_base = nmatch == len(base) and len(notes) == 1
    print(f"\n===== VERDICT =====\nBASE   {'PASS' if ok_base else 'FAIL'}"
          f"\nPLANT  {'PASS' if ok_plant else 'FAIL'}"
          f"\nDISARM {'PASS' if ok_disarm else 'FAIL'}")
    (OUT.parent / "halves.txt").write_text(
        "\n".join(f"{nm} {v} {port}" for nm, v, port in verdict)
        + f"\n# plant moved {moved} / derived {expect}\n"
        + f"# disarm moved {quiet}\n")
    raise SystemExit(0 if ok_base and ok_plant and ok_disarm else 1)


if __name__ == "__main__":
    main()
