#!/usr/bin/env python3
"""THE GATE for the 324 filled trampolines.  Runs each one, in its OWN PROCESS,
against a real clang index over `.agents/slop/clangshim/fixture.h`.

    python3 .agents/slop/clangfill/gate.py            # all 324
    python3 .agents/slop/clangfill/gate.py --plants   # + two plants and a disarm
    python3 .agents/slop/clangfill/gate.py --only 7   # one row, verbose

WHY ONE PROCESS PER ROW.  A libclang call with a NULL handle is a SEGFAULT for
some of the 320 and an answer for the rest, and a fault in row 200 would take the
other 199 with it.  So the instrument reports a fault as a fault, per row, instead
of as a short row set -- a missing row has to be a MISSING ROW and not a crash.

THE ROW IS A `SAW` LINE, printed by the row's own `_run`, naming the arguments it
ACTUALLY called with and the class of the answer.  The census is part of the
result: a row that printed nothing is counted as `no-row`, never as a pass.

THE TWO CLASSES OF ANCHOR, and they are not the same claim:
  * `threaded` -- bend handed the law its argument.  That is `Tramp_anchor`, whose
    `String` filename bend made and `io_cbuf` walked into a `const char *`, and
    the scalars of the driven rows, which `Tramp_drive` fills from `i+1` per slot;
  * `fixture` -- a real handle or record the fixture supplied because bend's every
    value is LINEAR and cannot hand one to two laws.  The row says which.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import abi  # noqa: E402

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
SHIM = REPO / ".agents" / "slop" / "clangshim"
PRODUCT = REPO / "tinybendygrad" / "runtime" / "autogen" / "libclang.bend"
LIBCLANG = "/Library/Developer/CommandLineTools/usr/lib/libclang.dylib"
CC = ["cc", "-w", "-O0", "-L" + os.path.dirname(LIBCLANG), "-lclang",
      "-Wl,-rpath," + os.path.dirname(LIBCLANG)]

def dispatch(rows):
    """One bend arm per row: `case k:` CALLS the law, which is what makes bend emit
    its `CID`, which is what makes `io_eff(CID(law), ...)` compile.

    ONE `match`, 324 arms, and bend type-checks every arm, so every law is
    statically reached and every `CID` exists -- while only the arm `k` selects
    runs.  That is the whole reason this is a `match` and not a list of calls: a
    list of 324 calls in one `do` block is (a) 324 real calls per process, so the
    first SEGFAULT takes the rest with it, and (b) impossible anyway, because a
    libclang row takes a handle bend cannot give away twice.

    The argument of each call is a CONSTANT of the law's own declared type: `0n`
    for a scalar, `Ptr_CChar{}` for a `const char*`, and the nullary Data
    constructor for a handle or a record.  bend's linearity is satisfied -- a
    constant is used once -- and the C carrier replaces the zero Term with a real
    fixture handle, which the row names.
    """
    arms = []
    for k, r in enumerate(rows):
        args = [gate_arg(cl, y, i) for i, (_pn, _pb, _ct, cl, y) in enumerate(r["ps"])]
        call = "%s(%s)" % (r["name"], ", ".join(args))
        arms.append("    case %dn: IO.bind(%s, Unit, %s, _ => IO.print(\"GATE %s\"))"
                    % (k, r["rbend"], call, r["name"]))
    return ("# ---- THE DISPATCH: generated by `.agents/slop/clangfill/gate.py`.\n"
            "#\n"
            "# One arm per row, so bend reaches all 324 laws and emits all 324 `CID`s --\n"
            "# which is what `io_eff(CID(law), ...)` needs -- while only the arm `k` runs.\n"
            "def gate_pick(k: Nat) -> IO(Unit):\n"
            "  match k:\n" + "\n".join(arms)
            + "\n    case Succ{p}: IO.pure(Unit, Unit{})  # k beyond the last row\n")


# THE THREE SPELLINGS OF ZERO, and getting them wrong is a type error, not a wrong
# answer: `0n` is a `Nat`, `0` is a `U32`, and `I32`/`I64`/`U64`/`F64` are NULLARY
# Data types this product mints for ABI widths bend has no type for, so their value
# is the CONSTRUCTOR and the C carrier reads the zero Term.  A draft passed `0n` for
# every scalar and bend named both: `expected : I32 / observed : Nat`, then
# `expected : U32 / observed : Nat`.
# THE SLOT INDEX, not `0`.  With every scalar `0` a TRANSPOSE of two of them is a
# THEOREM -- `f[2]` and `f[3]` are the same value, so the rows cannot tell the two
# apart -- and `PLANT-args` measured exactly that: 0 rows moved, and reported FAIL.
# The slot index makes every scalar DISTINCT, so a transpose puts two different
# numbers in two different columns and the row moves.
def gate_arg(cls, ybend, i):
    return str(i) if ybend == "U32" else ("0n" if ybend == "Nat" else "%s{}" % ybend)


GATE_MAIN = '''
# ---- THE GATE'S OWN main, swapped in by `.agents/slop/clangfill/gate.py`.  The
# ---- product's main measures libclang with the ten FFI-lane laws and stays.
# `IO.args()` is `IO(List<String>)` -- a CONS list, so its ref count is 1, not 2,
# and the `main` that discovers this asked for `&2` and bend named the mismatch.
def gate_num.go(r: Maybe<&2, Nat>) -> Nat:
  match r:
    case Some{value}: value
    case None{}: 0n

def gate_num(s: String) -> Nat: gate_num.go(Nat.read(s))

def gate_nth_s(xs: List<&1, String>, n: Nat) -> String:
  match xs:
    case Nil{}: "@FALLBACK@"
    case h <> rest:
      match n:
        case 0n: h
        case 1n+p: gate_nth_s(rest, p)

def gate_first(xs: List<&1, String>) -> String: gate_nth_s(xs, 1n)

# `IO.args()` HAS argv[0] IN IT.  `bend2/effs/args.c` loops `i = io_argc .. 1` and
# reads `io_argv[i - 1]`, so the head of the list is the PROGRAM PATH -- measured:
# the anchor parsed a file whose name was the full path of `port.out` and
# `clang_parseTranslationUnit` answered NULL for it, which reads as a refusal and is
# one.  So argv[1] is the FILENAME the anchor parses and argv[2] is the ROW INDEX.
def gate_nth(xs: List<&1, String>, n: Nat) -> Nat:
  match xs:
    case Nil{}: 0n
    case h <> rest:
      match n:
        case 0n: gate_num(h)
        case 1n+p: gate_nth(rest, p)

def gate_k(xs: List<&1, String>) -> Nat: gate_nth(xs, 2n)

@DISPATCH@

def main() -> IO(Unit):
  do IO<Unit>:
    xs1 : List<&1, String> <- IO.args()
    nm : String <- IO.pure(String, gate_first(xs1))
    a : String <- Tramp_anchor(nm)
    IO.print("ANCHOR " ++ a)
    xs2 : List<&1, String> <- IO.args()
    k : Nat <- IO.pure(Nat, gate_k(xs2))
    gate_pick(k)
'''


def rows_list():
    return abi.rows_list()


def stage(dst: Path, plant=None):
    """COPY the product and its C files into a scratch dir and rewrite the imports.

    The product imports `../../../.agents/slop/clangshim/*.c`, which a `$TMPDIR`
    copy cannot resolve; rewriting it to `./name.c` beside COPIED files is the same
    trick `cl-port-gate.py` uses and the only reason this works outside the tree.
    """
    if dst.exists():
        shutil.rmtree(dst)
    dst.mkdir(parents=True)
    for f in ("libclang-ffi.c", "libclang-tramp.c", "fixture.h"):
        shutil.copy(SHIM / f, dst / f)
    rows = abi.rows_list()
    text = PRODUCT.read_text()
    text = re.sub(r'import "\.\./\.\./\.\./\.agents/slop/clangshim/([^"]+)"',
                  lambda m: 'import "./%s"' % m.group(1), text)
    main = GATE_MAIN.replace("@FALLBACK@", "fixture.c").replace(
        "@DISPATCH@", dispatch(rows).rstrip("\n"))
    text = re.sub(r"def main\(\) -> IO\(Unit\):\n(?:  .*\n|\n(?=  ))*",
                  main.lstrip("\n"), text, count=1)
    assert "gate_pick" in text, "the gate main was not substituted"
    (dst / "port.bend").write_text(text)
    if plant:
        # the plants edit the GENERATED C in the scratch copy, never the product:
        # the product is a generated file and a repair belongs in the generator.
        c = dst / "libclang-tramp.c"
        new, n = plant(c.read_text())
        assert n, "the plant matched nothing -- a plant that moves nothing is a disarm"
        c.write_text(new)
    return dst / "port.bend", len(rows)


def bend(bend_file: Path, out_c: Path, timeout=1800):
    return subprocess.run([str(REPO / "bin" / "bend"), str(bend_file), "-o", str(out_c)],
                          capture_output=True, text=True, timeout=timeout)


def build(work: Path):
    gen = work / "port.gen.c"
    r = bend(work / "port.bend", gen)
    if not gen.is_file():
        return None, "bend rc=%d\n%s" % (r.returncode, (r.stdout + r.stderr)[-2000:])
    r = subprocess.run(CC + ["-o", str(work / "port.out"), str(gen)],
                       capture_output=True, text=True, cwd=work)
    if r.returncode != 0:
        return None, "cc rc=%d\n%s" % (r.returncode, (r.stdout + r.stderr)[-3000:])
    return work / "port.out", None


# A ROW IS NOT DETERMINISTIC UNTIL ITS ADDRESSES ARE MASKED.  A box answer is the
# address of a `malloc` and a handle answer is a libclang pointer, and BOTH move
# between two runs of one binary -- so a row-by-row diff counted 186 rows "moved"
# for a PLANT that changed one comment and for a DISARM that changed nothing.
# Measured, and it is the reason every diff below is over masked rows.
PTR = re.compile(r"0x[0-9a-fA-F]{6,}")
# AND ONE MORE CLASS OF NON-DETERMINISM, WHICH IS NOT AN ADDRESS:
# `clang_hashCursor` ANSWERS A HASH OF A HEAP POINTER, so one binary and one fixture
# gave `-> int 1298492391` on one run and `-> int 2443500409` on the next.  A decimal
# of nine digits or more is masked as `0xBIG`.  THE COST, STATED: a genuine answer
# above 10^9 would also be masked, and this fixture has none -- the largest real
# answer over 324 rows is a token count and an enum value.
BIG = re.compile(r"(-> int )(\d{9,})")


def mask(row):
    return BIG.sub(r"\g<1>0xBIG", PTR.sub("0xPTR", row))


def rows_from(stderr):
    return [ln[4:] for ln in stderr.splitlines() if ln.startswith("SAW ")]


def run_one(binary: Path, k: int, timeout=60):
    """One row, in its own process.  Returns (rc, rows, stdout)."""
    try:
        r = subprocess.run([str(binary), "fixture.c", str(k)], capture_output=True,
                           text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return None, ["SAW timeout"], ""
    return r.returncode, rows_from(r.stderr), r.stdout


def census(binary: Path, n, only=None):
    out = []
    for k in range(n):
        if only is not None and k != only:
            continue
        rc, rows, so = run_one(binary, k)
        name = so.split("ANCHOR ")[-1].splitlines()[0][:0]  # anchor text is per-run
        mine = [r for r in rows if not r.startswith(("anchor", "text=", "SAW text"))]
        out.append(dict(k=k, rc=rc, rows=mine, all=rows, stdout=so))
    return out


def summarise(res, n):
    ok = [r for r in res if r["rc"] == 0 and r["rows"]]
    norow = [r for r in res if r["rc"] == 0 and not r["rows"]]
    fault = [r for r in res if r["rc"] is None or r["rc"] != 0]
    return ok, norow, fault


def plants():
    """Two plants and a disarm, and what each must move.

    A PLANT that moves nothing is a DISARM, and a disarm has to be the same lever
    at the same granularity as the plant it disarms -- so the disarm here edits one
    COMMENT line and the plant edits one ARGUMENT.

    `PLANT-args` transposes two scalar arguments inside `clang_getLocation`'s
    `_run`.  It must move the `line` and `column` columns of that one row and
    nothing else: the sentinel trap in this project is that `0` and `-1` have
    `hi == lo`, so a half-swap is invisible -- here both slots are DISTINCT
    integers, so the swap is visible in the row.

    `PLANT-sel` changes the fixture's field selector from `a` to `c`, which must
    move EVERY row whose answer depends on which cursor the fixture hands over.
    """
    # PLANT-scalar: ONE INTEGER, ONE ARGUMENT, and the row's `line` column must
    # move.  It is the lever the instrument can see.
    def scalar(text):
        old = "  unsigned p2 = (unsigned)(u32)f[2];\n  unsigned p3 = (unsigned)(u32)f[3];"
        assert old in text, "PLANT-scalar matched nothing"
        return text.replace(old,
                           "  unsigned p2 = (unsigned)(u32)f[2] + 1u;\n"
                           "  unsigned p3 = (unsigned)(u32)f[3];", 1), 1

    # PLANT-transpose: the swap is in the CALL, so each local keeps its own `f[i]`
    # and the ROW -- which prints the locals, i.e. the frame -- is byte-identical.
    # Measured: 0 rows moved.  That is a BLIND SPOT and it is reported as one: the
    # row prints the arguments, not what libclang received, so no argument swap at
    # the call site is falsifiable from outside the process.  Swapping the two
    # DECLARATIONS instead is worse -- a no-op by construction, also 0 rows.
    def transpose(text):
        old = "clang_getLocation(p0, p1, p2, p3);"
        new = "clang_getLocation(p0, p1, p3, p2);"
        assert old in text, "PLANT-transpose matched nothing"
        return text.replace(old, new, 1), text.count(old)

    def selector(text):
        # `a` -> `nosuchfield`: the walk then FINDS NOTHING, every fixture record is
        # the zero record, and every box-answering row must change.  `a` -> `c` moved
        # NOTHING: `c` is a real field of the same `Pair`, so the fixture answered
        # with a different cursor and the masked row was byte-identical.  A plant
        # has to break the fixture, not rename it.
        old = 'strcmp(s, "a") == 0'
        assert old in text, "PLANT-sel matched nothing"
        return text.replace(old, 'strcmp(s, "nosuchfield") == 0', 1), text.count(old)

    def disarm(text):
        # same LEVER, same file, one COMMENT line: the plant edits an argument, the
        # disarm edits a word, and the disarm must move nothing in FACT.
        old = "// CALL and not a thing this file had to build."
        assert old in text, "DISARM matched nothing"
        return text.replace(old, "// CALL and not a thing this file had to build, here.", 1), 1
    return [("PLANT-scalar", scalar), ("PLANT-sel", selector),
            ("PLANT-transpose", transpose), ("DISARM-comment", disarm)]


def diff_rows(a, b):
    return sorted(set(a) ^ set(b))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", type=int)
    ap.add_argument("--plants", action="store_true")
    a = ap.parse_args()
    work = Path(os.environ.get("TMPDIR", "/tmp")) / "clangfill-gate"
    names = [r["name"] for r in abi.rows_list()]

    def one_run(workdir, plant=None):
        bf, n = stage(workdir, plant)
        b, e = build(workdir)
        if b is None:
            return None, e
        return census(b, n), None

    base, err = one_run(work)
    if base is None:
        print("BUILD FAILED\n" + err)
        return 1
    if a.only is not None:
        rc, rows, so = run_one(work / "port.out", a.only)
        print("rc=%s" % rc)
        print("\n".join(rows))
        print(so)
        return 0

    def executed(res):
        out = {}
        for r in res:
            hit = [x for x in r["all"] if x.startswith(names[r["k"]] + " ")]
            if hit:
                out[names[r["k"]]] = mask(hit[0])
        return out
    base_rows = executed(base)
    again, e2 = one_run(Path(str(work) + "-again"))
    det = 0 if again is None else len(diff_rows(sorted(base_rows.values()),
                                                 sorted(executed(again).values())))
    print("DETERMINISM rows moved between two runs of ONE binary: %d" % det)
    base_rows = executed(base)
    if a.plants:
        for label, fn in plants():
            w2 = Path(str(work) + "-" + label)
            res, err = one_run(w2, fn)
            if res is None:
                print("%-14s BUILD FAILED -- a plant that does not build proves nothing\n%s"
                      % (label, err))
                continue
            got = executed(res)
            moved = diff_rows(sorted(base_rows.values()), sorted(got.values()))
            # `PLANT-transpose` is EXPECTED to move nothing and is labelled a blind
            # spot, so it is not scored PASS for moving nothing -- a control that
            # proves nothing and reports PASS looks exactly like one that does.
            expect_move = label != "DISARM-comment" and label != "PLANT-transpose"
            verdict = "PASS" if (len(moved) > 0) == expect_move else "FAIL"
            print("%-15s %s  rows moved %d  (base %d, plant %d)%s"
                  % (label, verdict, len(moved), len(base_rows), len(got),
                     "   BLIND SPOT, expected" if label == "PLANT-transpose" else ""))
            for m in moved[:4]:
                print("    %s" % m)
    # EXECUTED is "the row's OWN `SAW` line is on stderr", NOT "rc == 0".  Some of
    # the 324 fault with a NULL handle, and several print their row BEFORE the
    # fault -- the body ran, libclang answered, and something later in the same
    # process died.  Counting rc alone called those unexecuted, which is the
    # opposite of what happened.
    res = base
    done, dead, blank = [], [], []
    for r in res:
        hit = [x for x in r["all"] if x.startswith(names[r["k"]] + " ")]
        r["mine"] = hit
        (done if hit else (dead if r["rc"] else blank)).append(r)

    # A row's ANSWER, from the row and not from the source: everything after `-> `.
    # `SENTINELS` is libclang's own refusal vocabulary -- a NULL handle, -1, and an
    # empty string -- and a row that answers one of those RAN and was REFUSED, which
    # are two different facts and the report states both.
    SENTINELS = {"0", "0x0", "-1", "(null)", "", "0.0", "0.0\n"}
    cls, sentinel, real = {}, 0, 0
    for r in done:
        # a VOID row prints no `-> tail` at all -- there is no answer to print --
        # so it is counted as its own class and its own (absent) answer.
        tail = r["mine"][0].split("-> ", 1)[-1].strip() if "-> " in r["mine"][0] else "void"
        c, v = (tail.split(" ", 1) + [""])[:2]
        cls[c] = cls.get(c, 0) + 1
        if v in SENTINELS or v.split(" ")[0] in SENTINELS:
            sentinel += 1
        else:
            real += 1
    # and the ARGUMENT census, which is where the honesty is: a row whose every
    # argument is `0x0` was called with NULLS and whatever came back is libclang
    # answering a NULL, not the binding working.
    def args_part(row):
        """`name [cls] a=1 b=0x0 -> int 3` -> `a=1 b=0x0`; a VOID row has no `]`."""
        head = row.split("-> ")[0]
        return head[head.rfind("]") + 1:] if "]" in head else head
    allnull = sum(1 for r in done if "=0x0" in args_part(r["mine"][0]))
    print("ROWS %d   EXECUTED %d   ungated %d (faulted %d, rc0-no-row %d)"
          % (len(res), len(done), len(res) - len(done), len(dead), len(blank)))
    print("CENSUS rows-present == rows-expected on %d of %d" % (len(done), len(res)))
    print("ANSWER CLASSES  %s" % dict(sorted(cls.items())))
    print("ANSWER a refusal sentinel %d   a non-sentinel value %d" % (sentinel, real))
    print("ROWS called with at least one NULL argument %d" % allnull)
    for r in dead:
        print("  FAULT k=%d rc=%s %s" % (r["k"], r["rc"], names[r["k"]]))
    for r in blank:
        print("  NOROW k=%d rc=0 %s" % (r["k"], names[r["k"]]))
    return 0


if __name__ == "__main__":
    sys.exit(main())