import io

MARK = "# ===========================================================================\n# THE GATE FIXTURES"
MAINMARK = "# ===========================================================================\n# `main`."

rows = []
for line in open('.agents/slop/wip/main_rows.txt'):
    line = line.rstrip('\n')
    if not line:
        continue
    nm, call, lit = line.split('\t')
    rows.append((nm, call, lit))

cur = open('tinybendygrad/renderer/cstyle.bend').read()
head = cur[:cur.index(MARK)]

helpers = open('.agents/slop/wip/helpers_block.bend').read().rstrip('\n')

MAIN_HDR = '''# ===========================================================================
# `main`. %d ROWS, every one of them a STRING DIFF against CPython, in ten
# groups. The order is the group order and the groups are chosen so that a
# mutation in one CANNOT move a row in another unless it really is shared --
# which is what makes the mutation table at the foot mean something.
#
#   tmap_*   x6   the six `type_map`s (96 dtype cells)
#   rd_*     x42  `_render_dtype` over 7 dtypes x 6 devices (294 cells)
#   witem_*  x6   `code_for_workitem`, including the base's EMPTY dict
#   cfo_*    x74  the ALU table per device, incl. Clang's FIVE DELETIONS
#   kern_*   x8   `kernel_typedef` with the bound, incl. the no-local case
#   idx_*    x20  `render_index`: the swizzle/array cut on BOTH sides of each
#                device's `gep_arr_threshold`, the lane form, and the non-ALU
#                `(buf+idx)` arm with and without `idx.arg is Ops.ADD`
#   opt_*    x4   the six-cell option tables `render_kernel` never reads
#   type/ptr/acc/cast/leg/buf2  the four pointer/cast vocabulary defs
#   wmma_*   x4   `_wmma_name`, including `signed char` -> `signed_char`
#   under_*  x3   the `.replace(" ", "_")` both callers share
#   img_*    x3   the image arm, which BEATS the address space
#   hipockl / hipocml  the two extern families in full
#   kern2_*  x23  `render_kernel` end to end, one per device per prefix clause
#
# THE `py=` LITERALS ARE GENERATED BY CALLING CPython, NOT TYPED. The generator
# is `.agents/slop/wip/gen_main.py`; it builds this whole table from live
# `tinygrad` and writes both the row call and its oracle. A `py=` string that was
# transcribed by hand is a claim about CPython rather than a measurement of it,
# and the first version of this file had 215 of the second kind.
# ===========================================================================

''' % len(rows)

out = io.StringIO()
out.write(head)
out.write('\n' + helpers + '\n\n')
out.write(MAIN_HDR)
out.write("def main() -> IO(Unit):\n  do IO<Unit>:\n")
for nm, call, lit in rows:
    assert call.endswith(")"), call
    # EVERY row helper takes `py` as its SECOND argument, so the generated call is
    # `ROW(name, py, <the rest>)` rather than an appended literal.
    head, _, rest = call.partition("(")
    rest = rest[:-1]                      # strip the closing paren
    nm_arg, _, tail = rest.partition(", ")
    out.write(f"    _ : Unit <- {head}({nm_arg}, {lit}, {tail})\n")
out.write('    IO.print("")\n')
open('tinybendygrad/renderer/cstyle.bend', 'w').write(out.getvalue())
print("written", len(rows), "rows")