#!/bin/sh
# W-2 ladder driver + generator: the real bisection for Nat's ceiling.
#
# ONE FILE PER CANDIDATE. A candidate past the ceiling kills the process, so a
# single file looping over candidates prints every row up to the failure and
# nothing after -- and a fold/reversal bug could make the last printed row look
# like the largest. One file per candidate removes both hazards: each row is its
# own process, its own file, its own construction, and the ladder ORDER lives in
# this script, not in Bend data.
#
# ---------------------------------------------------------------------------
# ARITHMETIC, WRITTEN OUT. THE FIRST VERSION OF IT WAS WRONG.
#   2^48               = 281474976710656
#   base48 = 2^16*(2^32-1) = 65536*4294967295 = 2^48 - 2^16 = 281474976645120
#   base47 = 2^16*2^31    = 65536*2147483648 = 2^47        = 140737488355328
# I first wrote base48 down as 2^48, which put the ladder at base48-65534 ..
# base48+65538 -- straddling 2^48-65536 instead of 2^48. That produced the
# reading "2^48 printed and 2^49 died", i.e. a ceiling ABOVE the error
# message's own 2^48-1. A result that contradicts the tool's own error text is
# the tell that the arithmetic, not the compiler, is wrong.
# ---------------------------------------------------------------------------
# LADDER A: is the bound a MAGNITUDE bound or a PARITY bound? If odd values
# below 2^48 all survive and only 2^48 fails, the bound is magnitude. If
# 2^47+1 fails, the bound is parity and "ceiling = 2^48-1" is a coincidence of
# where the even/odd line falls. The two stories predict different things, so
# this is the row that decides it.
#
# Each .bend prints ONE line and nothing else, so "no W-2 line" unambiguously
# means "did not survive". The DIED branch always prints captured stderr, which
# is the only reason the four generator bugs recorded below were caught as
# generator bugs instead of being read as language walls.
#
# ROOT: one level up from `checks/`, and ASSERTED. See `.agents/slop/shells/README.md`.
# The old comment here said "three levels up -- this script lives at .agents/slop/w64/",
# and the arithmetic followed a comment about a location the file no longer occupies.
# Getting it wrong made all rows read DIED with "No such file or directory": the DRIVER
# manufactured the failures it then reported.
_d=${0%/*}; case $_d in "$0") _d=.;; esac
cd "$_d/.." || exit 1
[ -f pyproject.toml ] && [ -d tinybendygrad ] || { echo "$0: not at the repo root (pwd $PWD)" >&2; exit 3; }
D=.agents/slop/w64/cands
mkdir -p "$D"

B48='Nat.mul(65536n, 4294967295n)'
B47='Nat.mul(65536n, 2147483648n)'

emit() { # emit <k> <expr>
  cat > "$D/cand$1.bend" <<EOF
# W-2 candidate k=$1 -- generated by checks/gen.sh. Do not hand-edit.
# Prints exactly one line, or nothing at all.
import Base

def main() -> IO(Unit):
  do IO<Unit>:
    IO.print("W-2 k=$1 v=" ++ Nat.show($2))
EOF
}

# LADDER A -- ascending, straddling 2^48.
emit 0 "$B48"
emit 1 "Nat.add($B48, 65534n)"   # 2^48-2  even
emit 2 "Nat.add($B48, 65535n)"   # 2^48-1  odd
emit 3 "Nat.add($B48, 65536n)"   # 2^48    even
# LADDER B -- parity probe well below 2^48.
emit 4 "Nat.sub($B47, 1n)"       # 2^47-1  odd
emit 5 "Nat.add($B47, 1n)"       # 2^47+1  odd
emit 6 "Nat.add($B47, 2n)"       # 2^47+2  even

# GENERATOR BUGS, all of which presented as "the language failed":
#  (1) "${2}n, not $2n -- POSIX sh reads "$2n" as the variable "2n".
#  (2) A pure expression cannot be bound inside a `do` block at all: `v : Nat <-
#      expr` gives "expected : @-R:Type -> @k:(@_:Nat -> IO.OP<R>) -> IO.OP<R>"
#      (which reads like a mystery but only means "that is not an IO op"), and
#      `v = expr` gives "expected : a pattern". Pure arithmetic goes INLINE
#      into the IO.print argument, or into a pure `def`.
#  (3) `++` binds looser than one level of application: ".." ++ Nat.mul(a, b)
#      alone parses Nat.mul(...) as the RIGHT OPERAND of ++. A full
#      Nat.add(Nat.mul(..), n) is fine.
#  (4) A literal-suffix parameter needs braces, see (1).

for k in 0 1 2 3 4 5 6; do
  out=$(./bin/bend "$D/cand$k.bend" 2>&1 || true)
  line=$(printf '%s\n' "$out" | grep '^W-2 ' | head -1)
  if [ -n "$line" ]; then
    printf 'SURVIVED k=%s  %s\n' "$k" "$line"
  else
    err=$(printf '%s\n' "$out" | grep -v 'available: run bend update' | head -2 | tr '\n' '|')
    printf 'DIED     k=%s  %s\n' "$k" "$err"
  fi
done

# ---------------------------------------------------------------------------
# Controls. A red with no paired disarm proves nothing. Two rows: a candidate
# that MUST survive, and a candidate that MUST die. If the first reads DIED the
# driver is broken; if the second reads SURVIVED the ladder is not actually
# reaching the ceiling. Three units in this project were found disarmed.
echo "--- controls ---"
./bin/bend "$D/cand0.bend" >/dev/null 2>&1
echo "CONTROL must-survive (k=0, 2^48-2^16) exit=$? (want 0)"
./bin/bend "$D/cand3.bend" >/dev/null 2>&1
echo "CONTROL must-die     (k=3, 2^48)       exit=$? (want nonzero)"