#!/usr/bin/env python3
"""GENERATE both lanes of the `bitcast_dims` gate from `table.py`'s ONE fixture list.

Writes:
  .agents/slop/bitcastrow/bc-rows.bend   the PORT driver (39 rows)
  .agents/slop/bitcastrow/bc-oracle.py   the CPython oracle (39 rows)

Neither lane is hand-typed. The `.bend` side is emitted as an I64 (hi, lo) WORD PAIR per
dim, because a dim above 2**31 has no positive Bend literal and `i64_of_i32` SIGN
EXTENDS, which is the very defect under test -- `i64_of_hi_lo` is the only spelling that
can carry `dim = 2**60`.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from table import BANDS, ROWS, render, cpython  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent


def pair(n):
    """dim as (hi, lo) U32 words -- 2**60 is hi=134217728, and there is no literal for it."""
    assert 0 <= n < (1 << 64), n
    return n >> 32, n & 0xFFFFFFFF


def dim_term(n):
    hi, lo = pair(n)
    return f"H.i64_of_hi_lo({hi}, {lo})"


HEADER = '''# GENERATED by bc-gen.py from table.py -- DO NOT HAND-EDIT. The fixture list lives in
# `table.py` once and is emitted into BOTH lanes, so a fixture cannot be right on the
# bend side and wrong on the python side. Regenerate with:
#     .venv/bin/python .agents/slop/bitcastrow/bc-gen.py
#
# THE ROWS, AND WHY THIS UNIVERSE. `bitcast_dims` truncates to U32 THREE times, and the
# three have DIFFERENT boundaries, so one row at the documented threshold tests one of
# three defects:
#   L1  `H.lo32(i)`      bites at dim >= 2**32                     -- band D
#   L2  `U32.mul(i,inp)` bites at (dim mod 2**32)*inp >= 2**32      -- band B
#   L3  `sint_of(q)`     bites at (dim*inp)//out >= 2**31, which for out == 1 is
#       dim*inp >= 2**31 -- INSIDE the window the source comment claims is exact -- band C
# L3 is not in the prior census at all, because that census's port MODEL used Python ints
# for the answer and so never went through `i64_of_i32`'s sign extension.
#
# band A is the interior and must AGREE throughout; band F is `out == inp`, the `same`
# arm, which never reaches the arithmetic; band G is the FIX'S OWN window edge.
#
# Every dim is an (hi, lo) WORD PAIR through `i64_of_hi_lo`, never `i64_of_i32`: the
# latter sign-extends, so it cannot express `dim = 2**60` at all.
import Base
import ./../../../tinybendygrad/helpers.bend as H
import ./../../../tinybendygrad/uop/ops.bend as O
import ./../../../tinybendygrad/uop/fold.bend as F

def p(nm: String, v: String) -> IO(Unit): IO.print(String.concat([nm, "=", v]))

def sint_text(s: O.Sint) -> String:
  match s:
    case O.SI{i}: H.i64_dec(i)
    case O.SU{u}: String.concat(["u", U32.show(u)])

def list_text.tail(ps: List<&2, O.Sint>) -> String:
  match ps:
    case Nil{}: "]"
    case x <> t: String.concat([",", sint_text(x), list_text.tail(t)])

def list_text(ps: List<&2, O.Sint>) -> String:
  match ps:
    case Nil{}: "[]"
    case x <> t: String.concat(["[", sint_text(x), list_text.tail(t)])

# A REFUSAL AND A SHAPE ARE ONE LINE, so the two are diffed together. Splitting them
# would let a row pass on the flag while the value moved -- the failure a name-comparing
# harness reports as agreement.
def show(m: Maybe<&2, List<&2, O.Sint>>) -> String:
  match m:
    case None{}: "raise"
    case Some{ps}: list_text(ps)

# THE SHAPE IS `[1, dim]` -- TWO AXES -- so a row carries the preserved prefix AND the
# scaled last dim, and `drop_last` dropping the wrong axis would move every row.
def row(nm: String, dim: H.I64, out: U32, inp: U32) -> IO(Unit):
  p(nm, show(F.bitcast_dims(Some{[O.SI{H.i64_of_i32(1)}, O.SI{dim}]}, out, inp)))

def main() -> IO(Unit):
  do IO<Unit>:
'''


def bend_driver():
    lines = [HEADER]
    for name, dim, inp, osz in ROWS:
        lines.append(f'    row("{name}", {dim_term(dim)}, {osz}, {inp})')
    lines.append("")
    return "\n".join(lines)


ORACLE = '''#!/usr/bin/env python3
"""GENERATED by bc-gen.py -- DO NOT HAND-EDIT. The CPython lane of the
`bitcast_dims` gate. Every expectation is CALLED, never typed: it is the real tinygrad
BITCAST arm (ops.py:390-396) reached through `Tensor.bitcast`.

ONE string per row and never empty: `raise`, or `[dim,...]` rendered from CPython's own
post-bitcast shape.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from table import ROWS, cpython, render  # noqa: E402

if __name__ == "__main__":
    for name, dim, inp, out in ROWS:
        print(f"{name}={render(cpython(dim, inp, out))}")
'''


if __name__ == "__main__":
    (HERE / "bc-rows.bend").write_text(bend_driver())
    (HERE / "bc-oracle.py").write_text(ORACLE)
    # PROVE the generated driver's row count against the table, in the same breath, so a
    # truncated write is caught here rather than by a gate that counts 38 and passes.
    got = sum(1 for l in (HERE / "bc-rows.bend").read_text().splitlines() if l.strip().startswith('row("'))
    assert got == len(ROWS), f"driver has {got} rows, table has {len(ROWS)}"
    print(f"wrote bc-rows.bend ({got} rows) and bc-oracle.py ({len(ROWS)} rows)")