#!/usr/bin/env python3
"""CONTROL FIXTURE for ew-consts-gate.py: its real oracle with ONE COMPARED row's value
replaced, so the lane DIFF fires inside `run()` -- after every lane has written and
after the native compile. Generated by harness.build_wrong_oracle; the changed row is
    'k_log2=CONTROL-a633fb25'
"""
import sys
sys.stdout.write('k_log2=CONTROL-a633fb25\nk_log10_2=1050288283\nk_inv_log2=1069066811\nk_sqrt_2=1068827891\nk_sqrt_2_over_pi=1061962282\nk_gelu=1027024659\nk_quick_gelu=1071242019\nk_selu_alpha=1071000957\nk_selu_gamma=1065778527\nk_pi=1078530011\nk_pi_2=1070141403\nk_sixth=1042983595\nk_half=1056964608\nk_one=1065353216\nk_two=1073741824\nk_neg_one=3212836864\nk_leak=1008981770\nk_rtol=925353388\nk_atol=841731191\nk_e=1076754516\nk_two_pi=1086918619\n')
