#!/usr/bin/env python3
"""CONTROL FIXTURE for beautiful-mnist-gate.py: its real oracle with ONE COMPARED row's value
replaced, so the lane DIFF fires inside `run()` -- after every lane has written and
after the native compile. Generated by harness.build_wrong_oracle; the changed row is
    'mdl_table=CONTROL-197cc1b6'
"""
import sys
sys.stdout.write('mdl_table=CONTROL-197cc1b6\nmdl_count=14\nmdl_pad5=2,2,2,2\nmdl_pad3=1,1,1,1\nmdl_in=(1,1,28,28)\nmdl_pool_k5=1,1,24,24,5,5\nmdl_pool_k2s2=1,32,10,10,2,2\nmdl_pool_ns=(1,32,24,26)\nmdl_walk=conv2d=(1,32,24,24) relu=(1,32,24,24) conv2d=(1,32,20,20) relu=(1,32,20,20) batchnorm=(1,32,20,20) max_pool2d=(1,32,10,10) conv2d=(1,64,8,8) relu=(1,64,8,8) conv2d=(1,64,6,6) relu=(1,64,6,6) batchnorm=(1,64,6,6) max_pool2d=(1,64,3,3) flatten=(1,576) linear=(1,10) \nmdl_out=(1,10)\nmdl_lin_in=(1,576)\nmdl_scale=3e4ccccd\nmdl_scale=3d10d0c3\nmdl_scale=3d715bf0\nmdl_scale=3d2aaaab\nmdl_bound=3d2aaaab\nmdl_conv0_w=32x1x5x5\nmdl_conv0_b=(32,)\nmdl_lin_w=(10,576)\nmdl_bn=w=(32,) b=(32,) rm=(32,) rv=(32,) nbt=(1,)\nmdl_bn=w=(64,) b=(64,) rm=(64,) rv=(64,) nbt=(1,)\nrelu1=4 CONST/0 BUFFER/0 CMPLT/2 WHERE/3 \nrelu2=7 CONST/0 BUFFER/0 CONST/0 STACK/2 RESHAPE/2 CMPLT/2 WHERE/3 \nlin1=5 BUFFER/0 BUFFER/0 MUL/2 BUFFER/0 ADD/2 \nout_a=loss:   2.25 test_accuracy: 97.50%\nout_b=loss:   0.00 test_accuracy: 10.00%\nout_c=loss:    nan test_accuracy:   nan%\nout_d=loss:    inf test_accuracy:   inf%\nw3_mask=3 CONST/0 CONST/0 EXPAND/2 \nw3_mask2d=4,10\n')
