#!/usr/bin/env python3
"""CONTROL FIXTURE for wk-f32-gate.py: its real oracle with ONE COMPARED row's value
replaced, so the lane DIFF fires inside `run()` -- after every lane has written and
after the native compile. Generated by harness.build_wrong_oracle; the changed row is
    'z=CONTROL-25417ad1'
"""
import sys
sys.stdout.write('z=CONTROL-25417ad1\none=1065353216\ntwo=1073741824\nm24m1=1266679807\nm24=1266679808\nm24p1=1266679808\nm32m2=1333788672\nm32m1=1333788672\nm32=1333788672\nm32p1=1333788672\np63=1358954496\ni64max=1593835520\nneg1=3212836864\nneg2=3221225472\nnegm32=3481272320\ni64min=3741319168\np45=1459617792\np45p1=1459617792\n')
