#!/usr/bin/env python3
"""CONTROL FIXTURE for ew-explog-gate.py: its real oracle with ONE COMPARED row's value
replaced, so the lane DIFF fires inside `run()` -- after every lane has written and
after the native compile. Generated by harness.build_wrong_oracle; the changed row is
    'ew_log=CONTROL-056ca871'
"""
import sys
sys.stdout.write('ew_log=CONTROL-056ca871\new_log10=4 CONST/0 LOG2/1 CONST/0=1050288283 MUL/2 \new_exp=5 CONST/0 CAST/1 CONST/0=1069066811 MUL/2 EXP2/1 \n')
